/* TechOps Hero — production playable-world presentation. */
(function(root,factory){var api=factory(root);if(typeof module==="object"&&module.exports)module.exports=api;if(root)root.TechOpsCampaignWorldVisuals=api;})(typeof globalThis!=="undefined"?globalThis:this,function(root){"use strict";
var VERSION=5,INTERACT_RANGE=2.15,PLAYER_DRAW_SIZE=46,SAFE_WALK_FRAME_MS=135;
var SAFE_WALK_FRAMES=Object.freeze({down:Object.freeze(["down0","down1","down0","down2"]),up:Object.freeze(["up0","up1","up0","up2"]),right:Object.freeze(["right0","right1","right0","right2"]),left:Object.freeze(["right0","right1","right0","right2"])});
var MOBILE_SAFE_AREA_CSS="#hud-top{padding-top:max(8px,env(safe-area-inset-top));padding-left:max(10px,env(safe-area-inset-left));padding-right:max(10px,env(safe-area-inset-right))}#dialogue{left:max(8px,env(safe-area-inset-left));right:max(8px,env(safe-area-inset-right));bottom:max(8px,env(safe-area-inset-bottom))}#dpad{left:max(16px,env(safe-area-inset-left));bottom:max(20px,env(safe-area-inset-bottom))}#touch-buttons{right:max(18px,env(safe-area-inset-right));bottom:max(24px,env(safe-area-inset-bottom))}@media(pointer:coarse){#dlg-options button,#battle-actions button,#eod-rewards button{min-height:44px}}";
function installMobileSafeArea(){try{if(!root||!root.document||root.document.getElementById("production-mobile-safe-area"))return false;var style=root.document.createElement("style");style.id="production-mobile-safe-area";style.textContent=MOBILE_SAFE_AREA_CSS;(root.document.head||root.document.documentElement).appendChild(style);return true;}catch(e){return false;}}
function animations(){return root&&root.TechOpsMikeAnimations?root.TechOpsMikeAnimations:null;}
function distance(ax,ay,bx,by){var dx=Number(ax||0)-Number(bx||0),dy=Number(ay||0)-Number(by||0);return Math.sqrt(dx*dx+dy*dy);}
function candidates(state){state=state||{};var out=[];(state.npcs||[]).forEach(function(n){if(n&&!n.done)out.push({kind:"npc",x:n.x,y:n.y,source:n,priority:n.ambient?1:4});});(state.devices||[]).forEach(function(d){if(d&&!d.fixed)out.push({kind:"device",x:d.x,y:d.y,source:d,priority:3});});(state.portals||[]).forEach(function(p){if(p)out.push({kind:"portal",x:p.x,y:p.y,source:p,priority:2});});return out;}
function nearestInteractable(state,range){state=state||{};range=typeof range==="number"?range:INTERACT_RANGE;var best=null;candidates(state).forEach(function(c){var d=distance(state.px,state.py,c.x,c.y);if(d>range)return;if(!best||d<best.distance-.001||(Math.abs(d-best.distance)<.001&&c.priority>best.priority))best={kind:c.kind,x:c.x,y:c.y,source:c.source,priority:c.priority,distance:d};});return best;}
function lightProfile(state){state=state||{};var zone="default";try{if(typeof root.zoneAt==="function")zone=String(root.zoneAt(state.px,state.py)||"default").toLowerCase();}catch(e){}var profiles={factory:{vignette:.17,warm:.10,cool:.02},engineering:{vignette:.14,warm:.07,cool:.07},server:{vignette:.20,warm:.01,cool:.13},office:{vignette:.11,warm:.08,cool:.03},lobby:{vignette:.10,warm:.05,cool:.05}},p=profiles[zone]||{vignette:.12,warm:.05,cool:.04};return{zone:zone,vignette:p.vignette,warm:p.warm,cool:p.cool};}
function canRender(){try{return typeof cv!=="undefined"&&typeof ctx!=="undefined"&&typeof S!=="undefined"&&!!cv&&!!ctx&&!!S;}catch(e){return false;}}
function worldToScreen(tx,ty){if(!canRender())return null;var ts=cv.height/14,sc=ts/TILE;return{x:(tx*TILE+TILE/2-camX)*sc,y:(ty*TILE+TILE/2-camY)*sc,scale:sc};}
function safePlayerFrame(state,tm){state=state||{};tm=Number(tm||0);var facing=["up","down","left","right"].indexOf(state.fx)>=0?state.fx:"down";if(state.partyUntil&&tm<state.partyUntil)return{key:"party",flip:false,state:"party",semantic:"party",index:0};if(state.thumbsUntil&&tm<state.thumbsUntil)return{key:"thumbs",flip:false,state:"thumbs",semantic:"thumbs",index:0};if(state.inDialog)return{key:"laptop",flip:false,state:"interact",semantic:"interact",index:0};if(!state.moving)return{key:facing==="left"?"right0":facing+"0",flip:facing==="left",state:"idle",semantic:"idle_"+facing,index:0};var frames=SAFE_WALK_FRAMES[facing]||SAFE_WALK_FRAMES.down,index=Math.floor(tm/SAFE_WALK_FRAME_MS)%frames.length;return{key:frames[index],flip:facing==="left",state:"walk",semantic:"walk_"+facing,index:index};}
function playerFrame(state,tm){var api=animations();if(api&&typeof api.resolveDayShift==="function")return api.resolveDayShift(state,tm);return safePlayerFrame(state,tm);}
function drawProductionPlayer(state,tm){try{if(!state||typeof PLAYER_ATLAS==="undefined"||typeof playerImg==="undefined"||!PLAYER_ATLAS.frames)return false;var plan=playerFrame(state,tm),frame=PLAYER_ATLAS.frames[plan.key]||PLAYER_ATLAS.frames.down0;if(!frame)return false;var C=PLAYER_ATLAS.cell,dw=PLAYER_DRAW_SIZE,dh=PLAYER_DRAW_SIZE,dx=state.px*TILE+(TILE-dw)/2,dy=state.py*TILE+TILE-dh+3,cx=state.px*TILE+TILE/2,cy=state.py*TILE+TILE-2;ctx.save();ctx.globalAlpha=state.moving?.22:.28;ctx.fillStyle="#000";ctx.beginPath();ctx.ellipse(cx,cy,state.moving?13:11,state.moving?4.2:3.8,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.imageSmoothingEnabled=false;if(plan.flip){ctx.translate(dx+dw,0);ctx.scale(-1,1);ctx.drawImage(playerImg,frame[0]*C,frame[1]*C,C,C,0,dy,dw,dh);}else ctx.drawImage(playerImg,frame[0]*C,frame[1]*C,C,C,dx,dy,dw,dh);ctx.restore();return true;}catch(e){return false;}}
function drawInteractionCue(tm){var target=nearestInteractable(S);if(!target)return;var pt=worldToScreen(target.x,target.y);if(!pt)return;var pulse=.5+Math.sin(tm/220)*.18,radius=Math.max(15,19*pt.scale)+Math.sin(tm/250)*2;ctx.save();ctx.globalAlpha=pulse;ctx.strokeStyle=target.kind==="npc"?"#f2d46b":target.kind==="device"?"#7effcd":"#b388ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(pt.x,pt.y,radius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.88;ctx.font="bold 9px monospace";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="rgba(4,10,14,.82)";ctx.fillRect(pt.x-18,pt.y-radius-18,36,14);ctx.fillStyle="#f3f7f8";ctx.fillText("E / A",pt.x,pt.y-radius-11);ctx.restore();}
function drawGrade(tm){var p=lightProfile(S),w=cv.width,h=cv.height;ctx.save();var vignette=ctx.createRadialGradient(w*.5,h*.48,Math.min(w,h)*.12,w*.5,h*.48,Math.max(w,h)*.72);vignette.addColorStop(0,"rgba(0,0,0,0)");vignette.addColorStop(1,"rgba(0,0,0,"+p.vignette+")");ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);var drift=(Math.sin(tm/2600)+1)/2,warm=ctx.createLinearGradient(0,0,w,h);warm.addColorStop(0,"rgba(255,196,116,"+(p.warm*(.65+drift*.35))+")");warm.addColorStop(.55,"rgba(255,196,116,0)");ctx.fillStyle=warm;ctx.fillRect(0,0,w,h);var cool=ctx.createLinearGradient(w,0,0,h);cool.addColorStop(0,"rgba(102,187,255,"+p.cool+")");cool.addColorStop(.6,"rgba(102,187,255,0)");ctx.fillStyle=cool;ctx.fillRect(0,0,w,h);ctx.restore();}
function installPlayerRenderer(){try{if(typeof drawPlayer!=="function"||drawPlayer.__productionLocomotion)return false;var base=drawPlayer;drawPlayer=function(s,tm){if(!(s&&s.nightMode)&&drawProductionPlayer(s,tm||0))return true;return base.apply(this,arguments);};drawPlayer.__productionLocomotion=true;return true;}catch(e){return false;}}
function installDrawPolish(){try{if(typeof draw!=="function"||draw.__productionWorldPolish)return false;var base=draw;draw=function(){var result=base.apply(this,arguments);try{if(canRender()&&!(S&&S.nightMode)){var tm=typeof performance!=="undefined"&&performance.now?performance.now():Date.now();drawGrade(tm);if(!S.inDialog)drawInteractionCue(tm);}}catch(e){}return result;};draw.__productionWorldPolish=true;return true;}catch(e){return false;}}
function install(){return{mobileSafeArea:installMobileSafeArea(),playerRenderer:installPlayerRenderer(),drawPolish:installDrawPolish()};}
var installed=install();return{VERSION:VERSION,INTERACT_RANGE:INTERACT_RANGE,PLAYER_DRAW_SIZE:PLAYER_DRAW_SIZE,SAFE_WALK_FRAME_MS:SAFE_WALK_FRAME_MS,SAFE_WALK_FRAMES:SAFE_WALK_FRAMES,MOBILE_SAFE_AREA_CSS:MOBILE_SAFE_AREA_CSS,installMobileSafeArea:installMobileSafeArea,animations:animations,distance:distance,candidates:candidates,nearestInteractable:nearestInteractable,lightProfile:lightProfile,safePlayerFrame:safePlayerFrame,playerFrame:playerFrame,drawProductionPlayer:drawProductionPlayer,installPlayerRenderer:installPlayerRenderer,installDrawPolish:installDrawPolish,install:install,installed:installed};
});
