/* TechOps Hero — Chapters VII–X + epilogues authority v1
 * Main campaign authority: TechOpsCampaign / TechOpsStory / TechOpsCampaignAct2.
 * Good Boys state is read only to import interlude completion facts; it is never
 * used as late-game chapter progression state.
 */
(function(root){
  "use strict";
  if(!root || root.TechOpsLateGameCampaign) return;
  var VERSION=1, active=false, registered=false;
  function campaign(){try{return root.TechOpsCampaign&&root.TechOpsCampaign.load?root.TechOpsCampaign.load(root.localStorage):null;}catch(e){return null;}}
  function save(s){try{if(root.TechOpsCampaign&&root.TechOpsCampaign.save)root.TechOpsCampaign.save(s,root.localStorage);return true;}catch(e){root.__lateGameSaveError=String(e&&e.stack||e);return false;}}
  function story(s){s.story=s.story||{schemaVersion:1,completedActs:[],facts:{},ending:null};s.story.completedActs=s.story.completedActs||[];s.story.facts=s.story.facts||{};return s.story;}
  function facts(s){return story(s).facts;}
  function late(s){s.lateGame=s.lateGame||{};return s.lateGame.chapters||(s.lateGame.chapters={duetComplete:false,kRecognitionComplete:false,watchdogDefeated:false,orpheusReached:false,ending:null,campaignComplete:false,history:[],tutorial:null,watchdog:null});}
  function record(s,type,detail){late(s).history.push({type:type,detail:detail||null,at:new Date().toISOString()});save(s);}
  function act2(s){try{return root.TechOpsCampaignAct2&&root.TechOpsCampaignAct2.snapshot?root.TechOpsCampaignAct2.snapshot(s):{};}catch(e){return{};}}
  function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0));}
  function metrics(s){var snap=act2(s),ev=Number(snap.evidenceScore||0),tr=Number(snap.trustScore||0),evidence=ev>=10?clamp(ev,0,100):clamp(ev*25,0,100),trust=Math.abs(tr)>=10?clamp(tr,0,100):clamp(50+tr*15,0,100);if(s.lateGame&&s.lateGame.metrics){if(Number.isFinite(Number(s.lateGame.metrics.evidence)))evidence=clamp(s.lateGame.metrics.evidence,0,100);if(Number.isFinite(Number(s.lateGame.metrics.trust)))trust=clamp(s.lateGame.metrics.trust,0,100);}return{evidence:evidence,trust:trust,rawEvidence:ev,rawTrust:tr};}
  function morningstarPhase(){try{return root.TechOpsMORNINGSTARBuild?root.TechOpsMORNINGSTARBuild.getCurrentPhase():0;}catch(e){return 0;}}
  function safe(){try{if(active||!root.S||root.S.inDialog)return false;if(typeof B!=="undefined"&&B)return false;if(typeof NM!=="undefined"&&NM)return false;if(root.v725&&typeof root.v725.active==="function"&&root.v725.active())return false;return true;}catch(e){return false;}}
  function markFacts(s,list){var f=facts(s);list.forEach(function(k){f[k]=true;});}
  function tryCompleteAct(s,id){try{if(!root.TechOpsStory||typeof root.TechOpsStory.eligibleActs!=="function"||typeof root.TechOpsStory.completeAct!=="function")return false;if(story(s).completedActs.indexOf(id)>=0)return true;if(root.TechOpsStory.eligibleActs(s).indexOf(id)<0)return false;root.TechOpsStory.completeAct(s,id);return true;}catch(e){root.__lateGameStorySyncError=String(e&&e.stack||e);return false;}}
  function goodBoysMeta(){try{return root.S&&root.S.meta&&root.S.meta._v736||null;}catch(e){return null;}}
  function syncGoodBoysFacts(){var s=campaign(),m=goodBoysMeta();if(!s||!m)return false;if(m.done&&m.k&&m.waldo){markFacts(s,["k_freed","waldo_freed","warden_null_defeated","crew_returned_to_earth"]);s.lateGame=s.lateGame||{};s.lateGame.goodDogsImported=true;tryCompleteAct(s,"interlude");record(s,"good_dogs_interlude_imported",{mission:m.m||8});return true;}return false;}
  function scene(id,title,captions,actors){var v=root.v725;if(!v||!v.h||typeof v.register!=="function")return false;var H=v.h,shots=captions.map(function(cap,i){return{dur:i===captions.length-1?3200:2800,cap:cap,draw:function(x,tm){H.bg(x,i%2?"#0d1324":"#090d18");if(id==="late_duet"){x.strokeStyle="rgba(57,211,255,.5)";x.lineWidth=2;x.beginPath();x.moveTo(H.LW/2,H.BAR+50);x.lineTo(H.LW/2,H.LH-H.BAR-40);x.stroke();}if(id==="late_watchdog"){for(var d=0;d<6;d++){var px=130+(d%3)*360,py=H.BAR+80+Math.floor(d/3)*210;H.panel(x,px,py,300,150,"#10182c");H.txt(x,["PRODUCTION","ACCESS","TELEMETRY","NETWORK","PHYSICAL","SWARM"][d],px+150,py+35,14,d%2?H.CYAN:H.GREEN,"center",true);}}if(id==="late_orpheus"){H.panel(x,220,H.BAR+80,H.LW-440,H.LH-2*H.BAR-160,"#070b12");H.txt(x,"PROJECT ORPHEUS // ROOT",H.LW/2,H.BAR+125,18,H.PUR,"center",true);}if(id==="late_k_recognition")H.cityGlow(x,tm,24);var a=(actors&&actors[i])||actors&&actors[0]||"";if(a.indexOf("mike")>=0)H.mike(x,"down0",H.LW/2-170,H.LH-H.BAR-35,180);if(a.indexOf("felicia")>=0)H.felicia(x,"down0",H.LW/2+170,H.LH-H.BAR-35,180,true);if(a.indexOf("k")>=0)H.k(x,H.LW/2+170,H.LH-H.BAR-35,185,"idle");H.txt(x,title,H.LW/2,H.BAR+38,17,H.GOLD,"center",true);}};});return v.register(id,{title:title,shots:shots,cues:{1:"beep520",[shots.length-1]:"chime"}});}
  function registerScenes(){if(registered)return true;if(!root.v725)return false;scene("late_duet","CHAPTER VII — DUET PROTOCOL",["ORPHEUS has modeled every choice Mike makes alone.","You can't outrandom a system that learned your randomness.","The answer isn't one center. It's no center.","Distributed leadership becomes a control surface."],["mike","mike felicia","mike felicia","mike felicia"]);scene("late_k_recognition","CHAPTER VIII — GHOST FORK",["Waldo calls Mike home. K is already waiting.","Red in the Mirror.","Because I wrote it about you.","Red is me. You're the mirror.","I may not be the original. But I'm the one still alive."],["mike k","mike k","mike k","mike k","mike k"]);scene("late_watchdog","CHAPTER IX — WATCHDOG",["Production, access, telemetry, network, physical infrastructure and swarm fail together.","It's not separate incidents. It's one system using all of them.","Mike assigns owners instead of trying to become every owner.","I'm not carrying this alone. That's the point."],["mike felicia","mike felicia","mike felicia","mike felicia"]);scene("late_orpheus","CHAPTER X — ORPHEUS WAKES",["You call it judgment when you do it. You call it control when I do.","I call it responsibility. I don't delegate it to something that can't be held accountable.","Reliability without consent is just a nicer word for coercion.","The terminal waits for a human decision."],["mike","mike","mike","mike"]);scene("late_end_shutdown","ENDING — SHUTDOWN",["Prediction goes dark.","Tomorrow something will break. Mike will fix it because that is the job.","Not perfect. Human in the loop."],["mike","mike","mike"]);scene("late_end_control","ENDING — CONTROL",["99.7% uptime. Zero unplanned outages.","EMPLOYEE BEHAVIORS CORRECTED: 847.","I didn't build a better system. I became the system."],["mike","mike","mike"]);scene("late_end_open","ENDING — OPEN NETWORK",["Root is revoked, not transferred.","Authority is distributed across people who can challenge one another.","No single point of failure. Including Mike."],["mike felicia","mike felicia","mike felicia"]);scene("late_ep_red","EPILOGUE — RED",["K returns to the song after meeting Mike.","The tribute to a stranger became an interrogation of himself.","He may not be the original. He is alive. He is self-authored."],["k","k","k"]);scene("late_ep_queue","EPILOGUE — THE QUEUE",["A Shipping printer is simply broken.","No hidden intelligence. No cosmic clue. Just a printer.","The player chooses OBSERVE.","EVERY TICKET IS A DUNGEON. LEAVE IT BETTER THAN YOU FOUND IT."],["mike","mike","mike","mike"]);registered=true;return true;}
  function play(id,cb){registerScenes();if(root.v725&&root.v725.cines&&root.v725.cines.indexOf(id)>=0){active=true;return root.v725.play(id,function(){active=false;if(cb)cb();});}if(typeof root.dlg==="function"){active=true;root.dlg("CAMPAIGN",id.replace(/_/g," ").toUpperCase(),[{t:"Continue",f:function(){active=false;if(root.closeDlg)root.closeDlg();if(cb)cb();}}]);return true;}if(cb)cb();return false;}
  function setCharacter(id){try{if(!root.S)return false;root.S.meta=root.S.meta||{};root.S.meta._char=id==="felicia"?"felicia":"mike";if(typeof root.save==="function")root.save();return true;}catch(e){return false;}}
  var ChapterVII={canStart:function(){var s=campaign();if(!s)return false;var m=metrics(s),snap=act2(s),f=facts(s),l=late(s);return !l.duetComplete&&!!snap.violinistRevealed&&morningstarPhase()>=4&&!!f.mike_model_discovered&&m.trust>=60&&m.evidence>=50;},start:function(){if(!this.canStart()||active)return false;var s=campaign();record(s,"chapter_vii_started");play("late_duet",function(){ChapterVII.startSwitchingTutorial();});return true;},startSwitchingTutorial:function(){var s=campaign();if(!s)return false;var l=late(s);l.tutorial={step:0,switches:0,startedAt:new Date().toISOString()};save(s);setCharacter("mike");root.dlg("DUET PROTOCOL // MIKE","A physical dependency is failing while the signal layer is being manipulated. Mike can hold the repair boundary, but he cannot be in both layers at once.",[{t:"Hold the physical line",f:function(){ChapterVII._stepFelicia();}}]);return true;},_stepFelicia:function(){var s=campaign(),t=s&&late(s).tutorial;if(!s||!t)return false;t.step=1;t.switches++;save(s);setCharacter("felicia");root.dlg("DUET PROTOCOL // FELICIA","Control changes hands. Felicia can see the signal timing Mike cannot service while his hands are on the hardware.",[{t:"Parry the signal and close the portal",f:function(){ChapterVII._stepMike();}}]);return true;},_stepMike:function(){var s=campaign(),t=s&&late(s).tutorial;if(!s||!t)return false;t.step=2;t.switches++;save(s);setCharacter("mike");root.dlg("DUET PROTOCOL // MIKE","The signal is quiet. Mike verifies the repaired dependency while Felicia watches the telemetry. Neither owns the whole state.",[{t:"Verify together",f:function(){ChapterVII.onTutorialComplete();}}]);return true;},onTutorialComplete:function(){var s=campaign();if(!s)return false;var l=late(s),t=l.tutorial||{};t.step=3;t.switches=(t.switches||0)+1;t.completedAt=new Date().toISOString();l.duetComplete=true;markFacts(s,["duet_protocol_complete","felicia_playable","orbital_signal_found"]);try{if(root.TechOpsCampaignAct2&&root.TechOpsCampaignAct2.completeDuetProtocol)root.TechOpsCampaignAct2.completeDuetProtocol(s);}catch(e){root.__duetAct2Error=String(e&&e.stack||e);}tryCompleteAct(s,"act_6");record(s,"duet_protocol_completed",{switches:t.switches});setCharacter("mike");if(root.closeDlg)root.closeDlg();return true;}};
  var ChapterVIII={canStart:function(){var s=campaign();if(!s)return false;syncGoodBoysFacts();s=campaign();var f=facts(s),l=late(s);return !l.kRecognitionComplete&&!!(f.duet_protocol_complete||l.duetComplete)&&!!f.k_freed&&!!f.crew_returned_to_earth;},start:function(){if(!this.canStart()||active)return false;var s=campaign(),f=facts(s);record(s,"chapter_viii_started");if(f.mike_meets_k&&f.k_personhood_affirmed)return this.onRecognitionComplete("gk6-canonical");play("late_k_recognition",function(){ChapterVIII.onRecognitionComplete("fallback");});return true;},onRecognitionComplete:function(source){var s=campaign();if(!s)return false;var l=late(s);l.kRecognitionComplete=true;markFacts(s,["mike_meets_k","k_personhood_affirmed","ghost_fork_unlocked"]);tryCompleteAct(s,"act_7");record(s,"k_recognition_complete",{anchor:"Red is me. You're the mirror.",source:source||"late-game"});root.__kRecognition={completed:Date.now(),anchor:"Red is me. You're the mirror.",source:source||"late-game"};return true;}};
  var WATCHDOG_ASSIGNMENTS={production:"IT TEAM",access:"MIKE",telemetry:"FELICIA",network:"K",physical:"WALDO",swarm:"KATRIN + MANCHEZ"};
  var ChapterIX={canStart:function(){var s=campaign();if(!s)return false;var f=facts(s),l=late(s);return !l.watchdogDefeated&&!!f.mike_meets_k&&!!f.duet_protocol_complete&&morningstarPhase()>=5;},start:function(){if(!this.canStart()||active)return false;var s=campaign();record(s,"chapter_ix_started");play("late_watchdog",function(){ChapterIX.showDomainAssignment();});return true;},showDomainAssignment:function(){var s=campaign();if(!s||typeof root.dlg!=="function")return false;var l=late(s);l.watchdog={startedAt:new Date().toISOString(),assignments:{},resolved:{}};save(s);root.dlg("WATCHDOG // INCIDENT COMMAND","Six domains are failing at once. The mechanic is assignment, not omnipresence.<br><br>PRODUCTION · ACCESS · TELEMETRY · NETWORK · PHYSICAL · SWARM",[{t:"Distribute ownership",f:function(){ChapterIX.applyDistributedPlan();}},{t:"Mike takes every domain",f:function(){root.dlg("WATCHDOG // OVERLOAD","ORPHEUS predicts the single-owner response immediately. Two domains fail while Mike is crossing between them.<br><br><b>One person cannot be the topology.</b>",[{t:"Reassign the incident",f:function(){ChapterIX.showDomainAssignment();}}]);}}]);return true;},applyDistributedPlan:function(){var s=campaign();if(!s)return false;var w=late(s).watchdog;w.assignments=Object.assign({},WATCHDOG_ASSIGNMENTS);Object.keys(WATCHDOG_ASSIGNMENTS).forEach(function(d){w.resolved[d]=true;});save(s);root.dlg("WATCHDOG // DISTRIBUTED RESPONSE","Production → IT Team<br>Access → Mike<br>Telemetry → Felicia<br>Network → K<br>Physical → Waldo<br>Swarm → Katrin + Manchez<br><br>Every domain has one owner. No owner has the whole incident.",[{t:"Execute and verify",f:function(){ChapterIX.onWatchdogComplete();}}]);return true;},onWatchdogComplete:function(){var s=campaign();if(!s)return false;var l=late(s);l.watchdogDefeated=true;if(l.watchdog)l.watchdog.completedAt=new Date().toISOString();markFacts(s,["watchdog_defeated","orpheus_interface_reached"]);tryCompleteAct(s,"act_8");record(s,"watchdog_defeated",l.watchdog&&l.watchdog.assignments);if(root.closeDlg)root.closeDlg();return true;}};
  var EndingValidator={validate:function(id){var s=campaign();if(!s)return{valid:false,failures:["Campaign state unavailable"]};var m=metrics(s),f=facts(s),phase=morningstarPhase(),fail=[];if(id==="shutdown")return{valid:true,metrics:m};if(id==="control"){if(m.evidence<70)fail.push("Evidence: "+m.evidence+"/70");if(m.trust>=50)fail.push("Trust must be < 50 (current: "+m.trust+")");}else if(id==="open_network"){if(m.trust<70)fail.push("Trust: "+m.trust+"/70");if(phase<5)fail.push("MORNINGSTAR phase: "+phase+"/5");if(!f.k_personhood_affirmed)fail.push("Ghost Fork recognition incomplete");if(!f.watchdog_defeated)fail.push("Watchdog not defeated");}else return{valid:false,failures:["Unknown ending"]};return fail.length?{valid:false,failures:fail,metrics:m}:{valid:true,metrics:m};}};
  var ChapterX={canStart:function(){var s=campaign();if(!s)return false;var l=late(s),f=facts(s);return !l.ending&&!!f.watchdog_defeated&&!!f.orpheus_interface_reached;},start:function(){if(!this.canStart()||active)return false;var s=campaign();late(s).orpheusReached=true;record(s,"chapter_x_started");play("late_orpheus",function(){ChapterX.showEndingChoice();});return true;},showEndingChoice:function(){if(typeof root.dlg!=="function")return false;var b=EndingValidator.validate("control"),c=EndingValidator.validate("open_network"),opts=[{t:"SHUTDOWN — HUMAN IN THE LOOP",f:function(){ChapterX.selectEnding("shutdown");}}];if(b.valid)opts.push({t:"CONTROL — SYSTEM ADMINISTRATOR",f:function(){ChapterX.selectEnding("control");}});if(c.valid)opts.push({t:"OPEN NETWORK — NO SINGLE POINT OF FAILURE",f:function(){ChapterX.selectEnding("open_network");}});root.dlg("ORPHEUS // ROOT DECISION","ORPHEUS offers no boss health bar. Only authority.<br><br>CONTROL: "+(b.valid?"AVAILABLE":b.failures.join(" · "))+"<br>OPEN NETWORK: "+(c.valid?"AVAILABLE":c.failures.join(" · ")),opts);return true;},selectEnding:function(id){var v=EndingValidator.validate(id);if(!v.valid){root.__endingReject={id:id,failures:v.failures,at:Date.now()};return false;}var s=campaign(),l=late(s);l.ending=id;markFacts(s,["ending_chosen"]);story(s).ending=id;try{if(root.TechOpsStory&&root.TechOpsStory.chooseEnding&&!story(s).achievement)root.TechOpsStory.chooseEnding(s,id);}catch(e){root.__endingStoryError=String(e&&e.stack||e);}record(s,"ending_chosen",{id:id,metrics:v.metrics});if(root.closeDlg)root.closeDlg();var cine=id==="shutdown"?"late_end_shutdown":id==="control"?"late_end_control":"late_end_open";play(cine,function(){EpilogueRed.play();});return true;}};
  var EpilogueRed={play:function(){try{if(root.TechOpsDiegeticMusic)root.TechOpsDiegeticMusic.playRed();}catch(e){}play("late_ep_red",function(){Epilogue.start();});return true;}};
  var Epilogue={start:function(){var s=campaign();if(!s)return false;play("late_ep_queue",function(){var s2=campaign();if(!s2)return;var l=late(s2);l.campaignComplete=true;markFacts(s2,["campaign_complete"]);tryCompleteAct(s2,"epilogue");record(s2,"campaign_complete",{ending:l.ending});if(typeof root.dlg==="function")root.dlg("THE QUEUE","<b>EVERY TICKET IS A DUNGEON.</b><br><b>EVERY SYSTEM IS A RELATIONSHIP.</b><br><b>LEAVE IT BETTER THAN YOU FOUND IT.</b>",[{t:"Return to work",f:root.closeDlg}]);root.__campaignComplete={at:Date.now(),ending:l.ending};});return true;}};
  function autoTick(){registerScenes();syncGoodBoysFacts();if(!safe())return false;if(ChapterVII.canStart())return ChapterVII.start();if(ChapterVIII.canStart())return ChapterVIII.start();if(ChapterIX.canStart())return ChapterIX.start();if(ChapterX.canStart())return ChapterX.start();return false;}
  root.TechOpsChapterVII=ChapterVII;root.TechOpsChapterVIII=ChapterVIII;root.TechOpsChapterIX=ChapterIX;root.TechOpsChapterX=ChapterX;root.TechOpsEpilogueRed=EpilogueRed;root.TechOpsEpilogue=Epilogue;root.TechOpsEndingValidator=EndingValidator;
  root.TechOpsLateGameCampaign={VERSION:VERSION,metrics:function(){var s=campaign();return s?metrics(s):null;},syncGoodBoysFacts:syncGoodBoysFacts,registerScenes:registerScenes,check:autoTick,snapshot:function(){var s=campaign();return s?{version:VERSION,lateGame:late(s),facts:Object.assign({},facts(s)),metrics:metrics(s),morningstarPhase:morningstarPhase()}:null;}};
  (root.setInterval||setInterval)(autoTick,1500);autoTick();
})(typeof globalThis!=="undefined"?globalThis:this);
