/* TechOps Hero — EAST SIDE: The Missing Chapter v1.1
 * Canonical bridge: Good Dogs Protocol -> EAST SIDE -> Ghost Fork.
 * K-only, non-combat, six-by-two New Haven walk.
 */
(function(root,factory){
  var api=factory(root||{});
  if(typeof module==="object"&&module.exports)module.exports=api;
  if(root)root.TechOpsEastSide=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";
  var VERSION=2,SCHEMA=1,W=960,H=540,COLS=6,ROWS=2,WORLD_W=W*COLS,WORLD_H=H*ROWS;
  var SPEED={grounded:145,orbital:78},ORBITAL_THRESHOLD=55;
  var AUDIO_BASE="assets/audio/eastside/";
  var AUDIO={grounded:AUDIO_BASE+"eastside_grounded.ogg",orbital:AUDIO_BASE+"eastside_orbital.ogg",static:AUDIO_BASE+"static_burst.wav",breathing:AUDIO_BASE+"breathing_mechanical.wav"};
  var LYRIC_FRAGMENTS=["Bottle half-empty","chasing the static","mask on an angel","strings on my wrists","Everything dead got a habit of lingering","Gas station lights / Two in the morning","EAST SIDE!"];
  var STATIC=[
    {id:"radio_1",kind:"radio",x:860,y:680,fragment:0},{id:"phone_1",kind:"phone",x:1530,y:610,fragment:1},
    {id:"cig_1",kind:"cigarette",x:2210,y:735,fragment:2},{id:"radio_2",kind:"radio",x:2910,y:420,fragment:3},
    {id:"phone_2",kind:"phone",x:3610,y:680,fragment:4},{id:"cig_2",kind:"cigarette",x:4310,y:605,fragment:5},
    {id:"radio_3",kind:"radio",x:4920,y:700,fragment:6}
  ];
  var DOGS=[{id:"dog_1",x:3230,y:650},{id:"dog_2",x:3450,y:720},{id:"dog_3",x:3650,y:620}];
  var ANCHORS=[
    {id:"bottle",x:760,y:690,r:95,label:"BOTTLED WATER"},{id:"camera",x:1670,y:560,r:115,label:"RED CAMERA LIGHT"},
    {id:"grate",x:2540,y:690,r:105,label:"VENTILATION GRATE"},{id:"cuffs",x:4460,y:655,r:105,label:"HANDCUFFS"}
  ];
  var GROUNDING=[{id:"coffee",x:1160,y:690,r:95,label:"DRINK COFFEE"},{id:"bench",x:3010,y:710,r:105,label:"SIT ON BENCH"},{id:"rain",x:3920,y:580,r:110,label:"LISTEN TO RAIN"}];
  var GAS={x:4460,y:560,r:180},PORCH={x:5520,y:610,r:145};
  var REFRAIN_TIMES_MS=[],runtime=null,installTimer=null,autoTimer=null;

  function now(){return root.performance&&root.performance.now?root.performance.now():Date.now();}
  function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
  function dist(a,b,c,d){var x=a-c,y=b-d;return Math.sqrt(x*x+y*y);}
  function facts(){if(!root.S)return{};root.S.story=root.S.story||{schemaVersion:1,completedActs:[],facts:{},ending:null};root.S.story.facts=root.S.story.facts||{};return root.S.story.facts;}
  function goodDogsComplete(){var f=facts(),m=root.S&&root.S.meta||{},g=m.goodDogs||{};return!!(f.good_dogs_protocol_complete||m.good_dogs_protocol_complete||g.good_dogs_protocol_complete);}
  function legacyGhostForkStarted(){var m=root.S&&root.S.meta||{};for(var i=1;i<=6;i++)if(m["_v734gk"+i])return true;return false;}
  function ensure(){
    if(!root.S)return null;root.S.meta=root.S.meta||{};var s=root.S.meta.eastSide||(root.S.meta.eastSide={});
    s.schemaVersion=SCHEMA;if(s.phase!=="orbital")s.phase="grounded";if(!Number.isFinite(s.orbitalMeter))s.orbitalMeter=0;
    if(!Number.isFinite(s.x))s.x=260;if(!Number.isFinite(s.y))s.y=680;
    s.staticCollected=Array.isArray(s.staticCollected)?s.staticCollected:[];s.dogsPetted=Array.isArray(s.dogsPetted)?s.dogsPetted:[];
    s.anchorsSeen=Array.isArray(s.anchorsSeen)?s.anchorsSeen:[];s.groundingSeen=Array.isArray(s.groundingSeen)?s.groundingSeen:[];
    s.inventory=s.inventory||{};s.lyrics=Array.isArray(s.lyrics)?s.lyrics:[];s.unlocked=!!(s.unlocked||goodDogsComplete());
    if(legacyGhostForkStarted()&&!s.completed)s.legacyGhostFork=true;return s;
  }
  function persist(){try{if(typeof root.save==="function")return root.save()!==false;if(typeof root.saveGame==="function")return root.saveGame()!==false;}catch(e){root.__eastSideSaveError=String(e&&e.stack||e);}return false;}
  function snapshot(){var s=ensure()||{};return JSON.parse(JSON.stringify({schemaVersion:s.schemaVersion,unlocked:!!s.unlocked,started:!!s.started,completed:!!s.completed,phase:s.phase,orbitalMeter:s.orbitalMeter,x:s.x,y:s.y,staticCollected:s.staticCollected||[],dogsPetted:s.dogsPetted||[],anchorsSeen:s.anchorsSeen||[],groundingSeen:s.groundingSeen||[],inventory:s.inventory||{},lyrics:s.lyrics||[],gasChoice:s.gasChoice||null,knockCount:s.knockCount||0,fullStaticUnlocked:!!s.fullStaticUnlocked,kLanded:!!s.kLanded,legacyGhostFork:!!s.legacyGhostFork,porchPhaseLocked:!!s.porchPhaseLocked}));}
  function writeFact(k,v){v=v===undefined?true:v;facts()[k]=v;if(root.S&&root.S.meta)root.S.meta[k]=v;}
  function setPhase(next,reason,forced){var s=ensure();if(!s)return null;next=next==="orbital"?"orbital":"grounded";s.phase=next;s.phaseReason=reason||"environment";s.phaseChangedAt=Date.now();if(next==="orbital"&&forced)s.orbitalMeter=Math.max(s.orbitalMeter,70);if(next==="grounded")s.orbitalMeter=Math.min(s.orbitalMeter,20);if(runtime&&runtime.audio)runtime.audio.phase(next);if(runtime)runtime.phaseFlash={t:.55,phase:next};persist();return next;}
  function addStatic(id){var s=ensure(),item=STATIC.find(function(o){return o.id===id;});if(!s||!item||s.staticCollected.indexOf(id)>=0)return false;s.staticCollected.push(id);s.orbitalMeter=clamp(s.orbitalMeter+10,0,100);if(s.lyrics.indexOf(item.fragment)<0)s.lyrics.push(item.fragment);if(s.staticCollected.length===7){s.fullStaticUnlocked=true;writeFact("eastside_full_static_unlocked",true);}if(s.orbitalMeter>=ORBITAL_THRESHOLD)setPhase("orbital","static buildup",false);persist();return true;}
  function triggerAnchor(id){var s=ensure(),a=ANCHORS.find(function(o){return o.id===id;});if(!s||!a||s.anchorsSeen.indexOf(id)>=0)return false;s.anchorsSeen.push(id);s.orbitalMeter=clamp(s.orbitalMeter+24,0,100);setPhase("orbital",a.label,true);if(runtime&&runtime.audio)runtime.audio.trauma();persist();return true;}
  function ground(id){var s=ensure();if(!s)return false;if(s.groundingSeen.indexOf(id)<0)s.groundingSeen.push(id);s.orbitalMeter=Math.max(0,s.orbitalMeter-40);setPhase("grounded",id,false);if(runtime&&runtime.audio)runtime.audio.ground();persist();return true;}
  function petDog(id){var s=ensure(),d=DOGS.find(function(o){return o.id===id;});if(!s||!d)return false;if(s.dogsPetted.indexOf(id)<0){s.dogsPetted.push(id);s.inventory.ghost=(s.inventory.ghost||0)+1;}ground(id);persist();return true;}
  function chooseGas(enter){var s=ensure();if(!s||s.gasChoice)return false;s.gasChoice=enter?"enter":"pass";if(enter){s.orbitalMeter=clamp(s.orbitalMeter+28,0,100);setPhase("orbital","gas station memory",true);}else ground("gas_station_pass");persist();return true;}
  function collectBottle(){var s=ensure();if(!s||s.inventory.empty_bottle)return false;s.inventory.empty_bottle=true;s.orbitalMeter=clamp(s.orbitalMeter+5,0,100);persist();return true;}
  function canStart(){var s=ensure();return!!(s&&s.unlocked&&goodDogsComplete());}
  function ghostForkUnlocked(){var s=ensure();return!!(s&&(s.completed||s.legacyGhostFork||facts().ghost_fork_unlocked));}
  function complete(){var s=ensure();if(!s)return false;s.completed=true;s.kLanded=true;s.phase="grounded";s.orbitalMeter=0;s.completedAt=Date.now();s.inventory.k_headphones=true;writeFact("k_landed",true);writeFact("ghost_fork_unlocked",true);writeFact("eastside_completed",true);writeFact("k_headphones",true);persist();return true;}
  function resetForReplay(){var s=ensure();if(!s)return false;s.x=260;s.y=680;s.phase="grounded";s.orbitalMeter=0;s.knockCount=0;s.porchPhaseLocked=false;s.started=true;s.replay=true;persist();return true;}
  function setRefrainTimes(a){REFRAIN_TIMES_MS=(Array.isArray(a)?a:[]).map(Number).filter(Number.isFinite).sort(function(x,y){return x-y;});return REFRAIN_TIMES_MS.slice();}
  function refrainDue(prev,cur,tol){tol=Number.isFinite(tol)?tol:50;for(var i=0;i<REFRAIN_TIMES_MS.length;i++){var t=REFRAIN_TIMES_MS[i];if(t>prev+tol&&t<=cur+tol)return t;}return null;}
  function interactionAllowed(phase,type){if(phase!=="orbital")return true;return type==="static"||type==="dog"||type==="ground"||type==="porch";}

  function makeAudio(){if(!root.document)return null;var g=root.document.createElement("audio"),o=root.document.createElement("audio"),fx=root.document.createElement("audio"),b=root.document.createElement("audio");g.src=AUDIO.grounded;o.src=AUDIO.orbital;fx.src=AUDIO.static;b.src=AUDIO.breathing;g.loop=o.loop=b.loop=true;g.preload=o.preload=fx.preload=b.preload="auto";var d={g:g,o:o,fx:fx,b:b,duck:1,last:0};d.phase=function(p){g.volume=p==="grounded"?.4*d.duck:.02*d.duck;o.volume=p==="orbital"?.8*d.duck:.03*d.duck;b.volume=p==="orbital"?.34*d.duck:0;};d.play=function(){var t=Math.max(g.currentTime||0,o.currentTime||0);try{g.currentTime=o.currentTime=t;}catch(_){}[g,o,b].forEach(function(a){try{var p=a.play();if(p&&p.catch)p.catch(function(){});}catch(_){}});d.phase((ensure()||{}).phase);};d.trauma=function(){d.duck=.2;d.phase("orbital");try{fx.currentTime=0;fx.volume=.7;var p=fx.play();if(p&&p.catch)p.catch(function(){});}catch(_){}if(root.setTimeout)root.setTimeout(function(){d.duck=1;d.phase((ensure()||{}).phase);},900);};d.ground=function(){d.duck=1;d.phase("grounded");};d.stop=function(){[g,o,fx,b].forEach(function(a){try{a.pause();}catch(_){}});};d.tick=function(){var cur=Math.round(Math.max(g.currentTime||0,o.currentTime||0)*1000),hit=refrainDue(d.last,cur,50);d.last=cur;return hit;};return d;}
  function injectStyle(){if(!root.document||root.document.getElementById("east-side-style"))return;var e=root.document.createElement("style");e.id="east-side-style";e.textContent="#east-side-root{position:fixed;inset:0;z-index:2147482000;background:#050912;color:#eef7ff;font-family:'Press Start 2P',monospace;overflow:hidden;touch-action:none}#east-side-canvas{width:100%;height:100%;display:block;image-rendering:pixelated}.es-title{position:absolute;left:18px;top:max(18px,env(safe-area-inset-top));font-size:10px;letter-spacing:2px;text-shadow:0 2px #000}.es-objective{position:absolute;left:50%;transform:translateX(-50%);bottom:max(22px,env(safe-area-inset-bottom));padding:10px 14px;background:rgba(3,7,12,.78);border:1px solid rgba(255,190,79,.38);font-size:8px;line-height:1.5;text-align:center;max-width:78%}.es-pause{position:absolute;inset:8% 10%;background:rgba(4,8,15,.96);border:2px solid #68d7ff;padding:24px;overflow:auto;display:none;pointer-events:auto;line-height:1.7;font-size:8px}.es-pause.active{display:block}.es-pause h2{color:#68d7ff;font-size:13px}.es-pause .frag{color:#d5d9e4;margin:11px 0}.es-pause .locked{color:#4b5568}#east-side-touch{position:absolute;inset:0;pointer-events:none}.es-pad,.es-use{position:absolute;pointer-events:auto;user-select:none}.es-pad{left:18px;bottom:max(18px,env(safe-area-inset-bottom));width:150px;height:150px}.es-pad button,.es-use{border:1px solid rgba(126,255,205,.45);background:rgba(5,14,20,.72);color:#eafff5;font:9px 'Press Start 2P',monospace}.es-pad button{position:absolute;width:48px;height:48px;border-radius:14px}.es-up{left:51px;top:0}.es-down{left:51px;bottom:0}.es-left{left:0;top:51px}.es-right{right:0;top:51px}.es-use{right:24px;bottom:max(35px,env(safe-area-inset-bottom));width:92px;height:92px;border-radius:50%}@media(min-width:900px) and (pointer:fine){#east-side-touch{display:none}}";(root.document.head||root.document.documentElement).appendChild(e);}
  function rr(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
  function city(c,screen,camX,camY){var x0=screen*W-camX,p=[["#101b2a","#20374a"],["#111522","#263042"],["#12121b","#29243a"],["#0c1716","#203b32"],["#16110f","#403128"],["#10131b","#242c3b"]][screen];c.fillStyle=p[0];c.fillRect(x0,-camY,W,WORLD_H);for(var row=0;row<2;row++){var base=row*H+H-85-camY;for(var i=0;i<7;i++){var bw=90+(i%3)*35,bh=130+(i*37%170),bx=x0+i*145-20;c.fillStyle=p[1];c.fillRect(bx,base-bh,bw,bh);}c.fillStyle="#18222b";c.fillRect(x0,base,W,85);}}
  function backdrop(c,screen,camX,camY){var ids=["industrial","downtown","industrial","suburbs","longwharf","suburbs"],im=root.NM_BG734&&root.NM_BG734[ids[screen]];if(im&&im.complete&&im.naturalWidth){for(var r=0;r<2;r++)c.drawImage(im,screen*W-camX,r*H-camY,W,H);}else city(c,screen,camX,camY);}
  function drawK(c,x,y,h,flip){var u=h/100;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.fillStyle="#15241f";rr(c,-18*u,-58*u,36*u,55*u,7*u);c.fill();c.fillStyle="#b9855a";c.beginPath();c.arc(0,-70*u,14*u,0,Math.PI*2);c.fill();c.fillStyle="#12171a";c.fillRect(-15*u,-85*u,30*u,11*u);c.strokeStyle="#40e889";c.lineWidth=3*u;c.beginPath();c.arc(0,-71*u,18*u,.15,Math.PI-.15);c.stroke();c.restore();}
  function drawWaldo(c,x,y,h){var u=h/100;c.save();c.translate(x,y);c.fillStyle="#151920";rr(c,-24*u,-64*u,48*u,64*u,10*u);c.fill();c.fillStyle="#c98a5b";c.beginPath();c.arc(0,-76*u,14*u,0,Math.PI*2);c.fill();c.fillStyle="#0e1116";c.beginPath();c.arc(0,-82*u,15*u,Math.PI,0);c.fill();c.fillRect(-15*u,-84*u,30*u,9*u);c.restore();}
  function phaseOverlay(c,s,w,h){if(s.phase==="orbital"){c.fillStyle="rgba(37,20,58,.18)";c.fillRect(0,0,w,h);c.fillStyle="rgba(130,73,184,.12)";for(var y=0;y<h;y+=5)c.fillRect(0,y,w,1);c.strokeStyle="rgba(167,86,255,.55)";}else c.strokeStyle="rgba(78,216,255,.38)";c.lineWidth=8;c.strokeRect(3,3,w-6,h-6);}
  function nearest(s){var all=[];STATIC.forEach(function(o){if(s.staticCollected.indexOf(o.id)<0)all.push({type:"static",id:o.id,x:o.x,y:o.y,label:"TUNE STATIC"});});DOGS.forEach(function(o){all.push({type:"dog",id:o.id,x:o.x,y:o.y,label:"PET DOG"});});GROUNDING.forEach(function(o){all.push({type:"ground",id:o.id,x:o.x,y:o.y,label:o.label});});if(!s.inventory.empty_bottle)all.push({type:"bottle",id:"empty_bottle",x:620,y:720,label:"CHECK TRASH CAN"});if(!s.gasChoice)all.push({type:"gas",id:"gas",x:GAS.x,y:GAS.y,label:"GAS STATION"});if(s.x>W*5-120)all.push({type:"porch",id:"porch",x:PORCH.x,y:PORCH.y,label:"WALDO'S PORCH"});var best=null,bd=Infinity;all.forEach(function(o){var d=dist(s.x,s.y,o.x,o.y);if(d<bd){best=o;bd=d;}});return bd<=120?best:null;}
  function objective(s){if(s.x<W)return"Walk east. No rush.";if(s.x<W*2)return s.phase==="orbital"?"The camera is not Cell 118. Keep moving.":"Convenience store · keep your own pace.";if(s.x<W*3)return"Underpass · the city keeps going.";if(s.x<W*4)return"Dog park · something living recognizes you.";if(s.x<W*5)return s.gasChoice?"Keep walking.":"Gas station ahead · enter or pass.";return"Amber porch light. Waldo's place.";}
  function closePause(){if(!runtime)return;var p=root.document&&root.document.getElementById("east-side-pause");if(p)p.classList.remove("active");runtime.paused=false;}
  function gasChoice(){runtime.paused=true;var p=root.document.getElementById("east-side-pause");p.innerHTML="<h2>GAS STATION LIGHTS</h2><p>Two in the morning, even when the clock says otherwise.</p><button id='es-enter'>ENTER</button> <button id='es-pass'>WALK PAST</button>";p.classList.add("active");p.querySelector("#es-enter").onclick=function(){chooseGas(true);closePause();runtime.msg="The fluorescent hum becomes the station again.";runtime.msgT=3;};p.querySelector("#es-pass").onclick=function(){chooseGas(false);closePause();runtime.msg="You keep the sidewalk under your feet.";runtime.msgT=2.4;};}
  function pause(){if(!runtime||runtime.cutscene)return;var p=root.document.getElementById("east-side-pause");if(p.classList.contains("active")){closePause();return;}var s=ensure(),html="<h2>EAST SIDE // STATIC</h2><p>"+s.staticCollected.length+"/7 frequencies recovered.</p>";for(var i=0;i<7;i++)html+="<div class='"+(s.lyrics.indexOf(i)>=0?"frag":"locked")+"'>"+(s.lyrics.indexOf(i)>=0?LYRIC_FRAGMENTS[i]:"[ STATIC ]")+"</div>";if(s.fullStaticUnlocked)html+="<p><b>EAST SIDE (FULL STATIC)</b> unlocked in MUSIC.</p>";p.innerHTML=html;p.classList.add("active");runtime.paused=true;}
  function interact(){if(!runtime||runtime.cutscene)return false;var s=ensure(),o=nearest(s);if(!o||!interactionAllowed(s.phase,o.type))return false;if(o.type==="static")addStatic(o.id);else if(o.type==="dog")petDog(o.id);else if(o.type==="ground")ground(o.id);else if(o.type==="bottle")collectBottle();else if(o.type==="gas"){gasChoice();return true;}else if(o.type==="porch"){beginRecognition();return true;}runtime.msg=o.type==="static"?"STATIC FOUND · "+s.staticCollected.length+"/7":o.type==="dog"?"GROUNDING · warm fur, wet pavement, present tense":"GROUNDING";runtime.msgT=2.2;return true;}
  function beginRecognition(){if(!goodDogsComplete())return false;var s=ensure();s.knockCount=0;persist();runtime.cutscene={phase:"knock",t:0};runtime.keys={};runtime.msg="KNOCK · four taps";runtime.msgT=99;return true;}
  function knock(){if(!runtime||!runtime.cutscene||runtime.cutscene.phase!=="knock")return false;var s=ensure();s.knockCount=(s.knockCount||0)+1;runtime.knockFlash=.18;if(s.knockCount>=4){runtime.cutscene.phase="timeline";runtime.cutscene.t=0;runtime.msg="";if(runtime.audio)runtime.audio.stop();}persist();return true;}
  function recognitionBeat(ms){if(ms<4000)return{label:"Door opens.",waldo:false};if(ms<8000)return{label:"",waldo:true};if(ms<13000)return{label:"Only rain.",waldo:true};if(ms<21000)return{label:"K removes his headphones.",waldo:true};if(ms<30000)return{label:"K: \"I don't feel like I landed.\"",waldo:true};if(ms<38000)return{label:"Waldo: \"You did. Ground's just loud.\"",waldo:true};if(ms<45000)return{label:"Waldo steps aside.",waldo:true};return{label:"complete",waldo:true};}
  function finishRecognition(){complete();runtime.fade=1;runtime.finished=true;if(root.setTimeout)root.setTimeout(function(){stop();try{if(typeof root.toast==="function")root.toast("EAST SIDE complete · Ghost Fork unlocked",4200);}catch(_){}},800);}
  function forced(s){ANCHORS.forEach(function(a){if(s.anchorsSeen.indexOf(a.id)<0&&dist(s.x,s.y,a.x,a.y)<=a.r){if(triggerAnchor(a.id)&&runtime){runtime.msg=a.label+" · ORBITAL";runtime.msgT=2.3;}}});if(s.x>=W*5&&!s.porchPhaseLocked){s.porchPhaseLocked=true;setPhase("orbital","Waldo street",true);persist();}}
  function update(dt){if(!runtime||runtime.paused||runtime.finished)return;var s=ensure();if(runtime.cutscene){if(runtime.cutscene.phase==="timeline"){runtime.cutscene.t+=dt*1000;if(runtime.cutscene.t>=45000)finishRecognition();}return;}var dx=(runtime.keys.ArrowRight||runtime.keys.d?1:0)-(runtime.keys.ArrowLeft||runtime.keys.a?1:0),dy=(runtime.keys.ArrowDown||runtime.keys.s?1:0)-(runtime.keys.ArrowUp||runtime.keys.w?1:0);if(dx||dy){var l=Math.sqrt(dx*dx+dy*dy),sp=SPEED[s.phase];s.x=clamp(s.x+dx/l*sp*dt,70,WORLD_W-80);s.y=clamp(s.y+dy/l*sp*dt,250,WORLD_H-70);runtime.idleT=0;}else runtime.idleT+=dt;if(s.x>W&&s.x<W*2&&runtime.idleT>2.2&&s.anchorsSeen.indexOf("camera")<0)triggerAnchor("camera");forced(s);if(runtime.msgT>0)runtime.msgT-=dt;if(runtime.audio){var hit=runtime.audio.tick();if(hit!==null)runtime.refrain={t:.18,phase:s.phase};}if(runtime.refrain)runtime.refrain.t-=dt;runtime.saveT+=dt;if(runtime.saveT>1.5){runtime.saveT=0;persist();}}
  function draw(){
    if(!runtime||!runtime.ctx)return;var canvas=runtime.canvas,ctx=runtime.ctx,s=ensure();if(!s)return;
    var vw=canvas.width,vh=canvas.height,scale=Math.min(vw/W,vh/H),viewW=vw/scale,viewH=vh/scale;
    var camX=clamp(s.x-viewW*.45,0,Math.max(0,WORLD_W-viewW)),camY=clamp(s.y-viewH*.60,0,Math.max(0,WORLD_H-viewH));
    ctx.save();ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,viewW,viewH);for(var i=0;i<COLS;i++)backdrop(ctx,i,camX,camY);
    ctx.strokeStyle=s.phase==="orbital"?"rgba(180,170,220,.18)":"rgba(145,206,230,.30)";for(var r=0;r<70;r++){var rx=(r*137+now()/8)%viewW,ry=(r*83+now()/3)%viewH;ctx.beginPath();ctx.moveTo(rx,ry);ctx.lineTo(rx-5,ry+12);ctx.stroke();}
    ctx.fillStyle="#ffb84e";ctx.shadowColor="#ffb84e";ctx.shadowBlur=22;ctx.fillRect(5488-camX,475-camY,34,54);ctx.shadowBlur=0;
    STATIC.forEach(function(o){if(s.staticCollected.indexOf(o.id)>=0)return;ctx.fillStyle="#b07cff";ctx.fillRect(o.x-camX-7,o.y-camY-7,14,14);});
    DOGS.forEach(function(o){ctx.fillStyle=s.dogsPetted.indexOf(o.id)>=0?"#79d9ff":"#d49a4d";ctx.fillRect(o.x-camX-16,o.y-camY-22,32,18);});
    drawK(ctx,s.x-camX,s.y-camY,92,!!(runtime.keys.ArrowLeft||runtime.keys.a));
    if(runtime.cutscene&&runtime.cutscene.phase==="timeline"){var beat=recognitionBeat(runtime.cutscene.t);if(beat.waldo)drawWaldo(ctx,PORCH.x-camX+100,PORCH.y-camY,96);ctx.fillStyle="rgba(2,4,8,.62)";ctx.fillRect(0,viewH-92,viewW,92);ctx.fillStyle="#f3f5f7";ctx.font="11px monospace";ctx.textAlign="center";ctx.fillText(beat.label,viewW/2,viewH-45);}ctx.restore();
    ctx.save();phaseOverlay(ctx,s,vw,vh);if(runtime.refrain&&runtime.refrain.t>0){ctx.fillStyle=runtime.refrain.phase==="orbital"?"rgba(255,45,45,.32)":"rgba(50,220,255,.28)";ctx.fillRect(0,0,vw,vh);}if(runtime.knockFlash>0){ctx.fillStyle="rgba(255,184,78,.22)";ctx.fillRect(0,0,vw,vh);runtime.knockFlash-=.016;}if(runtime.fade){ctx.fillStyle="rgba(0,0,0,"+runtime.fade+")";ctx.fillRect(0,0,vw,vh);}ctx.restore();
    var obj=root.document&&root.document.querySelector("#east-side-root .es-objective");if(obj)obj.textContent=runtime.cutscene?(runtime.cutscene.phase==="knock"?"KNOCK · "+(s.knockCount||0)+"/4":recognitionBeat(runtime.cutscene.t).label):(runtime.msgT>0?runtime.msg:((nearest(s)||{}).label||objective(s)));
  }
  function frame(ts){if(!runtime)return;var dt=Math.min(.05,Math.max(0,(ts-runtime.last)/1000));runtime.last=ts;update(dt);draw();runtime.raf=(root.requestAnimationFrame||function(fn){return root.setTimeout(function(){fn(now());},16);})(frame);}
  function resize(){if(!runtime)return;var d=Math.min(2,root.devicePixelRatio||1);runtime.canvas.width=Math.max(1,Math.round(root.innerWidth*d));runtime.canvas.height=Math.max(1,Math.round(root.innerHeight*d));}
  function bind(id,key){var e=root.document.getElementById(id);if(!e)return;function dn(ev){ev.preventDefault();runtime.keys[key]=true;}function up(ev){ev.preventDefault();runtime.keys[key]=false;}e.addEventListener("pointerdown",dn);e.addEventListener("pointerup",up);e.addEventListener("pointercancel",up);}
  function start(opts){opts=opts||{};var s=ensure();if(!s||!canStart())return false;if(runtime)return true;if(s.completed&&opts.replay)resetForReplay();else{s.started=true;s.startedAt=s.startedAt||Date.now();persist();}if(!root.document)return true;injectStyle();var host=root.document.createElement("div");host.id="east-side-root";host.innerHTML="<canvas id='east-side-canvas'></canvas><div class='es-title'>EAST SIDE // K // 72 HOURS AFTER REENTRY</div><div class='es-objective'></div><div id='east-side-pause' class='es-pause'></div><div id='east-side-touch'><div class='es-pad'><button id='es-up' class='es-up'>▲</button><button id='es-left' class='es-left'>◀</button><button id='es-right' class='es-right'>▶</button><button id='es-down' class='es-down'>▼</button></div><button id='es-use' class='es-use'>USE</button></div>";root.document.body.appendChild(host);runtime={keys:{},last:now(),msg:"",msgT:0,paused:false,cutscene:null,finished:false,fade:0,knockFlash:0,idleT:0,saveT:0,audio:makeAudio(),canvas:host.querySelector("canvas"),root:host};runtime.ctx=runtime.canvas.getContext("2d");resize();root.addEventListener("resize",resize);runtime.kd=function(e){if(["j","k","l","z","x","Shift"].indexOf(e.key)>=0){e.preventDefault();return;}if(e.key==="Escape"||e.key==="p"||e.key==="P"){e.preventDefault();pause();return;}if(e.key==="e"||e.key==="E"||e.key===" "){e.preventDefault();if(runtime.cutscene&&runtime.cutscene.phase==="knock")knock();else interact();return;}runtime.keys[e.key]=true;};runtime.ku=function(e){runtime.keys[e.key]=false;};root.addEventListener("keydown",runtime.kd,true);root.addEventListener("keyup",runtime.ku,true);bind("es-up","ArrowUp");bind("es-down","ArrowDown");bind("es-left","ArrowLeft");bind("es-right","ArrowRight");host.querySelector("#es-use").addEventListener("pointerdown",function(e){e.preventDefault();if(runtime.cutscene&&runtime.cutscene.phase==="knock")knock();else interact();});if(runtime.audio)runtime.audio.play();frame(runtime.last);return true;}
  function stop(){if(!runtime)return false;try{if(runtime.audio)runtime.audio.stop();if(runtime.raf)(root.cancelAnimationFrame||root.clearTimeout)(runtime.raf);root.removeEventListener("resize",resize);root.removeEventListener("keydown",runtime.kd,true);root.removeEventListener("keyup",runtime.ku,true);if(runtime.root&&runtime.root.parentNode)runtime.root.parentNode.removeChild(runtime.root);}catch(_){}runtime=null;return true;}
  function isActive(){return!!runtime;}
  function blockGhostFork(id){return/^gk[1-6]$/.test(String(id||""))&&!ghostForkUnlocked();}
  function installGhostForkGate(){var c=root.v725;if(!c||typeof c.play!=="function")return false;if(c.play.__eastSideGate)return true;var base=c.play;c.play=function(id){if(blockGhostFork(id)){try{if(goodDogsComplete()&&typeof root.toast==="function")root.toast("EAST SIDE must be completed before Ghost Fork.",3600);}catch(_){}if(goodDogsComplete()&&!isActive())scheduleAuto(400);return false;}return base.apply(this,arguments);};c.play.__eastSideGate=true;c.play.__eastSideBase=base;return true;}
  function installMusicEntry(){if(typeof root.dlg!=="function"||root.dlg.__eastSideMusicEntry)return false;var base=root.dlg;root.dlg=function(name,body,options){if(String(name||"").toUpperCase()==="WORKSTATION // MUSIC"&&goodDogsComplete()){options=Array.isArray(options)?options.slice():[];var s=ensure(),label=s.completed?"Replay EAST SIDE":s.started?"Resume EAST SIDE":"Play EAST SIDE — The Missing Chapter";options.unshift({t:label,f:function(){try{if(typeof root.closeDlg==="function")root.closeDlg();}catch(_){}start({replay:!!s.completed});}});if(s.fullStaticUnlocked)options.unshift({t:"EAST SIDE (Full Static) — unlocked",f:function(){try{if(typeof root.toast==="function")root.toast("Full Static mix unlocked. Authored audio asset required for playback.",3800);}catch(_){}}});}return base.call(this,name,body,options);};root.dlg.__eastSideMusicEntry=true;return true;}
  function canAuto(){if(!root.document||!goodDogsComplete())return false;var s=ensure();if(!s||s.completed||s.started||runtime)return false;if(root.document.querySelector("#good-dogs-cutscene-overlay.active,.cinematic-overlay.active,#cinematic.active"))return false;if(root.S&&root.S.inDialog)return false;return true;}
  function scheduleAuto(delay){if(!root.setTimeout)return false;if(autoTimer)root.clearTimeout(autoTimer);autoTimer=root.setTimeout(function attempt(){autoTimer=null;if(canAuto()){start();return;}var s=ensure();if(s&&!s.completed&&!s.started&&goodDogsComplete())autoTimer=root.setTimeout(attempt,1200);},delay||2600);return true;}
  function install(){ensure();installGhostForkGate();installMusicEntry();if(root.setInterval&&!installTimer)installTimer=root.setInterval(function(){installGhostForkGate();installMusicEntry();var s=ensure();if(s&&s.unlocked&&!s.completed&&!s.started&&goodDogsComplete()&&!autoTimer)scheduleAuto(2200);},700);if(goodDogsComplete())scheduleAuto(2800);return true;}
  var API={VERSION:VERSION,SCHEMA:SCHEMA,W:W,H:H,COLS:COLS,ROWS:ROWS,WORLD_W:WORLD_W,WORLD_H:WORLD_H,AUDIO:AUDIO,LYRIC_FRAGMENTS:LYRIC_FRAGMENTS.slice(),STATIC:STATIC.slice(),DOGS:DOGS.slice(),ANCHORS:ANCHORS.slice(),GROUNDING:GROUNDING.slice(),ensure:ensure,snapshot:snapshot,persist:persist,goodDogsComplete:goodDogsComplete,legacyGhostForkStarted:legacyGhostForkStarted,canStart:canStart,setPhase:setPhase,addStatic:addStatic,triggerAnchor:triggerAnchor,ground:ground,petDog:petDog,chooseGas:chooseGas,collectBottle:collectBottle,complete:complete,ghostForkUnlocked:ghostForkUnlocked,resetForReplay:resetForReplay,setRefrainTimes:setRefrainTimes,refrainDue:refrainDue,interactionAllowed:interactionAllowed,nearestInteractable:nearest,objective:objective,recognitionBeat:recognitionBeat,blockGhostFork:blockGhostFork,installGhostForkGate:installGhostForkGate,installMusicEntry:installMusicEntry,start:start,stop:stop,isActive:isActive,install:install};install();return API;
});
