/* TechOps Hero — EAST SIDE: The Missing Chapter v1.0
 * Canonical bridge: Good Dogs Protocol -> Ghost Fork.
 * Player: K. No combat. Six-by-two New Haven walk with psychological phase state.
 */
(function(root,factory){
  var api=factory(root||{});
  if(typeof module==="object"&&module.exports)module.exports=api;
  if(root)root.TechOpsEastSide=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";
  var VERSION=1,SCHEMA=1,W=960,H=540,COLS=6,ROWS=2,WORLD_W=W*COLS,WORLD_H=H*ROWS;
  var SPEED={grounded:145,orbital:78},ORBITAL_THRESHOLD=55;
  var AUDIO_BASE="assets/audio/eastside/";
  var AUDIO={grounded:AUDIO_BASE+"eastside_grounded.ogg",orbital:AUDIO_BASE+"eastside_orbital.ogg",static:AUDIO_BASE+"static_burst.wav",breathing:AUDIO_BASE+"breathing_mechanical.wav"};
  var LYRIC_FRAGMENTS=["Bottle half-empty","chasing the static","mask on an angel","strings on my wrists","Everything dead got a habit of lingering","Gas station lights / Two in the morning","EAST SIDE!"];
  var STATIC=[
    {id:"radio_1",kind:"radio",x:860,y:680,fragment:0},{id:"phone_1",kind:"phone",x:1530,y:610,fragment:1},
    {id:"cig_1",kind:"cigarette",x:2210,y:735,fragment:2},{id:"radio_2",kind:"radio",x:2910,y:420,fragment:3},
    {id:"phone_2",kind:"phone",x:3610,y:680,fragment:4},{id:"cig_2",kind:"cigarette",x:4310,y:605,fragment:5},
    {id:"radio_3",kind:"radio",x:4920,y:700,fragment:6}
  ];
  var DOGS=[{id:"dog_1",x:3230,y:650},{id:"dog_2",x:3450,y:720},{id:"dog_3",x:3650,y:620}];
  var ANCHORS=[
    {id:"bottle",x:760,y:690,r:95,label:"BOTTLED WATER"},{id:"camera",x:1670,y:560,r:115,label:"RED CAMERA LIGHT"},
    {id:"grate",x:2540,y:690,r:105,label:"VENTILATION GRATE"},{id:"cuffs",x:4460,y:655,r:105,label:"HANDCUFFS"}
  ];
  var GROUNDING=[{id:"coffee",x:1160,y:690,r:95,label:"COFFEE"},{id:"bench",x:3010,y:710,r:105,label:"BENCH"},{id:"rain",x:3920,y:580,r:110,label:"LISTEN TO RAIN"}];
  var GAS={x:4460,y:560,r:180},PORCH={x:5520,y:610,r:145};
  var REFRAIN_TIMES_MS=[],runtime=null,installTimer=null,autoTimer=null;

  function perfNow(){return root.performance&&root.performance.now?root.performance.now():Date.now();}
  function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
  function distance(ax,ay,bx,by){var dx=ax-bx,dy=ay-by;return Math.sqrt(dx*dx+dy*dy);}
  function story(){return root.S&&root.S.story?root.S.story:null;}
  function facts(){var s=story();if(!s)return{};s.facts=s.facts||{};return s.facts;}
  function goodDogsComplete(){var f=facts(),m=root.S&&root.S.meta||{},g=m.goodDogs||{};return!!(f.good_dogs_protocol_complete||m.good_dogs_protocol_complete||g.good_dogs_protocol_complete);}
  function legacyGhostForkStarted(){var m=root.S&&root.S.meta||{};for(var i=1;i<=6;i++)if(m["_v734gk"+i])return true;return false;}
  function ensure(){
    if(!root.S)return null;root.S.meta=root.S.meta||{};var s=root.S.meta.eastSide||(root.S.meta.eastSide={});
    s.schemaVersion=SCHEMA;if(!s.phase)s.phase="grounded";if(!Number.isFinite(s.orbitalMeter))s.orbitalMeter=0;
    if(!Number.isFinite(s.x))s.x=260;if(!Number.isFinite(s.y))s.y=680;
    s.staticCollected=Array.isArray(s.staticCollected)?s.staticCollected:[];s.dogsPetted=Array.isArray(s.dogsPetted)?s.dogsPetted:[];
    s.anchorsSeen=Array.isArray(s.anchorsSeen)?s.anchorsSeen:[];s.groundingSeen=Array.isArray(s.groundingSeen)?s.groundingSeen:[];
    s.inventory=s.inventory||{};s.lyrics=Array.isArray(s.lyrics)?s.lyrics:[];s.unlocked=!!(s.unlocked||goodDogsComplete());
    if(legacyGhostForkStarted()&&!s.completed)s.legacyGhostFork=true;return s;
  }
  function persist(){try{if(typeof root.save==="function")return root.save()!==false;if(typeof root.saveGame==="function")return root.saveGame()!==false;}catch(e){root.__eastSideSaveError=String(e&&e.stack||e);}return false;}
  function snapshot(){var s=ensure()||{};return JSON.parse(JSON.stringify({schemaVersion:s.schemaVersion,unlocked:!!s.unlocked,started:!!s.started,completed:!!s.completed,phase:s.phase,orbitalMeter:s.orbitalMeter,x:s.x,y:s.y,staticCollected:s.staticCollected||[],dogsPetted:s.dogsPetted||[],anchorsSeen:s.anchorsSeen||[],groundingSeen:s.groundingSeen||[],inventory:s.inventory||{},lyrics:s.lyrics||[],gasChoice:s.gasChoice||null,knockCount:s.knockCount||0,fullStaticUnlocked:!!s.fullStaticUnlocked,kLanded:!!s.kLanded,legacyGhostFork:!!s.legacyGhostFork}));}
  function writeFact(name,value){var f=facts();f[name]=value===undefined?true:value;if(root.S&&root.S.meta)root.S.meta[name]=value===undefined?true:value;}
  function setPhase(next,reason,forced){var s=ensure();if(!s)return null;next=next==="orbital"?"orbital":"grounded";if(s.phase!==next){s.phase=next;s.phaseReason=reason||"environment";s.phaseChangedAt=Date.now();}if(next==="orbital"&&forced)s.orbitalMeter=Math.max(s.orbitalMeter,70);if(next==="grounded")s.orbitalMeter=Math.min(s.orbitalMeter,20);if(runtime&&runtime.audio)runtime.audio.phase(next);if(runtime)runtime.phaseFlash={t:.55,phase:next};persist();return s.phase;}
  function addStatic(id){var s=ensure(),item=STATIC.find(function(x){return x.id===id;});if(!s||!item||s.staticCollected.indexOf(id)>=0)return false;s.staticCollected.push(id);s.orbitalMeter=clamp(s.orbitalMeter+10,0,100);if(s.lyrics.indexOf(item.fragment)<0)s.lyrics.push(item.fragment);if(s.staticCollected.length===STATIC.length){s.fullStaticUnlocked=true;writeFact("eastside_full_static_unlocked",true);}if(s.orbitalMeter>=ORBITAL_THRESHOLD)setPhase("orbital","static buildup",false);persist();return true;}
  function triggerAnchor(id){var s=ensure(),a=ANCHORS.find(function(x){return x.id===id;});if(!s||!a)return false;if(s.anchorsSeen.indexOf(id)<0)s.anchorsSeen.push(id);s.orbitalMeter=clamp(s.orbitalMeter+24,0,100);setPhase("orbital",a.label,true);if(runtime&&runtime.audio)runtime.audio.trauma();persist();return true;}
  function ground(id){var s=ensure();if(!s)return false;if(s.groundingSeen.indexOf(id)<0)s.groundingSeen.push(id);s.orbitalMeter=Math.max(0,s.orbitalMeter-40);setPhase("grounded",id,false);if(runtime&&runtime.audio)runtime.audio.ground();persist();return true;}
  function petDog(id){var s=ensure(),d=DOGS.find(function(x){return x.id===id;});if(!s||!d)return false;if(s.dogsPetted.indexOf(id)<0){s.dogsPetted.push(id);s.inventory.ghost=(s.inventory.ghost||0)+1;}ground(id);persist();return true;}
  function chooseGas(enter){var s=ensure();if(!s||s.gasChoice)return false;s.gasChoice=enter?"enter":"pass";if(enter){s.orbitalMeter=clamp(s.orbitalMeter+28,0,100);setPhase("orbital","gas station memory",true);}else ground("gas_station_pass");persist();return true;}
  function collectBottle(){var s=ensure();if(!s||s.inventory.empty_bottle)return false;s.inventory.empty_bottle=true;s.orbitalMeter=clamp(s.orbitalMeter+5,0,100);persist();return true;}
  function canStart(){var s=ensure();return!!(s&&s.unlocked&&goodDogsComplete());}
  function ghostForkUnlocked(){var s=ensure();return!!(s&&(s.completed||s.legacyGhostFork||facts().ghost_fork_unlocked));}
  function complete(){var s=ensure();if(!s)return false;s.completed=true;s.kLanded=true;s.phase="grounded";s.orbitalMeter=0;s.completedAt=Date.now();s.inventory.k_headphones=true;writeFact("k_landed",true);writeFact("ghost_fork_unlocked",true);writeFact("eastside_completed",true);writeFact("k_headphones",true);persist();return true;}
  function resetForReplay(){var s=ensure();if(!s)return false;s.x=260;s.y=680;s.phase="grounded";s.orbitalMeter=0;s.knockCount=0;s.started=true;s.replay=true;persist();return true;}
  function setRefrainTimes(times){REFRAIN_TIMES_MS=(Array.isArray(times)?times:[]).map(Number).filter(Number.isFinite).sort(function(a,b){return a-b;});return REFRAIN_TIMES_MS.slice();}
  function refrainDue(prevMs,curMs,tolerance){tolerance=Number.isFinite(tolerance)?tolerance:50;for(var i=0;i<REFRAIN_TIMES_MS.length;i++){var t=REFRAIN_TIMES_MS[i];if(t>prevMs-tolerance&&t<=curMs+tolerance)return t;}return null;}

  function makeAudio(){
    if(!root.document)return null;var grounded=root.document.createElement("audio"),orbital=root.document.createElement("audio"),staticFx=root.document.createElement("audio"),breath=root.document.createElement("audio");
    grounded.preload=orbital.preload=staticFx.preload=breath.preload="auto";grounded.src=AUDIO.grounded;orbital.src=AUDIO.orbital;staticFx.src=AUDIO.static;breath.src=AUDIO.breathing;grounded.loop=orbital.loop=breath.loop=true;
    var missing={};[["grounded",grounded],["orbital",orbital],["static",staticFx],["breathing",breath]].forEach(function(p){p[1].addEventListener("error",function(){missing[p[0]]=true;});});
    var deck={grounded:grounded,orbital:orbital,staticFx:staticFx,breath:breath,missing:missing,duck:1,lastTime:0};
    deck.play=function(){var t=Math.max(grounded.currentTime||0,orbital.currentTime||0);try{grounded.currentTime=t;orbital.currentTime=t;}catch(_){}[grounded,orbital,breath].forEach(function(a){try{var p=a.play();if(p&&p.catch)p.catch(function(){});}catch(_){}});deck.phase((ensure()||{}).phase||"grounded");};
    deck.phase=function(phase){var base=deck.duck;grounded.volume=phase==="grounded"?.40*base:.02*base;orbital.volume=phase==="orbital"?.80*base:.03*base;breath.volume=phase==="orbital"?.34*base:0;};
    deck.trauma=function(){deck.duck=.2;deck.phase("orbital");try{staticFx.currentTime=0;staticFx.volume=.7;var p=staticFx.play();if(p&&p.catch)p.catch(function(){});}catch(_){}if(root.setTimeout)root.setTimeout(function(){deck.duck=1;deck.phase((ensure()||{}).phase);},900);};
    deck.ground=function(){deck.duck=1;deck.phase("grounded");};deck.stop=function(){[grounded,orbital,staticFx,breath].forEach(function(a){try{a.pause();}catch(_){}});};
    deck.tick=function(){var cur=Math.round(Math.max(grounded.currentTime||0,orbital.currentTime||0)*1000),hit=refrainDue(deck.lastTime,cur,50);deck.lastTime=cur;return hit;};return deck;
  }
  function injectStyle(){if(!root.document||root.document.getElementById("east-side-style"))return;var st=root.document.createElement("style");st.id="east-side-style";st.textContent="#east-side-root{position:fixed;inset:0;z-index:2147482000;background:#050912;color:#eef7ff;font-family:'Press Start 2P',monospace;overflow:hidden;touch-action:none}#east-side-canvas{width:100%;height:100%;display:block;image-rendering:pixelated}#east-side-hud{position:absolute;inset:0;pointer-events:none}.es-title{position:absolute;left:18px;top:max(18px,env(safe-area-inset-top));font-size:10px;letter-spacing:2px;text-shadow:0 2px #000}.es-objective{position:absolute;left:50%;transform:translateX(-50%);bottom:max(22px,env(safe-area-inset-bottom));padding:10px 14px;background:rgba(3,7,12,.74);border:1px solid rgba(255,190,79,.38);font-size:8px;line-height:1.5;text-align:center;max-width:78%}.es-pause{position:absolute;inset:8% 10%;background:rgba(4,8,15,.96);border:2px solid #68d7ff;padding:24px;overflow:auto;display:none;pointer-events:auto;line-height:1.7;font-size:8px}.es-pause.active{display:block}.es-pause h2{color:#68d7ff;font-size:13px}.es-pause .frag{color:#d5d9e4;margin:11px 0}.es-pause .locked{color:#4b5568}#east-side-touch{position:absolute;inset:0;pointer-events:none}.es-pad,.es-use{position:absolute;pointer-events:auto;user-select:none;-webkit-user-select:none}.es-pad{left:18px;bottom:max(18px,env(safe-area-inset-bottom));width:150px;height:150px}.es-pad button,.es-use{border:1px solid rgba(126,255,205,.45);background:rgba(5,14,20,.72);color:#eafff5;font:9px 'Press Start 2P',monospace}.es-pad button{position:absolute;width:48px;height:48px;border-radius:14px}.es-up{left:51px;top:0}.es-down{left:51px;bottom:0}.es-left{left:0;top:51px}.es-right{right:0;top:51px}.es-use{right:24px;bottom:max(35px,env(safe-area-inset-bottom));width:92px;height:92px;border-radius:50%}@media(min-width:900px) and (pointer:fine){#east-side-touch{display:none}}@media(prefers-reduced-motion:reduce){#east-side-root *{animation:none!important}}";(root.document.head||root.document.documentElement).appendChild(st);}
  function rr(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
  function drawPixelCity(c,screen,camX,camY){var lx=screen*W-camX,p=[["#101b2a","#20374a","#3f6170"],["#111522","#263042","#445168"],["#12121b","#29243a","#50405d"],["#0c1716","#203b32","#3f6550"],["#16110f","#403128","#7a5f41"],["#10131b","#242c3b","#4d5a70"]][screen%6];c.fillStyle=p[0];c.fillRect(lx,-camY,W,WORLD_H);for(var row=0;row<2;row++){var base=row*H+H-85-camY;for(var i=0;i<7;i++){var bw=90+(i%3)*35,bh=130+(i*37%170),bx=lx+i*145-20;c.fillStyle=p[1];c.fillRect(bx,base-bh,bw,bh);c.fillStyle=p[2];for(var wx=bx+14;wx<bx+bw-10;wx+=28)for(var wy=base-bh+18;wy<base-18;wy+=30)if((i+wx+wy)%5)c.fillRect(wx,wy,8,10);}c.fillStyle="#18222b";c.fillRect(lx,base,W,85);}}
  function drawBackdrop(c,screen,camX,camY){var ids=["industrial","downtown","industrial","suburbs","longwharf","suburbs"],im=root.NM_BG734&&root.NM_BG734[ids[screen]];if(im&&im.complete&&im.naturalWidth){var dx=screen*W-camX;for(var row=0;row<2;row++)c.drawImage(im,dx,row*H-camY,W,H);}else drawPixelCity(c,screen,camX,camY);}
  function drawK(c,x,y,h,flip){try{var A=root.K_STUDIO,src=root.TO_K_STUDIO;if(A&&A.frames&&src){runtime.kImage=runtime.kImage||new root.Image();if(!runtime.kImage.src)runtime.kImage.src=src;var im=runtime.kImage,fr=A.frames.studio0||A.frames[Object.keys(A.frames)[0]],C=A.cell||fr[2],CH=A.cellH||C;if(im.complete&&im.naturalWidth){c.save();c.imageSmoothingEnabled=false;if(flip){c.translate(x,0);c.scale(-1,1);c.drawImage(im,fr[0]*C,fr[1]*CH,C,CH,-h*.42,y-h,h*.84,h);}else c.drawImage(im,fr[0]*C,fr[1]*CH,C,CH,x-h*.42,y-h,h*.84,h);c.restore();return;}}}catch(_){}var u=h/100;c.save();c.translate(x,y);c.fillStyle="#15241f";rr(c,-18*u,-58*u,36*u,55*u,7*u);c.fill();c.fillStyle="#b9855a";c.beginPath();c.arc(0,-70*u,14*u,0,Math.PI*2);c.fill();c.fillStyle="#12171a";c.fillRect(-15*u,-85*u,30*u,11*u);c.strokeStyle="#40e889";c.lineWidth=3*u;c.beginPath();c.arc(0,-71*u,18*u,.15,Math.PI-.15);c.stroke();c.restore();}
  function drawWaldo(c,x,y,h){var u=h/100;c.save();c.translate(x,y);c.fillStyle="#151920";rr(c,-24*u,-64*u,48*u,64*u,10*u);c.fill();c.fillStyle="#c98a5b";c.beginPath();c.arc(0,-76*u,14*u,0,Math.PI*2);c.fill();c.fillStyle="#0e1116";c.beginPath();c.arc(0,-82*u,15*u,Math.PI,0);c.fill();c.fillRect(-15*u,-84*u,30*u,9*u);c.restore();}
  function phaseFilter(c,s,w,h){if(s.phase==="orbital"){c.fillStyle="rgba(37,20,58,.18)";c.fillRect(0,0,w,h);c.fillStyle="rgba(130,73,184,.12)";for(var y=0;y<h;y+=5)c.fillRect(0,y,w,1);c.strokeStyle="rgba(167,86,255,.55)";c.lineWidth=9;c.strokeRect(3,3,w-6,h-6);}else{c.strokeStyle="rgba(78,216,255,.38)";c.lineWidth=8;c.strokeRect(3,3,w-6,h-6);}}
  function nearestInteractable(s){var all=[];STATIC.forEach(function(o){if(s.staticCollected.indexOf(o.id)<0)all.push({type:"static",id:o.id,x:o.x,y:o.y,label:"TUNE STATIC"});});DOGS.forEach(function(o){all.push({type:"dog",id:o.id,x:o.x,y:o.y,label:"PET DOG"});});GROUNDING.forEach(function(o){all.push({type:"ground",id:o.id,x:o.x,y:o.y,label:o.label});});if(!s.inventory.empty_bottle)all.push({type:"bottle",id:"empty_bottle",x:620,y:720,label:"CHECK TRASH CAN"});if(!s.gasChoice)all.push({type:"gas",id:"gas",x:GAS.x,y:GAS.y,label:"GAS STATION"});if(s.x>W*5-120)all.push({type:"porch",id:"porch",x:PORCH.x,y:PORCH.y,label:"WALDO'S PORCH"});var best=null,bd=1e9;all.forEach(function(o){var d=distance(s.x,s.y,o.x,o.y);if(d<bd){bd=d;best=o;}});return bd<=120?best:null;}
  function objective(s){if(s.x<W)return"Walk east. No rush.";if(s.x<W*2)return s.phase==="orbital"?"The camera is not Cell 118. Keep moving.":"Convenience store · keep your own pace.";if(s.x<W*3)return"Underpass · the city keeps going.";if(s.x<W*4)return"Dog park · something living recognizes you.";if(s.x<W*5)return s.gasChoice?"Keep walking.":"Gas station ahead · enter or pass.";return"Amber porch light. Waldo's place.";}
  function closePause(){if(!runtime)return;var p=root.document&&root.document.getElementById("east-side-pause");if(p)p.classList.remove("active");runtime.paused=false;}
  function openGasChoice(){if(!runtime||!root.document)return;runtime.paused=true;var box=root.document.getElementById("east-side-pause");box.innerHTML="<h2>GAS STATION LIGHTS</h2><p>Two in the morning, even when the clock says otherwise.</p><button id='es-gas-enter'>ENTER</button> <button id='es-gas-pass'>WALK PAST</button>";box.classList.add("active");box.querySelector("#es-gas-enter").onclick=function(){chooseGas(true);closePause();runtime.msg="The fluorescent hum becomes the station again.";runtime.msgT=3;};box.querySelector("#es-gas-pass").onclick=function(){chooseGas(false);closePause();runtime.msg="You keep the sidewalk under your feet.";runtime.msgT=2.4;};}
  function togglePause(){if(!runtime||runtime.cutscene)return;var p=root.document.getElementById("east-side-pause");if(p.classList.contains("active")){closePause();return;}var s=ensure(),html="<h2>EAST SIDE // STATIC</h2><p>"+s.staticCollected.length+"/7 frequencies recovered.</p>";for(var i=0;i<LYRIC_FRAGMENTS.length;i++)html+="<div class='"+(s.lyrics.indexOf(i)>=0?"frag":"locked")+"'>"+(s.lyrics.indexOf(i)>=0?LYRIC_FRAGMENTS[i]:"[ STATIC ]")+"</div>";if(s.fullStaticUnlocked)html+="<p><b>EAST SIDE (FULL STATIC)</b> unlocked in MUSIC.</p>";html+="<p>Press ESC / P to return.</p>";p.innerHTML=html;p.classList.add("active");runtime.paused=true;}
  function interact(){if(!runtime||runtime.cutscene)return false;var s=ensure(),o=nearestInteractable(s);if(!o)return false;if(s.phase==="orbital"&&o.type!=="porch"&&o.type!=="static")return false;if(o.type==="static"){addStatic(o.id);runtime.msg="STATIC FOUND · "+s.staticCollected.length+"/7";runtime.msgT=2;return true;}if(o.type==="dog"){petDog(o.id);runtime.msg="GROUNDING · warm fur, wet pavement, present tense";runtime.msgT=2.4;return true;}if(o.type==="ground"){ground(o.id);runtime.msg="GROUNDING · "+o.label;runtime.msgT=2;return true;}if(o.type==="bottle"){collectBottle();runtime.msg="Bottle half-empty. Inventory: EMPTY BOTTLE.";runtime.msgT=2.6;return true;}if(o.type==="gas"){openGasChoice();return true;}if(o.type==="porch"){beginRecognition();return true;}return false;}
  function beginRecognition(){if(!goodDogsComplete())return false;var s=ensure();s.knockCount=0;persist();if(runtime){runtime.cutscene={phase:"knock",t:0};runtime.keys={};runtime.msg="KNOCK · four taps";runtime.msgT=99;}return true;}
  function knock(){if(!runtime||!runtime.cutscene||runtime.cutscene.phase!=="knock")return false;var s=ensure();s.knockCount=(s.knockCount||0)+1;runtime.knockFlash=.18;if(s.knockCount>=4){runtime.cutscene.phase="timeline";runtime.cutscene.t=0;runtime.msg="";runtime.msgT=0;if(runtime.audio)runtime.audio.stop();}persist();return true;}
  function recognitionBeat(ms){if(ms<4000)return{label:"Door opens.",waldo:false,headphones:true};if(ms<8000)return{label:"",waldo:true,headphones:true};if(ms<13000)return{label:"Only rain.",waldo:true,headphones:true};if(ms<21000)return{label:"K removes his headphones.",waldo:true,headphones:false};if(ms<30000)return{label:"K: \"I don't feel like I landed.\"",waldo:true,headphones:false};if(ms<38000)return{label:"Waldo: \"You did. Ground's just loud.\"",waldo:true,headphones:false};if(ms<45000)return{label:"Waldo steps aside.",waldo:true,headphones:false};return{label:"complete",waldo:true,headphones:false};}
  function finishRecognition(){complete();if(runtime){runtime.fade=1;runtime.finished=true;}if(root.setTimeout)root.setTimeout(function(){stop();try{if(typeof root.toast==="function")root.toast("EAST SIDE complete · Ghost Fork unlocked",4200);}catch(_){}},800);}
  function checkForcedAnchors(s){ANCHORS.forEach(function(a){if(s.anchorsSeen.indexOf(a.id)>=0)return;if(distance(s.x,s.y,a.x,a.y)<=a.r){triggerAnchor(a.id);if(runtime){runtime.msg=a.label+" · ORBITAL";runtime.msgT=2.3;}}});if(s.x>=W*5&&!s.porchPhaseLocked){s.porchPhaseLocked=true;setPhase("orbital","Waldo street",true);persist();}}
  function update(dt){if(!runtime||runtime.paused||runtime.finished)return;var s=ensure();if(!s)return;if(runtime.cutscene){if(runtime.cutscene.phase==="timeline"){runtime.cutscene.t+=dt*1000;if(runtime.cutscene.t>=45000)finishRecognition();}return;}var dx=(runtime.keys.ArrowRight||runtime.keys.d?1:0)-(runtime.keys.ArrowLeft||runtime.keys.a?1:0),dy=(runtime.keys.ArrowDown||runtime.keys.s?1:0)-(runtime.keys.ArrowUp||runtime.keys.w?1:0);if(dx||dy){var l=Math.sqrt(dx*dx+dy*dy)||1,sp=SPEED[s.phase];s.x=clamp(s.x+dx/l*sp*dt,70,WORLD_W-80);s.y=clamp(s.y+dy/l*sp*dt,250,WORLD_H-70);runtime.idleT=0;}else runtime.idleT+=dt;if(s.x>W&&s.x<W*2&&runtime.idleT>2.2&&!s.cameraIdleTriggered){s.cameraIdleTriggered=true;triggerAnchor("camera");runtime.msg="The red light tracks you.";runtime.msgT=2.8;}checkForcedAnchors(s);if(runtime.msgT>0)runtime.msgT-=dt;if(runtime.knockFlash>0)runtime.knockFlash-=dt;if(runtime.phaseFlash){runtime.phaseFlash.t-=dt;if(runtime.phaseFlash.t<=0)runtime.phaseFlash=null;}if(runtime.audio){var hit=runtime.audio.tick();if(hit!==null)runtime.refrainFlash={t:.18,phase:s.phase};}if(runtime.refrainFlash){runtime.refrainFlash.t-=dt;if(runtime.refrainFlash.t<=0)runtime.refrainFlash=null;}runtime.saveT=(runtime.saveT||0)+dt;if(runtime.saveT>1.5){runtime.saveT=0;persist();}}
  function draw(){if(!runtime||!runtime.ctx)return;var c=runtime.canvas,ctx=runtime.ctx,s=ensure();if(!s)return,vw=c.width,vh=c.height,scale=Math.min(vw/W,vh/H),viewW=vw/scale,viewH=vh/scale,camX=clamp(s.x-viewW*.45,0,WORLD_W-viewW),camY=clamp(s.y-viewH*.60,0,WORLD_H-viewH);ctx.save();ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,viewW,viewH);for(var i=0;i<COLS;i++)drawBackdrop(ctx,i,camX,camY);ctx.strokeStyle=s.phase==="orbital"?"rgba(180,170,220,.18)":"rgba(145,206,230,.30)";ctx.lineWidth=1;var tm=perfNow()/12;for(var r=0;r<85;r++){var rx=(r*137+tm*1.7)%viewW,ry=(r*83+tm*4)%viewH;ctx.beginPath();ctx.moveTo(rx,ry);ctx.lineTo(rx-5,ry+12);ctx.stroke();}ctx.fillStyle="#1a2430";ctx.fillRect(330-camX,610-camY,240,90);ctx.fillStyle="#26394b";ctx.fillRect(1250-camX,490-camY,420,210);ctx.fillStyle="#321d31";ctx.fillRect(2150-camX,430-camY,650,300);ctx.fillStyle="#163426";ctx.fillRect(3090-camX,520-camY,650,220);ctx.fillStyle="#5f6232";ctx.fillRect(4400-camX,470-camY,230,210);ctx.fillStyle=s.phase==="orbital"?"#1b1b22":"#283242";ctx.fillRect(5320-camX,390-camY,390,310);ctx.fillStyle="#ffb84e";ctx.shadowColor="#ffb84e";ctx.shadowBlur=22;ctx.fillRect(5488-camX,475-camY,34,54);ctx.shadowBlur=0;STATIC.forEach(function(o){if(s.staticCollected.indexOf(o.id)>=0)return;var x=o.x-camX,y=o.y-camY;ctx.fillStyle="#b07cff";ctx.fillRect(x-7,y-7,14,14);ctx.strokeStyle="#e1c8ff";ctx.strokeRect(x-11,y-11,22,22);});DOGS.forEach(function(o){var x=o.x-camX,y=o.y-camY;ctx.fillStyle=s.dogsPetted.indexOf(o.id)>=0?"#79d9ff":"#d49a4d";ctx.fillRect(x-16,y-22,32,18);ctx.fillRect(x+10,y-30,10,12);});drawK(ctx,s.x-camX,s.y-camY,92,!!(runtime.keys.ArrowLeft||runtime.keys.a));if(runtime.cutscene&&runtime.cutscene.phase==="timeline"){var b=recognitionBeat(runtime.cutscene.t);if(b.waldo)drawWaldo(ctx,PORCH.x-camX+100,PORCH.y-camY,96);ctx.fillStyle="rgba(2,4,8,.58)";ctx.fillRect(0,viewH-92,viewW,92);ctx.fillStyle="#f3f5f7";ctx.font="11px 'Press Start 2P',monospace";ctx.textAlign="center";ctx.fillText(b.label,viewW/2,viewH-45);}ctx.restore();ctx.save();phaseFilter(ctx,s,vw,vh);if(runtime.phaseFlash){ctx.fillStyle=runtime.phaseFlash.phase==="orbital"?"rgba(145,65,210,.28)":"rgba(64,220,255,.20)";ctx.fillRect(0,0,vw,vh);}if(runtime.refrainFlash){ctx.fillStyle=runtime.refrainFlash.phase==="orbital"?"rgba(255,45,45,.32)":"rgba(50,220,255,.28)";ctx.fillRect(0,0,vw,vh);}if(runtime.knockFlash>0){ctx.fillStyle="rgba(255,184,78,.22)";ctx.fillRect(0,0,vw,vh);}if(runtime.fade>0){ctx.fillStyle="rgba(0,0,0,"+runtime.fade+")";ctx.fillRect(0,0,vw,vh);}ctx.restore();var obj=root.document&&root.document.querySelector("#east-side-root .es-objective");if(obj)obj.textContent=runtime.cutscene?(runtime.cutscene.phase==="knock"?"KNOCK · "+(s.knockCount||0)+"/4":recognitionBeat(runtime.cutscene.t).label):(runtime.msgT>0?runtime.msg:((nearestInteractable(s)||{}).label||objective(s)));}
  function loop(ts){if(!runtime)return;var dt=Math.min(.05,Math.max(0,(ts-runtime.last)/1000));runtime.last=ts;update(dt);draw();runtime.raf=(root.requestAnimationFrame||function(f){return root.setTimeout(function(){f(perfNow());},16);})(loop);}
  function resize(){if(!runtime||!runtime.canvas)return;var dpr=Math.min(2,root.devicePixelRatio||1);runtime.canvas.width=Math.max(1,Math.round(root.innerWidth*dpr));runtime.canvas.height=Math.max(1,Math.round(root.innerHeight*dpr));}
  function bindTouch(id,key){var el=root.document.getElementById(id);if(!el)return;function down(e){e.preventDefault();if(runtime)runtime.keys[key]=true;}function up(e){e.preventDefault();if(runtime)runtime.keys[key]=false;}el.addEventListener("pointerdown",down);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up);}
  function start(opts){opts=opts||{};var s=ensure();if(!s||!canStart())return false;if(runtime)return true;if(s.completed&&opts.replay)resetForReplay();else{s.started=true;s.startedAt=s.startedAt||Date.now();persist();}if(!root.document)return true;injectStyle();var host=root.document.createElement("div");host.id="east-side-root";host.innerHTML="<canvas id='east-side-canvas'></canvas><div id='east-side-hud'><div class='es-title'>EAST SIDE // K // 72 HOURS AFTER REENTRY</div><div class='es-objective'></div><div id='east-side-pause' class='es-pause'></div></div><div id='east-side-touch'><div class='es-pad'><button id='es-up' class='es-up'>▲</button><button id='es-left' class='es-left'>◀</button><button id='es-right' class='es-right'>▶</button><button id='es-down' class='es-down'>▼</button></div><button id='es-use' class='es-use'>USE</button></div>";root.document.body.appendChild(host);runtime={keys:{},last:perfNow(),msg:"",msgT:0,paused:false,cutscene:null,finished:false,fade:0,phaseFlash:null,knockFlash:0,idleT:0,audio:null,canvas:host.querySelector("canvas"),root:host,kImage:null};runtime.ctx=runtime.canvas.getContext("2d");runtime.audio=makeAudio();resize();root.addEventListener("resize",resize);runtime.onKeyDown=function(e){if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," ","p","P","Escape","e","E","a","d","w","s","j","k","l","z","x","Shift"].indexOf(e.key)>=0)e.preventDefault();if(["j","k","l","z","x"].indexOf(e.key)>=0)return;if(e.key==="Escape"||e.key==="p"||e.key==="P"){togglePause();return;}if(e.key==="e"||e.key==="E"||e.key===" "){if(runtime.cutscene&&runtime.cutscene.phase==="knock")knock();else interact();return;}runtime.keys[e.key]=true;};runtime.onKeyUp=function(e){runtime.keys[e.key]=false;};root.addEventListener("keydown",runtime.onKeyDown,true);root.addEventListener("keyup",runtime.onKeyUp,true);bindTouch("es-up","ArrowUp");bindTouch("es-down","ArrowDown");bindTouch("es-left","ArrowLeft");bindTouch("es-right","ArrowRight");host.querySelector("#es-use").addEventListener("pointerdown",function(e){e.preventDefault();if(runtime.cutscene&&runtime.cutscene.phase==="knock")knock();else interact();});if(runtime.audio)runtime.audio.play();runtime.last=perfNow();loop(runtime.last);return true;}
  function stop(){if(!runtime)return false;try{if(runtime.audio)runtime.audio.stop();if(runtime.raf)(root.cancelAnimationFrame||root.clearTimeout)(runtime.raf);root.removeEventListener("resize",resize);root.removeEventListener("keydown",runtime.onKeyDown,true);root.removeEventListener("keyup",runtime.onKeyUp,true);if(runtime.root&&runtime.root.parentNode)runtime.root.parentNode.removeChild(runtime.root);}catch(_){}runtime=null;return true;}
  function isActive(){return!!runtime;}
  function blockGhostFork(id){return/^gk[1-6]$/.test(String(id||""))&&!ghostForkUnlocked();}
  function installGhostForkGate(){var c=root.v725;if(!c||typeof c.play!=="function")return false;if(c.play.__eastSideGate)return true;var base=c.play;c.play=function(id){if(blockGhostFork(id)){try{if(goodDogsComplete()&&typeof root.toast==="function")root.toast("EAST SIDE must be completed before Ghost Fork.",3600);}catch(_){}if(goodDogsComplete()&&!isActive())scheduleAuto(400);return false;}return base.apply(this,arguments);};c.play.__eastSideGate=true;c.play.__eastSideBase=base;return true;}
  function installMusicEntry(){if(typeof root.dlg!=="function"||root.dlg.__eastSideMusicEntry)return false;var base=root.dlg;root.dlg=function(name,body,options){if(String(name||"").toUpperCase()==="WORKSTATION // MUSIC"&&goodDogsComplete()){options=Array.isArray(options)?options.slice():[];var s=ensure(),label=s.completed?"Replay EAST SIDE":s.started?"Resume EAST SIDE":"Play EAST SIDE — The Missing Chapter";options.unshift({t:label,f:function(){try{if(typeof root.closeDlg==="function")root.closeDlg();}catch(_){}start({replay:!!s.completed});}});if(s.fullStaticUnlocked)options.unshift({t:"EAST SIDE (Full Static) — unlocked",f:function(){try{if(typeof root.toast==="function")root.toast("Full Static mix unlocked. Authored audio asset required for playback.",3800);}catch(_){}}});}return base.call(this,name,body,options);};root.dlg.__eastSideMusicEntry=true;root.dlg.__eastSideBase=base;return true;}
  function canAutoLaunch(){if(!root.document||!goodDogsComplete())return false;var s=ensure();if(!s||s.completed||s.started||runtime)return false;if(root.document.querySelector("#good-dogs-cutscene-overlay.active,.cinematic-overlay.active,#cinematic.active"))return false;try{if(root.S&&root.S.inDialog)return false;}catch(_){}return true;}
  function scheduleAuto(delay){if(!root.setTimeout)return false;if(autoTimer)root.clearTimeout(autoTimer);autoTimer=root.setTimeout(function attempt(){autoTimer=null;if(canAutoLaunch()){start();return;}var s=ensure();if(s&&!s.completed&&!s.started&&goodDogsComplete())autoTimer=root.setTimeout(attempt,1200);},delay||2600);return true;}
  function install(){ensure();installGhostForkGate();installMusicEntry();if(root.setInterval&&!installTimer)installTimer=root.setInterval(function(){installGhostForkGate();installMusicEntry();var s=ensure();if(s&&s.unlocked&&!s.completed&&!s.started&&goodDogsComplete()&&!autoTimer)scheduleAuto(2200);},700);if(goodDogsComplete())scheduleAuto(2800);return true;}
  var API={VERSION:VERSION,SCHEMA:SCHEMA,W:W,H:H,COLS:COLS,ROWS:ROWS,WORLD_W:WORLD_W,WORLD_H:WORLD_H,AUDIO:AUDIO,LYRIC_FRAGMENTS:LYRIC_FRAGMENTS.slice(),STATIC:STATIC.slice(),DOGS:DOGS.slice(),ANCHORS:ANCHORS.slice(),GROUNDING:GROUNDING.slice(),ensure:ensure,snapshot:snapshot,persist:persist,goodDogsComplete:goodDogsComplete,legacyGhostForkStarted:legacyGhostForkStarted,canStart:canStart,setPhase:setPhase,addStatic:addStatic,triggerAnchor:triggerAnchor,ground:ground,petDog:petDog,chooseGas:chooseGas,collectBottle:collectBottle,complete:complete,ghostForkUnlocked:ghostForkUnlocked,resetForReplay:resetForReplay,setRefrainTimes:setRefrainTimes,refrainDue:refrainDue,nearestInteractable:nearestInteractable,objective:objective,recognitionBeat:recognitionBeat,blockGhostFork:blockGhostFork,installGhostForkGate:installGhostForkGate,installMusicEntry:installMusicEntry,start:start,stop:stop,isActive:isActive,install:install};install();return API;
});
