/* TechOps Hero — 118/1984 hard title-button owner v8.
 * Fresh title entry: cockpit interact -> GD_CUT_02 -> playable flight ->
 * GD_CUT_03 -> canonical prison impact -> fresh M3 prison gameplay.
 * Every authored phase fails closed and reports its exact failure on-device.
 */
(function(root){
  "use strict";
  if(!root||!root.document)return;
  var PRIOR=root.TechOpsGoodBoysButtonHardFix;if(PRIOR&&Number(PRIOR.VERSION||0)>=8)return;
  var VERSION=8,lastLaunch=0,launching=false,depTimer=0;
  function target(t){try{return t&&t.closest&&t.closest("#btn-v736");}catch(_){return null;}}
  function freshConfig(){return {mission:3,k:false,waldo:false,evidence:[]};}
  function phase(name,extra){root.__goodBoysOpeningPhase=Object.assign({phase:name,owner:"hard-title-button-v8",at:Date.now()},extra||{});}
  function clearForeignUi(){try{["act1-reference","good-boys-story-cine","good-boys-premise","good-boys-ship-interlude","good-boys-opening-error","good-boys-deck-v4","good-boys-deck-supplied","good-boys-flight-v4","good-boys-crash-v4","good-boys-crash-canonical"].forEach(function(id){var n=root.document.getElementById(id);if(n)n.remove();});}catch(_){}try{var d=root.document.getElementById("dialogue");if(d)d.classList.add("hidden");if(root.S)root.S.inDialog=false;}catch(_){}try{var p=root.document.getElementById("panel");if(p)p.classList.add("hidden");}catch(_){}try{var e=root.document.getElementById("eod");if(e)e.classList.add("hidden");}catch(_){} }
  function setButton(text,disabled){try{var b=root.document.getElementById("btn-v736");if(b){b.disabled=!!disabled;b.textContent=text;}}catch(_){} }
  function depsReady(){var c=root.GoodDogsCutscenes,o=root.TechOpsGoodBoysOpeningV4,a=root.TechOpsGoodDogsSingleAtlasAuthority,d=root.TechOpsGoodBoysShipDeckScene,x=root.TechOpsGoodBoysCrashScene;return !!(c&&parseFloat(c.VERSION||0)>=2.9&&typeof c.play==="function"&&o&&typeof o.showDeckInteraction==="function"&&o.showDeckInteraction.__goodShipDeckV3&&typeof o.showSpaceFlight==="function"&&typeof o.showCrashScene==="function"&&o.showCrashScene.__canonicalCrashArtV2&&a&&Number(a.VERSION||0)>=2&&a.installed!==false&&d&&Number(d.VERSION||0)>=3&&x&&Number(x.VERSION||0)>=2);}
  function dependencySnapshot(){return {cutscenes:root.GoodDogsCutscenes&&root.GoodDogsCutscenes.VERSION||null,opening:root.TechOpsGoodBoysOpeningV4&&root.TechOpsGoodBoysOpeningV4.VERSION||null,deck:root.TechOpsGoodBoysShipDeckScene&&root.TechOpsGoodBoysShipDeckScene.VERSION||null,crash:root.TechOpsGoodBoysCrashScene&&root.TechOpsGoodBoysCrashScene.VERSION||null,atlas:root.TechOpsGoodDogsSingleAtlasAuthority&&root.TechOpsGoodDogsSingleAtlasAuthority.VERSION||null};}
  function waitForDeps(timeout){return new Promise(function(resolve,reject){var start=Date.now();function poll(){if(depsReady()){resolve(true);return;}if(Date.now()-start>=timeout){var e=new Error("Opening dependencies not ready: "+JSON.stringify(dependencySnapshot()));e.code="GOOD_BOYS_DEPS_TIMEOUT";reject(e);return;}depTimer=root.setTimeout(poll,50);}poll();});}
  function esc(v){return String(v==null?"":v).replace(/[&<>\"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c];});}
  function showOpeningError(err){var old=root.document.getElementById("good-boys-opening-error");if(old)old.remove();var ph=root.__goodBoysOpeningPhase&&root.__goodBoysOpeningPhase.phase||"unknown",msg=String(err&&err.message||err||"Unknown opening failure");var box=root.document.createElement("div");box.id="good-boys-opening-error";box.style.cssText="position:fixed;inset:0;z-index:160000;display:flex;align-items:center;justify-content:center;padding:22px;background:#02050af2;color:#eaf6ff;font-family:monospace";box.innerHTML='<div style="width:min(620px,100%);border:1px solid #ff6b81;background:#071019;padding:22px;box-shadow:0 18px 60px #000"><div style="color:#ff8fa3;font-weight:700;letter-spacing:.12em">GOOD DOGS OPENING ERROR</div><p style="line-height:1.55;margin-bottom:10px">The story opening stopped before prison gameplay. It will not jump around the missing scene.</p><div style="border:1px solid #294252;background:#040a10;padding:10px;margin:0 0 14px;font-size:11px;line-height:1.45"><b style="color:#72dcff">FAILED PHASE:</b> '+esc(ph)+'<br><b style="color:#ffb14a">REASON:</b> '+esc(msg)+'</div><button type="button" style="width:100%;min-height:52px;border:1px solid #67e8f9;background:#0a1a28;color:#fff;font:700 13px monospace">RETRY OPENING</button></div>';root.document.body.appendChild(box);box.querySelector("button").onclick=function(){box.remove();launch("retry");};root.__goodBoysOpeningError=String(err&&err.stack||err);root.__goodBoysOpeningErrorDetail={phase:ph,message:msg,deps:dependencySnapshot(),at:Date.now(),version:VERSION};root.__goodBoysHardButtonLaunch={ok:false,status:"opening-error",phase:ph,error:msg,at:Date.now(),version:VERSION};}
  function mount(source){var cfg=freshConfig();if(!root.v736||typeof root.v736.start!=="function")throw new Error("v736.start unavailable");clearForeignUi();phase("prison-handoff",{mission:cfg.mission});var ok=root.v736.start({mission:cfg.mission,k:false,waldo:false,evidence:[],directGameplay:true});var c=root.NM&&root.NM._v736;if(!c||c.ending)throw new Error("Katrin/Manchez M3 prison runtime did not mount synchronously");if(Number(c.m||0)!==cfg.mission)throw new Error("Fresh 118/1984 entry mounted wrong mission: "+String(c.m));phase("prison-gameplay",{mission:cfg.mission});root.__goodBoysPhysicalLaunchActive=false;root.__goodBoysHardButtonLaunch={ok:true,status:"prison-gameplay",source:source||"unknown",mission:cfg.mission,active:c.active||null,pair:!!(c.chars&&c.chars.katrin&&c.chars.manchez),atlasAuthority:root.__goodDogsAtlasAuthority||null,actorAuthority:root.__goodDogsActorRenderAuthority||null,at:Date.now(),version:VERSION};launching=false;return ok!==false;}
  function validMovieResult(result,id){if(!result)throw new Error(id+" returned no result");if(result.result&&result.result!=="COMPLETED"&&result.result!=="USER_SKIPPED")throw new Error(id+" did not complete: "+String(result.result));return result;}
  async function opening(source){phase("opening-dependencies");setButton("LOADING GOOD DOGS OPENING…",true);await waitForDeps(9000);var cine=root.GoodDogsCutscenes,o=root.TechOpsGoodBoysOpeningV4;
    phase("cockpit-interact");setButton("COCKPIT INTERACTION…",true);var deck=await o.showDeckInteraction();if(!deck||deck.completed!==true)throw new Error("Cockpit interaction did not complete");root.__goodBoysHardDeckResult=deck;
    phase("takeover-cutscene");setButton("TAKING CONTROL OF SHIP…",true);var takeover=validMovieResult(await cine.play("GD_CUT_02",{force:true,muted:true}),"GD_CUT_02");root.__goodBoysHardTakeoverClip=takeover;
    phase("space-flight");setButton("FLYING TO ORBITAL PRISON…",true);var flight=await o.showSpaceFlight();if(!flight||flight.completed!==true)throw new Error("Space flight did not complete");root.__goodBoysHardFlightResult=flight;
    phase("prison-approach-cutscene");setButton("APPROACHING ORBITAL PRISON…",true);var approach=validMovieResult(await cine.play("GD_CUT_03",{force:true,muted:true}),"GD_CUT_03");root.__goodBoysHardApproachClip=approach;
    phase("crash-scene");setButton("IMPACT SEQUENCE…",true);var crash=await o.showCrashScene();if(!crash||crash.completed!==true)throw new Error("Crash scene did not complete");root.__goodBoysHardCrashResult=crash;return mount(source);
  }
  function launch(source){var now=Date.now();if(launching||now-lastLaunch<700)return true;lastLaunch=now;launching=true;root.__goodBoysPhysicalLaunchActive=true;clearForeignUi();root.__goodBoysHardButtonLaunch={ok:null,status:"opening",source:source||"unknown",mission:3,freshStoryStart:true,at:now,version:VERSION};setButton("OPENING 118/1984 — KATRIN + MANCHEZ…",true);opening(source).catch(function(err){launching=false;root.__goodBoysPhysicalLaunchActive=false;setButton("RETRY 118/1984 — KATRIN + MANCHEZ",false);showOpeningError(err);});return true;}
  function own(e){if(!target(e&&e.target))return;try{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();}catch(_){}launch(e&&e.type||"event");}
  root.document.addEventListener("pointerup",own,true);root.document.addEventListener("click",own,true);root.TechOpsGoodBoysButtonHardFix={VERSION:VERSION,launch:launch,freshConfig:freshConfig,opening:opening,clearForeignUi:clearForeignUi,depsReady:depsReady,dependencySnapshot:dependencySnapshot,get launching(){return launching;}};
})(typeof globalThis!=="undefined"?globalThis:this);
