/* TechOps Hero — Good Boys visual cohesion authority v2.
 * Uses only the already-approved Katrin/Manchez atlas and canonical campaign
 * backgrounds. No substitute character/background art is generated here.
 */
(function(root){
  "use strict";
  if(!root||root.TechOpsGoodBoysVisualPolish)return;
  var VERSION=2,installed=false,basePlayer=null,baseHud=null,img=null;
  var lastWho="",lastPose="",poseAt=0,frameAt=0,frameIndex=0;
  var STYLE={1:{scale:1.08,tint:"rgba(255,187,112,.035)",vignette:.10,ambient:"warm"},2:{scale:1.06,tint:"rgba(74,214,255,.045)",vignette:.13,ambient:"hangar"},3:{scale:1.08,tint:"rgba(84,108,255,.055)",vignette:.16,ambient:"orbital"},4:{scale:1.08,tint:"rgba(94,126,255,.060)",vignette:.17,ambient:"orbital"},5:{scale:1.09,tint:"rgba(35,235,255,.065)",vignette:.18,ambient:"core"},6:{scale:1.08,tint:"rgba(119,82,255,.060)",vignette:.18,ambient:"orbital"},7:{scale:1.10,tint:"rgba(255,68,84,.045)",vignette:.20,ambient:"escape"},8:{scale:1.07,tint:"rgba(255,191,124,.050)",vignette:.09,ambient:"dawn"}};
  function clock(){try{return root.performance&&root.performance.now?root.performance.now():Date.now();}catch(e){return Date.now();}}
  function campaign(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function mission(){try{var p=root.TechOpsGoodBoysProgressionAuthority;if(p&&typeof p.mission==="function")return Number(p.mission())||1;var c=campaign();return Math.max(1,Math.min(8,Number(c&&c.m)||1));}catch(e){return 1;}}
  function atlas(){return root.KATRIN_MANCHEZ||null;}
  function atlasImage(){try{var A=atlas();if(!A||!A.src||typeof root.Image!=="function")return null;if(!img||img.src!==A.src){img=new root.Image();img.src=A.src;}return img.complete&&img.naturalWidth?img:null;}catch(e){return null;}}
  function hasFrame(k){var A=atlas();return !!(A&&A.frames&&A.frames[k]);}
  function who(){var c=campaign();return c&&c.active==="manchez"?"manchez":"katrin";}
  function prefix(w){return w==="manchez"?"man_":"kat_";}
  function snap(v){return Math.round(Number(v)||0);}
  function actionPose(NM,w){var p=prefix(w);if(!NM||NM.hp<=0)return hasFrame(p+"down")?"down":"idle0";if(NM.ifr>0&&hasFrame(p+"wall_hit"))return "wall_hit";if(NM.dashT>0&&hasFrame(p+"roll"))return "roll";if(NM.jabAnim>0){if(NM.jabStage===2&&hasFrame(p+"strike"))return "strike";return hasFrame(p+"pounce")?"pounce":"strike";}if(NM.block&&hasFrame(p+"shield"))return "shield";if(!NM.onGround&&hasFrame(p+"leap"))return "leap";return Math.abs(Number(NM.vx)||0)>.35?"move":"idle";}
  function frameFor(NM,tm){var w=who(),p=prefix(w),pose=actionPose(NM,w),moving=pose==="move";if(w!==lastWho||pose!==lastPose){lastWho=w;lastPose=pose;poseAt=tm;frameAt=tm;frameIndex=0;}var period=moving?100:560;if(tm-frameAt>=period){var steps=Math.max(1,Math.floor((tm-frameAt)/period));frameIndex=(frameIndex+steps)%2;frameAt+=steps*period;}if(pose==="move"||pose==="idle")return p+(frameIndex?"idle1":"idle0");var exact=p+pose;if(hasFrame(exact))return exact;return p+"idle0";}
  function drawApprovedDog(x,NM,px,py,tm){try{if(!campaign())return false;var A=atlas(),im=atlasImage(),key=frameFor(NM,tm),fr=A&&A.frames&&A.frames[key];if(!im||!fr||fr.length<4)return false;var st=STYLE[mission()]||STYLE[1],baseH=Math.max(92,(Number(NM.h)||34)*2.70),h=snap(baseH*st.scale),dw=snap(h*(fr[2]/fr[3]));var cx=snap((Number(px)||0)+(Number(NM.w)||22)/2),base=snap((Number(py)||0)+(Number(NM.h)||34)+7);var moving=Math.abs(Number(NM.vx)||0)>.35,onGround=NM.onGround!==false;var bob=onGround&&moving?(frameIndex?1:0):0;var airborne=!onGround,shadowAlpha=airborne?.14:.30,shadowW=Math.max(18,snap(dw*(airborne?.24:.31)));x.save();x.imageSmoothingEnabled=false;x.save();x.globalAlpha=shadowAlpha;x.fillStyle="#000";x.beginPath();x.ellipse(cx,base-2,shadowW,airborne?3.5:6,0,0,Math.PI*2);x.fill();x.restore();var dx=snap(cx-dw/2),dy=snap(base-h-bob),flip=(Number(NM.face)||1)<0;if(flip){x.translate(cx,0);x.scale(-1,1);x.drawImage(im,fr[0],fr[1],fr[2],fr[3],snap(-dw/2),dy,dw,h);}else{x.drawImage(im,fr[0],fr[1],fr[2],fr[3],dx,dy,dw,h);}x.restore();root.__goodBoysVisualFrame={mission:mission(),who:w,key:key,frame:frameIndex,x:cx,y:base,h:h,pixelSnapped:true,smoothing:false};return true;}catch(e){root.__goodBoysVisualPolishError=String(e&&e.stack||e);return false;}}
  function environmentOverlay(x,tm){try{if(!campaign()||!x||!x.canvas)return;var W=x.canvas.width,H=x.canvas.height,m=mission(),st=STYLE[m]||STYLE[1],phase=(tm||clock())*.001;x.save();x.fillStyle=st.tint;x.fillRect(0,0,W,H);if(st.ambient==="orbital"||st.ambient==="core"){var gx=((Math.sin(phase*.55)+1)*.5)*W;var g=x.createLinearGradient(gx-140,0,gx+140,0);g.addColorStop(0,"rgba(40,210,255,0)");g.addColorStop(.5,st.ambient==="core"?"rgba(72,255,238,.065)":"rgba(104,126,255,.045)");g.addColorStop(1,"rgba(40,210,255,0)");x.fillStyle=g;x.fillRect(0,0,W,H);}else if(st.ambient==="escape"){x.globalAlpha=.45+.25*Math.sin(phase*2.2);x.fillStyle="rgba(255,42,58,.035)";x.fillRect(0,0,W,H);x.globalAlpha=1;}else if(st.ambient==="warm"||st.ambient==="dawn"){var rg=x.createRadialGradient(W*.72,H*.22,10,W*.72,H*.22,Math.max(W,H)*.7);rg.addColorStop(0,"rgba(255,190,118,.055)");rg.addColorStop(1,"rgba(255,190,118,0)");x.fillStyle=rg;x.fillRect(0,0,W,H);}else if(st.ambient==="hangar"){var y=snap(H*.70+Math.sin(phase*.8)*3);x.fillStyle="rgba(72,220,255,.035)";x.fillRect(0,y,W,2);}var vg=x.createRadialGradient(W/2,H*.48,Math.min(W,H)*.2,W/2,H*.48,Math.max(W,H)*.72);vg.addColorStop(.55,"rgba(0,0,0,0)");vg.addColorStop(1,"rgba(1,4,10,"+st.vignette+")");x.fillStyle=vg;x.fillRect(0,0,W,H);x.restore();}catch(e){root.__goodBoysVisualOverlayError=String(e&&e.stack||e);}}
  function install(){if(installed)return true;try{if(typeof root.drawNightPlayerAtlas==="function"&&!root.drawNightPlayerAtlas.__goodBoysVisualPolish){basePlayer=root.drawNightPlayerAtlas;var wrapped=function(x,NM,px,py,tm){if(NM&&NM._v736){if(drawApprovedDog(x,NM,px,py,Number(tm)||clock()))return true;}return basePlayer.apply(this,arguments);};wrapped.__goodBoysVisualPolish=true;wrapped.__goodDogsProduction=true;root.drawNightPlayerAtlas=wrapped;}var gd=root.TechOpsGoodDogsProduction;if(gd&&typeof gd.drawReferenceHUD==="function"&&!gd.drawReferenceHUD.__goodBoysVisualPolish){baseHud=gd.drawReferenceHUD;var hud=function(x,NM){environmentOverlay(x,clock());return baseHud.apply(this,arguments);};hud.__goodBoysVisualPolish=true;gd.drawReferenceHUD=hud;}installed=true;root.__goodBoysVisualPolishInstalled=true;return true;}catch(e){root.__goodBoysVisualPolishInstallError=String(e&&e.stack||e);return false;}}
  function acceptance(){var f=root.__goodBoysVisualFrame||null;return{version:VERSION,installed:installed,active:!!campaign(),mission:mission(),approvedAtlas:!!atlas(),atlasReady:!!atlasImage(),playerWrapped:!!(root.drawNightPlayerAtlas&&root.drawNightPlayerAtlas.__goodBoysVisualPolish),hudWrapped:!!(root.TechOpsGoodDogsProduction&&root.TechOpsGoodDogsProduction.drawReferenceHUD&&root.TechOpsGoodDogsProduction.drawReferenceHUD.__goodBoysVisualPolish),lastFrame:f,pixelSnapped:!f||!!f.pixelSnapped,smoothingDisabled:!f||f.smoothing===false,error:root.__goodBoysVisualPolishError||root.__goodBoysVisualPolishInstallError||null};}
  root.TechOpsGoodBoysVisualPolish={VERSION:VERSION,STYLE:STYLE,install:install,frameFor:frameFor,drawApprovedDog:drawApprovedDog,environmentOverlay:environmentOverlay,acceptance:acceptance};install();
})(typeof globalThis!=="undefined"?globalThis:this);