/* Good Boys campaign director v6 — gameplay presentation authority.
 * Opening ownership was retired from this module. TechOpsGoodBoysIntroRepair
 * exclusively owns Clip 1 -> ship systems -> Clip 2 -> premise -> M2.
 */
(function(root){
  "use strict";
  if(!root)return;
  try{var old=root.TechOpsGoodBoysCampaignDirector;if(old&&old.timer&&root.clearInterval)root.clearInterval(old.timer);if(old&&old.observer)old.observer.disconnect();}catch(_){}
  var VERSION=7,style=null,observer=null,shipImg=null,combo={step:0,last:0};
  function cs(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function active(){return !!cs();}
  function mission(){try{var a=root.TechOpsGoodBoysCampaignState;if(a&&typeof a.mission==="function")return Number(a.mission())||1;var m=root.S&&root.S.meta&&root.S.meta._v736;return Math.max(1,Math.min(8,Number(m&&m.m||1)));}catch(e){return 1;}}
  function now(){return root.performance&&root.performance.now?root.performance.now():Date.now();}
  function setMsg(t,ms){try{if(root.NM){root.NM.msg=t;root.NM.msgT=now()+(ms||1200);}}catch(e){}}
  function installStyle(){if(!root.document)return;style=root.document.getElementById("good-boys-director-style");if(!style){style=root.document.createElement("style");style.id="good-boys-director-style";(root.document.head||root.document.documentElement).appendChild(style);}style.textContent="#good-boys-director-controls{display:none!important;visibility:hidden!important;pointer-events:none!important}body.good-boys-cinematic #good-dogs-touch,body.good-boys-cinematic #good-boys-loop-controls,body.good-boys-cinematic #touch-buttons{display:none!important;visibility:hidden!important;pointer-events:none!important}";}
  function elementVisible(id){try{var el=root.document&&root.document.getElementById(id);if(!el)return false;if(el.classList&&el.classList.contains("hidden"))return false;var s=root.getComputedStyle?root.getComputedStyle(el):el.style;return !s||s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity||1)!==0;}catch(e){return false;}}
  function cinematicVisible(){try{return elementVisible("good-dogs-cutscene-overlay")||elementVisible("good-boys-ship-interlude")||elementVisible("gb-prison-cine")||elementVisible("good-boys-campaign-intro")||elementVisible("good-boys-earthfall-cine")||elementVisible("dialogue")||elementVisible("v725-cine");}catch(e){return false;}}
  function removeDirectorPads(){try{if(!root.document)return;var xs=root.document.querySelectorAll("#good-boys-director-controls");for(var i=0;i<xs.length;i++)xs[i].remove();}catch(e){}}
  function handoffControls(){try{if(!root.document)return false;removeDirectorPads();var legacy=root.document.getElementById("good-boys-loop-controls");if(legacy){legacy.style.setProperty("display","none","important");legacy.inert=true;legacy.setAttribute("aria-hidden","true");}var touch=root.document.getElementById("touch-buttons");if(touch&&active()){touch.style.setProperty("display","none","important");touch.inert=true;touch.setAttribute("aria-hidden","true");}var modern=root.TechOpsGoodBoysMobileControlsLayout;if(active()&&!cinematicVisible()&&modern&&typeof modern.apply==="function"){modern.apply();var box=root.document.getElementById("good-dogs-touch");if(box){box.inert=false;box.removeAttribute("inert");box.removeAttribute("aria-hidden");box.style.removeProperty("visibility");box.style.removeProperty("pointer-events");}}return true;}catch(e){root.__goodBoysDirectorControlHandoffError=String(e&&e.stack||e);return false;}}
  function nearestEnemy(range){try{var n=root.NM;if(!n||!n.enemies)return null,b=null,bd=1e9;for(var i=0;i<n.enemies.length;i++){var e=n.enemies[i];if(!e||e.alive===false||Number(e.hp)<=0||e.down>0)continue;var d=Math.abs((e.x||0)-(n.x||0));if(d<bd&&d<=(range||150)){bd=d;b=e;}}return b;}catch(e){return null;}}
  function rawAttack(){try{if(typeof root.nmJab==="function")return root.nmJab();if(typeof root.interact==="function")return root.interact();if(root.KeyboardEvent)root.dispatchEvent(new root.KeyboardEvent("keydown",{key:"e",bubbles:true,cancelable:true}));}catch(e){}}
  function duoAttack(){var t=now();if(t-combo.last>900)combo.step=0;combo.last=t;combo.step=(combo.step%3)+1;rawAttack();try{var c=cs(),n=root.NM,p=c&&c.partner;if(c)c.sync=Math.min(100,(Number(c.sync)||0)+(combo.step===3?8:3));if(p){p.anim=combo.step===3?18:10;p.face=n.face||1;}}catch(e){}var target=nearestEnemy(128);if(target&&combo.step>=2){var bonus=combo.step===3?9:4;target.hp=(Number(target.hp)||1)-bonus;target.hitT=Math.max(Number(target.hitT)||0,6);target.kb=(root.NM.face||1)*(combo.step===3?6:3);if(target.hp<=0)target.alive=false;}setMsg(combo.step===1?"KATRIN → setup":combo.step===2?"MANCHEZ → follow-up":"TANDEM LAUNCHER");try{if(typeof root.nmCheckClear==="function")root.nmCheckClear();}catch(e){}}
  function reliableThrow(){try{var c=cs(),n=root.NM,p=c&&c.partner,m=root.TechOpsGoodBoysReferenceMechanics;if(!c||!n||!p)return false;var d=Math.hypot((p.x||0)-(n.x||0),(p.y||0)-(n.y||0));if(d>125){p.x=n.x-(n.face||1)*42;p.y=n.y+4;p.vx=0;p.vy=0;p.onGround=!!n.onGround;}var ok=m&&m.throwOrCatch?m.throwOrCatch():false;if(!ok){p.vx=(n.face||1)*9;p.vy=-9.5;p.onGround=false;p.anim=18;ok=true;}var e=nearestEnemy(175);if(e){e.hp=(Number(e.hp)||1)-7;e.hitT=8;e.kb=(n.face||1)*5;if(e.hp<=0)e.alive=false;c.sync=Math.min(100,(Number(c.sync)||0)+8);combo.step=2;combo.last=now();setMsg("THROW → ATTACK to finish");}else setMsg("PARTNER THROW");return ok;}catch(e){return false;}}
  function fallbackDefinitions(){try{var g=root.TechOpsGoodBoysGameplayLoop;if(!g)return;var defs={2:{id:"hidden_bay",label:"THE HIDDEN BAY",objective:"Clear the hangar. Reach the secret ship and board.",accent:"#55dfff",hazard:"security",bg:"goodboys_hangar"},3:{id:"breach",label:"ORBITAL PRISON — BREACH",objective:"Survive impact. Reach Cell Block 118.",accent:"#ff8a4c",hazard:"debris",bg:"goodboys_breach"},4:{id:"cell118",label:"CELL 118",objective:"Verify K. Break the lock. Free him.",accent:"#55dfff",hazard:"security",bg:"goodboys_cell118"},5:{id:"core",label:"ACCESS CORE",objective:"Escort K. Open the route to 1984.",accent:"#22c55e",hazard:"security",bg:"goodboys_core"},6:{id:"cell1984",label:"CELL 1984",objective:"Break lockdown. Free Waldo.",accent:"#ef4444",hazard:"lockdown",bg:"goodboys_cell1984"},7:{id:"escape",label:"ESCAPE VELOCITY",objective:"Break the Warden. Reach the maintenance shuttle.",accent:"#f59e0b",hazard:"warden",bg:"goodboys_escape"},8:{id:"earthfall",label:"EARTHFALL",objective:"Get everyone home.",accent:"#ffd18b",hazard:"none",bg:"goodboys_earthfall"}};Object.keys(defs).forEach(function(k){g.PHASES[k]=defs[k];});}catch(e){root.__goodBoysDirectorMissionError=String(e&&e.stack||e);}}
  function syncMissionDefinitions(){try{var w=root.TechOpsGoodBoysBibleWorld;if(w&&w.syncDefinitions)return w.syncDefinitions();fallbackDefinitions();return true;}catch(e){root.__goodBoysDirectorMissionError=String(e&&e.stack||e);return false;}}
  function shuttleAtlas(){try{return root.SHUTTLE&&root.SHUTTLE.src&&root.SHUTTLE.frames?root.SHUTTLE:null;}catch(e){return null;}}
  function shuttleImage(){try{var A=shuttleAtlas();if(!A)return null;if(!shipImg||shipImg.src!==A.src){shipImg=new root.Image();shipImg.src=A.src;}return shipImg.complete&&shipImg.naturalWidth?shipImg:null;}catch(e){return null;}}
  function drawShip(x){try{var n=root.NM,A=shuttleAtlas(),im=shuttleImage();if(!n||mission()!==2||!n._gbShipRevealed||!A||!im)return;var fr=A.frames.sh_land||A.frames.sh_side0;if(!fr)return;var worldX=1390,screenX=worldX-(Number(n.cam)||0),base=(typeof root.NM_FLOOR==="number"?root.NM_FLOOR:430)-6,w=190,h=w*(fr[3]/fr[2]);if(screenX<-220||screenX>x.canvas.width+220)return;x.save();x.imageSmoothingEnabled=false;x.globalAlpha=.28;x.fillStyle="#38bdf8";x.beginPath();x.ellipse(screenX,base+5,92,12,0,0,Math.PI*2);x.fill();x.globalAlpha=1;x.drawImage(im,fr[0],fr[1],fr[2],fr[3],screenX-w/2,base-h,w,h);x.strokeStyle="#69d6ff";x.lineWidth=2;x.strokeRect(screenX-72,base-h-36,144,25);x.fillStyle="rgba(2,8,14,.9)";x.fillRect(screenX-71,base-h-35,142,23);x.fillStyle="#dff8ff";x.font="bold 9px monospace";x.textAlign="center";x.fillText("SECRET SHIP · BOARD",screenX,base-h-19);x.restore();}catch(e){root.__goodBoysShipDrawError=String(e&&e.stack||e);}}
  function installShipDraw(){try{var g=root.TechOpsGoodBoysGameplayLoop;if(!g||g.__directorShipDrawInstalled||typeof g.drawStageAccents!=="function")return false;var base=g.drawStageAccents;g.drawStageAccents=function(ctx){var r=base&&base.apply(this,arguments);drawShip(ctx);return r;};g.__directorShipDrawInstalled=true;return true;}catch(e){return false;}}
  function calmFrames(){try{var A=root.KATRIN_MANCHEZ;if(!A||!A.frames)return;var ks=A.frames.kat_stand||A.frames.kat_idle0,ms=A.frames.man_idle0;if(ks){A.frames.kat_idle0=ks;A.frames.kat_idle1=ks;}if(ms)A.frames.man_idle1=ms;}catch(e){}}
  function showOpening(done){try{var intro=root.TechOpsGoodBoysIntroRepair;if(intro&&typeof intro.launch==="function"&&!intro.launching)intro.launch();}catch(e){root.__goodBoysDirectorOpeningDelegateError=String(e&&e.stack||e);}if(done)done();return false;}
  function showCinematic(scenes,done){if(done)done();return false;}
  function progressionWatch(){try{var p=root.TechOpsGoodBoysProgressionAuthority;if(p&&p.tick)return p.tick();return false;}catch(e){return false;}}
  function installObserver(){try{if(root.__productionSingleCompositor){if(observer){observer.disconnect();observer=null;}root.__goodBoysDirectorObserverSuppressed=true;return false;}if(observer||!root.MutationObserver||!root.document)return false;observer=new root.MutationObserver(function(){if(active())handoffControls();});observer.observe(root.document.documentElement,{subtree:true,childList:true});return true;}catch(e){return false;}}
  function tick(){try{installStyle();syncMissionDefinitions();installShipDraw();calmFrames();installObserver();var on=active();if(root.document&&root.document.body){root.document.body.classList.toggle("good-boys-directed",on);root.document.body.classList.toggle("good-boys-cinematic",on&&cinematicVisible());}removeDirectorPads();if(on)handoffControls();}catch(e){root.__goodBoysDirectorError=String(e&&e.stack||e);}}
  tick();var timer=root.setInterval?root.setInterval(tick,150):null;
  root.TechOpsGoodBoysCampaignDirector={VERSION:VERSION,tick:tick,showOpening:showOpening,showCinematic:showCinematic,duoAttack:duoAttack,reliableThrow:reliableThrow,handoffControls:handoffControls,syncMissionDefinitions:syncMissionDefinitions,drawShip:drawShip,progressionWatch:progressionWatch,observer:observer,timer:timer,openingOwner:"TechOpsGoodBoysIntroRepair"};
})(typeof globalThis!=="undefined"?globalThis:this);