/* Good Boys Earthfall ending authority v3.
 * Owns the M8 return-home sequence and campaign completion. This prevents the
 * authored route from falling back into the legacy v7.36 b736m8 canvas reel.
 */
(function(root){
  "use strict";
  if(!root)return;
  try{var old=root.TechOpsGoodBoysEarthfallEnding;if(old&&old.timer&&root.clearInterval)root.clearInterval(old.timer);if(old&&old.detachInput)old.detachInput();}catch(_){}
  var VERSION=3,running=false,replaying=false,complete=false,scene=0,overlay=null,canvas=null,ctx=null,raf=0,img=null,lastFrame="",timer=null,inputAttached=false,previousFocus=null,settling=false,flagsApplied=false,calm=false,pausedAt=0,pausedDuration=0,startedAt=0;
  var SCENES=[
    {title:"ESCAPE BURN",kicker:"BLACKSITE MERIDIAN · SHUTTLE BAY",body:"The Warden is down. K drags the route controls offline while Waldo seals the maintenance hatch. Katrin and Manchez are aboard before the prison can rebuild its lock.",goal:"K · WALDO · KATRIN · MANCHEZ — ACCOUNTED FOR",frames:["sh_takeoff","sh_climb","sh_thrust2"]},
    {title:"EARTHFALL",kicker:"REENTRY CORRIDOR",body:"The stolen shuttle was built for maintenance hops, not atmospheric return. Heat eats the telemetry. K keeps the guidance alive. Waldo points at the only patch of ground they all recognize.",goal:"HOLD THE LINE · KEEP THE SHIP TOGETHER",frames:["sh_reentry","sh_damage0","sh_damage1"]},
    {title:"WALDO'S PLACE",kicker:"DAWN · HOME VECTOR",body:"The shuttle clears the tree line and turns Waldo's hidden bay into a very visible problem. The garage survives. Mostly. The porch light is still on.",goal:"HOME IS NOT QUIET · HOME IS HOME",frames:["sh_crash","sh_wreck"]},
    {title:"GOOD DOGS PROTOCOL — COMPLETE",kicker:"118 FREE · 1984 FREE",body:"K walks out under his own name. Waldo walks back through his own door. Katrin and Manchez do what they came to do: bring everyone home.",goal:"BREAKOUT COMPLETE · KATRIN + MANCHEZ UNLOCKED",frames:["sh_wreck"],cta:"SAVE & RETURN TO TITLE"}
  ];
  function now(){return root.performance&&root.performance.now?root.performance.now():Date.now();}
  function meta(){try{if(!root.S)return null;root.S.meta=root.S.meta||{};var m=root.S.meta._v736||(root.S.meta._v736={m:1,evidence:[],k:false,waldo:false,done:false});if(m.done&&Number(m.m)>8){m.m=8;root.__goodBoysTerminalMissionNormalized=true;}return m;}catch(e){return null;}}
  function cs(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function mission(){try{var c=cs(),m=meta();return Number(c&&c.m||m&&m.m||0)||0;}catch(e){return 0;}}
  function save(){try{if(typeof root.save==="function")return root.save()!==false;if(typeof root.saveGame==="function")return root.saveGame()!==false;return false;}catch(e){root.__goodBoysEarthfallSaveError=String(e&&e.stack||e);return false;} }
  function bgSrc(){try{var p=root.GOOD_BOYS_CUTSCENE_PLATES,keys=["warden_shuttle_bay","earthfall","crash_site","waldo_house"];if(p&&p[keys[scene]||"earthfall"])return p[keys[scene]||"earthfall"];var b=root.NM_BG734&&root.NM_BG734.goodboys_earthfall;if(b&&b.src)return b.src;var map=root.GOOD_BOYS_CAMPAIGN_BACKGROUND_SOURCE,k=map&&map.goodboys_earthfall,im=k&&root.NM_BG734&&root.NM_BG734[k];return im&&im.src||"";}catch(e){return "";}}
  function atlas(){try{return root.SHUTTLE&&root.SHUTTLE.src&&root.SHUTTLE.frames?root.SHUTTLE:null;}catch(e){return null;}}
  function atlasImage(){try{var a=atlas();if(!a)return null;if(!img||img.src!==a.src){img=new root.Image();img.src=a.src;}return img.complete&&img.naturalWidth?img:null;}catch(e){return null;}}
  function installStyle(){
    if(!root.document)return;var id="good-boys-earthfall-style",s=root.document.getElementById(id);if(s)return;
    s=root.document.createElement("style");s.id=id;s.textContent=[
      "#good-boys-earthfall-cine{position:fixed;inset:0;z-index:130000;background:#02050b center/contain no-repeat;color:#eef8ff;font-family:monospace;overflow:hidden;touch-action:pan-y}",
      "#good-boys-earthfall-cine:before,#good-boys-earthfall-cine:after{content:'';position:absolute;left:0;right:0;height:7vh;background:#000;z-index:4}#good-boys-earthfall-cine:before{top:0}#good-boys-earthfall-cine:after{bottom:0}",
      "#good-boys-earthfall-cine canvas{position:absolute;inset:0;width:100%;height:100%;z-index:2;image-rendering:pixelated}",
      "#good-boys-earthfall-cine .gbe-shade{position:absolute;inset:0;z-index:1;background:linear-gradient(to bottom,rgba(1,4,8,.12),rgba(1,4,8,.28) 45%,rgba(1,4,8,.96))}",
      "#good-boys-earthfall-cine .gbe-card{position:absolute;z-index:5;left:50%;bottom:max(9vh,calc(env(safe-area-inset-bottom) + 28px));transform:translateX(-50%);width:min(720px,92vw);box-sizing:border-box;padding:16px 18px;border:2px solid #ffd166;border-radius:14px;background:rgba(2,7,13,.94);box-shadow:0 0 42px #000c}",
      "#good-boys-earthfall-cine .gbe-kicker{color:#ffd166;font:700 10px/1.3 monospace;letter-spacing:.09em}#good-boys-earthfall-cine h2{margin:7px 0 9px;color:#fff;font:800 21px/1.1 monospace}#good-boys-earthfall-cine p{margin:0 0 10px;color:#d9edf7;font:13px/1.5 monospace}#good-boys-earthfall-cine .gbe-goal{padding:8px 10px;margin:0 0 12px;border-left:3px solid #55dfff;background:#07131ddd;color:#bfeaff;font:800 10px/1.4 monospace}#good-boys-earthfall-cine button{width:100%;min-height:50px;border:2px solid #ffd166;border-radius:10px;background:#171107;color:#fff5d6;font:800 12px monospace;touch-action:manipulation}",
      "#good-boys-earthfall-cine .gbe-card{max-height:calc(100% - 16vh - env(safe-area-inset-top) - env(safe-area-inset-bottom));overflow-y:auto;overscroll-behavior:contain}#good-boys-earthfall-cine .gbe-skip{margin-top:8px;min-height:44px;border:1px solid #738797;background:#07131d;color:#c6d6e1}#good-boys-earthfall-cine button:focus-visible{outline:3px solid #bfeaff;outline-offset:2px}#good-boys-earthfall-cine .gbe-error{color:#ffd166;margin-top:12px}#good-boys-earthfall-cine .gbe-error:empty{display:none}",
      "@media(max-height:500px){#good-boys-earthfall-cine .gbe-card{bottom:max(12px,env(safe-area-inset-bottom));max-height:calc(100% - 24px - env(safe-area-inset-top) - env(safe-area-inset-bottom));padding:10px 14px}#good-boys-earthfall-cine:before,#good-boys-earthfall-cine:after{height:3vh}}",
      "body.good-boys-earthfall-active #good-boys-director-controls,body.good-boys-earthfall-active #good-dogs-touch,body.good-boys-earthfall-active #good-boys-loop-controls,body.good-boys-earthfall-active #touch-buttons{display:none!important;visibility:hidden!important;pointer-events:none!important}"
    ].join("");(root.document.head||root.document.documentElement).appendChild(s);
  }
  function drawFrame(t){
    try{
      if(!running||!ctx||!canvas||root.document.hidden)return;t=calm?0:Math.max(0,t-startedAt-pausedDuration);var dpr=Math.max(1,Math.min(2,root.devicePixelRatio||1)),w=Math.max(1,Math.round(canvas.clientWidth*dpr)),h=Math.max(1,Math.round(canvas.clientHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.clearRect(0,0,w,h);
      var s=SCENES[scene],a=atlas(),im=atlasImage(),frames=s&&s.frames||[],idx=Math.floor(t/420)%Math.max(1,frames.length),key=frames[idx],fr=a&&a.frames&&a.frames[key];lastFrame=key||"";
      if(im&&fr){var targetW=Math.min(w*.48,460*dpr),targetH=targetW*(fr[3]/fr[2]),x=w*.5-targetW*.5,y=scene===0?h*.34:scene===1?h*.28:h*.43;ctx.save();ctx.imageSmoothingEnabled=false;if(scene===1&&!calm){ctx.globalAlpha=.18;for(var i=0;i<8;i++){ctx.fillStyle="#fff";ctx.fillRect((w*((i*.137+(t/5000))%1)),h*.16+i*23*dpr,60*dpr,2*dpr);}}ctx.globalAlpha=1;ctx.drawImage(im,fr[0],fr[1],fr[2],fr[3],x,y,targetW,targetH);ctx.restore();}
      if(scene===1){var glow=calm?.13:.13+.07*Math.sin(t/90);ctx.fillStyle="rgba(255,112,46,"+glow+")";ctx.fillRect(0,0,w,h*.7);}if(scene===2&&!calm){ctx.fillStyle="rgba(255,255,255,"+Math.max(0,.07*Math.sin(t/120))+")";ctx.fillRect(0,0,w,h);}raf=root.requestAnimationFrame?root.requestAnimationFrame(drawFrame):0;
    }catch(e){root.__goodBoysEarthfallDrawError=String(e&&e.stack||e);}
  }
  function render(){
    if(overlay){var bg=bgSrc();overlay.style.backgroundImage=bg?'linear-gradient(to bottom,rgba(1,4,8,.05),rgba(1,4,8,.55)),url("'+String(bg).replace(/"/g,"%22")+'")':'';}
    if(!overlay)return;var s=SCENES[scene],shownScene=scene;var card=overlay.querySelector(".gbe-card");if(!card)return;card.innerHTML='<div class="gbe-kicker">GOOD DOGS PROTOCOL · '+s.kicker+' · '+(scene+1)+' / '+SCENES.length+'</div><h2 id="gbe-title">'+s.title+'</h2><p id="gbe-story">'+s.body+'</p><div class="gbe-goal">'+s.goal+'</div><button id="gbe-next">'+(s.cta||(scene===SCENES.length-1?'END OPERATION':'CONTINUE'))+'</button>'+(scene<SCENES.length-1?'<button id="gbe-skip" class="gbe-skip">Skip ending &amp; save</button>':'')+'<p class="gbe-error" role="alert" aria-live="assertive"></p>';var b=card.querySelector("#gbe-next"),skip=card.querySelector("#gbe-skip");if(b){b.addEventListener("click",function(e){if(scene===shownScene)next(e);});if(typeof b.focus==="function")b.focus();}if(skip)skip.addEventListener("click",skipEnding);
  }
  function finishFlags(){
    try{if(complete)return true;var m=meta();if(!m)return false;if(!flagsApplied){m.k=true;m.waldo=true;m.done=true;m.m=8;root.S.meta._v736breakout=true;root.S.meta._v736pair=true;try{root.localStorage&&root.localStorage.setItem("techops_char_1181984","katrin_manchez");}catch(_){}var c=cs();if(c){c.m=8;c.ending=true;}if(root.NM){root.NM.enemies=[];root.NM.clear=false;root.NM._gbEarthfallComplete=true;}try{var semantic=root.TechOpsGoodDogsCampaignState;if(semantic&&typeof semantic.completeReturn==="function")semantic.completeReturn();}catch(e){root.__goodBoysSemanticCompletionError=String(e&&e.stack||e);return false;}flagsApplied=true;}if(!save())return false;complete=true;root.__goodBoysEarthfallCompleteAt=Date.now();return true;}catch(e){root.__goodBoysEarthfallCompleteError=String(e&&e.stack||e);return false;}
  }
  function visibility(){if(!running)return;if(root.document.hidden){pausedAt=now();if(raf&&root.cancelAnimationFrame)root.cancelAnimationFrame(raf);raf=0;}else{if(pausedAt)pausedDuration+=now()-pausedAt;pausedAt=0;if(ctx&&root.requestAnimationFrame)raf=root.requestAnimationFrame(drawFrame);}}
  function detachInput(){try{if(inputAttached&&root.document){root.document.removeEventListener("keydown",onKey,true);root.document.removeEventListener("visibilitychange",visibility);}}catch(_){}inputAttached=false;}
  function close(){try{if(raf&&root.cancelAnimationFrame)root.cancelAnimationFrame(raf);}catch(_){}raf=0;detachInput();try{if(overlay&&overlay.parentNode)overlay.parentNode.removeChild(overlay);}catch(_){}overlay=null;canvas=null;ctx=null;running=false;replaying=false;try{if(root.document&&root.document.body){root.document.body.classList.remove("good-boys-earthfall-active");root.document.body.classList.remove("good-boys-cinematic");}if(root.S)root.S.inDialog=false;if(previousFocus&&previousFocus.isConnected!==false&&typeof previousFocus.focus==="function")previousFocus.focus();}catch(_){} }
  function returnToTitle(){
    root.__goodBoysEarthfallReturnToTitle={at:Date.now(),saved:complete};
    try{if(root.location&&typeof root.location.reload==="function"){root.location.reload();return true;}}catch(e){root.__goodBoysEarthfallReloadError=String(e&&e.stack||e);}
    try{var d=root.document,title=d&&d.getElementById("title-screen"),hud=d&&d.getElementById("hud"),touch=d&&d.getElementById("touch-ui");if(title)title.classList.remove("hidden");if(hud)hud.classList.add("hidden");if(touch)touch.classList.add("hidden");return!!title;}catch(e){root.__goodBoysEarthfallReturnError=String(e&&e.stack||e);return false;}
  }
  function finish(){if(!running||settling||root.document.hidden)return false;settling=true;if(!finishFlags()){settling=false;scene=SCENES.length-1;render();var error=overlay&&overlay.querySelector(".gbe-error");if(error)error.textContent="Your ending could not be saved. Keep this page open and choose Save & return to title to retry.";return false;}close();returnToTitle();return true;}
  function skipEnding(e){if(e){e.preventDefault();e.stopPropagation();}return finish();}
  function next(e){if(e){e.preventDefault();e.stopPropagation();}if(!running||settling||root.document.hidden)return false;if(scene<SCENES.length-1){scene++;render();return true;}return finish();}
  function onKey(e){try{if(!running||!e||root.document.hidden)return;var k=e.code||e.key;if(k==="Tab"){var buttons=Array.from(overlay.querySelectorAll("button")).filter(function(b){return !b.disabled&&!b.hidden;}),i=buttons.indexOf(root.document.activeElement);e.preventDefault();e.stopImmediatePropagation();if(buttons.length)buttons[i<0?(e.shiftKey?buttons.length-1:0):(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();return;}if(e.repeat)return;if(k==="Escape"){e.stopImmediatePropagation();skipEnding(e);}else if(k==="KeyE"||k==="Enter"||k==="Space"||k===" "){e.stopImmediatePropagation();if(root.document.activeElement&&root.document.activeElement.id==="gbe-skip")skipEnding(e);else next(e);}}catch(err){root.__goodBoysEarthfallInputError=String(err&&err.stack||err);}}
  function attachInput(){try{if(inputAttached||!root.document)return;root.document.addEventListener("keydown",onKey,true);root.document.addEventListener("visibilitychange",visibility);inputAttached=true;}catch(e){root.__goodBoysEarthfallInputError=String(e&&e.stack||e);}}
  function begin(options){
    try{
      options=options||{};var replay=options.replay===true,m=meta();if(running)return true;if(!m||(m.done&&!replay)){complete=!!(m&&m.done);return false;}if(!root.document||!root.document.body)return false;installStyle();running=true;replaying=replay;complete=false;flagsApplied=false;settling=false;scene=0;previousFocus=root.document.activeElement;startedAt=now();pausedDuration=0;pausedAt=root.document.hidden?startedAt:0;calm=!!(root.matchMedia&&root.matchMedia('(prefers-reduced-motion: reduce)').matches);var c=cs();if(c)c.ending=true;if(root.NM){root.NM.enemies=[];root.NM.clear=false;}if(root.S)root.S.inDialog=true;root.document.body.classList.add("good-boys-earthfall-active");root.document.body.classList.add("good-boys-cinematic");overlay=root.document.createElement("div");overlay.id="good-boys-earthfall-cine";if(overlay.setAttribute){overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");overlay.setAttribute("aria-labelledby","gbe-title");overlay.setAttribute("aria-describedby","gbe-story");}var bg=bgSrc();if(bg)overlay.style.backgroundImage='linear-gradient(to bottom,rgba(1,4,8,.05),rgba(1,4,8,.55)),url("'+String(bg).replace(/"/g,"%22")+'")';overlay.innerHTML='<div class="gbe-shade"></div><canvas aria-hidden="true"></canvas><div class="gbe-card"></div>';root.document.body.appendChild(overlay);canvas=overlay.querySelector("canvas");ctx=canvas&&canvas.getContext?canvas.getContext("2d"):null;attachInput();render();if(ctx&&root.requestAnimationFrame&&!root.document.hidden)raf=root.requestAnimationFrame(drawFrame);root.__goodBoysEarthfallStartedAt=Date.now();root.__goodBoysEarthfallReplay=replay;return true;
    }catch(e){root.__goodBoysEarthfallError=String(e&&e.stack||e);running=false;detachInput();return false;}
  }
  function tick(){try{var m=meta();if(!m||running)return;if(m.done){complete=true;return;}if(mission()===8)begin();}catch(e){root.__goodBoysEarthfallError=String(e&&e.stack||e);}}
  function acceptance(){var m=meta();return{version:VERSION,running:running,replaying:replaying,scene:scene+1,sceneCount:SCENES.length,lastFrame:lastFrame,mission:mission(),done:!!(m&&m.done),k:!!(m&&m.k),waldo:!!(m&&m.waldo),breakout:!!(root.S&&root.S.meta&&root.S.meta._v736breakout),pair:!!(root.S&&root.S.meta&&root.S.meta._v736pair),overlay:!!(root.document&&root.document.getElementById("good-boys-earthfall-cine")),complete:complete,terminalMissionNormalized:!!root.__goodBoysTerminalMissionNormalized};}
  timer=root.setInterval?root.setInterval(tick,90):null;
  root.TechOpsGoodBoysEarthfallEnding={VERSION:VERSION,SCENES:SCENES,begin:begin,replay:function(){return begin({replay:true});},next:next,skip:skipEnding,finishFlags:finishFlags,returnToTitle:returnToTitle,tick:tick,acceptance:acceptance,detachInput:detachInput,timer:timer};
  tick();
})(typeof globalThis!=="undefined"?globalThis:this);
