/* TechOps Hero — production Good Dogs co-op authority v4.
 * Visual authority pass for the user-supplied Good Dogs sheets:
 *   - force Katrin/Manchez atlas art over generic Mike/Night Walker art;
 *   - alias the ship/prison/cockpit boards into the mission background map;
 *   - add a richer co-op HUD and mobile controls without drawNM ownership.
 */
(function(root){
  "use strict";
  if(!root)return;
  var VERSION=4;
  var dogImage=null,shipImage=null,bgStyle=null,starting=false,baseEnterNight=null,baseNightPlayer=null,baseDrawNM=null,hudStyle=null;
  var COLORS={katrin:"#22b8ff",manchez:"#ff9f1c",green:"#3cff78",red:"#ff4055",bg:"rgba(4,8,14,.92)",line:"rgba(120,210,255,.30)",text:"#eff8ff"};
  function productionCompositorActive(){try{return !!(root.TechOpsProductionWrapperGuard||root.__productionSingleCompositor||root.__productionCompositorPlanned);}catch(e){return false;}}
  function atlas(){return root.KATRIN_MANCHEZ||root.DOGS_ACTION||root.DOGS||null;}
  function campaign(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function activeWho(){var c=campaign();return c&&c.active==="manchez"?"manchez":"katrin";}
  function charState(who){var c=campaign();return c&&c.chars&&c.chars[who]?c.chars[who]:null;}
  function imgReady(slot,A){try{if(!A||!A.src||typeof root.Image!=="function")return null;var im=slot==="ship"?shipImage:dogImage;if(!im||im.src!==A.src){im=new root.Image();im.src=A.src;if(slot==="ship")shipImage=im;else dogImage=im;}return im.complete&&im.naturalWidth?im:null;}catch(e){return null;}}
  function atlasReady(){return imgReady("dog",atlas());}
  function shipAtlas(){return root.SHUTTLE||root.GOOD_SHIP||null;}
  function shipReady(){return imgReady("ship",shipAtlas());}
  function alias(fr,to,from){if(fr&&!fr[to]&&fr[from])fr[to]=fr[from];}
  function normalizePartnerIdleFrames(){try{var A=atlas();if(!A||!A.frames)return false;["kat","man"].forEach(function(p){alias(A.frames,p+"_idle0",p+"_idle");alias(A.frames,p+"_idle1",p+"_walk");for(var i=0;i<8;i++)alias(A.frames,p+"_idle"+i,p+"_idle"+(i%2));alias(A.frames,p+"_strike",p+"_pounce");alias(A.frames,p+"_leap",p+"_pounce");alias(A.frames,p+"_roll",p+"_dash");alias(A.frames,p+"_shield",p+"_hack");alias(A.frames,p+"_wall_hit",p+"_down");});return true;}catch(e){return false;}}
  function conservativeFrame(who,NM,now){var p=who==="manchez"?"man_":"kat_",A=atlas(),has=function(k){return !!(A&&A.frames&&A.frames[k]);};if(!NM||NM.hp<=0)return p+"down";if(NM.ifr>0&&has(p+"wall_hit"))return p+"wall_hit";if(NM.dashT>0&&has(p+"roll"))return p+"roll";if(NM.jabAnim>0)return has(p+"strike")?p+"strike":p+"pounce";if(NM.block&&has(p+"shield"))return p+"shield";if(!NM.onGround&&has(p+"leap"))return p+"leap";return p+((Math.floor((now||0)/(Math.abs(NM.vx||0)>.45?145:720))%2)?"idle1":"idle0");}
  function drawAtlasFrame(x,A,im,key,dx,dy,dw,dh,flip,alpha){try{var fr=A&&A.frames&&A.frames[key];if(!im||!fr||fr.length<4)return false;x.save();x.imageSmoothingEnabled=false;x.globalAlpha=alpha==null?1:alpha;if(flip){x.translate(dx+dw/2,0);x.scale(-1,1);x.drawImage(im,fr[0],fr[1],fr[2],fr[3],-dw/2,dy,dw,dh);}else x.drawImage(im,fr[0],fr[1],fr[2],fr[3],dx,dy,dw,dh);x.restore();return true;}catch(e){return false;}}
  function fallbackDog(x,who,cx,base,h,flip,pose,now){var u=h/100,t=now||0,blue=who==="katrin",coat=blue?"#f5f5f1":"#fff2d7",trim=blue?COLORS.katrin:COLORS.manchez,hat=blue?"#05080d":"#3b2515",vest=blue?"#080b12":"#203018",bob=Math.sin(t/180)*2*u,lean=pose&&pose.indexOf("strike")>=0?10*u:0;x.save();if(flip){x.translate(cx,0);x.scale(-1,1);x.translate(-cx,0);}x.translate(0,bob);x.fillStyle="rgba(0,0,0,.28)";x.beginPath();x.ellipse(cx,base-2,31*u,6*u,0,0,7);x.fill();x.fillStyle=coat;x.beginPath();x.ellipse(cx-6*u+lean,base-32*u,30*u,18*u,0,0,7);x.fill();x.fillStyle=vest;x.beginPath();x.ellipse(cx-5*u+lean,base-35*u,24*u,15*u,0,0,7);x.fill();x.fillStyle=coat;x.beginPath();x.ellipse(cx+18*u+lean,base-49*u,16*u,15*u,0,0,7);x.fill();x.fillStyle=hat;x.beginPath();x.arc(cx+15*u+lean,base-60*u,15*u,Math.PI,0);x.fill();x.fillRect(cx+2*u+lean,base-60*u,27*u,10*u);x.fillStyle=trim;x.beginPath();x.arc(cx+5*u+lean,base-35*u,5*u,0,7);x.fill();x.strokeStyle=coat;x.lineWidth=6*u;x.beginPath();x.moveTo(cx-34*u+lean,base-38*u);x.quadraticCurveTo(cx-56*u+lean,base-65*u-Math.sin(t/80)*7*u,cx-37*u+lean,base-72*u);x.stroke();x.strokeStyle=coat;x.lineWidth=5*u;[-20,-3,14].forEach(function(l){x.beginPath();x.moveTo(cx+l*u+lean,base-20*u);x.lineTo(cx+(l+4)*u+lean,base-3*u);x.stroke();});if(pose&&/strike|pounce|roll/.test(pose)){x.strokeStyle=trim;x.lineWidth=4*u;x.beginPath();x.arc(cx+35*u+lean,base-38*u,32*u,-.55,.38);x.stroke();}x.restore();}
  function drawDogFrame(x,key,cx,base,h,flip,alpha){try{var A=atlas(),im=atlasReady(),fr=A&&A.frames&&A.frames[key];if(im&&fr){var dw=h*(fr[2]/fr[3]);x.save();x.globalAlpha=alpha==null?1:alpha;x.fillStyle="#000";x.globalAlpha*=.28;x.beginPath();x.ellipse(cx,base-2,Math.max(18,dw*.31),5.5,0,0,7);x.fill();x.globalAlpha=alpha==null?1:alpha;drawAtlasFrame(x,A,im,key,cx-dw/2,base-h,dw,h,flip,1);x.restore();return true;}fallbackDog(x,key&&key.indexOf("man_")===0?"manchez":"katrin",cx,base,h,flip,key,root.performance&&performance.now?performance.now():0);return true;}catch(e){return false;}}
  function drawActiveDog(x,NM,px,py,now){var cs=campaign();if(!cs||!cs.active)return false;var who=activeWho(),c=cs.chars&&cs.chars[who];if(c&&c.downed)return false;var h=Math.max(84,(NM.h||34)*2.5),cx=px+(NM.w||22)/2,base=py+(NM.h||34)+9;return drawDogFrame(x,conservativeFrame(who,NM,now||0),cx,base,h,(NM.face||1)<0,1);}
  function roundRect(x,px,py,w,h,r,fill,stroke){x.beginPath();if(x.roundRect)x.roundRect(px,py,w,h,r);else x.rect(px,py,w,h);if(fill)x.fill();if(stroke)x.stroke();}
  function bar(x,px,py,w,h,val,max,color){var p=Math.max(0,Math.min(1,(Number(val)||0)/Math.max(1,Number(max)||1)));x.fillStyle="rgba(0,0,0,.65)";roundRect(x,px,py,w,h,3,true,false);x.fillStyle=color;roundRect(x,px+2,py+2,(w-4)*p,h-4,2,true,false);}
  function dogPortrait(x,who,px,py,size){var p=who==="manchez"?"man_":"kat_",key=p+"idle0",A=atlas(),im=atlasReady(),fr=A&&A.frames&&A.frames[key];x.save();x.fillStyle=who==="katrin"?"#071b2b":"#2a1605";roundRect(x,px,py,size,size,8,true,false);x.strokeStyle=who==="katrin"?COLORS.katrin:COLORS.manchez;x.lineWidth=2;roundRect(x,px,py,size,size,8,false,true);if(im&&fr){var h=size-4,dw=h*(fr[2]/fr[3]);drawAtlasFrame(x,A,im,key,px+(size-dw)/2,py+2,dw,h,false,1);}else fallbackDog(x,who,px+size/2,py+size-4,size*.95,false,"idle",0);x.restore();}
  function drawReferenceHUD(x,NM){if(root.__goodBoysHideHud)return;var cs=campaign();if(!cs)return;var W=(root.cv&&root.cv.width)||x.canvas.width,H=(root.cv&&root.cv.height)||x.canvas.height,compact=W<700,pad=compact?10:16,cardW=compact?Math.min(154,(W-34)/2):196,cardH=compact?58:66;function card(who,left){var c=charState(who)||{},color=who==="katrin"?COLORS.katrin:COLORS.manchez,px=left?pad:W-pad-cardW,py=pad+4,portrait=cardH-10;x.save();x.fillStyle=COLORS.bg;x.strokeStyle=color;x.lineWidth=2;roundRect(x,px,py,cardW,cardH,9,true,true);dogPortrait(x,who,px+5,py+5,portrait);x.fillStyle=color;x.font="bold "+(compact?10:12)+"px monospace";x.textAlign="left";x.fillText(who.toUpperCase(),px+portrait+12,py+17);var hp=(who===activeWho()&&NM)?NM.hp:(c.hp==null?100:c.hp),mx=c.maxHp||100;bar(x,px+portrait+12,py+27,cardW-portrait-20,10,hp,mx,COLORS.red);x.fillStyle="#cfe8ff";x.font="bold 8px monospace";x.fillText(Math.max(0,Math.round(hp))+" / "+mx,px+portrait+12,py+50);if(who===activeWho()){x.fillStyle=color;x.textAlign="right";x.fillText("ACTIVE",px+cardW-8,py+50);}x.restore();}card("katrin",true);card("manchez",false);var titleW=Math.min(compact?220:370,W*.48),tx=(W-titleW)/2,ty=pad+6;x.save();x.fillStyle="rgba(3,8,12,.88)";x.strokeStyle="rgba(60,255,120,.45)";roundRect(x,tx,ty,titleW,compact?42:50,7,true,true);x.fillStyle=COLORS.green;x.textAlign="center";x.font="bold "+(compact?9:11)+"px monospace";x.fillText("GOOD DOGS PROTOCOL",W/2,ty+16);x.fillStyle="#d8fce5";x.font="bold "+(compact?7:9)+"px monospace";x.fillText("SHIP → PRISON 736 → 118 / 1984",W/2,ty+32);x.restore();var sync=Math.max(0,Math.min(100,Number(cs.sync)||0)),sw=Math.min(230,W*.44),sx=(W-sw)/2,sy=H-(compact?48:56);x.save();x.fillStyle="rgba(2,8,10,.87)";x.strokeStyle=sync>=100?COLORS.green:"#38779a";roundRect(x,sx,sy,sw,24,6,true,true);bar(x,sx+48,sy+7,sw-58,10,sync,100,sync>=100?COLORS.green:"#44c9ff");x.fillStyle=sync>=100?COLORS.green:"#dcefff";x.font="bold 8px monospace";x.textAlign="left";x.fillText(sync>=100?"SYNC!":"SYNC",sx+8,sy+16);x.restore();}
  function installBackgroundAliases(){try{root.NM_BG734=root.NM_BG734||{};var map={goodboys_hangar:["bg_shuttle_crew","shuttle_crew","waldo_garage"],goodboys_breach:["orbital_gate","goodboys_ship","orbital_tiles"],goodboys_cell118:["orbital_gate","orbital_eye"],goodboys_core:["orbital_eye","goodboys_cell1984"],goodboys_cell1984:["orbital_eye","orbital_gate"],goodboys_escape:["orbital_eye","goodboys_breach"],goodboys_earthfall:["waldo_loft","waldo_garage"]};Object.keys(map).forEach(function(k){if(root.NM_BG734[k])return;map[k].some(function(src){var im=root.NM_BG734[src]||root[src]||root["__GK_BG_"+src.toUpperCase()];if(im){root.NM_BG734[k]=im;return true;}return false;});});return true;}catch(e){return false;}}
  function installCssArtDirection(){try{if(!root.document)return false;if(bgStyle)return true;bgStyle=root.document.createElement("style");bgStyle.id="good-dogs-uploaded-art-direction";bgStyle.textContent="body.good-dogs-active canvas#game{image-rendering:pixelated}body.good-dogs-active #game-wrap:after{content:'GOOD DOGS ASSET PASS';position:fixed;left:max(10px,env(safe-area-inset-left));bottom:max(10px,env(safe-area-inset-bottom));font:bold 9px monospace;color:#dff6ff;background:#06101ddd;border:1px solid #22b8ff88;border-radius:8px;padding:5px 7px;pointer-events:none;z-index:5;opacity:.72}";(root.document.head||root.document.documentElement).appendChild(bgStyle);return true;}catch(e){return false;}}
  function markStarting(){starting=true;root.__TECHOPS_GOOD_DOGS_STARTING=true;}
  function isStarting(){return !!(starting||root.__TECHOPS_GOOD_DOGS_STARTING);}
  function installEntryFix(){try{if(typeof root.enterNight!=="function"||root.enterNight.__goodDogsProduction)return false;baseEnterNight=root.enterNight;root.enterNight=function(){if(!isStarting())return baseEnterNight.apply(this,arguments);var r=baseEnterNight.apply(this,arguments);try{if(root.v722&&typeof root.v722.active==="function"&&root.v722.active()&&typeof root.v722.skip==="function")root.v722.skip();}catch(e){}starting=false;root.__TECHOPS_GOOD_DOGS_STARTING=false;return r;};root.enterNight.__goodDogsProduction=true;return true;}catch(e){return false;}}
  function installStartCapture(){try{if(root.document&&!root.document.__goodDogsStartCapture){root.document.addEventListener("click",function(e){try{var t=e.target&&e.target.closest?e.target.closest("#btn-v736"):null;if(t)markStarting();}catch(_){}},true);root.document.__goodDogsStartCapture=true;}if(root.v736&&typeof root.v736.start==="function"&&!root.v736.start.__goodDogsProduction){var s=root.v736.start;root.v736.start=function(){markStarting();return s.apply(this,arguments);};root.v736.start.__goodDogsProduction=true;}return true;}catch(e){return false;}}
  function installPlayerAuthority(){try{if(typeof root.drawNightPlayerAtlas!=="function"||root.drawNightPlayerAtlas.__goodDogsProduction)return false;baseNightPlayer=root.drawNightPlayerAtlas;root.drawNightPlayerAtlas=function(x,NM,px,py,now){if(NM&&NM._v736){if(drawActiveDog(x,NM,px,py,now))return true;return false;}return baseNightPlayer.apply(this,arguments);};root.drawNightPlayerAtlas.__goodDogsProduction=true;return true;}catch(e){return false;}}
  function installHudAuthority(){try{if(productionCompositorActive())return false;if(typeof root.drawNM!=="function"||root.drawNM.__goodDogsHud)return false;baseDrawNM=root.drawNM;root.drawNM=function(){var r=baseDrawNM.apply(this,arguments);try{if(campaign()&&root.ctx&&root.NM)drawReferenceHUD(root.ctx,root.NM);}catch(e){}return r;};root.drawNM.__goodDogsHud=true;return true;}catch(e){return false;}}
  function ensureCampaignCss(){try{if(!root.document)return false;if(!hudStyle){hudStyle=root.document.getElementById("good-dogs-reference-style");if(!hudStyle){hudStyle=root.document.createElement("style");hudStyle.id="good-dogs-reference-style";hudStyle.textContent="body.good-dogs-active #hud{display:none!important}body.good-dogs-active #quest-tracker{display:none!important}body.good-dogs-active #touch-buttons{opacity:.88}body.good-dogs-active #dpad{transform:scale(.88);transform-origin:left bottom}";(root.document.head||root.document.documentElement).appendChild(hudStyle);}}var on=!!campaign();if(root.document.body)root.document.body.classList.toggle("good-dogs-active",on);return true;}catch(e){return false;}}
  function ensureMobileControls(){try{if(!root.document)return false;var id="good-dogs-touch",box=root.document.getElementById(id),on=!!campaign();if(!box){box=root.document.createElement("div");box.id=id;box.style.cssText="position:fixed;right:max(12px,calc(env(safe-area-inset-right) + 12px));bottom:max(88px,calc(env(safe-area-inset-bottom) + 88px));z-index:9998;display:none;grid-template-columns:repeat(2,64px);gap:7px;pointer-events:auto";function b(label,color,fn){var el=root.document.createElement("button");el.textContent=label;el.style.cssText="min-width:64px;min-height:48px;border:2px solid "+color+";border-radius:11px;background:#06101ddd;color:#eef9ff;font:bold 9px monospace;box-shadow:0 0 12px "+color+"55";el.addEventListener("pointerdown",function(ev){ev.preventDefault();ev.stopPropagation();try{fn();}catch(_){}},{passive:false});return el;}box.appendChild(b("⇄ SWAP",COLORS.katrin,function(){if(root.v736&&root.v736.swap)root.v736.swap();}));box.appendChild(b("SYNC",COLORS.manchez,function(){if(root.v736&&root.v736.finisher)root.v736.finisher();}));box.appendChild(b("K SUPPORT",COLORS.green,function(){if(root.v736&&root.v736.support)root.v736.support();}));root.document.body.appendChild(box);}box.style.display=on?"grid":"none";return true;}catch(e){return false;}}
  function acceptance(){try{var A=atlas(),B=root.NM_BG734||{};return{version:VERSION,source:"user-supplied Good Dogs visual direction",dogAtlas:!!(A&&A.frames),shipAtlas:!!shipAtlas(),backgrounds:["goodboys_hangar","goodboys_breach","goodboys_cell118","goodboys_cell1984","goodboys_escape"].filter(function(k){return !!B[k];}),pass:!!(A&&A.frames)};}catch(e){return{version:VERSION,error:String(e)}}}
  function tick(){installBackgroundAliases();normalizePartnerIdleFrames();installCssArtDirection();installStartCapture();installEntryFix();installPlayerAuthority();installHudAuthority();ensureCampaignCss();ensureMobileControls();}
  tick();var timer=null;try{if(!productionCompositorActive())timer=root.setInterval(tick,300);}catch(e){}
  root.TechOpsGoodDogsProduction={VERSION:VERSION,COLORS:COLORS,productionCompositorActive:productionCompositorActive,atlasReady:atlasReady,shipReady:shipReady,conservativeFrame:conservativeFrame,drawActiveDog:drawActiveDog,drawReferenceHUD:drawReferenceHUD,normalizePartnerIdleFrames:normalizePartnerIdleFrames,installBackgroundAliases:installBackgroundAliases,markStarting:markStarting,installEntryFix:installEntryFix,installStartCapture:installStartCapture,installPlayerAuthority:installPlayerAuthority,installHudAuthority:installHudAuthority,ensureCampaignCss:ensureCampaignCss,ensureMobileControls:ensureMobileControls,acceptance:acceptance,tick:tick,timer:timer};
})(typeof globalThis!=="undefined"?globalThis:this);
