/* TechOps Hero — Good Dogs opening sequence v4.
 * Canon physical flow:
 * GD_CUT_01 -> one contextual deck INTERACT -> playable space flight ->
 * GD_CUT_03 orbital/prison approach -> in-engine shuttle crash -> M2 prison.
 * The old three-terminal ship checklist is intentionally retired.
 */
(function(root){
  "use strict";
  if(!root||!root.document||root.TechOpsGoodBoysOpeningV4)return;
  var VERSION=4;
  function phase(name,extra){root.__goodBoysOpeningPhase=Object.assign({phase:name,owner:"good-boys-opening-v4",at:Date.now()},extra||{});}
  function remove(id){try{var n=root.document.getElementById(id);if(n)n.remove();}catch(_){} }
  function frame(rootEl,title,subtitle){
    rootEl.style.cssText="position:fixed;inset:0;z-index:150300;background:#02050a;color:#eff8ff;font-family:monospace;display:flex;align-items:center;justify-content:center;padding:max(8px,env(safe-area-inset-top)) 8px max(8px,env(safe-area-inset-bottom));box-sizing:border-box";
    var shell=root.document.createElement("div");shell.style.cssText="width:min(100%,980px);height:min(100%,760px);display:grid;grid-template-rows:auto 1fr auto;gap:8px;min-height:0";
    shell.innerHTML='<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;padding:4px 2px"><b style="color:#8df1ce;letter-spacing:.12em">'+title+'</b><span style="font-size:10px;color:#a8c6d8">'+subtitle+'</span></div><div data-stage style="position:relative;min-height:0;overflow:hidden;border:1px solid #315a70;background:#050b12;box-shadow:0 16px 50px #000"></div><div data-controls></div>';
    rootEl.appendChild(shell);return shell;
  }
  function drawAtlas(ctx,A,img,key,cx,base,h,flip){try{var fr=A&&A.frames&&A.frames[key];if(!fr||!img||!img.complete||!img.naturalWidth)return false;var w=h*(fr[2]/fr[3]);ctx.save();ctx.imageSmoothingEnabled=false;if(flip){ctx.translate(cx,0);ctx.scale(-1,1);ctx.drawImage(img,fr[0],fr[1],fr[2],fr[3],-w/2,base-h,w,h);}else ctx.drawImage(img,fr[0],fr[1],fr[2],fr[3],cx-w/2,base-h,w,h);ctx.restore();return true;}catch(_){return false;}}
  function showDeckInteraction(){return new Promise(function(resolve){
    remove("good-boys-ship-interlude");remove("good-boys-deck-v4");phase("ship-deck-interact");
    var host=root.document.createElement("div");host.id="good-boys-deck-v4";var shell=frame(host,"SHIP DECK · LIVE","GO TO THE CREW · INTERACT");var stage=shell.querySelector("[data-stage]"),controls=shell.querySelector("[data-controls]");
    var bg=new root.Image();bg.src="assets/v736/good_boys_ship/cockpit_pilot.jpg?v=20260903-deck-center-r1";var A=root.KATRIN_MANCHEZ||null,dog=A&&A.src?new root.Image():null;if(dog)dog.src=A.src;
    var canvas=root.document.createElement("canvas");canvas.width=960;canvas.height=540;canvas.style.cssText="width:100%;height:100%;object-fit:contain;image-rendering:auto";stage.appendChild(canvas);var ctx=canvas.getContext("2d"),done=false;
    function draw(){ctx.fillStyle="#06101a";ctx.fillRect(0,0,960,540);if(bg.complete&&bg.naturalWidth){var scale=Math.min(960/bg.naturalWidth,300/bg.naturalHeight),dw=bg.naturalWidth*scale,dh=bg.naturalHeight*scale;ctx.drawImage(bg,(960-dw)/2,34+(300-dh)/2,dw,dh);}ctx.fillStyle="rgba(0,8,14,.2)";ctx.fillRect(0,0,960,540);ctx.fillStyle="#8df1ce";ctx.font="700 18px monospace";ctx.fillText("CREW SIGNAL LOCKED",610,120);ctx.strokeStyle="#ffd166";ctx.lineWidth=4;ctx.strokeRect(610,145,250,215);ctx.fillStyle="rgba(255,209,102,.12)";ctx.fillRect(610,145,250,215);if(A&&dog){drawAtlas(ctx,A,dog,"kat_idle0",375,455,130,false);drawAtlas(ctx,A,dog,"man_idle0",500,455,130,false);}ctx.fillStyle="#fff";ctx.font="700 16px monospace";ctx.fillText("APPROACH / ACKNOWLEDGE",635,390);}
    bg.onload=draw;if(dog)dog.onload=draw;draw();
    controls.style.cssText="display:grid;grid-template-columns:1fr;gap:8px";controls.innerHTML='<button type="button" style="min-height:60px;border:1px solid #ffd166;background:#111b24;color:#fff;font:700 14px monospace;letter-spacing:.08em;touch-action:manipulation">USE / INTERACT</button>';
    var b=controls.querySelector("button");function finish(e){if(done)return;done=true;if(e){e.preventDefault();e.stopPropagation();}root.__goodBoysDeckInteract={completed:true,at:Date.now()};phase("ship-deck-complete");remove("good-boys-deck-v4");resolve({completed:true,interaction:"crew"});}
    b.addEventListener("pointerup",finish,{once:true});b.addEventListener("click",finish,{once:true});root.document.body.appendChild(host);root.__goodBoysDeckInteract={completed:false,at:Date.now()};
  });}
  function showSpaceFlight(){return new Promise(function(resolve){
    remove("good-boys-flight-v4");phase("space-flight");var host=root.document.createElement("div");host.id="good-boys-flight-v4";var shell=frame(host,"SPACE FLIGHT · MANUAL","HOLD COURSE TO BLACKSITE MERIDIAN");var stage=shell.querySelector("[data-stage]"),controls=shell.querySelector("[data-controls]");
    var canvas=root.document.createElement("canvas");canvas.width=960;canvas.height=540;canvas.style.cssText="width:100%;height:100%;image-rendering:pixelated";stage.appendChild(canvas);var ctx=canvas.getContext("2d"),A=root.SHUTTLE||null,img=A&&A.src?new root.Image():null;if(img)img.src=A.src;var x=480,held=0,start=performance.now(),last=start,done=false,raf=0;
    controls.style.cssText="display:grid;grid-template-columns:1fr 1fr;gap:8px";controls.innerHTML='<button data-dir="-1" type="button" style="min-height:58px;border:1px solid #55c7ff;background:#071624;color:#fff;font:700 18px monospace;touch-action:none">◀ STEER</button><button data-dir="1" type="button" style="min-height:58px;border:1px solid #55c7ff;background:#071624;color:#fff;font:700 18px monospace;touch-action:none">STEER ▶</button>';
    function shuttle(key,cx,cy,w){try{var fr=A&&A.frames&&A.frames[key];if(!fr||!img||!img.complete||!img.naturalWidth)return false;var h=w*(fr[3]/fr[2]);ctx.drawImage(img,fr[0],fr[1],fr[2],fr[3],cx-w/2,cy-h/2,w,h);return true;}catch(_){return false;}}
    function draw(now){var p=Math.min(1,(now-start)/5200);ctx.fillStyle="#01040a";ctx.fillRect(0,0,960,540);for(var i=0;i<80;i++){var sx=(i*137+(now*.22))%1000-20,sy=(i*73)%540,sz=1+(i%3);ctx.fillStyle="rgba(220,245,255,"+(0.3+(i%5)*.12)+")";ctx.fillRect(sx,sy,sz,sz);}ctx.strokeStyle="rgba(70,220,255,.25)";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(170,70);ctx.lineTo(360,470);ctx.moveTo(790,70);ctx.lineTo(600,470);ctx.stroke();ctx.fillStyle="#dff8ff";ctx.font="700 15px monospace";ctx.textAlign="center";ctx.fillText("BLACKSITE VECTOR  "+Math.round(p*100)+"%",480,42);var key=p<.22?"sh_thrust2":"sh_climb";if(!shuttle(key,x,330,180)){ctx.fillStyle="#cce9ff";ctx.fillRect(x-70,300,140,55);}root.__goodBoysSpaceFlight={active:!done,progress:p,x:Math.round(x),at:Date.now()};}
    function loop(now){if(done)return;var dt=Math.min(.06,(now-last)/1000);last=now;if(held)x=Math.max(260,Math.min(700,x+held*260*dt));draw(now);if(now-start>=5200){done=true;cancelAnimationFrame(raf);root.__goodBoysSpaceFlight={active:false,completed:true,progress:1,x:Math.round(x),at:Date.now()};phase("space-flight-complete");remove("good-boys-flight-v4");resolve({completed:true});return;}raf=requestAnimationFrame(loop);}function wire(b){var d=Number(b.dataset.dir);b.addEventListener("pointerdown",function(e){e.preventDefault();held=d;});["pointerup","pointercancel","pointerleave"].forEach(function(n){b.addEventListener(n,function(){held=0;});});}
    Array.prototype.forEach.call(controls.querySelectorAll("button"),wire);root.document.body.appendChild(host);raf=requestAnimationFrame(loop);
  });}
  function showCrashScene(){return new Promise(function(resolve){
    remove("good-boys-crash-v4");phase("crash-scene");var host=root.document.createElement("div");host.id="good-boys-crash-v4";var shell=frame(host,"APPROACH FAILURE","PRISON PERIMETER · IMPACT");var stage=shell.querySelector("[data-stage]"),controls=shell.querySelector("[data-controls]");controls.innerHTML='<div style="text-align:center;color:#ffd166;font:700 11px monospace">AUTOMATIC CINEMATIC</div>';
    var canvas=root.document.createElement("canvas");canvas.width=960;canvas.height=540;canvas.style.cssText="width:100%;height:100%;image-rendering:pixelated";stage.appendChild(canvas);var ctx=canvas.getContext("2d"),A=root.SHUTTLE||null,img=A&&A.src?new root.Image():null;if(img)img.src=A.src;var start=performance.now(),raf=0;
    function ship(key,cx,cy,w){try{var fr=A&&A.frames&&A.frames[key];if(!fr||!img||!img.complete||!img.naturalWidth)return false;var h=w*(fr[3]/fr[2]);ctx.drawImage(img,fr[0],fr[1],fr[2],fr[3],cx-w/2,cy-h/2,w,h);return true;}catch(_){return false;}}
    function loop(now){var t=(now-start)/1000;ctx.fillStyle=t<2.1?"#090d16":"#17110d";ctx.fillRect(0,0,960,540);ctx.fillStyle="#24303a";ctx.fillRect(0,405,960,135);ctx.fillStyle="#394752";for(var i=0;i<9;i++)ctx.fillRect(i*120,250+(i%2)*30,86,155);var key=t<1.2?"sh_reentry":t<2.35?"sh_crash":"sh_wreck";var cx=t<2.35?760-t*225:300,cy=t<2.35?100+t*145:390;if(t>1.2&&t<2.4){ctx.fillStyle="rgba(255,120,40,.28)";ctx.beginPath();ctx.arc(cx,cy,130,0,Math.PI*2);ctx.fill();}ship(key,cx,cy,t<2.35?220:260);ctx.fillStyle="#fff";ctx.font="700 14px monospace";ctx.fillText(t<2.35?"WARNING · GUIDANCE LOST":"IMPACT CONFIRMED · MOVE",30,45);root.__goodBoysCrashScene={active:t<3.3,frame:key,at:Date.now()};if(t>=3.3){cancelAnimationFrame(raf);root.__goodBoysCrashScene={active:false,completed:true,frame:"sh_wreck",at:Date.now()};phase("crash-complete");remove("good-boys-crash-v4");resolve({completed:true});return;}raf=requestAnimationFrame(loop);}root.document.body.appendChild(host);raf=requestAnimationFrame(loop);
  });}
  root.TechOpsGoodBoysOpeningV4={VERSION:VERSION,showDeckInteraction:showDeckInteraction,showSpaceFlight:showSpaceFlight,showCrashScene:showCrashScene};
})(typeof globalThis!=="undefined"?globalThis:this);
