/* Good Boys campaign director v3 — presentation authority.
 * Owns one mobile action pad, the premise cinematic, combo presentation and
 * the visible secret ship. Campaign progression/world identity live in the
 * dedicated bible/progression authorities so this file cannot race them.
 */
(function(root){
  "use strict";
  if(!root)return;
  try{var old=root.TechOpsGoodBoysCampaignDirector;if(old&&old.timer&&root.clearInterval)root.clearInterval(old.timer);if(old&&old.observer)old.observer.disconnect();}catch(_){}
  var VERSION=3,style=null,pad=null,observer=null,introRunning=false,transitionRunning=false,shipImg=null;
  var combo={step:0,last:0};
  function cs(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function active(){return !!cs();}
  function mission(){var c=cs();try{return Math.max(1,Math.min(8,Number(c&&c.m||root.S&&root.S.meta&&root.S.meta._v736&&root.S.meta._v736.m||1)));}catch(e){return 1;}}
  function now(){return root.performance&&root.performance.now?root.performance.now():Date.now();}
  function setMsg(t,ms){try{if(root.NM){root.NM.msg=t;root.NM.msgT=now()+(ms||1200);}}catch(e){}}
  function installStyle(){
    if(!root.document)return;
    style=root.document.getElementById("good-boys-director-style");
    if(!style){style=root.document.createElement("style");style.id="good-boys-director-style";(root.document.head||root.document.documentElement).appendChild(style);}
    style.textContent=[
      "body.good-boys-directed #good-dogs-touch,body.good-boys-directed #good-boys-loop-controls,body.good-boys-directed #touch-buttons{display:none!important;visibility:hidden!important;pointer-events:none!important}",
      "body.good-boys-cinematic #good-dogs-touch,body.good-boys-cinematic #good-boys-loop-controls,body.good-boys-cinematic #touch-buttons,body.good-boys-cinematic #good-boys-director-controls{display:none!important;visibility:hidden!important;pointer-events:none!important}",
      "#good-boys-director-controls{position:fixed;right:max(10px,calc(env(safe-area-inset-right) + 10px));bottom:max(106px,calc(env(safe-area-inset-bottom) + 106px));z-index:11050;display:none;grid-template-columns:repeat(2,70px);gap:8px;pointer-events:auto}",
      "body.good-boys-directed #good-boys-director-controls{display:grid}",
      "body.good-boys-directed.good-boys-cinematic #good-boys-director-controls{display:none!important}",
      "#good-boys-director-controls button{box-sizing:border-box;width:70px;height:52px;margin:0;padding:4px;border-radius:12px;background:#06101deb;color:#eef9ff;font:700 8px/1.15 monospace;touch-action:manipulation;box-shadow:0 0 14px #0008}",
      "#gbd-swap,#gbd-boost,#gbd-air{border:2px solid #38bdf8}#gbd-sync,#gbd-throw{border:2px solid #f59e0b}#gbd-attack{border:2px solid #22c55e}",
      "#good-boys-story-cine{position:fixed;inset:0;z-index:120000;background:#02050b center/cover no-repeat;display:flex;align-items:flex-end;justify-content:center;padding:18px max(14px,env(safe-area-inset-right)) max(22px,env(safe-area-inset-bottom));font-family:monospace;color:#eef8ff;overflow:hidden}",
      "#good-boys-story-cine:before,#good-boys-story-cine:after{content:'';position:absolute;left:0;right:0;height:7vh;background:#000;z-index:1}#good-boys-story-cine:before{top:0}#good-boys-story-cine:after{bottom:0}",
      "#good-boys-story-cine .gb-card{position:relative;z-index:2;width:min(720px,94vw);margin-bottom:5vh;background:rgba(2,7,13,.93);border:2px solid #38bdf8;border-radius:14px;padding:18px;box-shadow:0 0 38px #000b}",
      "#good-boys-story-cine .gb-kicker{color:#ffd166;font:700 11px monospace;letter-spacing:.08em}#good-boys-story-cine h2{margin:8px 0 10px;font:700 21px/1.15 monospace;color:#fff}#good-boys-story-cine p{margin:0 0 10px;font:13px/1.55 monospace;color:#d9edf7}#good-boys-story-cine .gb-goal{margin:0 0 14px;padding:8px 10px;border-left:3px solid #38bdf8;background:#07131ddd;color:#bfeaff;font:700 10px/1.45 monospace}#good-boys-story-cine button{width:100%;min-height:52px;border:2px solid #38bdf8;border-radius:10px;background:#071624;color:#eef8ff;font:700 12px monospace}",
      "@media(max-width:390px){#good-boys-director-controls{right:max(7px,calc(env(safe-area-inset-right) + 7px));bottom:max(100px,calc(env(safe-area-inset-bottom) + 100px));grid-template-columns:repeat(2,64px);gap:7px}#good-boys-director-controls button{width:64px;height:50px;font-size:7px}}"
    ].join("");
  }
  function elementVisible(id){try{var el=root.document&&root.document.getElementById(id);if(!el)return false;if(el.classList&&el.classList.contains("hidden"))return false;var s=root.getComputedStyle?root.getComputedStyle(el):el.style;return !s||s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity||1)!==0;}catch(e){return false;}}
  function cinematicVisible(){try{return elementVisible("good-boys-story-cine")||elementVisible("gb-prison-cine")||elementVisible("good-boys-campaign-intro")||elementVisible("good-boys-earthfall-cine")||elementVisible("dialogue")||elementVisible("v725-cine");}catch(e){return false;}}
  function killCompetingPads(){if(!root.document)return;["good-dogs-touch","good-boys-loop-controls"].forEach(function(id){var xs=root.document.querySelectorAll("#"+id);for(var i=0;i<xs.length;i++){var el=xs[i];el.style.setProperty("display","none","important");el.style.setProperty("visibility","hidden","important");el.style.setProperty("pointer-events","none","important");el.inert=true;el.setAttribute("aria-hidden","true");}});var touch=root.document.getElementById("touch-buttons");if(touch){touch.style.setProperty("display","none","important");touch.inert=true;}}
  function mk(id,label,fn){var b=root.document.createElement("button");b.id=id;b.type="button";b.textContent=label;b.addEventListener("pointerdown",function(e){e.preventDefault();e.stopPropagation();if(!cinematicVisible())fn();},{passive:false});return b;}
  function nearestEnemy(range){try{var n=root.NM;if(!n||!n.enemies)return null,b=null,bd=1e9;for(var i=0;i<n.enemies.length;i++){var e=n.enemies[i];if(!e||e.alive===false||Number(e.hp)<=0||e.down>0)continue;var d=Math.abs((e.x||0)-(n.x||0));if(d<bd&&d<=(range||150)){bd=d;b=e;}}return b;}catch(e){return null;}}
  function rawAttack(){try{if(typeof root.nmJab==="function")return root.nmJab();if(typeof root.interact==="function")return root.interact();if(root.KeyboardEvent)root.dispatchEvent(new root.KeyboardEvent("keydown",{key:"e",bubbles:true,cancelable:true}));}catch(e){}}
  function duoAttack(){var t=now();if(t-combo.last>900)combo.step=0;combo.last=t;combo.step=(combo.step%3)+1;rawAttack();try{var c=cs(),n=root.NM,p=c&&c.partner;if(c)c.sync=Math.min(100,(Number(c.sync)||0)+(combo.step===3?8:3));if(p){p.anim=combo.step===3?18:10;p.face=n.face||1;}}catch(e){}var target=nearestEnemy(128);if(target&&combo.step>=2){var bonus=combo.step===3?9:4;target.hp=(Number(target.hp)||1)-bonus;target.hitT=Math.max(Number(target.hitT)||0,6);target.kb=(root.NM.face||1)*(combo.step===3?6:3);if(target.hp<=0)target.alive=false;}setMsg(combo.step===1?"KATRIN → setup":combo.step===2?"MANCHEZ → follow-up":"TANDEM LAUNCHER");try{if(typeof root.nmCheckClear==="function")root.nmCheckClear();}catch(e){}}
  function reliableThrow(){try{var c=cs(),n=root.NM,p=c&&c.partner,m=root.TechOpsGoodBoysReferenceMechanics;if(!c||!n||!p)return false;var d=Math.hypot((p.x||0)-(n.x||0),(p.y||0)-(n.y||0));if(d>125){p.x=n.x-(n.face||1)*42;p.y=n.y+4;p.vx=0;p.vy=0;p.onGround=!!n.onGround;}var ok=m&&m.throwOrCatch?m.throwOrCatch():false;if(!ok){p.vx=(n.face||1)*9;p.vy=-9.5;p.onGround=false;p.anim=18;ok=true;}var e=nearestEnemy(175);if(e){e.hp=(Number(e.hp)||1)-7;e.hitT=8;e.kb=(n.face||1)*5;if(e.hp<=0)e.alive=false;c.sync=Math.min(100,(Number(c.sync)||0)+8);combo.step=2;combo.last=now();setMsg("THROW → ATTACK to finish");}else setMsg("PARTNER THROW");return ok;}catch(e){return false;}}
  function ensurePad(){if(!root.document||!root.document.body)return;var pads=root.document.querySelectorAll("#good-boys-director-controls");for(var i=1;i<pads.length;i++)pads[i].remove();pad=pads[0]||null;if(!pad){pad=root.document.createElement("div");pad.id="good-boys-director-controls";pad.appendChild(mk("gbd-swap","⇄ SWAP",function(){if(root.v736&&root.v736.swap)root.v736.swap();}));pad.appendChild(mk("gbd-sync","SYNC",function(){if(root.v736&&root.v736.finisher)root.v736.finisher();}));pad.appendChild(mk("gbd-attack","ATTACK",duoAttack));pad.appendChild(mk("gbd-boost","⬆ BOOST",function(){var m=root.TechOpsGoodBoysReferenceMechanics;if(m&&m.boostJump)m.boostJump();}));pad.appendChild(mk("gbd-air","AIR x2",function(){var m=root.TechOpsGoodBoysReferenceMechanics;if(m&&m.airDash)m.airDash();}));pad.appendChild(mk("gbd-throw","↗ THROW",reliableThrow));root.document.body.appendChild(pad);}}
  function fallbackDefinitions(){try{var g=root.TechOpsGoodBoysGameplayLoop;if(!g)return;var defs={1:{id:"waldo_property",label:"WALDO'S HOUSE",objective:"Search the property. Follow the trail through the garage.",accent:"#ffd166",hazard:"none",bg:"goodboys_home"},2:{id:"hidden_bay",label:"THE HIDDEN BAY",objective:"Clear the hangar. Reach the secret ship and board.",accent:"#55dfff",hazard:"security",bg:"goodboys_hangar"},3:{id:"breach",label:"ORBITAL PRISON — BREACH",objective:"Survive impact. Reach Cell Block 118.",accent:"#ff8a4c",hazard:"debris",bg:"goodboys_breach"},4:{id:"cell118",label:"CELL 118",objective:"Verify K. Break the lock. Free him.",accent:"#55dfff",hazard:"security",bg:"goodboys_cell118"},5:{id:"core",label:"ACCESS CORE",objective:"Escort K. Open the route to 1984.",accent:"#22c55e",hazard:"security",bg:"goodboys_core"},6:{id:"cell1984",label:"CELL 1984",objective:"Break lockdown. Free Waldo.",accent:"#ef4444",hazard:"lockdown",bg:"goodboys_cell1984"},7:{id:"escape",label:"ESCAPE VELOCITY",objective:"Break the Warden. Reach the maintenance shuttle.",accent:"#f59e0b",hazard:"warden",bg:"goodboys_escape"},8:{id:"earthfall",label:"EARTHFALL",objective:"Get everyone home.",accent:"#ffd18b",hazard:"none",bg:"goodboys_earthfall"}};Object.keys(defs).forEach(function(k){g.PHASES[k]=defs[k];});}catch(e){root.__goodBoysDirectorMissionError=String(e&&e.stack||e);}}
  function syncMissionDefinitions(){try{var w=root.TechOpsGoodBoysBibleWorld;if(w&&w.syncDefinitions)return w.syncDefinitions();fallbackDefinitions();return true;}catch(e){root.__goodBoysDirectorMissionError=String(e&&e.stack||e);return false;}}
  function shuttleAtlas(){try{return root.SHUTTLE&&root.SHUTTLE.src&&root.SHUTTLE.frames?root.SHUTTLE:null;}catch(e){return null;}}
  function shuttleImage(){try{var A=shuttleAtlas();if(!A)return null;if(!shipImg||shipImg.src!==A.src){shipImg=new root.Image();shipImg.src=A.src;}return shipImg.complete&&shipImg.naturalWidth?shipImg:null;}catch(e){return null;}}
  function drawShip(x){try{var n=root.NM,A=shuttleAtlas(),im=shuttleImage();if(!n||mission()!==2||!n._gbShipRevealed||!A||!im)return;var fr=A.frames.sh_land||A.frames.sh_side0;if(!fr)return;var worldX=1390,screenX=worldX-(Number(n.cam)||0),base=(typeof root.NM_FLOOR==="number"?root.NM_FLOOR:430)-6,w=190,h=w*(fr[3]/fr[2]);if(screenX<-220||screenX>x.canvas.width+220)return;x.save();x.imageSmoothingEnabled=false;x.globalAlpha=.28;x.fillStyle="#38bdf8";x.beginPath();x.ellipse(screenX,base+5,92,12,0,0,Math.PI*2);x.fill();x.globalAlpha=1;x.drawImage(im,fr[0],fr[1],fr[2],fr[3],screenX-w/2,base-h,w,h);x.strokeStyle="#69d6ff";x.lineWidth=2;x.strokeRect(screenX-72,base-h-36,144,25);x.fillStyle="rgba(2,8,14,.9)";x.fillRect(screenX-71,base-h-35,142,23);x.fillStyle="#dff8ff";x.font="bold 9px monospace";x.textAlign="center";x.fillText("SECRET SHIP · BOARD",screenX,base-h-19);x.restore();}catch(e){root.__goodBoysShipDrawError=String(e&&e.stack||e);}}
  function installShipDraw(){try{var g=root.TechOpsGoodBoysGameplayLoop;if(!g||g.__directorShipDrawInstalled||typeof g.drawStageAccents!=="function")return false;var base=g.drawStageAccents;g.drawStageAccents=function(ctx){var r=base&&base.apply(this,arguments);drawShip(ctx);return r;};g.__directorShipDrawInstalled=true;return true;}catch(e){return false;}}
  function calmFrames(){try{var A=root.KATRIN_MANCHEZ;if(!A||!A.frames)return;var ks=A.frames.kat_stand||A.frames.kat_idle0,ms=A.frames.man_idle0;if(ks){A.frames.kat_idle0=ks;A.frames.kat_idle1=ks;}if(ms)A.frames.man_idle1=ms;}catch(e){}}
  function backgroundSrc(key){try{var plateMap={goodboys_home:"waldo_house",goodboys_hangar:"hidden_bay",goodboys_approach:"orbital_approach",goodboys_earthfall:"earthfall"};var p=root.GOOD_BOYS_CUTSCENE_PLATES,pk=plateMap[key]||key;if(p&&p[pk])return p[pk];var im=root.NM_BG734&&root.NM_BG734[key];if(im&&im.src)return im.src;var map=root.GOOD_BOYS_CAMPAIGN_BACKGROUND_SOURCE,srcKey=map&&map[key],fb=srcKey&&root.NM_BG734&&root.NM_BG734[srcKey];return fb&&fb.src||"";}catch(e){return "";}}
  function showCinematic(scenes,done){if(transitionRunning||!root.document){if(done)done();return;}transitionRunning=true;var i=0,o=root.document.createElement("div");o.id="good-boys-story-cine";root.document.body.appendChild(o);try{if(root.S)root.S.inDialog=true;if(root.document.body)root.document.body.classList.add("good-boys-cinematic");}catch(e){}function render(){var s=scenes[i],src=backgroundSrc(s.k);o.style.backgroundImage=(src?'linear-gradient(to bottom,rgba(1,4,8,.08),rgba(1,4,8,.42) 45%,rgba(1,4,8,.96)),url("'+String(src).replace(/"/g,"%22")+'")':'linear-gradient(#07101b,#02050b)');o.innerHTML='<div class="gb-card"><div class="gb-kicker">GOOD BOYS PROTOCOL · '+(i+1)+' / '+scenes.length+'</div><h2>'+s.t+'</h2><p>'+s.p+'</p>'+(s.g?'<div class="gb-goal">'+s.g+'</div>':'')+'<button id="gb-cine-next">'+(s.cta||(i===scenes.length-1?'TAKE CONTROL':'CONTINUE'))+'</button></div>';o.querySelector("#gb-cine-next").addEventListener("pointerdown",next,{passive:false});}function next(e){if(e){e.preventDefault();e.stopPropagation();}i++;if(i<scenes.length){render();return;}try{o.remove();}catch(_){}try{if(root.S)root.S.inDialog=false;if(root.document.body)root.document.body.classList.remove("good-boys-cinematic");}catch(_){}transitionRunning=false;if(done)done();}render();}
  function showOpening(done){if(introRunning){if(done)done();return;}introRunning=true;showCinematic([
    {k:"goodboys_home",t:"WALDO'S PLACE",p:"The porch lights are on. The grill is cold. The dish is tracking something overhead — but Waldo is gone. Katrin and Manchez pick up his trail in the yard.",g:"SEARCH THE PROPERTY · FOLLOW WALDO'S TRAIL"},
    {k:"goodboys_home",t:"THE GARAGE WALL",p:"The trail crosses the porch and dies inside Waldo's garage. Fresh scrape marks trace a tool wall that should not move.",g:"YARD → PORCH → GARAGE → FALSE WALL"},
    {k:"goodboys_hangar",t:"THE HIDDEN BAY",p:"Behind the wall is a concealed launch bay and an unregistered ship. Waldo did not leave by car. He left Earth.",g:"CLEAR THE BAY · BOARD THE SECRET SHIP"},
    {k:"goodboys_approach",t:"118 / 1984",p:"The stolen nav cache points at Blacksite Meridian, an orbital detention complex. Cell 118 is filed under Mike's identity. Cell 1984 is Waldo. The prison will not grant docking clearance.",g:"FIND 118 FIRST · THEN REACH WALDO IN 1984",cta:"FOLLOW THE TRAIL"}
  ],function(){introRunning=false;if(done)done();});}
  function installStartCinematic(){try{if(!root.document||root.document.__goodBoysDirectorStartCapture)return;root.document.addEventListener("click",function(e){var t=e.target&&e.target.closest?e.target.closest("#btn-v736"):null;if(!t||t.dataset.gbdBypass==="1")return;e.preventDefault();e.stopImmediatePropagation();showOpening(function(){try{if(root.v725&&typeof root.v725.play==="function"&&!root.v725.play.__gbdSkipM1){var bp=root.v725.play;root.v725.play=function(id,cb){if(id==="b736m1"&&root.__gbdSkipBuiltinM1){root.__gbdSkipBuiltinM1=false;if(cb)cb();return true;}return bp.apply(this,arguments);};root.v725.play.__gbdSkipM1=true;}root.__gbdSkipBuiltinM1=true;if(root.v736&&root.v736.start)root.v736.start();}catch(err){root.__goodBoysDirectorStartError=String(err&&err.stack||err);}});},true);root.document.__goodBoysDirectorStartCapture=true;}catch(e){root.__goodBoysDirectorStartError=String(e&&e.stack||e);}}
  function progressionWatch(){try{var p=root.TechOpsGoodBoysProgressionAuthority;if(p&&p.tick)return p.tick();return false;}catch(e){return false;}}
  function installObserver(){try{if(observer||!root.MutationObserver||!root.document)return;observer=new root.MutationObserver(function(){if(active()){killCompetingPads();ensurePad();}});observer.observe(root.document.documentElement,{subtree:true,childList:true});}catch(e){}}
  function tick(){try{installStyle();installStartCinematic();syncMissionDefinitions();installShipDraw();calmFrames();installObserver();var on=active();if(root.document&&root.document.body){root.document.body.classList.toggle("good-boys-directed",on);root.document.body.classList.toggle("good-boys-cinematic",on&&cinematicVisible());}if(!on)return;killCompetingPads();ensurePad();}catch(e){root.__goodBoysDirectorError=String(e&&e.stack||e);}}
  tick();var timer=root.setInterval?root.setInterval(tick,150):null;
  root.TechOpsGoodBoysCampaignDirector={VERSION:VERSION,tick:tick,showOpening:showOpening,showCinematic:showCinematic,duoAttack:duoAttack,reliableThrow:reliableThrow,syncMissionDefinitions:syncMissionDefinitions,drawShip:drawShip,progressionWatch:progressionWatch,observer:observer,timer:timer};
})(typeof globalThis!=="undefined"?globalThis:this);
