/* Good Boys canon runtime — production authority v5.
 * World law: shared Night engine, independent Good Boys campaign world.
 * Route: Waldo's house -> hidden ship -> prison impact -> 118 -> 1984 -> escape -> Earth.
 */
(function(root){
  "use strict";
  if(!root||root.TechOpsGoodBoysCanon)return;
  var VERSION=5,chain=false,baseLoad=null,basePlay=null,baseDraw=null,baseToast=null;
  var SEQ={
    1:{name:"WALDO'S HOUSE",objective:"FIND WALDO'S TRAIL · REACH THE HIDDEN BAY",zone:"WALDO'S HOUSE — EARTH",bg:"goodboys_home",district:"goodboys_home",light:"home_gold"},
    2:{name:"THE HIDDEN BAY",objective:"POWER THE SECRET SHIP · CLEAR THE HANGAR · LAUNCH",zone:"WALDO'S SECRET HANGAR",bg:"goodboys_hangar",district:"goodboys_hangar",light:"launch_blue"},
    3:{name:"MAKE A DOOR",objective:"SURVIVE IMPACT · CROSS THE BREACH · ENTER DETENTION",zone:"ORBITAL DETENTION — HULL BREACH",bg:"goodboys_breach",district:"goodboys_breach",light:"impact_orange"},
    4:{name:"CELL 118",objective:"INVESTIGATE THE PRISONER · VERIFY · FREE K",zone:"DETENTION BLOCK 118",bg:"goodboys_cell118",district:"goodboys_cell118",light:"cell118_blue"},
    5:{name:"ACCESS CORE",objective:"DEFEND K · BREAK ORPHEUS ROUTING · OPEN 1984",zone:"ORPHEUS ACCESS CORE",bg:"orbital_eye",district:"orbital",light:"hack_green"},
    6:{name:"CELL 1984",objective:"FREE WALDO · HOLD BOTH SIDES · BREAK LOCKDOWN",zone:"SURVEILLANCE BLOCK 1984",bg:"goodboys_cell1984",district:"goodboys_cell1984",light:"emergency_red"},
    7:{name:"ESCAPE VELOCITY",objective:"BREAK THE WARDEN · STEAL THE MAINTENANCE SHUTTLE",zone:"COLLAPSING SHUTTLE BAY",bg:"goodboys_escape",district:"goodboys_escape",light:"escape_purple"},
    8:{name:"EARTHFALL",objective:"GET K · WALDO · KATRIN · MANCHEZ HOME",zone:"WALDO'S HOUSE — DAWN",bg:"goodboys_earthfall",district:"goodboys_earthfall",light:"earthfall_gold"}
  };
  var INTRO={
    b736m1:{title:"WALDO'S HOUSE",body:"Waldo is gone. Katrin and Manchez pick up his trail inside the house and follow it through the garage to a concealed launch bay.",hint:"MOVE AS A PAIR · SWAP · BOOST JUMP ×3 · AIR DASH ×2",asset:"goodboys_home",cta:"FOLLOW THE TRAIL"},
    b736m2:{title:"THE SECRET SHIP",body:"The hidden bay opens around an unregistered spacecraft. Restore the launch systems, clear the hangar, and get it airborne.",hint:"POWER COUPLERS · PARTNER THROW/CATCH · CLEAR THE BAY",asset:"goodboys_hangar",cta:"BOARD THE SHIP"},
    b736m3:{title:"NO DOCKING",body:"The orbital prison rejects the stolen ship and lights up its defense grid. The dogs choose the shortest route inside: full-speed impact.",hint:"PRISON APPROACH · DEFENSE FIRE · IMPACT VECTOR",asset:"goodboys_approach",cta:"MAKE A DOOR"}
  };
  function cs(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function meta(){try{return root.S&&root.S.meta&&root.S.meta._v736?root.S.meta._v736:null;}catch(e){return null;}}
  function mission(){var c=cs(),m=c&&c.m||meta()&&meta().m||1;return Math.max(1,Math.min(8,Number(m)||1));}
  function active(){return !!cs();}
  function latch(){chain=true;root.__TECHOPS_GOOD_BOYS_CANON_CHAIN=true;}
  function isChain(){return !!(chain||root.__TECHOPS_GOOD_BOYS_CANON_CHAIN||active());}
  function canonical(){return SEQ[mission()]||SEQ[1];}
  function assetSrc(key){try{return root.GOOD_BOYS_CAMPAIGN_ASSETS&&root.GOOD_BOYS_CAMPAIGN_ASSETS[key]||"";}catch(e){return "";}}
  function ensureAssets(){try{if(root.TechOpsGoodBoysCampaignAssets){root.TechOpsGoodBoysCampaignAssets.installDistricts();return true;}if(!root.document||root.document.getElementById("good-boys-campaign-assets-loader"))return false;var s=root.document.createElement("script");s.id="good-boys-campaign-assets-loader";s.src="good_boys_campaign_assets.js";(root.document.head||root.document.documentElement).appendChild(s);return true;}catch(e){return false;}}
  function cleanTitle(){
    try{if(!root.document)return false;var ts=root.document.getElementById("title-screen");if(!ts)return false;var all=ts.querySelectorAll("button,a,div,span,p");for(var i=0;i<all.length;i++){var el=all[i],t=(el.textContent||"").replace(/\s+/g," ").trim().toLowerCase();if(t.indexOf("play as mike instead")>=0){el.style.setProperty("display","none","important");el.setAttribute("aria-hidden","true");}}return true;}catch(e){return false;}
  }
  function suppressLegacyPresentation(){
    try{if(!isChain()||!root.document)return false;var toast=root.document.getElementById("toast");if(toast){var t=(toast.textContent||"").toUpperCase();if(t.indexOf("NIGHT CRAWL")>=0||t.indexOf("NEW HAVEN STREETS")>=0){toast.classList.add("hidden");toast.textContent="";}}var body=root.document.body;if(body)body.classList.add("good-boys-canon");return true;}catch(e){return false;}
  }
  function installToastAuthority(){
    try{if(typeof root.toast!=="function"||root.toast.__goodBoysCanon)return false;baseToast=root.toast;root.toast=function(msg){var t=String(msg||"").toUpperCase();if(isChain()&&(t.indexOf("NIGHT CRAWL")>=0||t.indexOf("NEW HAVEN STREETS")>=0))return;return baseToast.apply(this,arguments);};root.toast.__goodBoysCanon=true;return true;}catch(e){return false;}
  }
  function installStartAuthority(){try{if(!root.v736||typeof root.v736.start!=="function"||root.v736.start.__goodBoysCanon)return false;var start=root.v736.start;root.v736.start=function(){latch();ensureAssets();return start.apply(this,arguments);};root.v736.start.__goodBoysCanon=true;return true;}catch(e){return false;}}
  function installDistrictAuthority(){
    try{if(typeof root.nmLoadDistrict!=="function"||root.nmLoadDistrict.__goodBoysCanon)return false;baseLoad=root.nmLoadDistrict;root.nmLoadDistrict=function(id){var requested=id,cfg=canonical();if(isChain())id=cfg.district||"orbital";var r=baseLoad.call(this,id);try{if(isChain()&&root.NM){root.NM.district=id;root.NM._goodBoysRequestedDistrict=requested;root.NM._goodBoysCanonDistrict=id;}}catch(_){}return r;};root.nmLoadDistrict.__goodBoysCanon=true;return true;}catch(e){return false;}
  }
  function closeLegacyDialog(){try{if(root.S)root.S.inDialog=false;var d=root.document&&root.document.getElementById("dialogue");if(d)d.classList.add("hidden");}catch(e){}}
  function prepareNightRuntime(cb){
    var tries=0,maxTries=100;ensureAssets();
    function ready(){closeLegacyDialog();suppressLegacyPresentation();if(root.NM){try{var cfg=canonical();if(typeof root.nmLoadDistrict==="function")root.nmLoadDistrict(cfg.district);enforceBackground();if(cb)cb();}catch(e){root.__goodBoysHandoffError=String(e&&e.stack||e);}return;}if(++tries>=maxTries){root.__goodBoysCoreBroken="night_runtime_timeout";return;}try{(root.setTimeout||setTimeout)(ready,25);}catch(e){root.__goodBoysCoreBroken="night_runtime_timer_failed";}}
    try{if(!root.NM&&typeof root.enterNight==="function")root.enterNight();try{if(root.v722&&typeof root.v722.active==="function"&&root.v722.active()&&typeof root.v722.skip==="function")root.v722.skip();}catch(_){} }catch(e){root.__goodBoysHandoffError=String(e&&e.stack||e);}ready();
  }
  function showCampaignIntro(id,cb){
    var spec=INTRO[id];if(!spec)return false;
    try{if(!root.document){prepareNightRuntime(cb);return true;}var old=root.document.getElementById("good-boys-campaign-intro");if(old)old.remove();closeLegacyDialog();var o=root.document.createElement("div");o.id="good-boys-campaign-intro";var src=assetSrc(spec.asset);o.style.cssText="position:fixed;inset:0;z-index:100000;background:#02050a center/cover no-repeat;display:flex;align-items:flex-end;justify-content:center;padding:max(18px,env(safe-area-inset-bottom)) 14px;color:#eef8ff;font-family:monospace";if(src)o.style.backgroundImage='linear-gradient(to bottom,rgba(1,4,8,.06),rgba(1,4,8,.32) 45%,rgba(1,4,8,.94)),url("'+src.replace(/"/g,"%22")+'")';o.innerHTML='<div style="width:min(720px,96vw);margin-bottom:3vh;background:#050914ee;border:2px solid #55dfff;border-radius:14px;padding:18px;box-shadow:0 0 34px #0ea5e944"><div style="color:#ffd166;font:700 24px monospace;line-height:1.05">GOOD BOYS PROTOCOL — '+spec.title+'</div><p style="font-size:16px;line-height:1.55;margin:14px 0">'+spec.body+'</p><div style="color:#9fdcf0;font-size:13px;line-height:1.45">'+spec.hint+'</div><button id="good-boys-begin" style="width:100%;min-height:54px;margin-top:18px;border:2px solid #55dfff;border-radius:10px;background:#0a1726;color:#e9f8ff;font:700 15px monospace">'+spec.cta+'</button></div>';root.document.body.appendChild(o);var done=false,go=function(ev){if(ev){ev.preventDefault();ev.stopPropagation();}if(done)return;done=true;try{o.remove();}catch(_){}closeLegacyDialog();prepareNightRuntime(cb);};var b=root.document.getElementById("good-boys-begin");if(b){b.addEventListener("pointerdown",go,{once:true});b.addEventListener("click",go,{once:true});}return true;}catch(e){root.__goodBoysIntroError=String(e&&e.stack||e);prepareNightRuntime(cb);return false;}
  }
  function installOpeningAuthority(){try{if(!root.v725||typeof root.v725.play!=="function"||root.v725.play.__goodBoysCanon)return false;basePlay=root.v725.play;root.v725.play=function(id,cb){if(!INTRO[id])return basePlay.apply(this,arguments);latch();ensureAssets();return showCampaignIntro(id,cb);};root.v725.play.__goodBoysCanon=true;return true;}catch(e){return false;}}
  function hideLegacyUi(){try{if(!root.document)return false;var on=isChain(),ids=["hud","quest-tracker","chaos-banner","btn-twin","btn-sweep","btn-music"];ids.forEach(function(id){var el=root.document.getElementById(id);if(!el)return;if(on){if(el.dataset.gbCanonDisplay===undefined)el.dataset.gbCanonDisplay=el.style.display||"";el.style.setProperty("display","none","important");}else if(el.dataset.gbCanonDisplay!==undefined){el.style.display=el.dataset.gbCanonDisplay;delete el.dataset.gbCanonDisplay;}});if(root.document.body)root.document.body.classList.toggle("good-boys-canon",on);return true;}catch(e){return false;}}
  function enforceBackground(){try{if(!active()||!root.NM_BG734)return false;var cfg=canonical(),im=root.NM_BG734[cfg.bg];if(!im)return false;root.NM_BG734[root.NM.district]=im;root.NM_BG734.orbital=im;return true;}catch(e){return false;}}
  function drawHud(x){try{var c=cs();if(!c)return;var W=x.canvas.width,cfg=canonical(),compact=W<760;x.save();var stripY=compact?76:68,stripH=compact?38:34,edge=Math.max(6,W*.12);x.fillStyle="rgba(1,5,9,.88)";x.fillRect(edge,stripY,W-edge*2,stripH);x.strokeStyle=cfg.light==="emergency_red"?"#ef4455":cfg.light==="hack_green"?"#22c55e":cfg.light==="impact_orange"?"#ff8a4c":cfg.light==="earthfall_gold"?"#ffd166":"#38bdf8";x.lineWidth=1;x.strokeRect(edge+.5,stripY+.5,W-edge*2-1,stripH-1);x.textAlign="center";x.fillStyle="#f2f7fb";x.font="bold "+(compact?8:10)+"px monospace";x.fillText(cfg.name+" · "+cfg.objective,W/2,stripY+14);x.fillStyle="#9fdcf0";x.font="bold 7px monospace";x.fillText(cfg.zone+" · SYNC "+Math.round(c.sync||0)+"%",W/2,stripY+28);x.restore();}catch(e){}}
  function installHudAuthority(){try{if(typeof root.drawNM!=="function"||root.drawNM.__goodBoysCanon)return false;baseDraw=root.drawNM;root.drawNM=function(){var r=baseDraw.apply(this,arguments);try{if(active()&&root.ctx)drawHud(root.ctx);}catch(_){}return r;};root.drawNM.__goodBoysCanon=true;return true;}catch(e){return false;}}
  function healthCheck(){try{if(!active())return true;var c=cs(),cfg=canonical();if(!root.NM||!c.chars||!c.chars.katrin||!c.chars.manchez){root.__goodBoysCoreBroken="missing_pair_state";return false;}if(root.NM.district!==cfg.district){try{root.nmLoadDistrict(cfg.district);}catch(_){}}if(!isFinite(root.NM.x)||!isFinite(root.NM.y)){root.__goodBoysCoreBroken="invalid_player_position";return false;}root.__goodBoysCoreBroken=null;return true;}catch(e){root.__goodBoysCoreBroken=String(e);return false;}}
  function syncIdentity(){try{if(!active())return false;var c=cs(),cfg=canonical();c.canonName=cfg.name;c.canonObjective=cfg.objective;c.canonZone=cfg.zone;c.canonLight=cfg.light;c.canonBackground=cfg.bg;c.canonDistrict=cfg.district;root.NM._goodBoysCanon=true;root.NM._goodBoysMission=mission();root.NM._goodBoysWorld="waldo-house-to-orbital-prison";return true;}catch(e){return false;}}
  function tick(){ensureAssets();cleanTitle();installStartAuthority();installDistrictAuthority();installOpeningAuthority();installHudAuthority();installToastAuthority();hideLegacyUi();suppressLegacyPresentation();syncIdentity();enforceBackground();healthCheck();}
  tick();var timer=null;try{timer=root.setInterval(tick,120);}catch(e){}
  root.TechOpsGoodBoysCanon={VERSION:VERSION,SEQUENCE:SEQ,INTRO:INTRO,mission:mission,canonical:canonical,latch:latch,isChain:isChain,ensureAssets:ensureAssets,cleanTitle:cleanTitle,suppressLegacyPresentation:suppressLegacyPresentation,prepareNightRuntime:prepareNightRuntime,showCampaignIntro:showCampaignIntro,installStartAuthority:installStartAuthority,installDistrictAuthority:installDistrictAuthority,installOpeningAuthority:installOpeningAuthority,installHudAuthority:installHudAuthority,installToastAuthority:installToastAuthority,enforceBackground:enforceBackground,hideLegacyUi:hideLegacyUi,healthCheck:healthCheck,tick:tick,timer:timer};
})(typeof globalThis!=="undefined"?globalThis:this);
