/* Good Boys Access Core authority v5.
 * Mission 5 is K's route-control breach, not the legacy Mike Index boss fight.
 * Mission reads come only from the canonical persisted campaign authority.
 * Tick ownership is unified under TechOpsGoodBoysProgressionAuthority.
 */
(function(root){
  "use strict";
  if(!root)return;
  try{var old=root.TechOpsGoodBoysAccessCoreAuthority;if(old&&old.timer&&root.clearInterval)root.clearInterval(old.timer);}catch(_){}
  var VERSION=6,NODE_X=1070,timer=null,purges=0,seeds=0,lastPurge=0,lastState=null,resets=0,missionRepairs=0,interactionInstalled=false;
  function cs(){try{return root.NM&&root.NM._v736?root.NM._v736:null;}catch(e){return null;}}
  function meta(){try{return root.S&&root.S.meta&&root.S.meta._v736?root.S.meta._v736:null;}catch(e){return null;}}
  function mission(){try{var a=root.TechOpsGoodBoysCampaignState;if(a&&typeof a.mission==="function")return Number(a.mission())||0;var m=meta();return Number(m&&m.m)||0;}catch(e){return 0;}}
  function reconcileMission(reason){try{var a=root.TechOpsGoodBoysCampaignState;if(a&&typeof a.reconcile==="function"){var before=Number(cs()&&cs().m||0),ok=a.reconcile(reason||"access-core"),after=Number(cs()&&cs().m||0);if(ok&&before!==after)missionRepairs++;return ok;}var m=meta(),c=cs();if(!m||!c)return false;var canonical=Number(m.m)||0;if(canonical&&Number(c.m)!==canonical){var old=Number(c.m)||0;c.m=canonical;missionRepairs++;root.__goodBoysAccessCoreMissionRepair={runtime:old,canonical:canonical,reason:reason||"access-core",at:Date.now(),count:missionRepairs};}return true;}catch(e){root.__goodBoysAccessCoreMissionRepairError=String(e&&e.stack||e);return false;}}
  function syncState(){try{var canonical=mission();if(!canonical)return null;reconcileMission("sync-state");var c=cs(),n=root.NM;if(c!==lastState){lastState=c;if(n){n._gbAccessCoreSecuritySeeded=false;n._gbAccessCoreSeedAttempted=false;}resets++;}return c;}catch(e){root.__goodBoysAccessCoreStateError=String(e&&e.stack||e);return null;}}
  function legacyMike(e){try{if(!e)return false;var s=[e.kind,e.id,e.type,e.name].filter(Boolean).join(" ").toLowerCase().replace(/[\s_-]+/g,"");return s.indexOf("mikeindex")>=0||s.indexOf("technicianmike")>=0||s.indexOf("nightwalkermike")>=0;}catch(_){return false;}}
  function kind(name){try{return root.NM_KINDS&&root.NM_KINDS[name]||null;}catch(e){return null;}}
  function spawn(name,x){try{var k=kind(name);if(!k)return null;var floor=typeof root.NM_FLOOR==="number"?root.NM_FLOOR:430,h=Number(k.h)||40,hp=Math.round((Number(k.hp)||70)*1.18);return Object.assign({},k,{kind:name,name:k.name||name,x:x,y:floor-h,w:Number(k.w)||28,h:h,hp:hp,maxHp:hp,vx:0,windup:0,hitT:0,kb:0,launch:0,down:0,alive:true,cd:35,face:-1,weak:false,_counted:false,phase:1,_spawnX:x,_goodBoysAccessCore:true});}catch(e){return null;}}
  function livingNonLegacy(){try{return (root.NM&&root.NM.enemies||[]).filter(function(e){return e&&e.alive!==false&&Number(e.hp)>0&&!legacyMike(e);}).length;}catch(e){return 0;}}
  function seedSecurity(){try{var n=root.NM,c=cs();if(!n||mission()!==5||n._gbAccessCoreSecuritySeeded)return false;reconcileMission("seed-security");c=cs();if(!c)return false;var pack=[spawn("guard",650),spawn("hunter",1010),spawn("guard",1360)].filter(Boolean);if(!pack.length)return false;n.enemies=(n.enemies||[]).concat(pack);n._gbAccessCoreSecuritySeeded=true;n._gbBibleM5Reframed=true;c._adds66=true;c._goodBoysNoMikeIndex=true;seeds++;try{n.msg="ACCESS CORE — K NEEDS THE ROUTE CONTROLS · CLEAR SECURITY";n.msgT=(root.performance&&root.performance.now?root.performance.now():Date.now())+2600;}catch(_){}return true;}catch(e){root.__goodBoysAccessCoreSeedError=String(e&&e.stack||e);return false;}}
  function purge(){try{if(mission()!==5||!root.NM)return 0;reconcileMission("purge");var n=root.NM,es=n.enemies||[],removed=0;for(var i=es.length-1;i>=0;i--)if(legacyMike(es[i])){es.splice(i,1);removed++;}if(removed){purges+=removed;lastPurge=Date.now();n._gbBibleM5Reframed=true;var c=cs();if(c){c._adds66=true;c._goodBoysNoMikeIndex=true;}if(!n._gbAccessCoreSecuritySeeded&&livingNonLegacy()===0)seedSecurity();}return removed;}catch(e){root.__goodBoysAccessCorePurgeError=String(e&&e.stack||e);return 0;}}
  function nearNode(){try{return mission()===5&&root.NM&&Math.abs(Number(root.NM.x||0)-NODE_X)<=120;}catch(e){return false;}}
  function seizeAccessNode(){try{var c=cs(),n=root.NM;if(!c||!n||mission()!==5||livingNonLegacy()>0||!nearNode())return false;if(c._gbAccessNodeSeized)return true;c._gbAccessNodeSeized=true;c._gbAccessNodeSeizedAt=Date.now();n.msg="ACCESS GRID SEIZED · K OPENED THE ROUTE TO 1984";n.msgT=(root.performance&&root.performance.now?root.performance.now():Date.now())+2300;return true;}catch(e){root.__goodBoysAccessNodeError=String(e&&e.stack||e);return false;}}
  function installInteraction(){try{if(interactionInstalled||!root.document)return interactionInstalled;var key=function(e){if(mission()!==5||livingNonLegacy()>0||!nearNode())return;var k=String(e.key||"").toLowerCase();if(k!=="e"&&k!=="enter")return;e.preventDefault();e.stopImmediatePropagation();seizeAccessNode();};var pointer=function(e){var b=e.target&&e.target.closest?e.target.closest("#gb-use"):null;if(!b||mission()!==5||livingNonLegacy()>0||!nearNode())return;e.preventDefault();e.stopImmediatePropagation();seizeAccessNode();};root.document.addEventListener("keydown",key,true);root.document.addEventListener("pointerdown",pointer,true);interactionInstalled=true;return true;}catch(e){root.__goodBoysAccessNodeHookError=String(e&&e.stack||e);return false;}}
  function tick(){try{installInteraction();if(mission()!==5)return;var c=syncState();if(!c)return;var removed=purge(),n=root.NM;if(!n)return;c._adds66=true;c._goodBoysNoMikeIndex=true;n._gbBibleM5Reframed=true;if(!n._gbAccessCoreSecuritySeeded&&livingNonLegacy()===0&&(removed>0||!n._gbAccessCoreSeedAttempted)){n._gbAccessCoreSeedAttempted=true;seedSecurity();}if(n._gbAccessCoreSecuritySeeded&&livingNonLegacy()===0&&!c._gbAccessNodeSeized){n.msg=nearNode()?"ACCESS NODE IN RANGE · USE / E":"SECURITY CLEAR · ESCORT K TO THE ACCESS NODE";n.msgT=(root.performance&&root.performance.now?root.performance.now():Date.now())+700;}}catch(e){root.__goodBoysAccessCoreError=String(e&&e.stack||e);}}
  function acceptance(){var count=0,m=mission(),c=cs(),pm=meta();try{count=(root.NM&&root.NM.enemies||[]).filter(legacyMike).length;}catch(_){}return{version:VERSION,mission:m,runtimeMission:Number(c&&c.m||0),metaMission:Number(pm&&pm.m||0),missionDiverged:!!(c&&pm&&Number(c.m)!==Number(pm.m)),missionRepairs:missionRepairs,legacyMikeCount:count,purges:purges,seeds:seeds,resets:resets,lastPurge:lastPurge,securitySeeded:!!(root.NM&&root.NM._gbAccessCoreSecuritySeeded),nearNode:nearNode(),accessNodeSeized:!!(c&&c._gbAccessNodeSeized),interactionInstalled:interactionInstalled,canonicalOnly:true,unifiedTick:true,retryStateBound:cs()===lastState,pass:m!==5||count===0};}
  root.TechOpsGoodBoysAccessCoreAuthority={VERSION:VERSION,NODE_X:NODE_X,tick:tick,purge:purge,seedSecurity:seedSecurity,seizeAccessNode:seizeAccessNode,nearNode:nearNode,installInteraction:installInteraction,syncState:syncState,reconcileMission:reconcileMission,legacyMike:legacyMike,mission:mission,acceptance:acceptance,timer:null};tick();
})(typeof globalThis!=="undefined"?globalThis:this);
