// katrin_manchez.atlas.js -- source-derived v7.36 Good Dogs runtime atlas.
// Generated by scripts/extract_katrin_manchez_assets.py from Manchez and Katrin Knockdown Atlas.png.
window.KATRIN_MANCHEZ = {"src":"assets/v736/katrin_manchez_atlas.png","cell":0,"cellH":0,"pivot":[0,0],"frames":{"man_idle0":[4,4,178,157],"man_idle1":[186,4,151,162],"man_hack":[341,4,157,170],"man_pounce":[502,4,153,159],"man_bark":[659,4,178,157],"man_roll":[841,4,144,163],"man_wall_hit":[4,178,147,176],"man_look":[155,178,139,156],"man_strike":[298,178,173,158],"man_crouch":[475,178,145,154],"man_leap":[624,178,133,175],"man_down":[761,178,152,135],"man_wall_down":[4,358,136,156],"kat_idle0":[144,358,168,158],"kat_idle1":[316,358,142,154],"kat_hack":[462,358,152,181],"kat_pounce":[618,358,148,155],"kat_leap":[770,358,145,197],"kat_roll":[4,559,147,179],"kat_wall_hit":[155,559,143,170],"kat_bark":[302,559,165,142],"kat_look":[471,559,141,129],"kat_strike":[616,559,161,155],"kat_crouch":[781,559,148,151],"kat_shield":[4,742,168,133],"kat_down":[176,742,153,119],"kat_cheer":[333,742,119,142],"kat_down_heavy":[456,742,175,102],"kat_hack_low":[635,742,158,147],"kat_pounce_low":[797,742,149,138],"kat_leap_low":[4,893,129,137],"kat_dizzy":[137,893,160,128],"kat_stand":[301,893,121,134],"man_shield":[426,893,145,154],"man_down_wall":[575,893,136,156],"kat_sleep":[715,893,175,102],"kat_hack2":[4,1053,158,147],"kat_pounce2":[166,1053,149,138],"kat_leap2":[319,1053,129,137],"man_idle2":[452,1053,151,162],"man_idle3":[607,1053,153,159],"man_idle4":[764,1053,133,175],"man_idle5":[4,1232,144,163],"man_idle6":[152,1232,139,156],"kat_idle2":[295,1232,152,181],"kat_idle3":[451,1232,148,155],"kat_idle4":[603,1232,145,197],"kat_idle5":[752,1232,147,179],"kat_idle6":[4,1433,141,129]}};

/* v7.37 Good Boys ship-takeover presentation layer.
 * Uses the canonical Katrin/Manchez atlas to give the opening ship gameplay readable
 * locomotion, alert, hack and takeover poses without owning progression state.
 */
(function(root){
  "use strict";
  if(!root||!root.document||root.__goodDogsShipArtV1)return;
  root.__goodDogsShipArtV1=true;
  var img=new Image();img.src=root.KATRIN_MANCHEZ.src;
  function frame(ctx,key,x,y,w,flip){
    var f=root.KATRIN_MANCHEZ.frames[key];if(!f||!img.complete||!img.naturalWidth)return false;
    var h=w*(f[3]/f[2]);ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(img,f[0],f[1],f[2],f[3],0,0,w,h);}else ctx.drawImage(img,f[0],f[1],f[2],f[3],x,y,w,h);ctx.restore();return true;
  }
  function install(){
    var host=document.getElementById("good-boys-ship-interlude");if(!host||host.querySelector("canvas[data-good-dogs-art]"))return;
    var base=host.querySelector("canvas");if(!base)return;
    var art=document.createElement("canvas");art.width=960;art.height=540;art.dataset.goodDogsArt="1";art.setAttribute("aria-hidden","true");
    art.style.cssText="position:absolute;inset:0;width:100%;height:100%;pointer-events:none";
    var wrap=document.createElement("div");wrap.style.cssText="position:relative;width:100%;aspect-ratio:16/9;max-height:64vh";base.parentNode.insertBefore(wrap,base);wrap.appendChild(base);wrap.appendChild(art);base.style.cssText+=";position:absolute;inset:0;width:100%;height:100%;max-height:none";
    var ctx=art.getContext("2d"),lastX=115,lastCount=0,actionUntil=0,action="",raf=0;
    function pilot(){ctx.save();ctx.translate(850,298);ctx.fillStyle="#0b0e13";ctx.strokeStyle="#d97706";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-45,31,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillRect(-38,-14,76,83);ctx.strokeRect(-38,-14,76,83);ctx.fillStyle="#243442";ctx.fillRect(-56,55,112,34);ctx.fillStyle="#39bdf8";ctx.fillRect(-31,-52,62,10);ctx.restore();}
    function consoleUnit(x,accent){ctx.save();ctx.fillStyle="#07131c";ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.fillRect(x-58,178,116,116);ctx.strokeRect(x-58,178,116,116);ctx.fillStyle="#0c2636";ctx.fillRect(x-43,193,86,48);ctx.strokeRect(x-43,193,86,48);ctx.globalAlpha=.8;ctx.fillStyle=accent;ctx.fillRect(x-31,207,62,4);ctx.fillRect(x-20,219,40,4);ctx.restore();}
    function loop(t){
      if(!art.isConnected){cancelAnimationFrame(raf);return;}
      var s=root.__goodBoysOpeningGameplay||{},x=Number(s.x||115),moving=Math.abs(x-lastX)>1,count=Number(s.count||0),near=!!s.near,target=s.targetId||"";
      if(count>lastCount){actionUntil=t+620;action=target==="dock"?"takeover":"hack";lastCount=count;}
      ctx.clearRect(0,0,960,540);
      var sky=ctx.createLinearGradient(0,0,0,360);sky.addColorStop(0,"rgba(4,8,18,.96)");sky.addColorStop(1,"rgba(11,25,36,.88)");ctx.fillStyle=sky;ctx.fillRect(0,0,960,390);
      ctx.fillStyle="#02050a";ctx.fillRect(0,390,960,150);ctx.strokeStyle="#f97316";ctx.lineWidth=2;for(var i=0;i<8;i++){ctx.strokeRect(i*125+8,402,108,88);ctx.fillStyle=i%2?"#0b2638":"#29180c";ctx.fillRect(i*125+17,477,90,4);}
      ctx.fillStyle="#07111a";ctx.beginPath();ctx.moveTo(65,70);ctx.lineTo(895,70);ctx.lineTo(835,155);ctx.lineTo(125,155);ctx.closePath();ctx.fill();ctx.strokeStyle="#29485a";ctx.stroke();
      ctx.fillStyle="#020817";ctx.fillRect(145,83,670,58);ctx.fillStyle="#67b8ff";ctx.font="700 13px monospace";ctx.textAlign="center";ctx.fillText("BLACKSITE VECTOR // ORBITAL TRAFFIC CONTROL",480,116);
      consoleUnit(300,"#38bdf8");consoleUnit(555,"#f59e0b");consoleUnit(805,"#38bdf8");pilot();
      var katKey="kat_stand",manKey="man_idle0";
      if(actionUntil>t){katKey=action==="takeover"?"kat_pounce":"kat_hack";manKey=action==="takeover"?"man_pounce":"man_hack";}
      else if(near){katKey=target==="flight"?"kat_bark":"kat_crouch";manKey=target==="flight"?"man_bark":"man_crouch";}
      else if(moving){katKey=(Math.floor(t/150)%2)?"kat_pounce_low":"kat_leap_low";manKey=(Math.floor(t/150)%2)?"man_pounce":"man_leap";}
      else {katKey=(Math.floor(t/500)%2)?"kat_idle0":"kat_idle1";manKey=(Math.floor(t/500)%2)?"man_idle0":"man_idle1";}
      frame(ctx,katKey,x-52,320,92,false);frame(ctx,manKey,x+18,326,84,false);
      if(near){ctx.strokeStyle=target==="flight"?"#f59e0b":"#38bdf8";ctx.lineWidth=4;ctx.beginPath();ctx.arc(x+22,368,72,0,Math.PI*2);ctx.stroke();}
      lastX=x;raf=requestAnimationFrame(loop);
    }
    raf=requestAnimationFrame(loop);
  }
  var obs=new MutationObserver(install);obs.observe(document.documentElement,{childList:true,subtree:true});install();
})(typeof globalThis!=="undefined"?globalThis:this);
