// katrin_manchez.atlas.js -- source-derived v7.36 Good Dogs runtime atlas.
// Generated by scripts/extract_katrin_manchez_assets.py from Manchez and Katrin Knockdown Atlas.png.
window.KATRIN_MANCHEZ = {"src":"assets/v736/katrin_manchez_atlas.png","cell":0,"cellH":0,"pivot":[0,0],"frames":{"man_idle0":[4,4,178,157],"man_idle1":[186,4,151,162],"man_hack":[341,4,157,170],"man_pounce":[502,4,153,159],"man_bark":[659,4,178,157],"man_roll":[841,4,144,163],"man_wall_hit":[4,178,147,176],"man_look":[155,178,139,156],"man_strike":[298,178,173,158],"man_crouch":[475,178,145,154],"man_leap":[624,178,133,175],"man_down":[761,178,152,135],"man_wall_down":[4,358,136,156],"kat_idle0":[144,358,168,158],"kat_idle1":[316,358,142,154],"kat_hack":[462,358,152,181],"kat_pounce":[618,358,148,155],"kat_leap":[770,358,145,197],"kat_roll":[4,559,147,179],"kat_wall_hit":[155,559,143,170],"kat_bark":[302,559,165,142],"kat_look":[471,559,141,129],"kat_strike":[616,559,161,155],"kat_crouch":[781,559,148,151],"kat_shield":[4,742,168,133],"kat_down":[176,742,153,119],"kat_cheer":[333,742,119,142],"kat_down_heavy":[456,742,175,102],"kat_hack_low":[635,742,158,147],"kat_pounce_low":[797,742,149,138],"kat_leap_low":[4,893,129,137],"kat_dizzy":[137,893,160,128],"kat_stand":[301,893,121,134],"man_shield":[426,893,145,154],"man_down_wall":[575,893,136,156],"kat_sleep":[715,893,175,102],"kat_hack2":[4,1053,158,147],"kat_pounce2":[166,1053,149,138],"kat_leap2":[319,1053,129,137],"man_idle2":[452,1053,151,162],"man_idle3":[607,1053,153,159],"man_idle4":[764,1053,133,175],"man_idle5":[4,1232,144,163],"man_idle6":[152,1232,139,156],"kat_idle2":[295,1232,152,181],"kat_idle3":[451,1232,148,155],"kat_idle4":[603,1232,145,197],"kat_idle5":[752,1232,147,179],"kat_idle6":[4,1433,141,129]}};

/* v7.37 Good Boys ship presentation v4 — compact mobile deck + atlas-authoritative dogs.
 * Scoped only to Clip 1 -> playable ship systems -> Clip 2. Campaign/progression
 * ownership remains elsewhere; this module is presentation only.
 */
(function(root){
  "use strict";
  if(!root||!root.document||root.__goodDogsShipCanonicalV4)return;
  root.__goodDogsShipCanonicalV4=true;
  root.__goodDogsShipCanonicalV3=true;
  root.__goodDogsShipCanonicalV2=true;

  var cockpit=new root.Image(),dogImage=null;
  cockpit.src="assets/v736/good_boys_ship/cockpit_pilot.jpg?v=20260902-deck-map-r2";
  var raf=root.requestAnimationFrame?root.requestAnimationFrame.bind(root):function(fn){return root.setTimeout(function(){fn(Date.now());},16);};
  var caf=root.cancelAnimationFrame?root.cancelAnimationFrame.bind(root):root.clearTimeout.bind(root);

  function atlas(){return root.KATRIN_MANCHEZ&&root.KATRIN_MANCHEZ.frames?root.KATRIN_MANCHEZ:null;}
  function dogAtlas(){
    var A=atlas();if(!A||!A.src)return null;
    if(!dogImage||dogImage.src!==A.src){dogImage=new root.Image();dogImage.src=A.src;}
    return dogImage.complete&&dogImage.naturalWidth?dogImage:null;
  }
  function frameKey(who,kind,t){
    var p=who==="manchez"?"man_":"kat_",A=atlas(),f=A&&A.frames||{};
    var key=p+kind;if(f[key])return key;
    if(kind==="bark"&&f[p+"strike"])return p+"strike";
    if(kind==="pounce"&&f[p+"leap"])return p+"leap";
    return p+((Math.floor((t||0)/220)%2)?"idle1":"idle0");
  }
  function drawDog(ctx,who,kind,cx,foot,h,flip,t){
    var A=atlas(),im=dogAtlas(),key=frameKey(who,kind,t),fr=A&&A.frames&&A.frames[key];
    if(!im||!fr)return false;
    var w=h*(fr[2]/fr[3]),dx=cx-w/2,dy=foot-h;
    ctx.save();ctx.imageSmoothingEnabled=false;
    ctx.globalAlpha=.32;ctx.fillStyle="#000";ctx.beginPath();ctx.ellipse(cx,foot-2,Math.max(18,w*.34),6,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
    if(flip){ctx.translate(cx,0);ctx.scale(-1,1);ctx.drawImage(im,fr[0],fr[1],fr[2],fr[3],-w/2,dy,w,h);}else ctx.drawImage(im,fr[0],fr[1],fr[2],fr[3],dx,dy,w,h);
    ctx.restore();return true;
  }
  function fallbackDog(ctx,who,cx,foot,h){
    var blue=who==="katrin",w=h*1.12;ctx.save();ctx.fillStyle="rgba(0,0,0,.3)";ctx.beginPath();ctx.ellipse(cx,foot-2,w*.32,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=blue?"#eef8ff":"#ffe9c8";ctx.beginPath();ctx.ellipse(cx,foot-h*.38,w*.34,h*.22,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(cx+w*.23,foot-h*.57,h*.16,0,Math.PI*2);ctx.fill();ctx.fillStyle=blue?"#111827":"#4b341d";ctx.fillRect(cx-w*.02,foot-h*.68,w*.42,h*.12);ctx.fillStyle=blue?"#38bdf8":"#f59e0b";ctx.beginPath();ctx.arc(cx+w*.05,foot-h*.37,4,0,Math.PI*2);ctx.fill();ctx.restore();
  }
  function cover(ctx,img,x,y,w,h){
    if(!img||!img.complete||!img.naturalWidth)return false;
    var ir=img.naturalWidth/img.naturalHeight,rr=w/h,sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;
    if(ir>rr){sw=sh*rr;sx=(img.naturalWidth-sw)/2;}else{sh=sw/rr;sy=(img.naturalHeight-sh)/2;}
    ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);return true;
  }
  function rounded(ctx,x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);}

  function installLayoutPatch(){
    var css=document.getElementById("good-boys-ship-visual-hotfix-style");
    if(!css){css=document.createElement("style");css.id="good-boys-ship-visual-hotfix-style";(document.head||document.documentElement).appendChild(css);}
    css.textContent=[
      '#good-boys-ship-interlude{box-sizing:border-box!important;align-items:flex-start!important;justify-content:center!important;padding:max(6px,env(safe-area-inset-top)) 8px max(6px,env(safe-area-inset-bottom))!important;overflow:hidden!important}',
      '#good-boys-ship-interlude .gbi-ship-shell{box-sizing:border-box!important;width:min(100%,980px)!important;height:auto!important;max-height:100%!important;min-height:0!important;display:grid!important;grid-template-rows:min-content min-content min-content min-content 60px!important;gap:5px!important;align-content:start!important;overflow:hidden!important}',
      '#good-boys-ship-interlude .gbi-ship-head{box-sizing:border-box!important;min-height:0!important;height:auto!important;margin:0!important;padding:0 2px!important;display:flex!important;flex-direction:row!important;align-items:center!important;justify-content:space-between!important;gap:7px!important;font-size:10px!important;line-height:1.15!important}',
      '#good-boys-ship-interlude .gbi-system-list{box-sizing:border-box!important;display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;height:40px!important;min-height:40px!important;max-height:40px!important;margin:0!important;overflow:hidden!important;font-size:9px!important}',
      '#good-boys-ship-interlude .gbi-system-list>*{box-sizing:border-box!important;height:40px!important;min-height:40px!important;max-height:40px!important;margin:0!important;padding:4px 7px!important;display:flex!important;align-items:center!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
      '#good-boys-ship-interlude [data-good-dogs-ship-stage="1"]{box-sizing:border-box!important;position:relative!important;width:100%!important;height:min(44dvh,360px,calc((100vw - 16px)*.66))!important;min-height:220px!important;max-height:360px!important;aspect-ratio:auto!important;align-self:start!important;overflow:hidden!important;border:1px solid #2d5b70!important;box-shadow:0 10px 34px #000b!important;background:#02070d!important}',
      '#good-boys-ship-interlude [data-good-dogs-ship-stage="1"] canvas{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;max-height:none!important;min-height:0!important;border:0!important;box-shadow:none!important;background:transparent!important}',
      '#good-boys-ship-interlude .gbi-ship-msg{box-sizing:border-box!important;height:20px!important;min-height:20px!important;max-height:20px!important;margin:0!important;padding:0 4px!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important;white-space:nowrap!important;text-overflow:ellipsis!important;font-size:9px!important;line-height:1!important}',
      '#good-boys-ship-interlude .gbi-ship-controls{box-sizing:border-box!important;display:grid!important;grid-template-columns:1fr 1fr 1.25fr!important;gap:7px!important;height:60px!important;min-height:60px!important;max-height:60px!important;margin:0!important}',
      '#good-boys-ship-interlude .gbi-ship-controls button,#good-boys-ship-interlude button[data-move],#good-boys-ship-interlude button[data-interact]{box-sizing:border-box!important;height:60px!important;min-height:60px!important;max-height:60px!important;margin:0!important;padding:0 10px!important;font-size:11px!important;touch-action:none!important}',
      '@media(max-width:600px){#good-boys-ship-interlude .gbi-ship-shell{gap:4px!important;grid-template-rows:min-content min-content min-content min-content 56px!important}#good-boys-ship-interlude .gbi-ship-head{font-size:9px!important}#good-boys-ship-interlude .gbi-system-list{height:36px!important;min-height:36px!important;max-height:36px!important;font-size:8px!important}#good-boys-ship-interlude .gbi-system-list>*{height:36px!important;min-height:36px!important;max-height:36px!important;padding:3px 5px!important}#good-boys-ship-interlude [data-good-dogs-ship-stage="1"]{height:min(43dvh,320px,calc((100vw - 16px)*.68))!important;min-height:210px!important;max-height:320px!important}#good-boys-ship-interlude .gbi-ship-controls,#good-boys-ship-interlude .gbi-ship-controls button,#good-boys-ship-interlude button[data-move],#good-boys-ship-interlude button[data-interact]{height:56px!important;min-height:56px!important;max-height:56px!important}#good-boys-ship-interlude .gbi-ship-controls button{font-size:10px!important}}',
      '@media(max-height:690px){#good-boys-ship-interlude [data-good-dogs-ship-stage="1"]{height:min(37dvh,260px,calc((100vw - 16px)*.62))!important;min-height:175px!important}#good-boys-ship-interlude .gbi-system-list,#good-boys-ship-interlude .gbi-system-list>*{height:32px!important;min-height:32px!important;max-height:32px!important}#good-boys-ship-interlude .gbi-ship-controls,#good-boys-ship-interlude .gbi-ship-controls button,#good-boys-ship-interlude button[data-move],#good-boys-ship-interlude button[data-interact]{height:50px!important;min-height:50px!important;max-height:50px!important}}'
    ].join('');
  }

  function install(){
    var host=document.getElementById("good-boys-ship-interlude");if(!host)return false;
    installLayoutPatch();
    if(host.querySelector('canvas[data-good-dogs-canonical-art="4"]'))return true;
    var base=host.querySelector("canvas");if(!base)return false;
    var wrap=base.parentNode;
    if(!(wrap&&wrap.dataset&&wrap.dataset.goodDogsShipStage)){
      if(!(wrap&&wrap.style&&/position\s*:\s*relative/i.test(wrap.getAttribute("style")||""))){
        var holder=document.createElement("div");holder.dataset.goodDogsShipStage="1";base.parentNode.insertBefore(holder,base);holder.appendChild(base);wrap=holder;
      }else wrap.dataset.goodDogsShipStage="1";
    }
    wrap.dataset.goodDogsShipStage="1";
    base.style.cssText+=";position:absolute;inset:0;width:100%;height:100%;max-height:none";
    var old=wrap.querySelector('canvas[data-good-dogs-canonical-art]:not([data-good-dogs-canonical-art="4"])');if(old){old.style.opacity="0";old.style.zIndex="2";}

    var art=document.createElement("canvas");art.width=960;art.height=600;art.dataset.goodDogsCanonicalArt="4";art.setAttribute("aria-hidden","true");
    art.style.cssText="position:absolute;inset:0;width:100%;height:100%;z-index:7;pointer-events:none";wrap.appendChild(art);
    var ctx=art.getContext("2d"),lastX=115,lastCount=0,actionUntil=0,action="",handle=0;

    function panel(x,label,done,near,accent){
      var y=236,w=154,h=94;ctx.save();
      ctx.shadowBlur=near?20:8;ctx.shadowColor=done?"#34d399":accent;ctx.fillStyle=near?"rgba(15,31,45,.97)":"rgba(3,12,20,.91)";ctx.strokeStyle=done?"#34d399":near?"#ffd166":accent;ctx.lineWidth=near?4:2;rounded(ctx,x-w/2,y,w,h,9);ctx.fill();ctx.stroke();ctx.shadowBlur=0;
      ctx.fillStyle=done?"#34d399":accent;ctx.globalAlpha=.18;ctx.fillRect(x-w/2+8,y+9,w-16,36);ctx.globalAlpha=1;
      ctx.fillStyle="#effaff";ctx.font="700 12px monospace";ctx.textAlign="center";ctx.fillText(label,x,y+30);
      ctx.font="700 10px monospace";ctx.fillStyle=done?"#8df1ce":near?"#ffd166":"#90a9b8";ctx.fillText(done?"ONLINE":near?"INTERACT":"STANDBY",x,y+60);
      ctx.fillStyle="rgba(7,24,35,.95)";ctx.fillRect(x-w/2+18,y+72,w-36,8);ctx.fillStyle=done?"#34d399":near?"#ffd166":accent;ctx.fillRect(x-w/2+20,y+74,(w-40)*(done?1:near?.72:.18),4);ctx.restore();
    }
    function deck(t,s){
      var W=960,H=600;
      var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#07131f");g.addColorStop(.56,"#06101a");g.addColorStop(1,"#010408");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
      ctx.save();ctx.globalAlpha=.82;if(!cover(ctx,cockpit,0,50,W,245)){ctx.fillStyle="#0b1b28";ctx.fillRect(0,50,W,245);}ctx.restore();
      var shade=ctx.createLinearGradient(0,45,0,315);shade.addColorStop(0,"rgba(0,5,10,.18)");shade.addColorStop(.55,"rgba(0,5,10,.22)");shade.addColorStop(1,"rgba(0,5,10,.88)");ctx.fillStyle=shade;ctx.fillRect(0,45,W,285);
      ctx.fillStyle="rgba(2,8,14,.94)";ctx.fillRect(0,0,W,54);ctx.strokeStyle="#246075";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,54);ctx.lineTo(W,54);ctx.stroke();
      ctx.fillStyle="#9bf4d7";ctx.font="700 12px monospace";ctx.textAlign="left";ctx.fillText("SHIP DECK // SYSTEM RECOVERY",24,33);
      var done=s.systems||[],count=done.length;ctx.textAlign="right";ctx.fillStyle=count===3?"#34d399":"#8db9ca";ctx.fillText(count+" / 3 ONLINE",936,33);
      ctx.fillStyle="#03080d";ctx.fillRect(0,300,W,300);
      var floor=ctx.createLinearGradient(0,300,0,600);floor.addColorStop(0,"rgba(15,38,52,.98)");floor.addColorStop(1,"rgba(1,4,8,1)");ctx.fillStyle=floor;ctx.fillRect(0,300,W,300);
      ctx.save();ctx.globalAlpha=.28;ctx.strokeStyle="#55d9ff";ctx.lineWidth=1;for(var i=0;i<11;i++){ctx.beginPath();ctx.moveTo(480,300);ctx.lineTo(i*120-120,600);ctx.stroke();}for(var yy=335;yy<600;yy+=42){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke();}ctx.restore();
      ctx.strokeStyle="#f59e0b";ctx.globalAlpha=.48;ctx.lineWidth=3;for(var k=0;k<8;k++){ctx.beginPath();ctx.moveTo(k*150-70,570);ctx.lineTo(k*150+45,500);ctx.stroke();}ctx.globalAlpha=1;
      var glow=ctx.createRadialGradient(480,390,60,480,390,470);glow.addColorStop(0,"rgba(56,189,248,.11)");glow.addColorStop(1,"rgba(0,0,0,.42)");ctx.fillStyle=glow;ctx.fillRect(0,300,W,300);
      ctx.fillStyle="rgba(0,0,0,.38)";ctx.fillRect(0,292,W,14);
    }
    function loop(t){
      if(!art.isConnected){caf(handle);return;}
      var s=root.__goodBoysOpeningGameplay||{},x=Math.max(92,Math.min(866,Number(s.x||115))),moving=Math.abs(x-lastX)>1,count=Number(s.count||0),near=!!s.near,target=s.targetId||"",done=Array.isArray(s.systems)?s.systems:[];
      if(count>lastCount){actionUntil=t+650;action=target==="dock"?"pounce":"bark";lastCount=count;}
      deck(t,s);
      panel(300,"NAV ARRAY",done.indexOf("nav")>=0,near&&target==="nav","#38bdf8");
      panel(555,"FLIGHT CTRL",done.indexOf("flight")>=0,near&&target==="flight","#f59e0b");
      panel(805,"DOCK SECURITY",done.indexOf("dock")>=0,near&&target==="dock","#38bdf8");
      if(near){var tx=target==="nav"?300:target==="flight"?555:805;ctx.save();ctx.strokeStyle="#ffd166";ctx.lineWidth=3;ctx.globalAlpha=.72+.18*Math.sin(t/130);ctx.beginPath();ctx.arc(tx,398,62,0,Math.PI*2);ctx.stroke();ctx.restore();}
      var kind="idle";if(actionUntil>t)kind=action;else if(near&&target==="flight")kind="bark";else if(moving)kind=(Math.floor(t/170)%2)?"idle1":"idle0";else kind=(Math.floor(t/700)%2)?"idle1":"idle0";
      var bob=moving?Math.sin(t/80)*3:Math.sin(t/320)*1.5,foot=497;
      var katKind=kind.indexOf("idle")===0?kind:kind,manKind=kind.indexOf("idle")===0?kind:kind;
      if(!drawDog(ctx,"katrin",katKind,x-38,foot+bob,92,false,t))fallbackDog(ctx,"katrin",x-38,foot+bob,92);
      if(!drawDog(ctx,"manchez",manKind,x+42,foot-bob,88,false,t))fallbackDog(ctx,"manchez",x+42,foot-bob,88);
      ctx.save();ctx.fillStyle="rgba(2,7,12,.86)";ctx.strokeStyle="rgba(118,216,255,.35)";ctx.lineWidth=1;rounded(ctx,22,542,292,36,7);ctx.fill();ctx.stroke();ctx.fillStyle="#a6d9e8";ctx.font="700 10px monospace";ctx.textAlign="left";ctx.fillText(near?"SYSTEM IN RANGE // INTERACT":"MOVE TO THE NEXT LIT CONSOLE",38,564);ctx.restore();
      lastX=x;handle=raf(loop);
    }
    handle=raf(loop);return true;
  }

  var obs=new MutationObserver(function(){install();});obs.observe(document.documentElement,{childList:true,subtree:true});
  installLayoutPatch();install();
  root.GoodDogsShipCanonicalArt={VERSION:5,cockpit:"assets/v736/good_boys_ship/cockpit_pilot.jpg?v=20260902-deck-map-r2",dogs:"KATRIN_MANCHEZ",install:install};
})(typeof globalThis!=="undefined"?globalThis:this);

/* Good Boys M2 boarding action owner v2.
 * BOARD THE SHIP is owned by the mounted M2 gameplay runtime, never by canonical
 * metadata alone. During cinematic/runtime handoff an old ending runtime or no
 * runtime at all must remove the affordance instead of leaking a premise surface.
 */
(function(root){
  "use strict";
  if(!root||!root.document||root.__goodBoysBoardShipActionV2)return;
  root.__goodBoysBoardShipActionV2=true;
  var boarding=false,retryTimer=0;
  function state(){
    try{
      var p=root.TechOpsGoodBoysProgressionAuthority,n=root.NM,c=n&&n._v736,m=p&&p.mission?Number(p.mission()):Number(root.S&&root.S.meta&&root.S.meta._v736&&root.S.meta._v736.m||0);
      var living=n&&n.enemies?n.enemies.filter(function(e){return e&&e.alive!==false&&Number(e.hp)>0;}).length:0;
      return{p:p,n:n,c:c,m:m,living:living,revealed:!!(n&&n._gbShipRevealed),x:Number(n&&n.x||0)};
    }catch(e){return{m:0,living:99,revealed:false,x:0};}
  }
  function isLiveM2(s){return !!(s&&s.c&&!s.c.ending&&Number(s.c.m||0)===2&&s.m===2);}
  function remove(){var b=document.getElementById("good-boys-board-ship");if(b)b.remove();}
  function commit(attempt){
    var s=state();attempt=attempt||0;
    if(!isLiveM2(s)||!s.revealed||s.living>0||s.x<1080||!s.p||typeof s.p.advance!=="function"){boarding=false;remove();return false;}
    var ok=false;try{ok=!!s.p.advance(3,"boarded-secret-ship-button");}catch(e){root.__goodBoysBoardShipError=String(e&&e.stack||e);}
    root.__goodBoysBoardShipAttempt={ok:ok,attempt:attempt,mission:s.m,runtimeMission:Number(s.c&&s.c.m||0),x:s.x,at:Date.now()};
    if(ok){remove();return true;}
    if(attempt<6){clearTimeout(retryTimer);retryTimer=setTimeout(function(){commit(attempt+1);},140);return false;}
    boarding=false;return false;
  }
  function activate(e){
    var s=state();if(!isLiveM2(s)||!s.revealed||s.living>0||s.x<1080){remove();return false;}
    if(e){try{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();}catch(_){} }
    if(boarding)return true;boarding=true;var b=document.getElementById("good-boys-board-ship");if(b){b.disabled=true;b.textContent="BOARDING…";}commit(0);return true;
  }
  function legacyTarget(t){try{var b=t&&t.closest?t.closest("button"):null;return b&&/BOARD\s+(THE\s+)?SHIP/i.test(b.textContent||"")?b:null;}catch(_){return null;}}
  function rescue(e){if(legacyTarget(e&&e.target))activate(e);}
  function render(){
    var s=state(),b=document.getElementById("good-boys-board-ship");
    var visible=isLiveM2(s)&&s.revealed&&s.living===0&&s.x>=1080;
    if(!visible){if(b)remove();return;}
    if(!b){
      b=document.createElement("button");b.id="good-boys-board-ship";b.type="button";b.textContent="BOARD THE SHIP";b.setAttribute("aria-label","Board the secret ship");
      b.style.cssText="position:fixed;left:50%;bottom:max(88px,calc(env(safe-area-inset-bottom) + 78px));transform:translateX(-50%);z-index:15050;min-width:210px;min-height:54px;padding:12px 20px;border:2px solid #67e8f9;border-radius:8px;background:#071624;color:#fff;box-shadow:0 0 0 3px #051019,0 8px 30px #000b;font:800 13px monospace;letter-spacing:.08em;touch-action:manipulation";
      b.addEventListener("pointerup",activate);b.addEventListener("click",activate);document.body.appendChild(b);
    }
    if(!boarding){b.disabled=false;b.textContent="BOARD THE SHIP";}
  }
  document.addEventListener("pointerup",rescue,true);document.addEventListener("click",rescue,true);
  setInterval(render,80);render();
  root.TechOpsGoodBoysBoardShipAction={VERSION:2,activate:activate,render:render,state:state,isLiveM2:isLiveM2};
})(typeof globalThis!=="undefined"?globalThis:this);
