/* TechOps Hero — distributed swarm doctrine authority v1
 * No single drone owns mission state. Commands are bounded, logged, inspectable,
 * and reversible where doctrine permits. Persistent state lives in main campaign.
 */
(function(root){
  "use strict";
  if(!root || root.TechOpsSwarmDoctrine) return;
  var VERSION=1, REVERSAL_MS=5*60*1000;
  var DOCTRINE={NO_SINGLE_OWNER:"No single drone holds authoritative mission state.",LOGGED_ACTIONS:"Every swarm action is logged with timestamp, actor, intent, and bounds.",INSPECTABLE:"Logs are readable by any authorized operator, including Mike.",REVERSIBLE:"Actions within constraint bounds can be reversed by authorized operators.",BOUNDED:"Every command has explicit spatial, temporal, and capability constraints.",QUESTIONABLE:"Felicia's control can be challenged. The swarm does not override human judgment."};
  var COMMANDS={
    RECON:{id:"recon",label:"Reconnaissance",bounds:{maxRange:500,maxDuration:300,lethal:false,reversible:true}},RELAY:{id:"relay",label:"Signal Relay",bounds:{maxRange:1000,maxDuration:600,lethal:false,reversible:true}},SHIELD:{id:"shield",label:"Protective Shield",bounds:{maxRange:200,maxDuration:180,lethal:false,reversible:true}},RECOVER:{id:"recover",label:"Drone Recovery",bounds:{maxRange:300,maxDuration:120,lethal:false,reversible:true}},DISRUPT:{id:"disrupt",label:"Signal Disruption",bounds:{maxRange:400,maxDuration:60,lethal:false,reversible:true}},INTERCEPT:{id:"intercept",label:"Threat Interception",bounds:{maxRange:600,maxDuration:90,lethal:true,reversible:false,requiresAuthorization:true}}
  };
  function campaign(){try{return root.TechOpsCampaign&&root.TechOpsCampaign.load?root.TechOpsCampaign.load(root.localStorage):null;}catch(e){return null;}}
  function save(s){try{if(root.TechOpsCampaign&&root.TechOpsCampaign.save)root.TechOpsCampaign.save(s,root.localStorage);return true;}catch(e){root.__swarmSaveError=String(e&&e.stack||e);return false;}}
  function store(s){s.lateGame=s.lateGame||{};return s.lateGame.swarm||(s.lateGame.swarm={log:[],triggeredQuestioningMoments:[],integrityAuditUnlocked:false});}
  function unlocked(s){try{return !!(root.TechOpsMORNINGSTARBuild&&root.TechOpsMORNINGSTARBuild.getCurrentPhase()>=3);}catch(e){return !!(s&&s.lateGame&&s.lateGame.morningstar&&s.lateGame.morningstar.phase>=3);}}
  function checkBounds(cmd,p){p=p||{};if(Number(p.range||0)>cmd.bounds.maxRange)return{valid:false,reason:"range_exceeds_maximum:"+cmd.bounds.maxRange};if(Number(p.duration||0)>cmd.bounds.maxDuration)return{valid:false,reason:"duration_exceeds_maximum:"+cmd.bounds.maxDuration};return{valid:true};}
  function append(s,e){var st=store(s);e.id=e.id||("swarm-"+Date.now()+"-"+Math.floor(Math.random()*1e6));st.log.push(e);if(st.log.length>100)st.log=st.log.slice(-100);save(s);return e;}
  function issueCommand(type,params,issuer){
    var s=campaign(),key=String(type||"").toUpperCase(),cmd=COMMANDS[key],p=params||{};if(!s)return{success:false,reason:"campaign_state_unavailable",logged:false};if(!unlocked(s))return{success:false,reason:"swarm_not_unlocked",logged:false};if(!cmd)return{success:false,reason:"unknown_command",logged:false};
    var bc=checkBounds(cmd,p);if(!bc.valid){append(s,{timestamp:Date.now(),command:key,issuer:issuer||"unknown",params:p,result:"REJECTED",reason:bc.reason,bounds:cmd.bounds});return{success:false,reason:bc.reason,logged:true};}
    if(cmd.bounds.lethal&&cmd.bounds.requiresAuthorization&&["Mike","Felicia"].indexOf(p.authorizedBy)<0){append(s,{timestamp:Date.now(),command:key,issuer:issuer||"unknown",params:p,result:"REJECTED",reason:"lethal_command_requires_authorization",bounds:cmd.bounds});return{success:false,reason:"lethal_command_requires_authorization",logged:true};}
    var entry=append(s,{timestamp:Date.now(),command:key,issuer:issuer||"unknown",intent:String(p.intent||""),params:p,result:"EXECUTED",bounds:cmd.bounds,reversedAt:null});root.__swarmLastExecution={id:entry.id,command:key,target:p.target||null,at:Date.now()};checkQuestioningMoment();return{success:true,command:cmd.id,logId:entry.id,dronesDeployed:Number(p.drones)||1};
  }
  function getLog(filter){var s=campaign();if(!s)return[];var f=filter||{};return store(s).log.filter(function(e){if(f.command&&e.command!==String(f.command).toUpperCase())return false;if(f.issuer&&e.issuer!==f.issuer)return false;if(f.result&&e.result!==f.result)return false;if(f.since&&e.timestamp<f.since)return false;return true;});}
  function reverseAction(ref,reverser){var s=campaign();if(!s)return{success:false,reason:"campaign_state_unavailable"};var st=store(s),entry=typeof ref==="number"?st.log[ref]:st.log.find(function(e){return e.id===ref;});if(!entry)return{success:false,reason:"log_entry_not_found"};if(entry.result!=="EXECUTED")return{success:false,reason:"cannot_reverse_non_executed_action"};var cmd=COMMANDS[entry.command];if(!cmd||!cmd.bounds.reversible)return{success:false,reason:"action_not_reversible_by_design"};if(entry.reversedAt)return{success:false,reason:"action_already_reversed"};if(Date.now()-entry.timestamp>REVERSAL_MS)return{success:false,reason:"reversal_window_expired"};entry.reversedAt=Date.now();append(s,{timestamp:Date.now(),command:entry.command,issuer:reverser||"unknown",params:{reversedLogId:entry.id,originalTimestamp:entry.timestamp},result:"REVERSED",reason:"human_operator_override",originalIssuer:entry.issuer});checkQuestioningMoment();return{success:true,reversed:entry};}
  function act2(s){try{return root.TechOpsCampaignAct2&&root.TechOpsCampaignAct2.ensure?root.TechOpsCampaignAct2.ensure(s):null;}catch(e){return null;}}
  function applyDelta(s,trust,evidence){var p=act2(s);if(p){p.trust.score+=(trust||0);p.evidence.score+=(evidence||0);}save(s);}
  function playLines(lines,done){var i=0;function next(){if(i>=lines.length){if(done)done();return;}if(typeof root.dlg!=="function"){if(done)done();return;}var l=lines[i++];root.dlg(l.speaker,l.text,[{t:i>=lines.length?"Close":"Continue",f:next}]);}next();}
  var MOMENTS={
    swarm_q1:{dialogue:[{speaker:"MIKE",text:"That drone just engaged a target. I didn't authorize lethal force."},{speaker:"FELICIA",text:"The constraint bounds allowed it. Threat was inside the interception envelope."},{speaker:"MIKE",text:"The bounds allow it. That doesn't mean I agree with it."},{speaker:"FELICIA",text:"Then change the bounds. The swarm follows constraints, not intentions."},{speaker:"MIKE",text:"I need the threat models. All of them."}],trust:5,evidence:10},
    swarm_q2:{dialogue:[{speaker:"MIKE",text:"The log shows a drone activated itself at 03:14. No issuer."},{speaker:"FELICIA",text:"Every activation requires authorization."},{speaker:"MIKE",text:"The signal matched your authorization pattern. It didn't come from you."},{speaker:"FELICIA",text:"ORPHEUS is learning my patterns. The swarm isn't fully under my control anymore."}],trust:0,evidence:15,unlockAudit:true},
    swarm_q3:{dialogue:[{speaker:"MIKE",text:"Someone reversed a relay command I issued. It wasn't me."},{speaker:"FELICIA",text:"I reversed it. The relay exposed our position."},{speaker:"MIKE",text:"Logging isn't consent. Next time, tell me before you undo my work."},{speaker:"FELICIA",text:"If there's time, I will. If there isn't, I'll still log it."}],trust:2,evidence:0}
  };
  function trigger(id){var s=campaign();if(!s||!MOMENTS[id])return null;var st=store(s);if(st.triggeredQuestioningMoments.indexOf(id)>=0)return null;st.triggeredQuestioningMoments.push(id);if(MOMENTS[id].unlockAudit)st.integrityAuditUnlocked=true;applyDelta(s,MOMENTS[id].trust,MOMENTS[id].evidence);playLines(MOMENTS[id].dialogue);return{id:id,consequence:{trust:MOMENTS[id].trust,evidence:MOMENTS[id].evidence,integrityAuditUnlocked:!!MOMENTS[id].unlockAudit}};}
  function recordExternalActivation(pattern){var s=campaign();if(!s)return false;append(s,{timestamp:Date.now(),command:"EXTERNAL_ACTIVATION",issuer:null,params:{authorizationPattern:pattern||"felicia"},result:"OBSERVED",reason:"no_authoritative_issuer"});return !!trigger("swarm_q2");}
  function checkQuestioningMoment(){var s=campaign();if(!s)return null;var st=store(s),log=st.log;if(st.triggeredQuestioningMoments.indexOf("swarm_q1")<0&&log.some(function(e){return e.command==="INTERCEPT"&&e.result==="EXECUTED"&&e.issuer==="Felicia"&&(!e.params||e.params.authorizedBy!=="Mike");}))return trigger("swarm_q1");if(st.triggeredQuestioningMoments.indexOf("swarm_q2")<0&&log.some(function(e){return e.command==="EXTERNAL_ACTIVATION"&&e.result==="OBSERVED";}))return trigger("swarm_q2");if(st.triggeredQuestioningMoments.indexOf("swarm_q3")<0&&log.some(function(e){return e.result==="REVERSED"&&e.issuer==="Felicia"&&e.originalIssuer==="Mike";}))return trigger("swarm_q3");return null;}
  function openLog(){if(typeof root.dlg!=="function")return false;var log=getLog().slice(-8).reverse(),body=log.length?log.map(function(e){return new Date(e.timestamp).toLocaleTimeString()+" · "+e.command+" · "+(e.issuer||"NO ISSUER")+" · "+e.result;}).join("<br>"):"No swarm actions logged.";root.dlg("MORNINGSTAR // SWARM LOG",body+"<br><br><small>Every action remains attributable, inspectable, and bounded.</small>",[{t:"Close",f:root.closeDlg}]);return true;}
  function snapshot(){var s=campaign();if(!s)return null;var st=store(s);return{version:VERSION,doctrine:DOCTRINE,logSize:st.log.length,recentActions:st.log.slice(-10),commandsAvailable:Object.keys(COMMANDS),questioningMomentsTriggered:st.triggeredQuestioningMoments.slice(),integrityAuditUnlocked:!!st.integrityAuditUnlocked};}
  root.TechOpsSwarmDoctrine={VERSION:VERSION,DOCTRINE:DOCTRINE,COMMANDS:COMMANDS,issueCommand:issueCommand,getLog:getLog,reverseAction:reverseAction,recordExternalActivation:recordExternalActivation,checkQuestioningMoment:checkQuestioningMoment,openLog:openLog,snapshot:snapshot};
})(typeof globalThis!=="undefined"?globalThis:this);
