"use strict";
const assert=require("assert");
const fs=require("fs");
const vm=require("vm");
const source=fs.readFileSync("good_boys_reference_mechanics.js","utf8");
const prisonSource=fs.readFileSync("good_boys_prison_gameplay_v2.js","utf8");
new Function(source);
new Function(prisonSource);
assert.ok(/Combat never delegates to interact/.test(source),"combat/interact separation must be explicit");
assert.ok(!/root\.interact\(/.test(source),"paired combat must never call interact()");
assert.ok(/WHIFF · NO COMBO/.test(source),"whiffs must be observable and reset combo state");
assert.ok(/lastAttackHit/.test(source)&&/whiffs/.test(source)&&/hits/.test(source),"combat telemetry must distinguish hits from whiffs");
let t=1000,mode="hit";
const enemy={x:120,y:0,w:28,h:40,hp:100,maxHp:100,alive:true,down:0};
const sandbox={console,Date,Map,Math,performance:{now:()=>t},setInterval:()=>1,setTimeout:(fn)=>fn(),clearInterval:()=>{},NM:{_v736:{active:"katrin",sync:0,chars:{katrin:{hp:100},manchez:{hp:100}},partner:{x:10,y:0,w:22,h:34}},x:100,y:0,w:22,h:34,face:1,onGround:true,block:false,enemies:[enemy],hitStop:0},nmJab:()=>{if(mode==="hit")enemy.hp-=10;}};sandbox.globalThis=sandbox;
vm.runInNewContext(source,sandbox);
const api=sandbox.TechOpsGoodBoysReferenceMechanics;assert.ok(api&&api.VERSION>=3);
assert.strictEqual(api.pairedAttack(),true,"real damage must advance paired combo");
assert.strictEqual(api.state.comboStep,1);assert.strictEqual(api.state.hits,1);assert.strictEqual(api.state.whiffs,0);assert.strictEqual(sandbox.NM._v736.sync,2);
mode="whiff";t+=120;const syncBefore=sandbox.NM._v736.sync;assert.strictEqual(api.pairedAttack(),false,"whiff must not count as paired hit");assert.strictEqual(api.state.comboStep,0,"whiff must reset combo");assert.strictEqual(api.state.whiffs,1);assert.strictEqual(sandbox.NM._v736.sync,syncBefore,"whiff must not grant SYNC");
let interactions=0; sandbox.interact=()=>{interactions++;};delete sandbox.nmJab;
assert.strictEqual(api.pairedAttack(),false,"missing combat engine must not open interaction UI");
assert.strictEqual(interactions,0);assert.strictEqual(sandbox.NM._v736.sync,syncBefore);
// Both old control entrypoints must use the same hit/whiff authority.
vm.runInNewContext(fs.readFileSync('good_boys_campaign_director.js','utf8'),sandbox);
assert.strictEqual(sandbox.TechOpsGoodBoysCampaignDirector.duoAttack(),false);
assert.strictEqual(interactions,0);assert.strictEqual(sandbox.NM._v736.sync,syncBefore);

// Test the shipped composition, not only the reference authority in isolation.
sandbox.document={getElementById:()=>null,addEventListener:()=>{},body:{appendChild:()=>{}},createElement:()=>({style:{},dataset:{}})};
sandbox.NM._v736.m=3;sandbox.NM._v736.active="katrin";sandbox.NM.enemies=[enemy];enemy.hp=100;enemy.alive=true;mode="whiff";t+=120;
vm.runInNewContext(prisonSource,sandbox);
const prison=sandbox.TechOpsGoodBoysPrisonGameplayV2;
const hpBefore=enemy.hp,composedSyncBefore=sandbox.NM._v736.sync;
assert.strictEqual(api.pairedAttack(),false,"composed prison attack must preserve the base whiff result");
assert.strictEqual(enemy.hp,hpBefore,"prison bonuses cannot damage on a whiff");
assert.strictEqual(prison.acceptance().comboStep,0,"prison combo cannot advance on a whiff");
sandbox.NM._v736.active="manchez";t+=120;
assert.strictEqual(api.pairedAttack(),false);
assert.strictEqual(sandbox.NM._v736.sync,composedSyncBefore,"actor switching on whiffs cannot grant SYNC");
console.log("Good Dogs combat separation + whiff contract: PASS");
