'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const audio=fs.readFileSync('combat_audio.js','utf8'),combat=fs.readFileSync('night_combat.js','utf8'),game=fs.readFileSync('game.js','utf8');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function context(){
 const nodes=[],scheduled=[];let buffers=0;
 function param(){return {value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}};}
 function node(){const n={gain:param(),frequency:param(),pan:param(),Q:param(),connect(target){this.target=target;return target;},disconnect(){this.disconnected=true;},start(time){scheduled.push({node:this,time});},stop(time){this.until=time;}};nodes.push(n);return n;}
 return {state:'running',sampleRate:8000,currentTime:1,destination:{musicUntouched:true},createGain:node,createStereoPanner:node,createOscillator:node,createBiquadFilter:node,createBufferSource:node,createBuffer(_,length){buffers++;return {getChannelData(){return new Float32Array(length);}};},resume(){this.state='running';return Promise.resolve();},nodes,scheduled,buffers:()=>buffers};
}
function boot(){const root={console};vm.runInNewContext(audio,root);return root;}
test('all semantic cues produce scheduled finite, bounded voices',()=>{for(const name of Object.keys(boot().TechOpsCombatAudio.SPECS)){const r=boot(),ctx=context();assert.equal(r.TechOpsCombatAudio.play('combat_'+name,{context:ctx,volume:.8}),true);assert.ok(ctx.scheduled.length>0,name);assert.ok(ctx.scheduled.every(s=>s.node.until>s.time&&s.node.until-s.time<.4));assert.equal(r.__combatAudioLast.cue,name);assert.equal(ctx.destination.musicUntouched,true);}});
test('audio nodes disconnect on ended; one reusable noise buffer per context',()=>{const r=boot(),ctx=context();for(let i=0;i<10;i++){ctx.currentTime+=1;r.TechOpsCombatAudio.play('combat_cross',{context:ctx});for(const s of ctx.scheduled.splice(0))s.node.onended();}assert.equal(ctx.buffers(),1);assert.ok(ctx.nodes.every(n=>n.disconnected));});
test('volume zero, malformed volume and suspended context never queue effects',()=>{for(const volume of [0,-1,NaN,'invalid']){const r=boot(),ctx=context();r.TechOpsCombatAudio.play('combat_hit',{context:ctx,volume});r.TechOpsCombatAudio.play('combat_jab',{context:ctx,volume});assert.equal(ctx.nodes.length,0);}const r=boot(),ctx=context();ctx.state='suspended';r.TechOpsCombatAudio.play('combat_slam',{context:ctx});assert.equal(ctx.nodes.length,0);assert.equal(r.TechOpsCombatAudio.play('not-a-cue',{context:ctx}),false);});
test('large event bursts obey voice cap and same-cue rate limit',()=>{const r=boot(),ctx=context();for(let i=0;i<100;i++){const names=Object.keys(r.TechOpsCombatAudio.SPECS);r.TechOpsCombatAudio.play(names[i%names.length],{context:ctx});}assert.ok(r.__combatAudioLast.active<=14);assert.ok(ctx.scheduled.length<=28);});
test('missing Web Audio capability is cosmetic, not a gameplay exception',()=>{const r=boot();assert.doesNotThrow(()=>r.TechOpsCombatAudio.play('jab',{context:{state:'running'}}));assert.ok(r.__combatAudioError);});
test('partially failed audio graphs disconnect without blocking combat',()=>{const r=boot(),ctx=context();ctx.createOscillator=()=>{throw new Error('device changed');};assert.doesNotThrow(()=>r.TechOpsCombatAudio.play('jab',{context:ctx}));assert.ok(ctx.nodes.every(n=>n.disconnected));assert.match(r.__combatAudioError,/device changed/);});
function fight(){const sounds=[],r={console,S:{},sfx:id=>sounds.push(id),performance:{now:()=>1000}};vm.runInNewContext(combat,r);const e={x:150,y:396,w:24,h:34,hp:500,alive:true,cash:[1,1]},n={x:100,y:396,w:22,h:34,face:1,hp:100,onGround:true,district:'downtown',enemies:[e],platforms:[],cash:0};return {r,n,e,sounds,api:r.TechOpsNightCombat,tick(ms){for(let t=0;t<ms;t+=10)this.api.tick(n,.01,{});}};}
test('windup is silent; contact produces impact; whiffs have no hit or rhythm reward',()=>{const f=fight();f.api.attack(f.n,{});assert.deepEqual(f.sounds,[]);f.tick(60);assert.deepEqual(f.sounds,[]);f.tick(20);assert.deepEqual(f.sounds,['combat_jab']);f.tick(230);f.e.x=900;f.api.attack(f.n,{});f.tick(80);assert.equal(f.sounds.at(-1),'combat_whiff');assert.equal(f.n.combo,0);assert.ok(!f.sounds.includes('combat_beat'));});
test('confirmed rhythm adds a quiet cue while guarded hits do not duplicate impact',()=>{const f=fight();f.api.attack(f.n,{});f.tick(310);f.api.attack(f.n,{});f.tick(80);assert.ok(f.sounds.includes('combat_cross'));assert.ok(f.sounds.includes('combat_beat'));const g=fight();g.e.blocks=true;g.api.attack(g.n,{});g.tick(80);assert.deepEqual(g.sounds,['combat_guard']);});
test('grab, throw and player hurt each have their own semantic feedback',()=>{const f=fight();f.e.x=130;f.api.attack(f.n,{arrowright:true});assert.equal(f.sounds.at(-1),'combat_grab');f.tick(150);f.api.attack(f.n,{arrowright:true});assert.equal(f.sounds.at(-1),'combat_throw');f.api.hurt(f.n);assert.equal(f.sounds.at(-1),'combat_hurt');});
test('actual shared sfx route respects master mute, volume and existing context',()=>{const r=boot(),ctx=context();r.window=r;r.S={nightMode:{x:0,w:22}};r.V67SET={volSfx:.3};r.AudioContext=function(){return ctx;};r.webkitAudioContext=r.AudioContext;vm.createContext(r);vm.runInContext(game.slice(game.indexOf('let AC = null;'),game.indexOf('// ---------- achievements')),r);r.sfx('combat_cross');assert.equal(r.__combatAudioLast.cue,'cross');assert.ok(ctx.nodes.some(n=>n.gain.value===.3));const before=ctx.scheduled.length;vm.runInContext('sfxMuted=true',r);r.sfx('combat_slam');assert.equal(ctx.scheduled.length,before);});
test('sound module has no competing clock, music control, listener or random gameplay call',()=>{assert.doesNotMatch(audio,/setInterval|requestAnimationFrame|addEventListener|Math\.random|setMusic\(/);assert.ok(fs.readFileSync('production_bootstrap.js','utf8').includes('"combat_audio.js"'));});
console.log(`Combat audio: ${count} tests passed`);
