"use strict";
const assert=require("assert");
const fs=require("fs");
const vm=require("vm");
const source=fs.readFileSync("good_boys_reference_mechanics.js","utf8");
new Function(source);
assert.ok(/Combat never delegates to interact/.test(source),"combat/interact separation must be explicit");
assert.ok(!/root\.interact\(/.test(source),"paired combat must never call interact()");
assert.ok(/WHIFF · NO COMBO/.test(source),"whiffs must be observable and reset combo state");
assert.ok(/lastAttackHit/.test(source)&&/whiffs/.test(source)&&/hits/.test(source),"combat telemetry must distinguish hits from whiffs");
let t=1000,mode="hit";
const enemy={x:120,y:0,w:28,h:40,hp:100,maxHp:100,alive:true,down:0};
const sandbox={console,Date,Map,Math,performance:{now:()=>t},setInterval:()=>1,setTimeout:(fn)=>fn(),clearInterval:()=>{},NM:{_v736:{active:"katrin",sync:0,chars:{katrin:{hp:100},manchez:{hp:100}},partner:{x:10,y:0,w:22,h:34}},x:100,y:0,w:22,h:34,face:1,onGround:true,block:false,enemies:[enemy],hitStop:0},nmJab:()=>{if(mode==="hit")enemy.hp-=10;}};sandbox.globalThis=sandbox;
vm.runInNewContext(source,sandbox);
const api=sandbox.TechOpsGoodBoysReferenceMechanics;assert.ok(api&&api.VERSION>=3);
assert.strictEqual(api.pairedAttack(),true,"real damage must advance paired combo");
assert.strictEqual(api.state.comboStep,1);assert.strictEqual(api.state.hits,1);assert.strictEqual(api.state.whiffs,0);assert.strictEqual(sandbox.NM._v736.sync,2);
mode="whiff";t+=120;const syncBefore=sandbox.NM._v736.sync;assert.strictEqual(api.pairedAttack(),false,"whiff must not count as paired hit");assert.strictEqual(api.state.comboStep,0,"whiff must reset combo");assert.strictEqual(api.state.whiffs,1);assert.strictEqual(sandbox.NM._v736.sync,syncBefore,"whiff must not grant SYNC");
console.log("Good Dogs combat separation + whiff contract: PASS");
