'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(){
  const root={console,TechOpsNightDistricts:{downtown:{name:'DOWNTOWN'},industrial:{name:'INDUSTRIAL'},waldo:{name:'WALDO'},home:{name:'HOME'},sector04:{name:'SECTOR04'}},sfx(){}};
  vm.createContext(root);vm.runInContext(fs.readFileSync('night_travel.js','utf8'),root);
  const api=root.TechOpsNightTravel,n={district:'downtown',street:1,x:280,y:396,w:22,h:34,onGround:true,enemies:[],platforms:[],done:{},hp:100,cash:50};let arrivals=0;
  root.nmLoadDistrict=id=>{arrivals++;n.district=id;n.street=1;n.enemies=[{alive:true,hp:30,x:900}];n.platforms=[{x:400,y:330,w:100}];n.clear=false;api.arrive(n);};
  return {root,api,n,arrivals:()=>arrivals};
}
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('industrial arrival parks outside without spawning live interior enemies',()=>{
 const {api,n,root}=harness();root.nmLoadDistrict('industrial');assert.equal(api.outside(n),true);assert.equal(api.parked(n),true);assert.equal(n.enemies.length,0);assert.equal(n._buildingRoom.enemies.length,1);
 assert.equal(api.interact(n),false,'door requires walking');n.x=509;assert.equal(api.interact(n),true);assert.equal(n.location,'interior');assert.equal(api.parked(n),false);assert.equal(api.nearCar(n),false);assert.equal(api.start(n,'home'),false);assert.equal(n.enemies.length,1);
 n.enemies[0].hp=7;n.x=61;assert.equal(api.interact(n),true);assert.equal(n.enemies.length,0);n.x=509;api.interact(n);assert.equal(n.enemies[0].hp,7,'reentry preserves damage');
});
test('jumping near doors or car cannot activate them',()=>{const {api,n,root}=harness();root.nmLoadDistrict('industrial');n.x=509;n.onGround=false;assert.equal(api.doorway(n),null);n.x=120;assert.equal(api.nearCar(n),false);});
test('car exists on arrival street only, never later blocks or campaign scenes',()=>{const {api,n}=harness();assert.equal(api.parked(n),true);n.street=2;assert.equal(api.parked(n),false);n.street=1;for(const key of ['_v736','_sector04']){n[key]={};assert.equal(api.parked(n),false);assert.equal(api.start(n,'home'),false);delete n[key];}});
test('all ordinary route choices start playable trips, reject invalid destinations and remote starts',()=>{for(const to of ['home','waldo','industrial','downtown']){const {api,n}=harness();assert.equal(api.start(n,to),true);assert.equal(n.drive.dur,18000);assert.equal(api.start(n,'home'),false);}const {api,n}=harness();assert.equal(api.start(n,'missing'),false);assert.equal(api.start(n,'sector04'),false);n.x=900;assert.equal(api.start(n,'home'),false);});
test('legacy drive records become traffic trips, never the retired 1.5 second teleport',()=>{const {api,n,arrivals}=harness();n.drive={t:0,dur:1500,to:'home'};for(let i=0;i<90;i++)api.step(n,1/60);assert.ok(n.drive);assert.ok(n.drive.traffic.length);assert.equal(arrivals(),0);});
test('lane change is edge based for keyboard and analog; held input does not traverse all lanes',()=>{const {api,n}=harness();api.start(n,'home');for(let i=0;i<50;i++)api.step(n,1/60,{arrowdown:true});assert.equal(n.drive.lane,2);api.step(n,1/60,{});api.step(n,1/60,{arrowup:true});assert.equal(n.drive.lane,1);for(let i=0;i<20;i++)api.step(n,1/60,{});api.step(n,1/60,{}, {y:-1});assert.equal(n.drive.lane,0);});
test('collision applies once, slows progress, and does not damage Mike or cash',()=>{const {api,n}=harness();api.start(n,'home');n.drive.traffic=[{lane:1,x:.43,speed:2,hit:false}];api.step(n,.05);assert.equal(n.drive.integrity,75);assert.equal(n.drive.hits,1);assert.equal(n.hp,100);assert.equal(n.cash,50);api.step(n,.05);assert.equal(n.drive.hits,1);assert.ok(n.drive.slow>0);});
test('traffic in another lane passes safely',()=>{const {api,n}=harness();api.start(n,'home');n.drive.traffic=[{lane:0,x:.43,speed:2,hit:false}];for(let i=0;i<20;i++)api.step(n,.05);assert.equal(n.drive.hits,0);assert.equal(n.drive.dodged,1);});
test('wreck offers retry and return without awarding arrival or resetting room progress',()=>{const {api,n,arrivals}=harness();api.start(n,'industrial');n.drive.integrity=25;n.drive.traffic=[{lane:1,x:.4,speed:1,hit:false}];api.step(n,.05);assert.equal(n.drive.failed,true);const t=n.drive.elapsed;api.step(n,.05);assert.equal(n.drive.elapsed,t);assert.equal(arrivals(),0);assert.equal(api.retry(n),true);assert.equal(n.drive.integrity,100);n.drive.failed=true;assert.equal(api.returnToCar(n),true);assert.equal(n.district,'downtown');assert.equal(api.nearCar(n),true);assert.equal(arrivals(),0);});
test('successful drive arrives once, outside; another route preserves the visited interior',()=>{
 const {api,n,root,arrivals}=harness();root.nmLoadDistrict('industrial');n.x=509;api.interact(n);n.enemies[0].hp=11;n.x=61;api.interact(n);n.x=280;api.start(n,'home');n.drive.progress=.999;api.step(n,.05);assert.equal(n.drive,null);assert.equal(n.district,'home');assert.equal(arrivals(),2);api.step(n,.05);assert.equal(arrivals(),2);
 api.start(n,'industrial');n.drive.progress=.999;api.step(n,.05);assert.equal(n.location,'exterior');n.x=509;api.interact(n);assert.equal(n.enemies[0].hp,11);
});
test('cleared indoor encounter returns to curb, preserving completion',()=>{const {api,n,root}=harness();root.nmLoadDistrict('industrial');n.x=509;api.interact(n);n.enemies=[];n.done.industrial=true;n.street=2;assert.equal(api.cleared(n),true);assert.equal(n.location,'exterior');assert.equal(api.parked(n),true);assert.equal(n.done.industrial,true);});
test('each traffic wave leaves a reachable clear lane at every tested frame rate',()=>{for(const dt of [1/120,1/60,1/30,.05]){const {api,n}=harness();api.start(n,'home');let lastWave=0;for(let t=0;t<30&&n.drive;t+=dt){const d=n.drive;if(d.wave!==lastWave){lastWave=d.wave;const incoming=d.traffic.filter(c=>c.x>.75);const used=new Set(incoming.map(c=>c.lane));assert.ok(used.size<3);d.lane=[0,1,2].find(l=>!used.has(l));}api.step(n,dt);}assert.equal(n.drive,null);assert.equal(n.lastDrive.hits,0);}});
test('renderers are balanced and exclude indoor car without requiring a DOM',()=>{const {api,n,root}=harness();let depth=0,cars=0;root.nmCar=()=>cars++;const x=new Proxy({canvas:{width:1000,height:600},save(){depth++;},restore(){depth--;},createLinearGradient(){return {addColorStop(){}};}},{get(o,k){return k in o?o[k]:()=>{};}});api.start(n,'home');api.draw(x,n,0);assert.equal(cars,1);assert.equal(depth,0);n.drive=null;root.nmLoadDistrict('industrial');api.drawEntrance(x,n);assert.equal(depth,0);});
// Existing owners must call the module, with no parallel render/simulation loop.
const source=fs.readFileSync('night_travel.js','utf8');assert.ok(!/setInterval|requestAnimationFrame|setTimeout/.test(source));
console.log(JSON.stringify({suite:'night-travel',passed,failed:0}));
