'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let tests=0;
function test(name,fn){fn();tests++;console.log('PASS '+name);}
function boot(){const r=vm.createContext({console,performance:{now:()=>1000},matchMedia:()=>({matches:false})});for(const f of ['cinematic_systems.js','production_gameplay_experience.js','orbital_scene_staging.js'])vm.runInContext(fs.readFileSync(f,'utf8'),r,{filename:f});return r;}
function scene(r,m){const n={x:700,y:396,w:22,h:34,cam:500,onGround:true,_v736:{m,evidence:[{x:500,found:false},{x:800,found:false},{x:1100,found:false},{x:1400,found:false}]},enemies:[]};r.NM=n;r.S={nightMode:n,meta:{_v736:{m}}};return n;}
function context(W=768){const log=[];let depth=0;const c={canvas:{width:W,height:844},log,depth:()=>depth,save(){depth++;},restore(){depth--;assert.ok(depth>=0);},measureText:text=>({width:String(text).length*5})};for(const method of ['beginPath','rect','clip','fillRect','moveTo','lineTo','stroke','fill','fillText','closePath'])c[method]=(...args)=>{args.filter(a=>typeof a==='number').forEach(a=>assert.ok(Number.isFinite(a),method));log.push([method,...args]);};return c;}
function freeze(o){if(o&&typeof o==='object'){Object.values(o).forEach(freeze);Object.freeze(o);}return o;}
test('profiles are distinct, frozen, and cover only the four late prison scenes',()=>{const r=boot(),p=r.TechOpsOrbitalStaging.PROFILES;assert.deepEqual(Object.keys(p),['4','5','6','7']);assert.equal(new Set(Object.values(p).map(p=>p.id)).size,4);assert.ok(Object.isFrozen(p)&&Object.values(p).every(Object.isFrozen));});
test('stage geometry and registry definitions are never changed by staging',()=>{const r=boot();for(let m=4;m<=7;m++){const n=scene(r,m),before=JSON.stringify(r.TechOpsLevelRegistry.goodDogsMission(m));r.TechOpsOrbitalStaging.layout(n);assert.equal(JSON.stringify(r.TechOpsLevelRegistry.goodDogsMission(m)),before);}});
test('every referenced source frame exists in the approved manifest',()=>{const r=boot(),atlas=JSON.parse(fs.readFileSync('assets/handoff/atlas.json','utf8'));for(let m=4;m<=7;m++){const n=scene(r,m);for(const item of r.TechOpsOrbitalStaging.layout(n).items){assert.ok(atlas.atlases.prison.frames[item.frame]);assert.ok([.28,.55,.65,.72,.85,1].includes(item.depth));assert.ok(item.height>0&&item.height<=190);}}});
test('M4 consoles follow the real four clue positions rather than three legacy decorative markers',()=>{const r=boot(),n=scene(r,4);n._v736.evidence[0].found=true;const items=r.TechOpsOrbitalStaging.layout(n).items.filter(i=>i.frame===8);assert.deepEqual(Array.from(items,i=>i.x),[500,800,1100,1400]);assert.equal(items[0].alpha,.45);assert.equal(items[1].alpha,1);});
test('M4 old saves without evidence use registry consoles without inventing new evidence',()=>{const r=boot(),n=scene(r,4);delete n._v736.evidence;const items=r.TechOpsOrbitalStaging.layout(n).items;assert.equal(items.filter(i=>i.frame===8).length,3);assert.equal(n._v736.evidence,undefined);});
test('malformed or excessive evidence cannot create unbounded placements',()=>{const r=boot(),n=scene(r,4);n._v736.evidence=Array.from({length:10000},(_,x)=>({x}));assert.equal(r.TechOpsOrbitalStaging.layout(n).items.length,10);assert.equal(r.TechOpsOrbitalStaging.layout(n).items.filter(i=>i.frame===8).length,4);});
test('M5 access console and exit align with registry gameplay anchors',()=>{const r=boot(),n=scene(r,5),s=r.TechOpsOrbitalStaging.layout(n);assert.equal(s.items.find(i=>i.frame===8).x,1070);assert.equal(s.items.find(i=>i.frame===3).x,1480);});
test('M6 uplink uses the actual runtime position; cell remains at registry position',()=>{const r=boot(),n=scene(r,6);n._v736.uplink={x:430,hp:100};const s=r.TechOpsOrbitalStaging.layout(n);assert.equal(s.items.find(i=>i.frame===8).x,430);assert.equal(s.items.find(i=>i.frame===0).x,1360);});
test('M7 shuttle entrance aligns with canonical registry instead of an invented destination',()=>{const r=boot(),n=scene(r,7);assert.equal(r.TechOpsOrbitalStaging.layout(n).items.find(i=>i.frame===3).x,1580);});
test('ordinary streets, Sector 04, M1-M3 and M8 retain existing environment owners',()=>{const r=boot(),a=r.TechOpsOrbitalStaging;for(const m of [1,2,3,8])assert.equal(a.layout(scene(r,m)),null);const n=scene(r,4);delete n._v736;n.district='industrial';assert.equal(a.layout(n),null);n._sector04={};assert.equal(a.layout(n),null);});
test('Day state and a stale mission mirror cannot draw prison layers',()=>{const r=boot(),n=scene(r,4);r.S.nightMode=false;assert.equal(r.TechOpsOrbitalStaging.layout(n),null);r.S.nightMode=n;r.S.meta._v736.m=7;assert.equal(r.TechOpsOrbitalStaging.layout(n),null);});
test('all compositions are deterministic and accept frozen campaign/runtime state',()=>{const r=boot();for(let m=4;m<=7;m++){const n=scene(r,m);freeze(n);freeze(r.S);const before=JSON.stringify(r.S),a=r.TechOpsOrbitalStaging,one=JSON.stringify(a.layout(n));for(let i=0;i<10;i++){assert.equal(JSON.stringify(a.layout(n)),one);a.draw(context(),n,'back',1000,()=>true);}assert.equal(JSON.stringify(r.S),before);}});
test('failed source decode retains the background and reports no decoded success',()=>{const r=boot(),n=scene(r,4),ctx=context();assert.equal(r.TechOpsOrbitalStaging.draw(ctx,n,'back',0,()=>false),true);assert.equal(r.__orbitalStagingEvidence.decodedDraws,0);assert.equal(r.__orbitalStagingEvidence.finalArt,false);assert.equal(ctx.depth(),0);});
test('successful source calls are culled and bounded by viewport and layout',()=>{const r=boot(),n=scene(r,6),ctx=context(390),draws=[];r.TechOpsOrbitalStaging.draw(ctx,n,'back',0,(...a)=>{draws.push(a);return true;});assert.ok(draws.length>0&&draws.length<=8);assert.ok(draws.every(d=>d[1]==='prison'));assert.ok(ctx.log.length<35);assert.equal(r.__orbitalStagingEvidence.decodedDraws,draws.length);assert.equal(ctx.depth(),0);});
test('camera culling drops all offscreen approved props rather than repeatedly drawing them',()=>{const r=boot(),n=scene(r,5);n.cam=50000;let draws=0;r.TechOpsOrbitalStaging.draw(context(),n,'back',1000,()=>{draws++;return true;});assert.equal(draws,0);});
test('foreground treatment is below feet and bounded',()=>{const r=boot(),n=scene(r,7),ctx=context(390);r.TechOpsOrbitalStaging.draw(ctx,n,'front',0,()=>{throw Error('front must not cover actor with source props');});assert.ok(ctx.log.filter(i=>i[0]==='fillRect').every(i=>i[2]>=430));assert.ok(ctx.log.length<10);});
test('opened lighting requires recorded mission outcome, never an empty room or x position',()=>{const r=boot();for(const [m,key] of [[4,'cellOpened'],[5,'_gbAccessNodeSeized'],[6,'_gbWaldoFreed'],[7,'_gbWardenTandemDefeated']]){const n=scene(r,m);n.x=1750;r.TechOpsOrbitalStaging.draw(context(),n,'back',0,()=>true);assert.equal(r.__orbitalStagingEvidence.opened,false);n._v736[key]=true;r.TechOpsOrbitalStaging.draw(context(),n,'back',0,()=>true);assert.equal(r.__orbitalStagingEvidence.opened,true);}});
test('reduced motion produces identical drawing commands at different wall-clock times',()=>{const r=boot(),n=scene(r,4);r.matchMedia=()=>({matches:true});const a=context(),b=context();r.TechOpsOrbitalStaging.draw(a,n,'back',0,()=>true);r.TechOpsOrbitalStaging.draw(b,n,'back',900,()=>true);assert.deepEqual(a.log,b.log);});
test('landmarks do not cover source art with the old 116x96 opaque panel',()=>{const r=boot(),n=scene(r,4),ctx=context();r.TechOpsOrbitalStaging.drawLandmark(ctx,n,{x:800,label:'CELL 118',kind:'cell118'});assert.ok(!ctx.log.some(l=>l[0]==='fillRect'&&l[3]===116&&l[4]===96));assert.ok(ctx.log.some(l=>l[0]==='fillText'));assert.equal(ctx.depth(),0);});
test('labels yield to nearby airborne actor and avoid unconfirmed identity',()=>{const r=boot(),n=scene(r,5),ctx=context();n.x=760;n.y=200;n.onGround=false;r.TechOpsOrbitalStaging.drawLandmark(ctx,n,{x:760,label:'K',kind:'k'});assert.equal(ctx.log.length,0);n.onGround=true;r.TechOpsOrbitalStaging.drawLandmark(ctx,n,{x:760,label:'K',kind:'k'});assert.ok(ctx.log.some(l=>l[0]==='fillText'&&l[1]==='PRISONER'));});
test('canvas state is restored if an asset renderer fails',()=>{const r=boot(),n=scene(r,4),ctx=context();assert.throws(()=>r.TechOpsOrbitalStaging.draw(ctx,n,'back',0,()=>{throw Error('draw failure');}),/draw failure/);assert.equal(ctx.depth(),0);});
test('the existing cinematic renderer calls new staging without new draw/step wrappers',()=>{const r=boot(),n=scene(r,5),ctx=context();r.TechOpsArtHandoff.drawEnvironment(ctx,n,'back',1000);assert.equal(r.__orbitalStagingEvidence.level,'gooddogs.m5');assert.equal(r.__techOpsLayerEvidence.level,'gooddogs.m5');const source=fs.readFileSync('orbital_scene_staging.js','utf8');assert.doesNotMatch(source,/requestAnimationFrame|setInterval|setTimeout|drawNM\s*=|stepNM\s*=/);assert.match(fs.readFileSync('good_boys_gameplay_loop.js','utf8'),/staging\.drawLandmark/);});

test('decoded-only backdrop replaces baked landmark boxes without changing gameplay geometry',()=>{const r=boot(),n=scene(r,4),ctx=context(),api=r.TechOpsOrbitalStaging;assert.equal(api.drawBackdrop(ctx,n),false);assert.equal(ctx.log.length,0);r.TechOpsArtHandoff.image=()=>({complete:true,naturalWidth:1344});assert.equal(api.drawBackdrop(ctx,n),true);assert.ok(ctx.log.filter(x=>x[0]==='fillRect').length<70);assert.equal(ctx.depth(),0);assert.equal(n._v736.cellOpened,undefined);});
test('opened prisoner doors use the paired open source frame at the real interaction entrance',()=>{const r=boot(),n=scene(r,4);n._v736.cellOpened=true;assert.ok(r.TechOpsOrbitalStaging.layout(n).items.some(i=>i.frame===1&&i.x===1600));const n6=scene(r,6);n6._v736._gbWaldoFreed=true;assert.ok(r.TechOpsOrbitalStaging.layout(n6).items.some(i=>i.frame===1&&i.x===1360));});
test('cell art and objective follow the same runtime-width projection after registry initialization',()=>{const r=boot(),n=scene(r,4);n._v736.evidence.forEach(e=>e.found=true);r.NM_W=2200;assert.equal(r.TechOpsOrbitalStaging.layout(n).items.find(i=>i.frame===0).x,2000);assert.equal(r.TechOpsGameplayExperience.objective(n).targetX,2000);assert.equal(n._v736.cellOpened,undefined);});
test('offscreen target labels do not impersonate a visible target at the viewport edge',()=>{const r=boot(),n=scene(r,6),ctx=context(390);r.TechOpsOrbitalStaging.drawLandmark(ctx,n,{x:n.cam+450,label:'CELL 1984',kind:'cell1984'});assert.equal(ctx.log.length,0);r.TechOpsOrbitalStaging.drawLandmark(ctx,n,{x:n.cam-30,label:'UPLINK',kind:'console'});assert.equal(ctx.log.length,0);});
test('structural supports are anchored to existing platforms without changing geometry',()=>{const r=boot(),n=scene(r,4),ctx=context(390);n.platforms=[{x:550,y:310,w:150}];freeze(n);const before=JSON.stringify(n);r.TechOpsOrbitalStaging.draw(ctx,n,'back',0,()=>true);assert.ok(ctx.log.some(c=>c[0]==='fillRect'&&c[1]===58&&c[2]===322&&c[3]===10&&c[4]===108));assert.equal(JSON.stringify(n),before);});
test('excessive platform fixtures cannot create unbounded scenery work',()=>{const r=boot(),n=scene(r,4),ctx=context(390);n.platforms=Array.from({length:10000},()=>({x:550,y:310,w:150}));r.TechOpsOrbitalStaging.draw(ctx,n,'back',0,()=>true);assert.ok(ctx.log.length<100);});
test('distinct detention and shuttle scenery remains deterministic at portrait and desktop sizes',()=>{const r=boot();r.TechOpsArtHandoff.image=()=>({complete:true,naturalWidth:1344});for(const W of [390,1280]){const n4=scene(r,4),a=context(W),b=context(W);r.TechOpsOrbitalStaging.drawBackdrop(a,n4);r.TechOpsOrbitalStaging.drawBackdrop(b,n4);assert.deepEqual(a.log,b.log);const n7=scene(r,7),c=context(W);r.TechOpsOrbitalStaging.drawBackdrop(c,n7);assert.notDeepEqual(a.log,c.log);assert.ok(a.log.length<220&&c.log.length<220);}});
test('staging has no authority over the existing M5 3D renderer',()=>{const source=fs.readFileSync('orbital_scene_staging.js','utf8');assert.doesNotMatch(source,/TechOpsGoodDogs3D|\.eligible\s*=|\.setQuality\s*=/);const three=fs.readFileSync('good_dogs_3d_presentation.js','utf8');assert.match(three,/Number\(c\.m\)===5/);});
console.log('Orbital scene staging: '+tests+' tests passed');
