'use strict';
const assert=require('node:assert/strict');
const {boot,shift,close,tuesday,freeze,current,finish,plain,SHIPPING,PLATING,ACCESS}=require('./test_helpers/gameplay_fixture');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
for(const id of [SHIPPING,PLATING])for(const verification of ['strong','partial'])for(const outcome of ['restored','degraded','unmet'])test(id+' '+verification+'/'+outcome+' has an evidence-appropriate next shift',()=>{
 const b=boot(),s=shift(b);close(b,s,id,verification,outcome);tuesday(b,s);
 const record=current(b,s,id),kind=outcome!=='restored'?'restore':verification==='strong'?'stable':'recheck';assert.equal(record.kind,kind);
 if(kind==='stable'){assert.equal(record.phase,'complete');assert.throws(()=>b.C.performWorkdayFollowup(s,id,'observe','requester'),/no separate/);}
 else {const original=JSON.stringify({tickets:s.tickets,evidence:s.evidence,verification:s.verificationHistory,outcomes:s.humanOutcomes,assignments:s.assignments});const result=finish(b,s,id);assert.equal(result.phase,'complete');assert.equal(result.result.humanOutcome,'restored');assert.equal(result.result.ownerId,'mike');assert.equal(JSON.stringify({tickets:s.tickets,evidence:s.evidence,verification:s.verificationHistory,outcomes:s.humanOutcomes,assignments:s.assignments}),original);}
});
test('Day 1 cannot create next-shift state or expose handoff observations',()=>{const b=boot(),s=shift(b);const before=JSON.stringify(s);assert.equal(b.C.workdayHandoff(freeze(s)).length,0);assert.throws(()=>b.C.performWorkdayFollowup(s,SHIPPING,'observe','requester'),/Tuesday/);assert.equal(JSON.stringify(s),before);});
test('untouched tickets carry over without being closed or re-randomized',()=>{const b=boot(),s=tuesday(b,shift(b));assert.equal(current(b,s,SHIPPING).kind,'carryover');assert.equal(s.tickets[SHIPPING],undefined);assert.throws(()=>b.C.performWorkdayFollowup(s,SHIPPING,'observe','requester'),/no separate/);});
test('Impossible Access never enters ordinary recurrence or changes provenance',()=>{const b=boot(),s=tuesday(b,shift(b)),before=JSON.stringify(s);assert.deepEqual(plain(b.C.workdayHandoff(s).map(x=>x.ticketId)),[SHIPPING,PLATING]);assert.throws(()=>b.C.performWorkdayFollowup(s,ACCESS,'observe','requester'),/Unknown ordinary/);assert.equal(JSON.stringify(s),before);});
test('repeating Tuesday cannot reset work, duplicate history or rewind later chapters',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial');tuesday(b,s);finish(b,s,SHIPPING);s.campaign.day=4;s.campaign.chapter='later_chapter';s.night.position={x:10};const before=JSON.stringify(s);b.C.transitionToTuesday(s);assert.equal(JSON.stringify(s),before);});
test('migrated Tuesday saves expose a read-only deterministic handoff',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial');tuesday(b,s);delete s.workdayContinuity;const before=JSON.stringify(s);const read=b.C.workdayHandoff(freeze(plain(s)));assert.equal(read[0].kind,'recheck');assert.equal(JSON.stringify(s),before);b.C.performWorkdayFollowup(s,SHIPPING,'observe','requester');assert.ok(s.workdayContinuity.day2);});
test('rejected actions are atomic, including before lazy migration',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial','degraded');tuesday(b,s);delete s.workdayContinuity;for(const [action,value] of [['hypothesis','shift_access_gap'],['verify_requester'],['technical_check'],['remediate'],['observe','fake'],['fake']]){const before=JSON.stringify(s);assert.throws(()=>b.C.performWorkdayFollowup(s,SHIPPING,action,value));assert.equal(JSON.stringify(s),before);}});
test('history review does not count as an independent technical observation',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial');tuesday(b,s);b.C.performWorkdayFollowup(s,SHIPPING,'observe','requester');b.C.performWorkdayFollowup(s,SHIPPING,'observe','handoff');assert.throws(()=>b.C.performWorkdayFollowup(s,SHIPPING,'hypothesis','confirm_real_work'),/both required/);});
test('every follow-up phase round-trips through the canonical save key',()=>{const b=boot();let s=shift(b);close(b,s,PLATING,'partial','unmet');tuesday(b,s);for(const [a,v,p] of [['observe','requester','gather'],['observe','technical','gather'],['hypothesis','startup_dependency_gap','remediate'],['remediate',null,'technical_check'],['technical_check',null,'human_verify'],['verify_requester',null,'complete']]){b.C.performWorkdayFollowup(s,PLATING,a,v);b.C.save(s,b.store);const reboot=boot(b.store);s=reboot.C.load(b.store);assert.equal(current(reboot,s,PLATING).phase,p);}assert.deepEqual([...b.store.data.keys()],[b.C.SAVE_KEY]);});
test('duplicate evidence, hypotheses, fixes, checks and closure cannot farm history',()=>{const b=boot(),s=shift(b);close(b,s,PLATING,'partial','degraded');tuesday(b,s);for(const [a,v] of [['observe','requester'],['observe','technical'],['hypothesis','startup_dependency_gap'],['remediate'],['technical_check'],['verify_requester']]){b.C.performWorkdayFollowup(s,PLATING,a,v);const before=JSON.stringify(s);b.C.performWorkdayFollowup(s,PLATING,a,v);assert.equal(JSON.stringify(s),before);}});
test('unsupported hypotheses are nonterminal and do not spam rejection history',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial');tuesday(b,s);for(const key of ['requester','technical'])b.C.performWorkdayFollowup(s,SHIPPING,'observe',key);b.C.performWorkdayFollowup(s,SHIPPING,'hypothesis','assume_recurrence');assert.equal(current(b,s,SHIPPING).phase,'gather');const before=JSON.stringify(s);b.C.performWorkdayFollowup(s,SHIPPING,'hypothesis','assume_recurrence');assert.equal(JSON.stringify(s),before);finish(b,s,SHIPPING);assert.equal(current(b,s,SHIPPING).phase,'complete');});
test('reviewing new observations cannot undo a supported remediation',()=>{const b=boot(),s=shift(b);close(b,s,PLATING,'partial','degraded');tuesday(b,s);for(const k of ['requester','technical'])b.C.performWorkdayFollowup(s,PLATING,'observe',k);b.C.performWorkdayFollowup(s,PLATING,'hypothesis','startup_dependency_gap');b.C.performWorkdayFollowup(s,PLATING,'remediate');b.C.performWorkdayFollowup(s,PLATING,'observe','handoff');assert.equal(current(b,s,PLATING).phase,'technical_check');assert.throws(()=>b.C.performWorkdayFollowup(s,PLATING,'hypothesis','replace_hardware'),/cannot be replaced/);});
test('conflicting old outcomes remain conflicting in history after a new confirmed outcome',()=>{const b=boot(),s=shift(b);close(b,s,PLATING);s.humanOutcomes[PLATING]='degraded';tuesday(b,s);assert.equal(current(b,s,PLATING).kind,'reconcile');finish(b,s,PLATING);assert.equal(s.tickets[PLATING].humanOutcome,'restored');assert.equal(s.humanOutcomes[PLATING],'degraded');assert.equal(b.N.ticketRecord(s,PLATING).conflict,true);assert.equal(b.N.currentServiceRecord(s,PLATING).status,'VERIFIED / RESTORED');});
test('verified carryover completion uses its original investigation and owner',()=>{const b=boot(),s=tuesday(b,shift(b));close(b,s,PLATING);const record=current(b,s,PLATING);assert.equal(record.kind,'carryover');assert.equal(record.phase,'complete');assert.equal(record.result.ownerId,'amit');assert.equal(record.result.fromCarryover,true);});
test('handoff copy cannot mutate the persisted snapshot',()=>{const b=boot(),s=shift(b);close(b,s,SHIPPING,'partial');tuesday(b,s);const before=JSON.stringify(s);const copy=b.C.workdayHandoff(freeze(s));copy[0].phase='complete';copy[0].source.verification='strong';assert.equal(JSON.stringify(s),before);});
console.log('Workday follow-up contracts: '+count+' tests passed');
