"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm");
const src=fs.readFileSync("night_mobile_visual_cohesion.js","utf8"),boot=fs.readFileSync("production_bootstrap.js","utf8");
assert.doesNotThrow(()=>new Function(src),"Night mobile cohesion source must parse");
assert.ok(src.includes("grid-template-columns:repeat(3,52px)"),"Night actions must collapse to a compact three-column layout");
assert.ok(src.includes("#touch-buttons #tb-interact"),"Night context/punch control must receive a scoped compact size");
assert.ok(src.includes("#dpad{left:max(12px"),"Night d-pad must use the compact coarse-pointer layout");
assert.ok(src.includes("#toast{top:auto"),"Night tutorial toast must move out of the gameplay focal area");
assert.ok(src.includes("E PUNCH · J KICK · G GRAB · SPACE JUMP · ↑/↓ AIM"),"Night mobile tutorial must use the compact control hint");
assert.ok(src.includes("MutationObserver"),"Night mobile presentation must follow runtime ownership without another polling timer");
assert.ok(boot.includes('"night_mobile_visual_cohesion.js"'),"Production bootstrap must load Night mobile cohesion after Night input");
assert.ok(/VERSION=35/.test(boot),"Production bootstrap must cache-bump the Night mobile presentation change");
console.log("Night mobile visual contract: PASS");
