'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {boot,shift,close,tuesday,click,finish,freeze,plain,SHIPPING,PLATING,ACCESS}=require('./test_helpers/gameplay_fixture.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function prepared(){const b=boot(),s=shift(b);b.N.ensureWorld();return {b,s};}
function pin(b,id=SHIPPING){assert.equal(b.N.trackTicket(id),true);return b.C.load(b.store);}
function route(b,s){return b.N.taskFocus(s||b.C.load(b.store),b.r.S);}
function history(s){return plain({tickets:s.tickets,evidence:s.evidence,history:s.history,investigations:s.investigations||{},humanOutcomes:s.humanOutcomes});}
function clock(b){let at=1000;b.r.Date={now:()=>at};return v=>{at=v;};}
function waypoint(b){b.r.window=b.r;const src=fs.readFileSync('v713_hooks.js','utf8');vm.runInContext(src.slice(src.indexOf('  function bfs713'),src.indexOf('  let _objKey')),b.r,{filename:'v713-waypoint-real-source'});return {target:()=>b.r.objective713(),path:(sx,sy,tx,ty)=>b.r.bfs713(sx,sy,tx,ty)};}

test('reading the casebook does not silently pin a task or write progress',()=>{const {b,s}=prepared(),writes=b.store.writes;b.N.openTicketRecord(SHIPPING);assert.equal(b.store.writes,writes);assert.equal(s.presentation,undefined);assert.equal(route(b,s),null);assert.equal(b.r.dialog.options.filter(x=>x.t==='Track this case on the Day map').length,1);});
test('real casebook callback pins only a presentation preference and returns to world',()=>{const {b}=prepared(),before=b.C.load(b.store),original=history(before);b.N.openTicketRecord(SHIPPING);click(b,'Track this case on the Day map');const after=b.C.load(b.store);assert.equal(after.presentation.trackedTicketId,SHIPPING);assert.equal(b.r.S.inDialog,false);assert.equal(b.r.S.clock,540);assert.deepEqual(history(after),original);assert.equal(route(b).ticketId,SHIPPING);});
test('pin and unpin are idempotent and preserve unrelated presentation preferences',()=>{const {b,s}=prepared();s.presentation={textScale:1.2};b.C.save(s,b.store);pin(b);const writes=b.store.writes;pin(b);assert.equal(b.store.writes,writes);assert.equal(b.C.load(b.store).presentation.textScale,1.2);b.N.openTicketRecord(SHIPPING);click(b,'Stop tracking this case');assert.equal(route(b),null);const end=b.store.writes;b.N.trackTicket(null);assert.equal(b.store.writes,end);});
test('switching a pin replaces rather than accumulates destinations',()=>{const {b}=prepared();pin(b);pin(b,PLATING);assert.equal(route(b).ticketId,PLATING);assert.deepEqual(plain(b.C.load(b.store).presentation),{trackedTicketId:PLATING});});
test('the route targets the real contact position and follows contact movement',()=>{const {b}=prepared(),s=pin(b),npc=b.r.S.npcs.find(n=>n.id===b.N.CONTACTS.shipping.id);npc.x=22;npc.y=8;assert.equal(route(b,s).x,22);assert.equal(route(b,s).y,8);npc.x=23;assert.equal(route(b,s).x,23);});
test('missing, malformed or off-map contact coordinates never get guessed',()=>{for(const position of [{x:-1,y:4},{x:1.5,y:4},{x:99,y:4},{x:4,y:99},{x:NaN,y:4}]){const {b}=prepared(),s=pin(b);Object.assign(b.r.S.npcs.find(n=>n.id===b.N.CONTACTS.shipping.id),position);assert.equal(route(b,s),null);}const {b}=prepared(),s=pin(b);b.r.S.npcs=[];assert.equal(route(b,s),null);});
test('route phase follows the real investigation through supported repair and verification',()=>{const {b}=prepared(),s=pin(b);assert.equal(route(b,s).phase,'gather');b.I.recordEvidence(s,SHIPPING,'queue_trace');b.I.recordEvidence(s,SHIPPING,'compare_user');b.I.chooseHypothesis(s,SHIPPING,'permissions');assert.equal(route(b,s).phase,'remediate');assert.match(route(b,s).label,/SUPPORTED FIX/);b.I.applyFix(s,SHIPPING);assert.equal(route(b,s).phase,'technical_check');b.I.runTechnicalCheck(s,SHIPPING);assert.equal(route(b,s).phase,'human_verify');b.I.verifyHumanOutcome(s,SHIPPING);assert.equal(route(b,s),null);});
test('a temporary-workaround pin points to the real verification step, not a final fix',()=>{const {b}=prepared(),s=pin(b);b.I.recordEvidence(s,SHIPPING,'queue_trace');b.I.recordEvidence(s,SHIPPING,'compare_user');b.I.chooseHypothesis(s,SHIPPING,'permissions');b.I.applyWorkaround(s,SHIPPING);assert.equal(route(b,s).phase,'workaround_verify');assert.match(route(b,s).label,/TEST WORKAROUND/);b.I.verifyWorkaroundOutcome(s,SHIPPING);assert.equal(route(b,s),null);});
test('recording badge evidence removes access guidance without inventing a solved case',()=>{const {b}=prepared(),s=pin(b,ACCESS);assert.match(route(b,s).label,/REVIEW ACCESS/);b.C.recordGhostEvidence(s,{id:'badge_impossible_access',perspective:'delegated_partial',discoveredBy:'security'});assert.equal(route(b,s),null);assert.equal(s.tickets[ACCESS],undefined);});
test('a cold reload restores only the saved pin and derives the phase again',()=>{const {b}=prepared();pin(b,PLATING);const cold=boot(b.store);cold.N.ensureWorld();const writes=b.store.writes;assert.equal(cold.N.worldObjective().ticketId,PLATING);assert.equal(cold.N.worldObjective().phase,'gather');assert.equal(b.store.writes,writes);});
test('Night, battles, pause, dialogs, rooms, game over and clock-out suppress the map guide',()=>{for(const [key,value] of [['nightMode',{}],['inBattle',true],['paused',true],['inDialog',true],['room',{}],['gameOver',true],['clock',960]]){const {b}=prepared(),s=pin(b);b.r.S[key]=value;assert.equal(route(b,s),null,key);assert.equal(b.N.worldObjective(),null,key);}});
test('day mismatch, hidden page and later campaigns cannot show a stale Day 1 pin',()=>{const {b}=prepared(),s=pin(b);b.r.S.day=2;assert.equal(route(b,s),null);b.r.S.day=1;s.campaign.day=3;assert.equal(route(b,s),null);b.r.document={hidden:true};assert.equal(b.N.worldObjective(),null);});
test('Tuesday rechecks preserve the pin but derive the follow-up stage',()=>{const {b}=prepared(),s=pin(b);close(b,s,SHIPPING,'partial','restored');tuesday(b,s);b.N.ensureWorld();assert.equal(route(b,s).phase,'gather');b.C.performWorkdayFollowup(s,SHIPPING,'observe','requester');b.C.performWorkdayFollowup(s,SHIPPING,'observe','technical');const rec=b.C.workdayHandoff(s).find(r=>r.ticketId===SHIPPING);b.C.performWorkdayFollowup(s,SHIPPING,'hypothesis',b.C.followupDefinition(rec).correctHypothesis);assert.equal(route(b,s).phase,'human_verify');b.C.performWorkdayFollowup(s,SHIPPING,'verify_requester');assert.equal(route(b,s),null);assert.equal(s.tickets[SHIPPING].verification,'partial');});
test('Tuesday service repairs have a reachable track action with immutable Day 1 history',()=>{const {b,s}=prepared();close(b,s,SHIPPING,'partial','degraded');tuesday(b,s);b.N.ensureWorld();const original=history(s);b.N.openWorkdayFollowup(SHIPPING);click(b,'Track this case on the Day map');const tracked=b.C.load(b.store);assert.equal(route(b,tracked).phase,'gather');assert.deepEqual(history(tracked),original);finish(b,tracked,SHIPPING);assert.equal(route(b,tracked),null);assert.equal(tracked.tickets[SHIPPING].humanOutcome,'degraded');});
test('verified restoration carried into Tuesday creates no artificial route or recurrence',()=>{const {b}=prepared(),s=pin(b);close(b,s,SHIPPING);tuesday(b,s);b.N.ensureWorld();assert.equal(route(b,s),null);b.N.openWorkdayFollowup(SHIPPING);assert.ok(!b.r.dialog.options.some(o=>o.t==='Track this case on the Day map'));});
test('unfinished Day 1 investigations keep their actual phase after the Tuesday handoff',()=>{const {b}=prepared(),s=pin(b);b.I.recordEvidence(s,SHIPPING,'queue_trace');b.I.recordEvidence(s,SHIPPING,'compare_user');b.I.chooseHypothesis(s,SHIPPING,'permissions');tuesday(b,s);b.N.ensureWorld();assert.equal(route(b,s).phase,'remediate');assert.match(route(b,s).label,/SUPPORTED FIX/);});
test('completed, unassigned and prototype-shaped task IDs are refused without save writes',()=>{for(const id of ['__proto__','constructor','missing',undefined]){const {b}=prepared(),before=b.store.writes;assert.equal(b.N.trackTicket(id),false);assert.equal(b.store.writes,before);}const {b,s}=prepared();close(b,s,SHIPPING);b.C.save(s,b.store);const writes=b.store.writes;assert.equal(b.N.trackTicket(SHIPPING),false);assert.equal(b.store.writes,writes);b.C.save(b.C.createInitialState(),b.store);assert.equal(b.N.trackTicket(SHIPPING),false);});
test('save corruption and write failure do not overwrite or manufacture a tracked preference',()=>{const {b}=prepared();b.store.setItem(b.C.SAVE_KEY,'{bad');const writes=b.store.writes;assert.equal(b.N.trackTicket(SHIPPING),false);assert.equal(b.N.worldObjective(),null);assert.equal(b.store.writes,writes);assert.equal(b.store.getItem(b.C.SAVE_KEY),'{bad');const {b:good}=prepared();const before=good.store.getItem(good.C.SAVE_KEY);good.store.setItem=()=>{throw Error('quota');};assert.equal(good.N.trackTicket(SHIPPING),false);assert.match(good.r.dialog.name,/TRACKING UNAVAILABLE/);assert.equal(good.store.getItem(good.C.SAVE_KEY),before);});
test('read models work on frozen state and never add investigation or history entries',()=>{const {b}=prepared(),s=pin(b),before=JSON.stringify(s);freeze(s);freeze(b.r.S);for(let i=0;i<50;i++)assert.equal(route(b,s).ticketId,SHIPPING);assert.equal(JSON.stringify(s),before);});
test('live waypoint lookups are bounded, external writes refresh, and local pins invalidate immediately',()=>{const {b}=prepared();pin(b);const setTime=clock(b);let reads=0;const get=b.store.getItem.bind(b.store);b.store.getItem=k=>{reads++;return get(k);};for(let i=0;i<200;i++)b.N.worldObjective();assert.equal(reads,1);const s=b.C.load(b.store);s.presentation.trackedTicketId=PLATING;b.C.save(s,b.store);setTime(1249);assert.equal(b.N.worldObjective().ticketId,SHIPPING);setTime(1250);assert.equal(b.N.worldObjective().ticketId,PLATING);pin(b);assert.equal(b.N.worldObjective().ticketId,SHIPPING);});
test('new run identity and backwards wall-clock changes invalidate the cached save',()=>{const {b}=prepared();pin(b);const setTime=clock(b);assert.ok(b.N.worldObjective());const s=b.C.load(b.store);s.presentation.trackedTicketId=PLATING;b.C.save(s,b.store);b.r.S={...b.r.S};assert.equal(b.N.worldObjective().ticketId,PLATING);s.presentation.trackedTicketId=SHIPPING;b.C.save(s,b.store);setTime(900);assert.equal(b.N.worldObjective().ticketId,SHIPPING);});
test('the actual legacy waypoint selector gives an explicit active case priority over procedural devices',()=>{const {b}=prepared();pin(b);const w=waypoint(b);b.r.S.npcs.push({id:'ticket',x:5,y:4,type:{label:'ordinary'}});b.r.S.devices=[{npc:'ticket',x:6,y:4,fixed:false}];assert.equal(w.target().ticketId,SHIPPING);b.N.trackTicket(null);assert.equal(w.target().kind,'device');});
test('legacy BFS routes around walls to the real contact and never moves the player',()=>{const {b}=prepared();pin(b);const npc=b.r.S.npcs.find(n=>n.id===b.N.CONTACTS.shipping.id);npc.x=8;npc.y=4;b.r.S.map[4][6]=1;const w=waypoint(b),target=w.target(),before=plain(b.r.S),path=w.path(4,4,target.x,target.y);assert.ok(path.length>3);for(const [x,y] of path)assert.equal(b.r.S.map[y][x],0);const end=path[path.length-1];assert.ok(Math.abs(end[0]-8)+Math.abs(end[1]-4)<=1);assert.deepEqual(plain(b.r.S),before);});
test('clock-out keeps the original way-home authority even with a persistent case pin',()=>{const {b}=prepared();pin(b);const w=waypoint(b);b.r.S.clock=960;assert.equal(w.target(),null);assert.equal(b.C.load(b.store).presentation.trackedTicketId,SHIPPING);});
test('classic-script state cannot expose an old window-world case target',()=>{const b=boot(undefined,{classicState:true});shift(b);b.N.ensureWorld();pin(b);vm.runInContext('S={nightMode:true};',b.r);assert.equal(b.N.worldObjective(),null);});
test('blocking presentation suppresses a case target without loading or changing progress',()=>{const {b}=prepared();pin(b);const before=b.store.getItem(b.C.SAVE_KEY);b.r.TechOpsPresentationDirector={isBlocking:()=>true};assert.equal(b.N.worldObjective(),null);assert.equal(b.store.getItem(b.C.SAVE_KEY),before);});
console.log(`Campaign task focus: ${passed} tests passed`);
