'use strict';
const assert=require('node:assert/strict');
const {boot,shift,close,click,freeze,SHIPPING,PLATING}=require('./test_helpers/gameplay_fixture');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function supported(b,s,id=SHIPPING){b.I.recordEvidence(s,id,id===SHIPPING?'printer_self_test':'local_login');b.I.recordEvidence(s,id,id===SHIPPING?'queue_trace':'integration_service');b.I.chooseHypothesis(s,id,id===SHIPPING?'permissions':'integration_failure');}
test('reading an absent investigation cannot create a store or history',()=>{const b=boot(),s=shift(b),before=JSON.stringify(s);assert.equal(b.I.getRecord(freeze(s),SHIPPING),null);assert.equal(JSON.stringify(s),before);});
test('reading a frozen present investigation is non-mutating',()=>{const b=boot(),s=shift(b);b.I.recordEvidence(s,SHIPPING,'queue_trace');const before=JSON.stringify(s);const r=b.I.getRecord(freeze(s),SHIPPING);r.evidence.push('other');assert.equal(JSON.stringify(s),before);});
test('insufficient evidence and unknown hypotheses cannot create history',()=>{const b=boot(),s=shift(b),before=JSON.stringify(s);assert.throws(()=>b.I.chooseHypothesis(s,SHIPPING,'permissions'));assert.throws(()=>b.I.chooseHypothesis(s,SHIPPING,'fake'));assert.equal(JSON.stringify(s),before);});
for(const id of [SHIPPING,PLATING])test(id+' needs the diagnostic clue, not just any two observations',()=>{const b=boot(),s=shift(b);const ids=id===SHIPPING?['printer_self_test','compare_user']:['local_login','controller_reachability'];ids.forEach(e=>b.I.recordEvidence(s,id,e));const before=JSON.stringify(s);const result=b.I.chooseHypothesis(s,id,id===SHIPPING?'permissions':'integration_failure');assert.equal(result.needsEvidence,true);assert.equal(JSON.stringify(s),before);b.I.recordEvidence(s,id,id===SHIPPING?'queue_trace':'integration_service');assert.equal(b.I.chooseHypothesis(s,id,id===SHIPPING?'permissions':'integration_failure').correct,true);});
test('reviewing an additional clue cannot regress technical validation',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyFix(s,SHIPPING);b.I.recordEvidence(s,SHIPPING,'compare_user');assert.equal(s.investigations[SHIPPING].phase,'technical_check');b.I.runTechnicalCheck(s,SHIPPING);b.I.recordEvidence(s,SHIPPING,'queue_trace');assert.equal(s.investigations[SHIPPING].phase,'human_verify');});
test('repeat fixes/checks/support cannot change the phase or history',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyFix(s,SHIPPING);b.I.runTechnicalCheck(s,SHIPPING);for(const run of [()=>b.I.applyFix(s,SHIPPING),()=>b.I.runTechnicalCheck(s,SHIPPING),()=>b.I.chooseHypothesis(s,SHIPPING,'permissions')]){const before=JSON.stringify(s);run();assert.equal(JSON.stringify(s),before);}});
test('a stale different hypothesis cannot replace remediation in progress',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyFix(s,SHIPPING);const before=JSON.stringify(s);assert.throws(()=>b.I.chooseHypothesis(s,SHIPPING,'network_path'),/cannot replace/);assert.equal(JSON.stringify(s),before);});
test('repeat rejected hypotheses do not spam history',()=>{const b=boot(),s=shift(b);b.I.recordEvidence(s,SHIPPING,'queue_trace');b.I.recordEvidence(s,SHIPPING,'printer_self_test');b.I.chooseHypothesis(s,SHIPPING,'network_path');const before=JSON.stringify(s);b.I.chooseHypothesis(s,SHIPPING,'network_path');assert.equal(JSON.stringify(s),before);});
test('the review screen offers resume, not a phase-resetting hypothesis path',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyFix(s,SHIPPING);b.C.save(s,b.store);b.I.openVerification(SHIPPING);click(b,'Review evidence');assert.ok(b.r.dialog.options.some(x=>x.t==='Resume current step'));assert.ok(!b.r.dialog.options.some(x=>x.t.startsWith('Form hypothesis')));click(b,'Resume current step');assert.match(b.r.dialog.name,/VERIFY TECHNICALLY/);});
test('double-tapping a stale closure callback is safe and awards no second closure',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyFix(s,SHIPPING);b.I.runTechnicalCheck(s,SHIPPING);b.C.save(s,b.store);b.I.openVerification(SHIPPING);const cb=b.r.dialog.options.find(x=>x.t==='Requester confirms restored').f;cb();const before=b.store.getItem(b.C.SAVE_KEY);assert.doesNotThrow(cb);assert.equal(b.store.getItem(b.C.SAVE_KEY),before);assert.equal(b.C.load(b.store).verificationHistory.length,1);});
test('an unloaded investigation module cannot turn world interaction into instant closure',()=>{const b=boot();shift(b);b.N.ensureWorld();b.N.install();b.r.TechOpsCampaignInvestigations=undefined;const p=b.r.S.meta.campaignAct1Native.shipping;b.r.S.px=p.x;b.r.S.py=p.y;b.r.interact();assert.equal(b.r.dialog.name,'INVESTIGATION UNAVAILABLE');assert.equal(b.C.load(b.store).tickets[SHIPPING],undefined);});
test('a malformed investigation cannot fall through to the legacy instant resolver',()=>{const b=boot(),s=shift(b);s.investigations={[SHIPPING]:{evidence:null,ruledOut:[]}};b.C.save(s,b.store);b.N.ensureWorld();b.N.install();b.I.install();const p=b.r.S.meta.campaignAct1Native.shipping;b.r.S.px=p.x;b.r.S.py=p.y;b.r.interact();assert.equal(b.r.dialog.name,'INVESTIGATION UNAVAILABLE');assert.equal(b.C.load(b.store).tickets[SHIPPING],undefined);});
test('a stale evidence callback after another closure rereads the record safely',()=>{const b=boot(),s=shift(b);b.I.openInvestigation(SHIPPING);click(b,'Begin investigation');const cb=b.r.dialog.options.find(x=>x.t==='Run printer self-test').f;const updated=b.C.load(b.store);close(b,updated,SHIPPING);b.C.save(updated,b.store);const before=b.store.getItem(b.C.SAVE_KEY);assert.doesNotThrow(cb);assert.equal(b.store.getItem(b.C.SAVE_KEY),before);});
test('temporary workarounds cannot bypass a supported hypothesis or real limited-service confirmation',()=>{const b=boot(),s=shift(b),before=JSON.stringify(s);assert.throws(()=>b.I.applyWorkaround(s,SHIPPING),/Supported hypothesis/);assert.throws(()=>b.I.verifyWorkaroundOutcome(s,SHIPPING),/Test the temporary/);assert.equal(JSON.stringify(s),before);supported(b,s);b.I.applyWorkaround(s,SHIPPING);assert.equal(s.tickets[SHIPPING],undefined);assert.equal(s.investigations[SHIPPING].phase,'workaround_verify');});
test('a confirmed workaround produces partial/degraded canonical closure, never full restoration',()=>{const b=boot(),s=shift(b);supported(b,s,PLATING);b.I.applyWorkaround(s,PLATING);b.I.verifyWorkaroundOutcome(s,PLATING);assert.equal(s.tickets[PLATING].verification,'partial');assert.equal(s.humanOutcomes[PLATING],'degraded');assert.equal(s.tickets[PLATING].ownerId,'amit');assert.equal(s.verificationHistory.at(-1).strength,'partial');});
test('reported restoration requires technical proof and stays partial',()=>{const b=boot(),s=shift(b);supported(b,s);assert.throws(()=>b.I.recordReportedOutcome(s,SHIPPING),/Technical check/);b.I.applyFix(s,SHIPPING);b.I.runTechnicalCheck(s,SHIPPING);b.I.recordReportedOutcome(s,SHIPPING);assert.equal(s.tickets[SHIPPING].verification,'partial');assert.equal(s.humanOutcomes[SHIPPING],'restored');assert.equal(s.investigations[SHIPPING].phase,'complete');});
test('temporary workaround verification resumes after a cold reload',()=>{const b=boot(),s=shift(b);supported(b,s,PLATING);b.I.applyWorkaround(s,PLATING);b.C.save(s,b.store);const fresh=boot(b.store);fresh.I.openInvestigation(PLATING);assert.match(fresh.r.dialog.name,/VERIFY LIMITED SERVICE/);assert.equal(fresh.C.load(fresh.store).tickets[PLATING],undefined);});
test('duplicate temporary workaround actions do not create extra history or change phase',()=>{const b=boot(),s=shift(b);supported(b,s);b.I.applyWorkaround(s,SHIPPING);const before=JSON.stringify(s);b.I.applyWorkaround(s,SHIPPING);assert.equal(JSON.stringify(s),before);assert.throws(()=>b.I.verifyHumanOutcome(s,SHIPPING),/Technical check/);assert.throws(()=>b.I.recordReportedOutcome(s,SHIPPING),/Technical check/);});
test('workaround preview can be declined without changing the saved investigation',()=>{const b=boot(),s=shift(b);supported(b,s);b.C.save(s,b.store);b.I.openRemediation(SHIPPING);const before=b.store.getItem(b.C.SAVE_KEY),writes=b.store.writes;click(b,'Use a temporary workaround and hand off');assert.match(b.r.dialog.body,/PARTIAL \/ DEGRADED/);click(b,'Continue full remediation');assert.equal(b.store.getItem(b.C.SAVE_KEY),before);assert.equal(b.store.writes,writes);assert.match(b.r.dialog.name,/REMEDIATE/);});
console.log('Investigation integrity: '+count+' tests passed');
