'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('night_session.js','utf8');let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function boot(){
 const elements=new Map(),classes=new Set();
 function element(id){const attrs=new Set();return {id,style:{},textContent:'',classList:{contains:k=>attrs.has(k),add:k=>attrs.add(k),remove:k=>attrs.delete(k)},children:[],setAttribute(){},appendChild(e){this.children.push(e);elements.set(e.id,e);},focus(){this.focused=true;},remove(){elements.delete(this.id);}};}
 const document={hidden:false,getElementById:id=>elements.get(id)||null,createElement:()=>element(''),body:{classList:{toggle(k,v){v?classes.add(k):classes.delete(k);}},appendChild(e){elements.set(e.id,e);}}};
 const r={console,document,S:{day:1,clock:1080,meta:{},inDialog:false},NM:{district:'downtown',done:{},x:100,w:22,street:1,enemies:[],cash:50,kills:2},keys:{arrowright:true},TechOpsNightOrder:['downtown','longwharf'],TechOpsNightDistricts:{downtown:{name:'DOWNTOWN',streets:2},longwharf:{name:'LONG WHARF',streets:2}},dlg(title,body,options){r.dialog={title,body,options};r.S.inDialog=true;},closeDlg(){r.S.inDialog=false;},exitNight(){r.exitCount=(r.exitCount||0)+1;r.api.settle(r.NM,r.S,true);r.S.nightMode=null;r.NM=null;}};r.S.nightMode=r.NM;vm.runInNewContext(source,r);r.api=r.TechOpsNightSession;return {r,api:r.api,elements,element,classes};
}
test('night time flows independently of render cadence and never ages office tickets',()=>{for(const dt of [.016,.05,.1,.25]){const {r,api}=boot();r.S.tickets=[{age:30}];for(let t=0;t<8-1e-8;t+=dt)api.tick(r.NM,r.S,dt);assert.equal(r.S.clock,1082);assert.equal(r.S.tickets[0].age,30);assert.equal(api.session(r.NM).elapsedMinutes,2);}});
test('hidden tabs, dialogs, battles, settings and panels pause clock and input',()=>{for(const mode of ['hidden','dialog','battle','panel','v67-settings']){const {r,api,elements,element}=boot();if(mode==='hidden')r.document.hidden=true;else if(mode==='dialog')r.S.inDialog=true;else if(mode==='battle')r.S.inBattle=true;else elements.set(mode,element(mode));for(let i=0;i<100;i++)assert.equal(api.tick(r.NM,r.S,.1),true);assert.equal(r.S.clock,1080);assert.equal(r.keys.arrowright,false);}});
test('long suspension frames, NaN and negatives never advance simulation clock',()=>{const {r,api}=boot();for(const dt of [60,1,NaN,Infinity,-4])api.tick(r.NM,r.S,dt);assert.equal(r.S.clock,1080);assert.equal(api.session(r.NM).seconds,0);});
test('Good Dogs, Sector 04 and Waldo keep their own session rules',()=>{for(const patch of [{_v736:{}},{_sector04:{}},{district:'waldo'}]){const {r,api}=boot();Object.assign(r.NM,patch);assert.equal(api.tick(r.NM,r.S,5),false);assert.equal(r.NM._nightSession,undefined);assert.equal(api.requestHome(r.NM),false);}});
test('home choice is cancellable and creates no reward before confirmation',()=>{const {r,api}=boot();r.NM.district='home';r.NM.x=1600;assert.equal(api.requestHome(r.NM),true);assert.equal(r.dialog.options[0].t,'Rest until morning');r.dialog.options[1].f();assert.equal(r.S.inDialog,false);assert.equal(r.exitCount,undefined);assert.equal(api.session(r.NM).settled,false);assert.equal(r.NM.vx,0);});
test('cinematic skip and automatic finish settle exactly once without input leakage',()=>{for(const skip of [false,true]){const {r,api,elements,classes}=boot();r.NM.district='home';const n=r.NM;api.requestHome(n);r.dialog.options[0].f();assert.equal(r.S.inDialog,true);assert.ok(elements.has('night-home-transition'));if(skip)elements.get('night-home-transition').children[0].onclick();else for(let i=0;i<40;i++)api.tick(n,r.S,.1);assert.equal(r.exitCount,1);assert.equal(api.finishHome(n),false);assert.equal(api.settle(n,r.S,true),false);assert.equal(r.S.meta.lastNight.cash,50);assert.equal(classes.has('techops-night-streets'),false);assert.equal(elements.has('night-home-transition'),false);assert.equal(r.keys.arrowright,false);}});
test('cinematic does not advance or settle while the page is hidden',()=>{const {r,api}=boot();r.NM.district='home';api.requestHome(r.NM);r.dialog.options[0].f();r.document.hidden=true;for(let i=0;i<100;i++)api.tick(r.NM,r.S,.1);assert.equal(r.exitCount,undefined);assert.equal(api.session(r.NM).transition.age,0);});
test('stale home callbacks cannot exit a replacement world',()=>{const {r,api}=boot();r.NM.district='home';api.requestHome(r.NM);const fn=r.dialog.options[0].f;r.NM={district:'home',done:{},enemies:[]};fn();assert.equal(r.NM._nightSession,undefined);assert.equal(r.exitCount,undefined);});
test('route journal and field guide are reachable and do not mutate campaign facts',()=>{const {r,api}=boot();r.NM.enemies=[{alive:true,hp:10}];r.TechOpsCampaign={load:()=>({flags:{day_work_unlocked:false}})};api.openJournal();assert.match(r.dialog.body,/1 opponent/);assert.doesNotMatch(r.dialog.body,/violinist|orpheus|ghost.fork/i);r.dialog.options[0].f();assert.match(r.dialog.title,/FIELD GUIDE/);assert.match(r.dialog.body,/miss earns no combo/);r.dialog.options[1].f();assert.equal(r.S.inDialog,false);});
test('production wiring uses existing step/draw and no extra timer or loop',()=>{const hooks=fs.readFileSync('night_hooks.js','utf8'),guard=fs.readFileSync('production_wrapper_guard.js','utf8');assert.ok(guard.includes('TechOpsNightSession.tick(world(),state(),arguments[0])'));assert.ok(!hooks.includes('TechOpsNightSession.tick('));assert.ok(hooks.includes('TechOpsNightSession.requestHome(NM)'));assert.ok(guard.includes('"night-home-transition"'));assert.ok(guard.includes('TechOpsNightSession.draw(x,n)'));assert.doesNotMatch(source,/setInterval|requestAnimationFrame|setTimeout/);assert.doesNotMatch(hooks.slice(hooks.indexOf('function nmNextStage()'),hooks.indexOf('function exitNight(')),/advanceClock\(/);});
console.log(`Night session: ${count} tests passed`);
