'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('./campaign_act1.js'),ui=fs.readFileSync('campaign_office_memory.js','utf8');let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const clone=x=>JSON.parse(JSON.stringify(x));
function record(state,overrides={}){return C.recordOfficeClosure(state,{kind:'procedural',id:'34:printer:0',day:4,title:'Printer Offline',typeId:'printer',ownerId:'mike',department:'Shipping',humanNeed:'Print a real shipping label.',verification:'partial',humanOutcome:'unknown',pendingRepeat:true,...overrides});}
function act(state,id,action,value,day=5){return C.followUpAction(state,id,day,action,value);}
function evidence(state,r){act(state,r.id,'intake');act(state,r.id,'observe','service_probe');act(state,r.id,'observe','requester_trial');}
function solve(state,r,hyp){evidence(state,r);assert.equal(act(state,r.id,'hypothesis',hyp).correct,true);if(hyp!=='verification_only')act(state,r.id,'remediate');act(state,r.id,'verify');act(state,r.id,'publish');}
test('closure snapshots are idempotent and retain provenance',()=>{const s=C.createInitialState(),r=record(s,{ownerId:'Amit'});record(s,{ownerId:'mike',verification:'strong'});assert.equal(s.officeMemory.order.length,1);assert.equal(s.officeMemory.records[r.id].ownerId,'Amit');r.ownerId='changed';assert.equal(s.officeMemory.records[r.id].ownerId,'Amit');assert.equal(s.officeMemory.records[r.id].verification,'partial');});
test('risk is not an observed incident and unobserved seeds stay out of UI records',()=>{const s=C.createInitialState();record(s);const [r]=C.officeRecords(s,4);assert.equal(r.due,false);assert.equal(r.repeatRisk,true);assert.deepEqual(r.followUp.observations,{});assert.equal(r.pendingRepeat,undefined);assert.doesNotMatch(JSON.stringify(r),/hypothesis_supported|recurrence.confirmed/);});
test('future, unknown and skipped verification actions are rejected',()=>{const s=C.createInitialState(),r=record(s);assert.throws(()=>act(s,r.id,'intake',null,4),/not due/);assert.throws(()=>act(s,r.id,'publish'),/verification required/);assert.throws(()=>act(s,r.id,'verify'),/supported resolution/);assert.throws(()=>act(s,r.id,'hypothesis','requester_path'),/Two independent/);assert.throws(()=>act(s,'missing','intake'),/Unknown follow-up/);});
test('requester-path recurrence needs independent checks, targeted remedy and real verification',()=>{const s=C.createInitialState(),r=record(s);const facts=JSON.stringify({flags:s.flags,evidence:s.evidence,trust:s.trust});evidence(s,r);const f=s.officeMemory.records[r.id].followUp;assert.equal(f.observations.service_probe.passed,true);assert.equal(f.observations.requester_trial.passed,false);const wrong=act(s,r.id,'hypothesis','service_dependency');assert.equal(wrong.correct,false);assert.equal(f.phase,'hypothesis');act(s,r.id,'hypothesis','requester_path');assert.throws(()=>act(s,r.id,'verify'),/supported resolution/);act(s,r.id,'remediate');act(s,r.id,'verify');act(s,r.id,'publish');assert.equal(f.phase,'closed');assert.equal(s.officeMemory.knowledge.printer.verified,true);assert.equal(JSON.stringify({flags:s.flags,evidence:s.evidence,trust:s.trust}),facts);assert.equal(s.officeMemory.records[r.id].verification,'partial');});
test('incomplete restoration produces evidence of a service dependency failure',()=>{const s=C.createInitialState(),r=record(s,{humanOutcome:'degraded',pendingRepeat:false});solve(s,r,'service_dependency');assert.equal(s.officeMemory.records[r.id].followUp.observations.service_probe.passed,false);});
test('weak verification without recurrence is repaired without inventing a fault',()=>{const s=C.createInitialState(),r=record(s,{pendingRepeat:false});solve(s,r,'verification_only');assert.equal(s.officeMemory.records[r.id].followUp.fixApplied,false);assert.equal(s.officeMemory.records[r.id].followUp.verified,true);});
test('strong restored work creates a knowledge opportunity, not guaranteed repeat failure',()=>{const s=C.createInitialState(),r=record(s,{verification:'strong',humanOutcome:'restored',pendingRepeat:false});assert.equal(r.repeatRisk,false);solve(s,r,'verification_only');assert.equal(s.officeMemory.records[r.id].followUp.fixApplied,false);});
test('duplicate observations and closure callbacks cannot multiply evidence or rewards',()=>{const s=C.createInitialState(),r=record(s);act(s,r.id,'intake');act(s,r.id,'observe','service_probe');const len=s.officeMemory.records[r.id].followUp.events.length;assert.equal(act(s,r.id,'observe','service_probe').changed,false);assert.equal(s.officeMemory.records[r.id].followUp.events.length,len);act(s,r.id,'observe','requester_trial');act(s,r.id,'hypothesis','requester_path');act(s,r.id,'remediate');act(s,r.id,'verify');act(s,r.id,'publish');const before=JSON.stringify(s);assert.equal(act(s,r.id,'publish').changed,false);assert.equal(JSON.stringify(s),before);});
test('every follow-up phase survives canonical save and cold reload',()=>{let s=C.createInitialState(),r=record(s),raw;const store={setItem(_,v){raw=v;},getItem(){return raw;}};for(const [action,value] of [['intake'],['observe','requester_trial'],['observe','service_probe'],['hypothesis','requester_path'],['remediate'],['verify'],['publish']]){act(s,r.id,action,value);C.save(s,store);s=C.load(store);}assert.equal(s.officeMemory.records[r.id].followUp.phase,'closed');assert.equal(s.officeMemory.records[r.id].ownerId,'mike');});
function authored(){const s=C.createInitialState();for(const id of C.TICKETS)C.assignTicket(s,id,id==='plating_workstation_down'?'amit':'mike');C.completeStandup(s);C.completeWorkstation(s);return s;}
test('old authored closures import without fabricated timestamps or badge-resolution work',()=>{const s=authored();C.resolveTicket(s,'shipping_cannot_print',{technicalResolution:true,verification:'partial',humanOutcome:'restored'});C.resolveTicket(s,'impossible_access_event',{technicalResolution:true,verification:'strong',humanOutcome:'restored'});delete s.officeMemory;delete s.tickets.shipping_cannot_print.completedAt;const migrated=C.migrate(s),records=C.officeRecords(migrated,2);assert.equal(records.length,1);assert.equal(records[0].completedAt,null);assert.equal(records[0].ownerId,'mike');assert.equal(records[0].followUp.events.length,0);assert.throws(()=>record(s,{kind:'authored',id:'impossible_access_event'}),/not ordinary/);});
test('Tuesday handoff is idempotent and preserves ongoing follow-up progress',()=>{const s=authored();C.resolveTicket(s,'plating_workstation_down',{technicalResolution:true,verification:'partial',humanOutcome:'degraded'});s.flags.sector04_completed=true;C.transitionToTuesday(s);const r=C.officeRecords(s,2)[0];C.followUpAction(s,r.id,2,'intake');s.campaign.day=4;s.campaign.chapter='later_campaign';const before=JSON.stringify(s);C.transitionToTuesday(s);assert.equal(JSON.stringify(s),before);});
test('ledger capacity never evicts unresolved work; completed records can retire',()=>{const s=C.createInitialState();for(let i=0;i<240;i++)record(s,{id:String(i)});assert.equal(record(s,{id:'overflow'}),null);assert.equal(s.officeMemory.order.length,240);const first=s.officeMemory.records[s.officeMemory.order[0]];solve(s,first,'requester_path');assert.ok(record(s,{id:'new'}));assert.equal(s.officeMemory.order.length,240);assert.equal(s.officeMemory.records[first.id],undefined);});
function boot(store){const values=new Map();store=store||{writes:0,getItem:k=>values.get(k)||null,setItem(k,v){this.writes++;values.set(k,v);}};const r={console,TechOpsCampaign:C,localStorage:store,S:{day:5,clock:540,meta:{},inDialog:false},dlg(title,body,options){r.dialog={title,body,options};r.S.inDialog=true;},closeDlg(){r.S.inDialog=false;},advanceClock(min){r.S.clock+=min;},save(){r.baseSaves=(r.baseSaves||0)+1;}};vm.runInNewContext(ui,r);return {r,U:r.TechOpsOfficeMemory,store};}
function click(b,label){const o=b.r.dialog.options.find(o=>o.t===label);assert.ok(o,label);o.f();}
test('real UI route completes an investigation and publishes reusable knowledge',()=>{const b=boot(),s=C.createInitialState(),r=record(s);C.save(s,b.store);b.U.open();click(b,'Printer Offline · RECHECK');click(b,'Talk to the requester');click(b,'Check the technical service');click(b,'Watch the requester repeat the real task');click(b,'A requester-specific service path');click(b,'Apply the targeted correction');click(b,'Recheck service AND requester outcome');click(b,'Publish verified handoff to the knowledge base');assert.equal(C.load(b.store).officeMemory.records[r.id].followUp.phase,'closed');assert.equal(b.r.S.meta.kb.printer,true);assert.equal(b.r.S.clock,561);assert.equal(b.r.baseSaves,1);});
test('read-only menu visits do not advance the clock or rewrite records',()=>{const b=boot(),s=C.createInitialState();record(s);C.save(s,b.store);const writes=b.store.writes;b.U.open('all');b.U.open('all');assert.equal(b.store.writes,writes);assert.equal(b.r.S.clock,540);});
test('save-controlled labels are escaped in text, titles and option HTML',()=>{const b=boot(),s=C.createInitialState();record(s,{title:'<img src=x onerror=alert(1)>',ownerId:'<script>bad</script>'});C.save(s,b.store);b.U.open();assert.doesNotMatch(b.r.dialog.options[0].t,/<img/);b.r.dialog.options[0].f();assert.doesNotMatch(b.r.dialog.body,/<script>|<img/);assert.match(b.r.dialog.body,/&lt;script&gt;/);});
test('corrupt or blocked storage fails visibly without overwriting progress',()=>{let writes=0;const b=boot({getItem(){return '{bad';},setItem(){writes++;}});assert.equal(b.U.open(),false);assert.match(b.r.dialog.title,/UNAVAILABLE/);assert.equal(writes,0);});
test('failed follow-up save cannot grant knowledge or spend shift time',()=>{const s=C.createInitialState(),r=record(s),raw=JSON.stringify(s),b=boot({getItem(){return raw;},setItem(){throw new Error('quota');}});b.U.act(r.id,'intake');assert.equal(b.r.S.clock,540);assert.equal(b.r.S.meta.kb,undefined);assert.match(b.r.dialog.title,/UNAVAILABLE/);assert.equal(JSON.parse(raw).officeMemory.records[r.id].followUp.phase,'intake');});
test('procedural and delegated capture never upgrades unverified work',()=>{const b=boot(),n={id:7,done:true,name:'Operator',dept:'Manufacturing',type:{id:'printer',label:'Printer Offline'},correctDiag:true};b.U.captureTicket(n,b.r.S,'Amit');const r=C.officeRecords(C.load(b.store),6)[0];assert.equal(r.ownerId,'Amit');assert.equal(r.verification,'partial');assert.equal(r.humanOutcome,'unknown');const writes=b.store.writes;b.U.captureTicket({...n,type:{id:'shadow'}},b.r.S);b.U.captureTicket({...n,done:false},b.r.S);assert.equal(b.store.writes,writes);});
test('stale and night-mode UI callbacks cannot act on completed or inactive work',()=>{const b=boot(),s=C.createInitialState(),r=record(s,{pendingRepeat:false});solve(s,r,'verification_only');C.save(s,b.store);const writes=b.store.writes;b.U.act(r.id,'publish');assert.equal(b.store.writes,writes);assert.equal(b.r.S.clock,540);b.r.S.nightMode={};assert.equal(b.U.open(),false);assert.equal(b.U.act(r.id,'intake'),false);});
test('knowledge projection is idempotent and cannot introduce unknown gameplay types',()=>{const s=C.createInitialState(),r=record(s,{pendingRepeat:false});solve(s,r,'verification_only');s.officeMemory.knowledge.shadow={verified:true};const b=boot();b.U.syncKnowledge(s,b.r.S);const before=JSON.stringify(b.r.S);b.U.syncKnowledge(s,b.r.S);assert.equal(JSON.stringify(b.r.S),before);assert.equal(b.r.S.meta.kb.printer,true);assert.equal(b.r.S.meta.kb.shadow,undefined);});
test('live native and later-day desk menus expose the handoff without a new wrapper',()=>{assert.ok(fs.readFileSync('campaign_native_act1.js','utf8').includes('handoffOption()'));assert.ok(fs.readFileSync('office_hooks.js','utf8').includes('Shift handoff / follow-up work'));assert.doesNotMatch(ui,/setInterval|setTimeout|requestAnimationFrame|root\.interact\s*=/);});
console.log(`Office memory: ${count} tests passed`);
