"use strict";
const assert=require("assert");
const fs=require("fs");
const source=fs.readFileSync("good_boys_ship_approach.js","utf8");
new Function(source);
assert.ok(/compatibility shim/i.test(source),"legacy approach module must be explicitly compatibility-only");
assert.ok(source.includes("TechOpsGoodBoysShipFlight"),"legacy approach module must delegate to canonical ship flight");
assert.ok(source.includes("compatibilityOnly:true"),"compatibility status must be observable");
assert.ok(!source.includes('id==="GD_CUT_02"'),"legacy approach must not intercept authored cutscenes");
assert.ok(!source.includes("GoodDogsCutscenes.play"),"legacy approach must not wrap the Good Dogs cutscene player");
assert.ok(!source.includes("asteroid_1"),"supplied ship artwork must have one production authority, not a duplicate shim copy");
console.log("Good Boys legacy ship approach compatibility guard: PASS");
