'use strict';
const assert=require('node:assert/strict');
const {boot,shift,close,tuesday,click,current,finish,SHIPPING,PLATING}=require('./test_helpers/gameplay_fixture');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function setup(id=SHIPPING,verification='partial',outcome='restored'){const b=boot(),s=shift(b);close(b,s,id,verification,outcome);tuesday(b,s);return {b,s};}
test('Tuesday contacts are actually placed and repeat placement is idempotent',()=>{const {b}=setup();assert.equal(b.N.ensureWorld(),true);const first=JSON.stringify(b.r.S.meta.campaignAct1Native);b.N.ensureWorld();assert.equal(JSON.stringify(b.r.S.meta.campaignAct1Native),first);assert.equal(b.r.S.npcs.filter(x=>x.id==='campaign_shipping').length,1);assert.equal(b.r.S.npcs.some(x=>x.id==='campaign_access'),false);assert.equal(b.r.S.npcs.find(x=>x.id==='campaign_standup').name,'SHIFT HANDOFF');});
test('next-shift placement does not overlap existing noncampaign NPCs',()=>{const {b}=setup();b.r.S.npcs=[{id:'other',x:34,y:12}];b.N.ensureWorld();const board=b.r.S.meta.campaignAct1Native.standup;assert.notDeepEqual({x:board.x,y:board.y},{x:34,y:12});});
test('actual adjacent interaction reaches the next-shift investigation',()=>{const {b}=setup();b.N.ensureWorld();b.N.install();b.I.install();const p=b.r.S.meta.campaignAct1Native.shipping;b.r.S.px=p.x;b.r.S.py=p.y;b.r.S.inDialog=false;b.r.interact();assert.equal(b.r.dialog.name,'SHIPPING // NEXT SHIFT');assert.match(b.r.dialog.body,/VERIFICATION DUE/);assert.equal(b.r.baseInteractions,undefined);});
test('Tuesday board opens the workstation, not a replay of Day 1 standup',()=>{const {b}=setup();b.N.ensureWorld();b.N.install();const p=b.r.S.meta.campaignAct1Native.standup;b.r.S.px=p.x;b.r.S.py=p.y;b.r.S.inDialog=false;b.r.interact();assert.equal(b.r.dialog.name,'MIKE // WORKSTATION');click(b,'QUEUE');assert.equal(b.r.dialog.name,'WORKSTATION // SHIFT HANDOFF');});
test('QUEUE, TEAMS and original casebook all expose the same handoff',()=>{const {b}=setup();b.N.openWorkstationTab('QUEUE');assert.equal(b.r.dialog.name,'WORKSTATION // SHIFT HANDOFF');b.N.openWorkstationTab('TEAMS');click(b,'Review shift handoff');assert.equal(b.r.dialog.name,'WORKSTATION // SHIFT HANDOFF');b.N.openTicketRecord(SHIPPING);click(b,'Next-shift follow-up');assert.equal(b.r.dialog.name,'SHIPPING // NEXT SHIFT');});
test('reviewing the handoff, original records, and observations is read-only',()=>{const {b}=setup(),before=b.store.writes;b.N.openWorkdayHandoff();b.N.openWorkdayFollowup(SHIPPING);b.N.openTicketRecord(SHIPPING);b.N.openTicketHistory();assert.equal(b.store.writes,before);});
for(const id of [SHIPPING,PLATING])test(id+' recheck UI requires both observations and real requester confirmation',()=>{const {b}=setup(id);b.N.openWorkdayFollowup(id);assert.ok(!b.r.dialog.options.some(x=>/Requester performs/.test(x.t)));click(b,'Ask the next-shift requester');click(b,'Continue follow-up');click(b,id===SHIPPING?'Trace the next-shift label job':'Check integration across a controlled restart');click(b,'Continue follow-up');click(b,'Technical path is healthy; verify the real task');assert.equal(current(b,b.C.load(b.store),id).phase,'human_verify');click(b,'Review observations');click(b,'Resume current step');click(b,'Requester performs and confirms the task');assert.match(b.r.dialog.body,/NEXT SHIFT VERIFIED/);assert.equal(current(b,b.C.load(b.store),id).result.verification,'strong');});
for(const id of [SHIPPING,PLATING])test(id+' degraded-service UI includes hypothesis, repair, recheck, and task confirmation',()=>{const {b}=setup(id,'partial','degraded');b.N.openWorkdayFollowup(id);click(b,'Ask the next-shift requester');click(b,'Continue follow-up');click(b,id===SHIPPING?'Trace the next-shift label job':'Check integration across a controlled restart');click(b,'Continue follow-up');click(b,id===SHIPPING?'Next-shift queue authorization gap':'Integration dependency not persistent at boot');click(b,'Apply the supported remediation');click(b,'Run the technical recheck');click(b,'Requester performs and confirms the task');assert.equal(current(b,b.C.load(b.store),id).phase,'complete');});
test('a stale requester-confirmation callback cannot close twice or add history',()=>{const {b}=setup();b.N.openWorkdayFollowup(SHIPPING);click(b,'Ask the next-shift requester');click(b,'Continue follow-up');click(b,'Trace the next-shift label job');click(b,'Continue follow-up');click(b,'Technical path is healthy; verify the real task');const cb=b.r.dialog.options.find(x=>x.t==='Requester performs and confirms the task').f;cb();const before=b.store.getItem(b.C.SAVE_KEY);assert.doesNotThrow(cb);assert.equal(b.store.getItem(b.C.SAVE_KEY),before);});
test('current service visuals can improve while original casebook remains degraded',()=>{const {b,s}=setup(PLATING,'partial','degraded');assert.equal(b.V.presentationFor('plating',s).variant,'follow_up');finish(b,s,PLATING);assert.equal(b.V.presentationFor('plating',s).variant,'restored');assert.equal(b.N.ticketRecord(s,PLATING).status,'FOLLOW-UP NEEDED');assert.equal(b.N.currentServiceRecord(s,PLATING).status,'VERIFIED / RESTORED');});
test('completed follow-up contacts remember the actual next-shift outcome',()=>{const {b,s}=setup();finish(b,s,SHIPPING);b.C.save(s,b.store);b.N.resolveTicket(SHIPPING);assert.match(b.r.dialog.body,/NEXT SHIFT VERIFIED/);assert.match(b.N.ticketFollowUp(s,SHIPPING),/recorded separately/);assert.ok(!b.r.dialog.options.some(x=>/Apply|performs/.test(x.t)));});
test('sound settings are reachable from the existing workstation without adding a tab',()=>{const {b}=setup();b.r.TechOpsCombatAudio={openSettings(back){b.settingsBack=back;}};b.N.openWorkstation();click(b,'Combat sound & captions');assert.equal(b.settingsBack,b.N.openWorkstation);assert.equal(b.N.WORKSTATION_TABS.length,5);});
test('unresolved carryover has a resume action, not an instant closure',()=>{const b=boot(),s=tuesday(b,shift(b));b.N.openWorkdayFollowup(SHIPPING);click(b,'Resume original investigation');assert.match(b.r.dialog.body,/HUMAN NEED/);assert.equal(b.C.load(b.store).tickets[SHIPPING],undefined);});
test('blocked storage fails visibly and cannot replace the authoritative save',()=>{const {b}=setup();b.N.openWorkdayFollowup(SHIPPING);const before=b.store.getItem(b.C.SAVE_KEY);b.store.setItem=()=>{throw Error('quota');};click(b,'Ask the next-shift requester');assert.match(b.r.dialog.name,/ACTION UNAVAILABLE/);assert.equal(b.store.getItem(b.C.SAVE_KEY),before);});
test('historical casebook visuals do not borrow a later restoration',()=>{const {b,s}=setup(PLATING,'partial','degraded');finish(b,s,PLATING);assert.equal(b.V.presentationFor('plating',s,'PLATING // NEXT SHIFT').variant,'restored');assert.equal(b.V.presentationFor('plating',s,'CASEBOOK // PLATING WORKSTATION DOWN').variant,'follow_up');});
test('resuming an already constructed Tuesday world installs contacts immediately',()=>{const {b}=setup();assert.equal(b.r.S.npcs.length,0);b.N.install();assert.ok(b.r.S.npcs.some(x=>x.id==='campaign_shipping'));assert.ok(b.r.S.meta.campaignAct1Native);});
test('old Day 1 security contacts do not leak into the Tuesday contact set',()=>{const {b}=setup();b.r.S.npcs.push({id:'campaign_access',x:38,y:12});b.N.ensureWorld();assert.equal(b.r.S.npcs.some(x=>x.id==='campaign_access'),false);});
test('carried work completion never invents a new firsthand provenance',()=>{const b=boot(),s=tuesday(b,shift(b));close(b,s,PLATING);b.C.save(s,b.store);b.N.openWorkdayFollowup(PLATING);assert.match(b.r.dialog.body,/Recorded completion owner: Amit/);assert.doesNotMatch(b.r.dialog.body,/firsthand/);});
for(const id of [SHIPPING,PLATING])for(const path of ['reported','workaround'])test(id+' '+path+' choice reaches Tuesday consequences through normal field UI',()=>{
 const b=boot();shift(b);b.N.ensureWorld();b.N.install();b.I.install();const p=b.r.S.meta.campaignAct1Native[id===SHIPPING?'shipping':'plating'];b.r.S.px=p.x;b.r.S.py=p.y;b.r.S.inDialog=false;b.r.interact();
 click(b,'Begin investigation');click(b,id===SHIPPING?'Run printer self-test':'Check local workstation health');click(b,'Continue investigation');click(b,id===SHIPPING?'Trace one customs-label job':'Inspect production integration service');click(b,'Continue investigation');click(b,'Form hypothesis');click(b,id===SHIPPING?'Permissions':'Integration Failure');click(b,'Plan remediation');
 if(path==='workaround'){click(b,'Use a temporary workaround and hand off');click(b,'Apply and test the temporary workaround');click(b,'Requester confirms limited service');}
 else{click(b,'Apply remediation');click(b,'Run technical check');click(b,'Record reported restoration; recheck next shift');click(b,'Save partial verification');}
 let state=b.C.load(b.store);assert.equal(state.tickets[id].verification,'partial');assert.equal(state.tickets[id].humanOutcome,path==='workaround'?'degraded':'restored');const original=JSON.stringify(state.tickets[id]);
 tuesday(b,state);b.N.openWorkdayFollowup(id);assert.match(b.r.dialog.body,path==='workaround'?/SERVICE FOLLOW-UP/:/VERIFICATION DUE/);click(b,'Ask the next-shift requester');click(b,'Continue follow-up');click(b,id===SHIPPING?'Trace the next-shift label job':'Check integration across a controlled restart');click(b,'Continue follow-up');
 if(path==='workaround'){click(b,id===SHIPPING?'Next-shift queue authorization gap':'Integration dependency not persistent at boot');click(b,'Apply the supported remediation');click(b,'Run the technical recheck');}
 else click(b,'Technical path is healthy; verify the real task');
 click(b,'Requester performs and confirms the task');state=b.C.load(b.store);assert.equal(current(b,state,id).phase,'complete');assert.equal(JSON.stringify(state.tickets[id]),original);
});
console.log('Workday follow-up UI/runtime: '+count+' tests passed');
