"use strict";
const assert = require("assert");
const fs = require("fs");

delete global.TechOpsMikeAnimations;
const visuals = require("./campaign_world_visuals.js");
assert.strictEqual(visuals.VERSION, 10);
assert.strictEqual(visuals.INTERACT_RANGE, 2.15);
assert.strictEqual(visuals.SAFE_WALK_FRAME_MS, 135);
assert.strictEqual(visuals.distance(0, 0, 3, 4), 5);
assert.deepStrictEqual(visuals.SAFE_WALK_FRAMES.down, ["down0", "down1", "down0", "down2"]);
assert.deepStrictEqual(visuals.SAFE_WALK_FRAMES.up, ["up0", "up1", "up0", "up2"]);
assert.deepStrictEqual(visuals.SAFE_WALK_FRAMES.right, ["right0", "right1", "right0", "right2"]);
assert.deepStrictEqual(visuals.SAFE_WALK_FRAMES.left, ["right0", "right1", "right0", "right2"]);
let f = visuals.safePlayerFrame({ fx: "down", moving: false }, 0);
assert.strictEqual(f.key, "down0"); assert.strictEqual(f.state, "idle");
f = visuals.safePlayerFrame({ fx: "left", moving: false }, 0); assert.strictEqual(f.key, "right0"); assert.strictEqual(f.flip, true);
f = visuals.safePlayerFrame({ fx: "down", moving: true }, 135); assert.strictEqual(f.key, "down1");
f = visuals.safePlayerFrame({ fx: "down", moving: true }, 270); assert.strictEqual(f.key, "down0");
f = visuals.safePlayerFrame({ fx: "down", moving: true }, 405); assert.strictEqual(f.key, "down2");
f = visuals.safePlayerFrame({ fx: "left", moving: true }, 405); assert.strictEqual(f.key, "right2"); assert.strictEqual(f.flip, true);
f = visuals.safePlayerFrame({ fx: "up", moving: false, inDialog: true }, 0); assert.strictEqual(f.key, "laptop"); assert.strictEqual(f.state, "interact");
const state = { px:10, py:10, npcs:[{id:"ambient",x:11,y:10,ambient:true,done:false},{id:"ticket",x:10,y:11,ambient:false,done:false}], devices:[{id:"device",x:12,y:10,fixed:false}], portals:[{id:"portal",x:10,y:12}] };
let target = visuals.nearestInteractable(state);
assert.strictEqual(target.kind, "npc"); assert.strictEqual(target.source.id, "ticket"); assert.strictEqual(target.distance, 1);
state.npcs[1].done = true; target = visuals.nearestInteractable(state); assert.strictEqual(target.source.id, "ambient");
state.npcs[0].done = true; target = visuals.nearestInteractable(state); assert.strictEqual(target.kind, "device"); assert.strictEqual(target.distance, 2);
state.devices[0].fixed = true; target = visuals.nearestInteractable(state); assert.strictEqual(target.kind, "portal");
state.portals = []; assert.strictEqual(visuals.nearestInteractable(state), null);
const profile = visuals.lightProfile({ px:0, py:0 });
assert.ok(profile.vignette >= 0 && profile.vignette < 0.5); assert.ok(profile.warm >= 0 && profile.cool >= 0);
assert.ok(visuals.MOBILE_SAFE_AREA_CSS.includes("safe-area-inset-top"));
assert.ok(visuals.MOBILE_SAFE_AREA_CSS.includes("safe-area-inset-bottom"));
assert.ok(visuals.MOBILE_SAFE_AREA_CSS.includes("safe-area-inset-left"));
assert.ok(visuals.MOBILE_SAFE_AREA_CSS.includes("safe-area-inset-right"));
assert.ok(visuals.MOBILE_SAFE_AREA_CSS.includes("min-height:44px"));
assert.strictEqual(typeof visuals.loadNightReference, "function");
assert.strictEqual(typeof visuals.loadGoodDogsProduction, "function");
assert.strictEqual(typeof visuals.loadGoodBoysMechanics, "function");
assert.strictEqual(typeof visuals.loadGoodBoysCanon, "function");
assert.strictEqual(typeof visuals.loadGoodBoysGameplayLoop, "function");

const goodDogs = fs.readFileSync("good_dogs_production_runtime.js", "utf8");
const goodDogsVersion = Number((goodDogs.match(/var\s+VERSION\s*=\s*(\d+)/)||[])[1]||0);
assert.ok(goodDogsVersion >= 3, "Good Dogs production runtime must retain compositor-owned v3+ architecture");
assert.ok(/productionCompositorActive/.test(goodDogs), "Good Dogs production runtime must defer render ownership to the production compositor");
assert.ok(/drawActiveDog/.test(goodDogs) && /KATRIN_MANCHEZ/.test(goodDogs));
assert.ok(/never substitute attack\/crouch\/knockdown art for walk/.test(goodDogs));
assert.ok(/drawReferenceHUD/.test(goodDogs) && /GOOD DOGS PROTOCOL/.test(goodDogs));

const mechanics = fs.readFileSync("good_boys_reference_mechanics.js", "utf8");
assert.ok(/Three boost jumps/i.test(mechanics) && /function boostJump/.test(mechanics) && /n\.jumps=3/.test(mechanics), "Good Boys must retain the three-jump partner boost contract");
assert.ok(/two air dashes/i.test(mechanics) && /state\.airDashes>=2/.test(mechanics) && /function airDash/.test(mechanics), "Good Boys must retain two airborne dashes");
assert.ok(/partnerThrow/.test(mechanics) && /midAirCatch/.test(mechanics));

const canon = fs.readFileSync("good_boys_canon_runtime.js", "utf8");
const canonVersion=Number((canon.match(/var VERSION=(\d+)/)||[])[1]||0);
assert.ok(canonVersion>=6, `Good Boys canon runtime must retain compositor ownership (found v${canonVersion})`);
assert.ok(/productionCompositorActive/.test(canon) && /drawHud:drawHud/.test(canon) && /syncIdentity:syncIdentity/.test(canon), "canon must expose production compositor/router callbacks");
assert.ok(/WALDO'S HOUSE/.test(canon) && /THE HIDDEN BAY/.test(canon) && /MAKE A DOOR/.test(canon));
assert.ok(/FIND WALDO'S TRAIL · REACH THE HIDDEN BAY/.test(canon));
assert.ok(/INVESTIGATE THE PRISONER · VERIFY · FREE K/.test(canon));
assert.ok(/FREE WALDO · HOLD BOTH SIDES · BREAK LOCKDOWN/.test(canon));
assert.ok(/goodboys_home/.test(canon) && /goodboys_hangar/.test(canon) && /goodboys_breach/.test(canon));
assert.ok(/prepareNightRuntime/.test(canon) && /night_runtime_timeout/.test(canon), "mobile handoff must wait for NM runtime");
assert.ok(/suppressLegacyPresentation/.test(canon) && /NEW HAVEN STREETS/.test(canon), "Good Boys must suppress inherited Night Crawler presentation");
assert.ok(/style\.setProperty\("display","none","important"\)/.test(canon));
assert.ok(!/toDataURL/.test(canon));

const assets = fs.readFileSync("good_boys_campaign_assets.js", "utf8");
["goodboys_home","goodboys_hangar","goodboys_approach","goodboys_breach","goodboys_cell118","goodboys_cell1984","goodboys_escape","goodboys_earthfall"].forEach(id=>assert.ok(assets.includes(id), id+" asset missing"));
assert.ok(/WALDO'S HOUSE/.test(assets) && /HIDDEN BAY/.test(assets));
assert.ok(/IMPACT VECTOR ACCEPTED/.test(assets) && /MAKE A DOOR/.test(canon));
assert.ok(/NM_DISTRICTS/.test(assets) && /installDistricts/.test(assets), "generated visuals must be wired as playable Night-engine districts");
assert.ok(!/NEW HAVEN/.test(assets), "Good Boys world assets must not inherit New Haven identity");

const loop = fs.readFileSync("good_boys_gameplay_loop.js", "utf8");
const loopVersion=Number((loop.match(/var VERSION=(\d+)/)||[])[1]||0);
assert.ok(loopVersion>=4, `concept gameplay loop must retain compositor ownership (found v${loopVersion})`);
assert.ok(/productionCompositorActive/.test(loop), "production gameplay loop must defer Night draw/step ownership to compositor");
assert.ok(/sheet 3 = moment-to-moment HUD\/gameplay/.test(loop), "gameplay loop must declare concept-sheet authority");
assert.ok(/CELL 118 — FREE K/.test(loop) && /CELL 1984 — FREE WALDO/.test(loop));
assert.ok(/Run for the shuttle\. Build Sync\. Finish together\./.test(loop));
assert.ok(/good-boys-loop-controls/.test(loop));
["gbl-dash","gbl-attack","gbl-block","gbl-swap","gbl-boost","gbl-throw","gbl-sync","gbl-k"].forEach(id=>assert.ok(loop.includes(id), id+" control missing"));
assert.ok(/c\.chars\.katrin/.test(loop) && /c\.chars\.manchez/.test(loop) && /c\.partner/.test(loop), "loop must repair linked-pair state");
assert.ok(/drawDogCard/.test(loop) && /P1 ACTIVE/.test(loop), "concept HUD must show persistent Katrin/Manchez status and active control");
assert.ok(/drawLinkStatus/.test(loop) && /LINK!/.test(loop), "concept HUD must expose linked-pair Sync state");
assert.ok(/#touch-buttons,body\.good-boys-loop #good-dogs-touch\{display:none!important\}/.test(loop), "generic Night/co-op buttons must not compete with Good Boys controls");
assert.ok(/_goodBoysReferenceScale=1\.55/.test(loop), "Good Boys should retain hero-scale presentation metadata");
assert.ok(/concept_v4/.test(loop) && /controls:8/.test(loop), "acceptance telemetry must expose current concept HUD authority and control count");
assert.ok(/var STAGES=/.test(loop) && /configureStage/.test(loop), "Good Boys must own authored side-view stage geometry");
assert.ok(/_goodBoysStageAuthority="concept_geometry_v1"/.test(loop), "stage authority must be observable for QA");
assert.ok(/HULL BREACH — BOOST \/ AIR DASH/.test(loop) && /applyHazards/.test(loop), "breach hazards must exercise reference traversal mechanics");
assert.ok(/CELL 118/.test(loop) && /CELL 1984/.test(loop) && /MAINTENANCE SHUTTLE/.test(loop), "orbital landmarks must be visually authored into gameplay");
assert.ok(/drawStageAccents/.test(loop) && /foreground rails\/pipes/.test(loop), "stage must include foreground depth treatment");
assert.ok(/installStep/.test(loop) && /root\.stepNM=/.test(loop), "legacy standalone Night physics extension must remain available outside production");
assert.ok(/emergency_red/.test(canon) && /hack_green/.test(canon) && /impact_orange/.test(canon), "mission lighting language must match campaign route");

const accessCore = fs.readFileSync("good_boys_access_core_authority.js", "utf8");
assert.ok(/canonical Mike Index encounter/.test(accessCore));
assert.ok(/function isMikeIndex/.test(accessCore) && /function seedMikeIndex/.test(accessCore) && /function settleMikeIndex/.test(accessCore), "Access Core must own the canonical Mike Index encounter");
assert.ok(/recorded-behavior-only/.test(accessCore) && /_predictionHistoryOnly=true/.test(accessCore), "Mike Index must predict from recorded behavior only");
assert.ok(/parkPrematureSecurity/.test(accessCore) && /seedSecurity/.test(accessCore), "route security must occur after the Mike Index beat rather than replacing it");
assert.ok(/mike_index_defeated/.test(accessCore) && /k_identity_status/.test(accessCore), "Mike Index completion must affirm K and write semantic state");
assert.ok(/function syncState/.test(accessCore) && /c!==lastState/.test(accessCore) && /_gbAccessCoreSecuritySeeded=false/.test(accessCore), "Access Core retries must reset encounter seeding for each new _v736 state");

const semantic = fs.readFileSync("good_dogs_campaign_state.js", "utf8");
["good_dogs_signal_heard","k_freed","mike_index_defeated","waldo_freed","warden_null_defeated","good_dogs_protocol_complete","watchdog_k_available","watchdog_waldo_available","watchdog_good_dogs_available"].forEach(flag=>assert.ok(semantic.includes(flag),flag+" semantic state missing"));
assert.ok(/markTransition/.test(semantic) && /completeReturn/.test(semantic) && /installTransitionBridge/.test(semantic), "Good Dogs state must bridge compressed missions into named Story Bible facts");
assert.ok(/story\.completedActs\.indexOf\("interlude"\)/.test(semantic), "Good Dogs return must write back into the main campaign interlude");

const earthfall = fs.readFileSync("good_boys_earthfall_ending.js", "utf8");
assert.ok(/ESCAPE BURN/.test(earthfall) && /EARTHFALL/.test(earthfall) && /WALDO'S PLACE/.test(earthfall) && /GOOD BOYS PROTOCOL — COMPLETE/.test(earthfall), "Earthfall must own the full return-home cinematic");
assert.ok(/sh_takeoff/.test(earthfall) && /sh_reentry/.test(earthfall) && /sh_crash/.test(earthfall) && /sh_wreck/.test(earthfall), "Earthfall must animate the real shuttle atlas states");
assert.ok(/m\.done=true/.test(earthfall) && /_v736breakout=true/.test(earthfall) && /_v736pair=true/.test(earthfall), "Earthfall must commit campaign completion and pair unlocks");

const progression = fs.readFileSync("good_boys_progression_authority.js", "utf8");
assert.ok(/next===8/.test(progression) && /TechOpsGoodBoysEarthfallEnding/.test(progression) && /\.begin\(\)/.test(progression), "M7 completion must route directly into authored Earthfall");
assert.ok(/good-boys-earthfall-cine/.test(progression), "Earthfall must participate in gameplay input blocking");

const boot = fs.readFileSync("bg_noc.js", "utf8");
assert.ok(boot.includes("good_boys_access_core_authority.js") && boot.includes("good_boys_earthfall_ending.js") && boot.includes("good_dogs_campaign_state.js"), "production bootstrap must wire Access Core, Earthfall and semantic state authorities");
assert.ok(/function loadAccessCore\(\)\{if\(!appendScript\([^\n]*good_boys_access_core_authority\.js[^\n]*loadEarthfall/.test(boot), "Access Core loader must hand off to Earthfall");
assert.ok(/function loadEarthfall\(\)\{if\(!appendScript\([^\n]*good_boys_earthfall_ending\.js[^\n]*loadCampaignState/.test(boot), "Earthfall loader must hand off to semantic state");
assert.ok(/function loadCampaignState\(\)\{if\(!appendScript\([^\n]*good_dogs_campaign_state\.js[^\n]*loadProgression/.test(boot), "semantic state loader must hand off to progression");
assert.ok(/function loadBibleWorld\(\)\{if\(!appendScript\([^\n]*good_boys_bible_world\.js[^\n]*loadAccessCore/.test(boot), "Bible World loader must hand off to Access Core");

const worldSource = fs.readFileSync("campaign_world_visuals.js", "utf8");
assert.ok(worldSource.includes("good_dogs_production_runtime.js"));
assert.ok(worldSource.includes("good_boys_reference_mechanics.js"));
assert.ok(worldSource.includes("good_boys_canon_runtime.js"));
assert.ok(worldSource.includes("good_boys_gameplay_loop.js"), "deployed bootstrap must load concept gameplay loop after canon");

global.TechOpsMikeAnimations = require("./mike_animation_manifest.js");
f = visuals.playerFrame({ fx:"right", moving:true }, global.TechOpsMikeAnimations.WALK_FRAME_MS);
assert.strictEqual(f.key, "right1"); assert.strictEqual(f.semantic, "walk_right");
assert.strictEqual(visuals.animations(), global.TechOpsMikeAnimations);
assert.strictEqual(global.TechOpsMikeAnimations.actionFrameApproved("f000"), false);
assert.strictEqual(global.TechOpsMikeAnimations.actionFrameApproved("f181"), false);
console.log("Campaign playable world visuals + Good Boys Story Bible route v8: PASS");
