'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('production_gameplay_experience.js','utf8');
let tests=0;
function test(name,fn){fn();tests++;console.log('PASS '+name);}
function boot(){const r=vm.createContext({console,performance:{now:()=>1000},matchMedia:()=>({matches:false})});vm.runInContext(fs.readFileSync('cinematic_systems.js','utf8'),r);vm.runInContext(source,r);return r;}
function scene(r,m){const c={m,evidence:[],chars:{katrin:{hp:100},manchez:{hp:120}},partner:{x:20},sync:0};const n={x:180,y:396,w:22,h:34,onGround:true,enemies:[],_v736:c};r.NM=n;r.S={nightMode:n,meta:{_v736:{m}},inDialog:false};return n;}
function guide(r){return r.TechOpsGameplayExperience.objective(r.NM);}
function freeze(o){if(o&&typeof o==='object'){Object.values(o).forEach(freeze);Object.freeze(o);}return o;}
function canvas(){const words=[];const x={canvas:{width:390,height:844},words,measureText:t=>({width:String(t).length*4})};for(const fn of ['save','restore','beginPath','roundRect','rect','fill','stroke','fillRect'])x[fn]=()=>{};x.fillText=(text)=>words.push(text);return x;}
test('load starts no loop, context, listener or duplicate DOM HUD',()=>{const r=boot();for(const name of ['requestAnimationFrame','setTimeout','setInterval','AudioContext','addEventListener'])r[name]=()=>{throw Error(name);};r.document={getElementById:()=>null,createElement:()=>{throw Error('new DOM');}};vm.runInContext(source,r);r.TechOpsGameplayExperience.install();assert.equal(r.TechOpsGameplayExperience.VERSION,2);});
test('live upgrade stops old loop and removes only retired owned surfaces',()=>{const removed=[],r=boot();let stopped=0;r.TechOpsGameplayExperience={VERSION:1,stop:()=>stopped++};r.document={getElementById:id=>({remove:()=>removed.push(id)})};vm.runInContext(source,r);assert.equal(stopped,1);assert.deepEqual(removed,['px-objective','px-action','px-impact','production-gameplay-experience-style']);});
test('all eight mission descriptions derive IDs from the actual immutable registry',()=>{const r=boot();for(let m=1;m<=8;m++){scene(r,m);assert.equal(guide(r).id,r.TechOpsLevelRegistry.goodDogsMission(m).id);}});
test('M4 follows actual clue objects and needs three observations, not walking distance',()=>{const r=boot(),n=scene(r,4);n.x=1700;n._v736.evidence=[{x:500,found:true},{x:800,found:false},{x:1100,found:false},{x:1400,found:false}];const g=guide(r);assert.equal(g.phase,'investigate');assert.equal(g.targetX,1400);assert.match(g.detail,/1 \/ 3/);assert.match(g.detail,/LEFT/);assert.doesNotMatch(JSON.stringify(g),/100%|[0-9]m\b|OPEN CELL/);assert.ok(!Object.hasOwn(g,'progress'));});
test('M4 clue completion points to the real cell entrance and does not claim the prisoner free',()=>{const r=boot(),n=scene(r,4);n._v736.evidence=[1,2,3].map(x=>({x,found:true}));assert.equal(guide(r).text,'OPEN CELL 118');assert.equal(guide(r).targetX,r.TechOpsLevelRegistry.goodDogsCell118().entranceX);assert.equal(guide(r).targetX,1600);assert.equal(n._v736.cellOpened,undefined);});
test('M4 empty enemy list cannot certify ambush success',()=>{const r=boot(),n=scene(r,4);n._v736.cellOpened=true;assert.equal(guide(r).phase,'ambush');n._v736._gbCell118AmbushCleared=true;assert.equal(guide(r).phase,'secured');});
test('M4 no K reveal in guidance before the native release',()=>{const r=boot();scene(r,4);assert.doesNotMatch(guide(r).text,/\bK\b/);});
test('M5 empty room does not skip the Mike Index',()=>{const r=boot();scene(r,5);assert.equal(guide(r).phase,'index');});
test('M5 guidance distinguishes boss, incoming security, node and secured route',()=>{const r=boot(),n=scene(r,5),c=n._v736;c._gbMikeIndexDefeated=true;assert.equal(guide(r).phase,'security');n._gbAccessCoreSecuritySeeded=true;n.enemies=[{hp:20,alive:true}];assert.equal(guide(r).phase,'security');n.enemies=[];c.pendingSpawn={};assert.equal(guide(r).phase,'security');c.pendingSpawn=null;assert.equal(guide(r).targetX,1070);assert.equal(guide(r).phase,'node');c._gbAccessNodeSeized=true;assert.equal(guide(r).phase,'secured');});
test('M6 uses actual decrypt seconds and measured surveillance state',()=>{const r=boot(),n=scene(r,6);n._v736.uplink={hp:120};n._v736.decrypt=31.4;r.TechOpsArtHandoff.surveillance=()=>({observed:true,sheltered:false});assert.match(guide(r).detail,/32s.*IN SCAN/);r.TechOpsArtHandoff.surveillance=()=>({observed:false,sheltered:true});assert.match(guide(r).detail,/CATWALK COVER/);});
test('M6 zero decrypt alone cannot imply final wave or release completion',()=>{const r=boot(),n=scene(r,6),c=n._v736;c.uplink={hp:20};c.decrypt=0;assert.equal(guide(r).phase,'final-wave');c._gbFinalWaveComplete=true;assert.equal(guide(r).phase,'release');c._gbWaldoFreed=true;assert.equal(guide(r).phase,'secured');});
test('M6 lost or uninitialized uplink does not look like success',()=>{const r=boot(),n=scene(r,6);assert.equal(guide(r).phase,'initializing');n._v736.uplink={hp:0};assert.equal(guide(r).phase,'failed');});
test('M7 empty boss roster and walking to shuttle cannot bypass tandem guidance',()=>{const r=boot(),n=scene(r,7);n.x=1700;assert.equal(guide(r).phase,'warden');n._v736.sync=100;assert.match(guide(r).detail,/SYNC READY/);n._v736._gbWardenTandemDefeated=true;assert.equal(guide(r).targetX,1580);assert.match(guide(r).detail,/LEFT/);assert.equal(n._v736._gbShuttleReached,undefined);});
test('M3 reads native relay and exit coordinates and phase without invoking mutating helpers',()=>{const r=boot(),n=scene(r,3);r.TechOpsGoodBoysPrisonGameplayV2={RELAY_X:931,EXIT_X:1381};n._v736.prisonOpsV2={phase:'terminal'};assert.equal(guide(r).targetX,931);n._v736.prisonOpsV2.phase='exfil';assert.equal(guide(r).targetX,1381);});
test('M2 pending wave is not an empty-room victory',()=>{const r=boot(),n=scene(r,2);n._v736.pendingSpawn={};assert.match(guide(r).text,/INBOUND/);n._v736.pendingSpawn=null;n._v736.pairPuzzle={solved:false};assert.equal(guide(r).phase,'interlock');});
test('M1 points to Hidden Bay only after trail state exists',()=>{const r=boot(),n=scene(r,1);assert.equal(guide(r).targetX,null);n._gbWaldoTrailComplete=true;assert.equal(guide(r).targetX,1460);});
test('M8 does not manufacture campaign completion',()=>{const r=boot(),n=scene(r,8);assert.equal(guide(r).phase,'home');assert.equal(r.S.meta._v736.done,undefined);});
test('dialog, battle, driving, ending, hidden and presentation-owned surfaces suppress guidance',()=>{for(const cause of ['dialog','battle','drive','ending','hidden','presentation','modal','title']){const r=boot(),n=scene(r,4);if(cause==='dialog')r.S.inDialog=true;if(cause==='battle')r.S.inBattle=true;if(cause==='drive')n.drive={};if(cause==='ending')n._v736.ending=true;if(cause==='hidden')r.document={hidden:true};if(cause==='presentation')r.TechOpsPresentationDirector={isBlocking:()=>true};if(cause==='modal')r.TechOpsProductionWrapperGuard={hasBlockingModal:()=>true};if(cause==='title')r.document={getElementById:()=>({classList:{contains:()=>false},style:{display:'block',visibility:'visible'}})};assert.equal(guide(r),null,cause);}});
test('stale runtime, Day state, game over and canonical mission divergence never show an old objective',()=>{const r=boot(),n=scene(r,4);r.S.meta._v736.m=5;assert.equal(guide(r),null);r.S.meta._v736.m=4;r.S.nightMode=false;assert.equal(guide(r),null);r.S.nightMode={};assert.equal(guide(r),null);r.S.nightMode=n;r.S.gameOver=true;assert.equal(guide(r),null);});
test('invalid missions fail closed without repairing or clamping the save',()=>{const r=boot(),n=scene(r,4);for(const value of [0,9,4.5,NaN,'__proto__']){n._v736.m=value;assert.equal(guide(r),null);assert.equal(r.S.meta._v736.m,4);}});
test('all read models accept frozen runtime and preserve all save/mission fields',()=>{for(let m=1;m<=8;m++){const r=boot(),n=scene(r,m);freeze(n);freeze(r.S);const before=JSON.stringify(r.S);for(let i=0;i<30;i++)guide(r);assert.equal(JSON.stringify(r.S),before);}});
test('the native HUD consumes guidance in its original objective slot',()=>{const r=boot(),n=scene(r,4);r.TechOpsGoodBoysCanon={SEQUENCE:{4:{name:'CELL 118',objective:'old'}}};vm.runInContext(fs.readFileSync('good_boys_hud_lite.js','utf8'),r);const ctx=canvas();r.TechOpsGoodBoysHudLite.drawHud(ctx,n);assert.ok(ctx.words.includes('VERIFY THE PRISONER'));assert.ok(ctx.words.includes('0 / 3 REQUIRED CLUES'));assert.ok(ctx.words.includes('KATRIN'));assert.ok(ctx.words.includes('MANCHEZ'));});
test('Night status preserves explicit clear and pending state and excludes other modes',()=>{const r=boot(),n=scene(r,1);delete n._v736;n.district='downtown';const api=r.TechOpsGameplayExperience;assert.equal(api.streetStatus(n),'CHECK THE STREET');n.clear=true;assert.match(api.streetStatus(n),/SECURED/);n.wavePending=true;assert.match(api.streetStatus(n),/INBOUND/);n.enemies=[{hp:20,alive:true}];assert.equal(api.streetStatus(n),'1 HOSTILES');n._sector04={};assert.equal(api.streetStatus(n),'');});
test('landmark utilities return real finite metadata without a fake endpoint after route end',()=>{const r=boot(),row={stage:{landmarks:[{x:300},{x:100},{x:NaN}]}},a=r.TechOpsGameplayExperience;assert.equal(a.nextLandmark(row,400),null);assert.equal(a.nextLandmark(row,150).x,300);assert.equal(a.nearestLandmark(row,140).mark.x,100);assert.equal(row.stage.landmarks[0].x,300);});
test('paused missions cannot leak objective guidance',()=>{const r=boot(),n=scene(r,4);r.S.paused=true;assert.equal(guide(r),null);delete n._v736;n.district='downtown';assert.equal(r.TechOpsGameplayExperience.streetStatus(n),'');});
test('classic-script state takes precedence over stale window aliases',()=>{const r=boot(),n=scene(r,4);vm.runInContext('let S={nightMode:NM,paused:true};',r);assert.equal(r.TechOpsGameplayExperience.objective(n),null);});
test('classic-script world is used when no explicit world is supplied',()=>{const r=boot(),n=scene(r,4);r.realWorld=n;r.NM={};vm.runInContext('let NM=realWorld;',r);assert.equal(r.TechOpsGameplayExperience.objective().mission,4);});
console.log('Gameplay experience: '+tests+' tests passed');
