window.applyJuice=function(h){
const vars="var wave=1,fever=0,feverActive=false,feverTime=0,wavePending=false,nextWaveTimer=0,waveStart=0,beatOrigin=0,bestScore=parseInt(localStorage.getItem('brBestScore')||'0',10),bestCombo=parseInt(localStorage.getItem('brBestCombo')||'0',10),popTimer=0;";
const helpers=`
function mult(){return Math.min(5,1+Math.floor(Math.max(0,combo-1)/5)*.5)*(feverActive?2:1)}
function saveBest(){if(score>bestScore){bestScore=score;localStorage.setItem('brBestScore',score)}if(combo>bestCombo){bestCombo=combo;localStorage.setItem('brBestCombo',combo)}}
function pop(t,c){var e=document.getElementById('rewardPop');if(!e)return;e.textContent=t;e.style.color=c||'#00ff88';e.style.opacity=1;e.style.transform='translate(-50%,-50%) scale(1.12)';clearTimeout(popTimer);popTimer=setTimeout(function(){e.style.opacity=0;e.style.transform='translate(-50%,-50%) scale(.92)'},520)}
function rewardHUD(){var w=document.getElementById('waveHud'),f=document.getElementById('feverHud'),b=document.getElementById('feverFill'),x=document.getElementById('bestHud');if(w)w.textContent='WAVE '+wave+' • '+enemies.length+' LEFT';if(f)f.textContent=feverActive?'🔥 FEVER '+feverTime.toFixed(1)+'s':'FEVER '+Math.floor(fever)+'%';if(b)b.style.width=(feverActive?100:fever)+'%';if(x)x.textContent='BEST '+bestScore+' • CHAIN '+bestCombo}
function addFever(n){if(feverActive)return;fever=Math.min(100,fever+n);if(fever>=100){feverActive=true;feverTime=8;fever=100;pop('FEVER ×2 • 8s','#ffee55');tone(220,.12,.17);setTimeout(function(){tone(330,.12,.15)},90);setTimeout(function(){tone(440,.15,.13)},180)}rewardHUD()}
function onBeat(){var p=(performance.now()-beatOrigin)%500;return p<105||p>395}
function waveDone(){if(wavePending||enemies.length)return;wavePending=true;nextWaveTimer=1.15;var sec=(performance.now()-waveStart)/1000,bonus=Math.max(0,Math.floor((22-sec)*30));if(bonus){score+=bonus;pop('FAST CLEAR +'+bonus,'#55ddff')}else pop('WAVE CLEAR','#00ff88');health=Math.min(100,health+8);saveBest();updateUI()}
`;
const gems=`function createGems(count){count=count===undefined?(gems.length?10:25):count;for(var i=0;i<count;i++){var rare=Math.random()<.12,gm=mat(rare?0xffd33d:0x00ff88,{emissive:rare?0xffaa00:0x00ff88,emissiveIntensity:rare?1.2:.8,transparent:true,opacity:.94}),g=new THREE.Mesh(new THREE.OctahedronGeometry(rare?.52:.4),gm);if(i<platforms.length*2&&platforms.length){var p=platforms[i%platforms.length];g.position.set(p.x+(Math.random()-.5)*(p.w-1),p.y+p.h/2+1,p.z+(Math.random()-.5)*(p.d-1))}else g.position.set((Math.random()-.5)*40,1+Math.random()*3,(Math.random()-.5)*40);g.userData.spin=Math.random()*.05+.02;g.userData.bobOffset=Math.random()*Math.PI*2;g.userData.rare=rare;scene.add(g);gems.push(g)}}`;
const enemies=`function createEnemies(count){count=count||Math.min(22,6+wave*2);for(var i=0;i<count;i++){var e=new THREE.Group(),elite=wave>2&&Math.random()<Math.min(.28,.05+wave*.025),body=mat(elite?0x3a002f:0x330000,{roughness:.8}),red=mat(elite?0xff35c8:0xff0000,{emissive:elite?0xff35c8:0xff0000,emissiveIntensity:.65}),b=new THREE.Mesh(new THREE.BoxGeometry(elite?.82:.7,elite?1.15:1,elite?.6:.5),body);b.position.y=.8;e.add(b);var hd=new THREE.Mesh(new THREE.BoxGeometry(.5,.5,.5),body);hd.position.y=1.6;e.add(hd);var eye=new THREE.Mesh(new THREE.SphereGeometry(.08,6,6),red);eye.position.set(-.12,1.65,.26);e.add(eye);var eye2=eye.clone();eye2.position.x=.12;e.add(eye2);var a=new THREE.Mesh(new THREE.BoxGeometry(.2,.6,.2),body);a.position.set(-.45,.8,0);e.add(a);var a2=a.clone();a2.position.x=.45;e.add(a2);var l=new THREE.Mesh(new THREE.BoxGeometry(.25,.6,.25),body);l.position.set(-.15,.3,0);e.add(l);var l2=l.clone();l2.position.x=.15;e.add(l2);e.userData={health:(elite?3:2)+Math.floor((wave-1)/4),speed:.014+Math.random()*.012+Math.min(.012,wave*.0012),walkCycle:0,armL:a,armR:a2,legL:l,legR:l2,hitTimer:0,elite:elite};var x,z;do{x=(Math.random()-.5)*40;z=(Math.random()-.5)*40}while(Math.abs(x)<6&&Math.abs(z)<6);e.position.set(x,0,z);scene.add(e);enemies.push(e)}rewardHUD()}`;
const attack=`function performAttack(){if(attackCooldown>0||!gameStarted||gameOver)return;var beat=onBeat(),hit=false;attackCooldown=feverActive?.22:.36;player.userData.attacking=true;player.userData.attackTime=0;tone(beat?190:150,.12,.18);var geo=new THREE.RingGeometry(.45,feverActive?2.35:2.05,20),am=new THREE.MeshBasicMaterial({color:beat?0x88ffcc:0x00ff88,transparent:true,opacity:.82,side:THREE.DoubleSide}),ring=new THREE.Mesh(geo,am);ring.position.copy(player.position);ring.position.y+=1.45;ring.rotation.x=-Math.PI/2;scene.add(ring);var st=performance.now();(function fx(now){var q=(now-st)/240;ring.scale.setScalar(1+q*2.25);am.opacity=.82*(1-q);if(q<1)requestAnimationFrame(fx);else scene.remove(ring)})(st);for(var i=enemies.length-1;i>=0;i--){var en=enemies[i],d=player.position.distanceTo(en.position);if(d<(feverActive?3.45:3.05)){hit=true;en.userData.health--;en.userData.hitTimer=.18;var dir=new THREE.Vector3().subVectors(en.position,player.position).normalize();en.position.add(dir.multiplyScalar(beat?1.45:1));if(beat){score+=Math.round(12*mult());addFever(5)}if(en.userData.health<=0){var pts=en.userData.elite?100:50,m=mult();score+=Math.round(pts*m);combo+=en.userData.elite?3:2;comboTimer=feverActive?6:4.25;addFever(en.userData.elite?32:20);if(en.userData.elite)pop('ELITE DOWN +'+Math.round(pts*m),'#ff66dd');else if(beat)pop('ON BEAT +'+Math.round(pts*m+12*m),'#88ffcc');deathFx(en.position);scene.remove(en);enemies.splice(i,1);saveBest();updateUI()}}}if(hit&&beat){combo++;comboTimer=feverActive?6:4.25;saveBest()}waveDone()}`;
const pickup=`function updateGems(){for(var i=gems.length-1;i>=0;i--){var g=gems[i];g.rotation.y+=g.userData.spin;g.position.y+=Math.sin(Date.now()*.002+g.userData.bobOffset)*.005;if(player.position.distanceTo(g.position)<1.5){var rare=!!g.userData.rare,m=mult(),pts=rare?50:10;scene.remove(g);gems.splice(i,1);score+=Math.round(pts*m);combo+=rare?2:1;comboTimer=feverActive?6:4.25;addFever(rare?22:6);if(rare){health=Math.min(100,health+5);pop('GOLD DROP +'+Math.round(pts*m),'#ffd84a');tone(880,.15,.17)}else tone(660,.1,.13);saveBest();updateUI();var s=new THREE.Mesh(new THREE.SphereGeometry(rare?.72:.5,8,8),new THREE.MeshBasicMaterial({color:rare?0xffd84a:0x00ff88,transparent:true,opacity:.8}));s.position.copy(g.position);s.userData.life=1;s.userData.isSparkle=true;scene.add(s);particles.push(s)}}if(gems.length<7)createGems(10)}`;
const ui=`function updateUI(){saveBest();var m=mult();document.getElementById('score').textContent='💎 '+score+(m>1?' ×'+m.toFixed(1):'');document.getElementById('health').textContent='❤️ '+Math.max(0,health);var c=document.getElementById('combo');if(combo>1){c.textContent='CHAIN '+combo+' • ×'+m.toFixed(1);c.style.fontSize=(18+Math.min(combo,12)*1.5)+'px';c.style.color=feverActive?'#ffee55':'#ffaa00'}else c.textContent='';rewardHUD()}`;
const animate=`function animate(time){requestAnimationFrame(animate);var delta=Math.min((time-lastTime)/1000,.1)||0;lastTime=time;if(gameStarted&&!gameOver){updatePlayer(delta);updateEnemies(delta);updateGems();if(feverActive){feverTime-=delta;if(feverTime<=0){feverActive=false;fever=0;feverTime=0;pop('FEVER OVER','#aaa');updateUI()}}if(comboTimer>0&&!feverActive){comboTimer-=delta;if(comboTimer<=0){combo=0;updateUI()}}if(wavePending){nextWaveTimer-=delta;if(nextWaveTimer<=0){wave++;wavePending=false;waveStart=performance.now();createEnemies();createGems(6);pop('WAVE '+wave,'#55ddff');tone(260,.12,.16);setTimeout(function(){tone(390,.13,.14)},100);updateUI()}}}updateParticles(delta);updateCamera();updateMinimap();renderer.render(scene,camera)}`;
h=h.replace("var scene,camera,renderer,player,gems=[],enemies=[],particles=[],platforms=[],score=0,health=100,combo=0,comboTimer=0,gameStarted=false,gameOver=false,keys={},cameraAngle=0,cameraPitch=.3,velocity={x:0,y:0,z:0},onGround=false,attackCooldown=0,beatPulse=0,audioCtx=null,isMobile=('ontouchstart'in window)||navigator.maxTouchPoints>0,lastTime=0;","var scene,camera,renderer,player,gems=[],enemies=[],particles=[],platforms=[],score=0,health=100,combo=0,comboTimer=0,gameStarted=false,gameOver=false,keys={},cameraAngle=0,cameraPitch=.3,velocity={x:0,y:0,z:0},onGround=false,attackCooldown=0,beatPulse=0,audioCtx=null,isMobile=('ontouchstart'in window)||navigator.maxTouchPoints>0,lastTime=0;"+vars);
h=h.replace('<div id="ui"><div id="score">💎 0</div><div id="health">❤️ 100</div><div id="combo"></div><div id="message"></div></div>','<div id="ui"><div id="score">💎 0</div><div id="health">❤️ 100</div><div id="combo"></div><div id="waveHud" style="position:absolute;top:92px;left:20px;font:700 14px monospace;color:#55ddff">WAVE 1</div><div id="feverHud" style="position:absolute;top:116px;left:20px;font:700 13px monospace;color:#ffee55">FEVER 0%</div><div style="position:absolute;top:136px;left:20px;width:150px;height:7px;border:1px solid rgba(255,238,85,.5)"><div id="feverFill" style="height:100%;width:0;background:#ffee55;box-shadow:0 0 8px #ffee55"></div></div><div id="bestHud" style="position:absolute;top:154px;left:20px;font:700 11px monospace;color:#8a8a9a"></div><div id="rewardPop" style="position:absolute;top:40%;left:50%;transform:translate(-50%,-50%) scale(.92);font:900 26px monospace;opacity:0;transition:.18s;text-shadow:0 0 16px currentColor;white-space:nowrap"></div><div id="message"></div></div>');
h=h.replace(/function init\(\)\{/,helpers+'function init(){');
h=h.replace(/function createGems\(\)\{[\s\S]*?\}\nfunction createEnemies/,gems+'\nfunction createEnemies');
h=h.replace(/function createEnemies\(\)\{[\s\S]*?\}\nfunction setupControls/,enemies+'\nfunction setupControls');
h=h.replace(/function startGame\(\)\{[\s\S]*?\}\nfunction performAttack/,"function startGame(){startScreen.style.display='none';gameStarted=true;waveStart=performance.now();beatOrigin=performance.now();initAudio();pop('CHAIN • FEVER • WAVES','#00ff88');updateUI();if(!isMobile&&gameCanvas.requestPointerLock)gameCanvas.requestPointerLock()}\nfunction performAttack");
h=h.replace(/function performAttack\(\)\{[\s\S]*?\}\nfunction deathFx/,attack+'\nfunction deathFx');
h=h.replace(/function updateGems\(\)\{[\s\S]*?\}\nfunction updateParticles/,pickup+'\nfunction updateParticles');
h=h.replace(/function updateUI\(\)\{[\s\S]*?\}function showMessage/,ui+'function showMessage');
h=h.replace(/function animate\(time\)\{[\s\S]*?\}\naddEventListener\('resize'/,animate+"\naddEventListener('resize'");
h=h.replace("var sp=(keys.shift?.25:.15)*(delta*60),r=","var sp=(keys.shift?.25:.15)*(delta*60)*(feverActive?1.18:1),r=");
h=h.replace('Play as the Beat Master — collect gems and defeat enemies.','Chain hits, stay on beat, trigger FEVER, and survive escalating waves.');
h=h.replace('TESTER BUILD • REFERENCE MODEL + CONTROL FIX','TESTER BUILD • JUICE LOOP');
return h;
};
