/* Deterministic packing of ImageGen-authored art. No poses are synthesized.
 * Usage: node scripts/build_visual_combat.cjs [directory of original PNGs]
 * Without an argument, rebuilds sprites from the checked-in lossless sources.
 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),out=path.join(root,'assets/visual-combat'),sourceDir=path.join(out,'source');
const source=process.argv[2];
const sheets=[
 ['punch','exec-ccc4d5ab-ea86-4e7c-a0fe-0ff0bb61ced2.png',[0,267,520,809,1024],['jab','cross','uppercut','low']],
 ['kick','exec-e7aba934-997c-4644-827e-17ef1ff607df.png',[0,266,533,729,1024],['kick','rising-kick','sweep','launcher']],
 ['air','exec-e9b126cf-1b36-4975-9aa0-2cef1af47920.png',[0,264,500,771,1024],['air','air-kick','air-slam','dash']],
 ['grapple','exec-4013140a-a5a6-4b66-8993-1c88bd73c678.png',[0,264,511,770,1024],['grab','throw','throw-up','throw-down']],
 ['defence','exec-60d2c8f6-6f82-4426-900e-0af541b0f560.png',[0,270,531,772,1024],['block','hurt','down','get-up']]
];
const plates=[
 ['industrial','exec-fe900f7d-6d0a-43b3-b558-df31716db199.png','QA-011',.60],
 ['longwharf','exec-1a83076c-fb0a-4e03-9c92-34bb719a3761.png','QA-015',.60],
 ['gooddogs-home','exec-e38f9412-6fad-422d-874a-614729b1cc88.png','QA-017',.61],
 ['waldo','exec-ea49455a-f86d-4649-b473-4419f5ced28c.png','QA-025',500/793],
 ['home','exec-88a62320-4ce5-47d9-917c-ee32e02bbc0b.png','QA-027',490/793]
];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function rawImage(file){return sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true});}
function extract(raw,rect){
 const [sx,sy,w,h]=rect,b=Buffer.alloc(w*h*4);let minX=w,minY=h,maxX=-1,maxY=-1;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){
  const s=((sy+y)*raw.info.width+sx+x)*4,d=(y*w+x)*4,r=raw.data[s],g=raw.data[s+1],blue=raw.data[s+2];
  if(r>140&&blue>140&&r-g>75&&blue-g>75)continue;
  b[d]=r;b[d+1]=g;b[d+2]=blue;b[d+3]=raw.data[s+3];
  if(b[d+3]){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}
 }
 if(maxX<0)throw Error('Empty source frame '+rect);
 return {data:b,width:w,height:h,bounds:[minX,minY,maxX-minX+1,maxY-minY+1]};
}
async function cropped(frame){const [left,top,width,height]=frame.bounds;return sharp(frame.data,{raw:{width:frame.width,height:frame.height,channels:4}}).extract({left,top,width,height});}
async function main(){
 fs.mkdirSync(sourceDir,{recursive:true});const sources={};
 for(const [id,file] of sheets){
  const dst=path.join(sourceDir,id+'.webp');
  if(source)await sharp(path.join(source,file)).webp({lossless:true,effort:6}).toFile(dst);
  sources[id]={path:'assets/visual-combat/source/'+id+'.webp',sha256:hash(fs.readFileSync(dst))};
 }
 const C=176,H=144,standingHeight=96,scale=96/221,composites=[],moves={};let index=0;
 for(const [id,,rows,names] of sheets){
  const raw=await rawImage(path.join(sourceDir,id+'.webp'));if(raw.info.width!==1536||raw.info.height!==1024)throw Error('Unexpected sheet dimensions '+id);
  for(let row=0;row<4;row++){
   const frames=[];
   for(let col=0;col<4;col++){
    const sourceRect=[col*384,rows[row],384,rows[row+1]-rows[row]],frame=extract(raw,sourceRect),[bx,by,bw,bh]=frame.bounds;
    let anchor=192;
    if(!names[row].startsWith('air')&&!['down','get-up'].includes(names[row])){
     let sum=0,count=0;for(let y=Math.max(by,by+bh-7);y<by+bh;y++)for(let x=bx;x<bx+bw;x++)if(frame.data[(y*384+x)*4+3]){sum+=x;count++;}
     anchor=sum/count;
    }
    const w=Math.round(bw*scale),h=Math.round(bh*scale),left=Math.round(C/2+(bx-anchor)*scale),top=H-6-h;
    if(left<0||left+w>C||top<0)throw Error('Packed frame clipped: '+names[row]+' '+col);
    const cut=await cropped(frame),buf=await cut.resize(w,h,{kernel:'nearest'}).png().toBuffer();
    const dest=[(index%4)*C,Math.floor(index/4)*H,C,H];
    composites.push({input:buf,left:dest[0]+left,top:dest[1]+top});
    frames.push({rect:dest,pivot:[C/2,H-6],sourceRect,sourceBounds:frame.bounds,anchorX:Number(anchor.toFixed(2))});index++;
   }
   moves[names[row]]={source:id,frames};
  }
 }
 const atlas=await sharp({create:{width:C*4,height:H*Math.ceil(index/4),channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(composites).png().toBuffer();
 fs.writeFileSync(path.join(out,'mike-moves.png'),atlas);
 const manifest={version:1,src:'assets/visual-combat/mike-moves.png',sha256:hash(atlas),standingHeight,cell:[C,H],frameCount:index,moves,sources};
 fs.writeFileSync(path.join(out,'mike-moves.json'),JSON.stringify(manifest,null,2)+'\n');
 fs.writeFileSync(path.join(root,'night_move_atlas.js'),'/* Generated by scripts/build_visual_combat.cjs. */\n(function(r){r.TECHOPS_NIGHT_MOVE_ATLAS='+JSON.stringify(manifest)+';})(typeof globalThis!=="undefined"?globalThis:this);\n');
 if(source){
  const pmeta={version:1,provenance:'ImageGen cleanup of real-frame concept overpaints; these are assets, not gameplay screenshots.',plates:{}};
  const captures=JSON.parse(fs.readFileSync(path.join(root,'docs/visual-combat/capture-manifest.json'))).captures;
  for(const [id,file,qa,groundRatio] of plates){const src=path.join(source,file),dst=path.join(out,id+'.webp');await sharp(src).webp({quality:92,effort:6}).toFile(dst);const meta=await sharp(dst).metadata(),capture=captures.find(c=>c.id===qa);pmeta.plates[id]={src:'assets/visual-combat/'+id+'.webp',qa,groundRatio,width:meta.width,height:meta.height,sourceSha256:hash(fs.readFileSync(src)),sha256:hash(fs.readFileSync(dst)),capture:{path:'docs/visual-combat/'+capture.file,sha256:capture.sha256}};}
  fs.writeFileSync(path.join(out,'scene-sources.json'),JSON.stringify(pmeta,null,2)+'\n');
  const propSrc=path.join(source,'exec-d01cdb36-4947-457b-a42b-db10565386fa.png');
  await sharp(propSrc).webp({lossless:true,effort:6}).toFile(path.join(sourceDir,'props.webp'));
 }
 const propRaw=await rawImage(path.join(sourceDir,'props.webp')),props={},pcomp=[];
 const rects=[[75,100,560,460],[675,130,340,440],[1125,105,345,460],[1560,200,420,365]];
 for(const [i,name] of ['mower','grill','dish','chest'].entries()){
  const rect=rects[i].map(v=>Math.round(v*propRaw.info.width/2048));
  const f=extract(propRaw,rect),cut=await cropped(f),w=Math.round(f.bounds[2]*.25),h=Math.round(f.bounds[3]*.25);
  const b=await cut.resize(w,h,{kernel:'nearest'}).png().toBuffer();pcomp.push({input:b,left:i*160+Math.round((160-w)/2),top:138-h});props[name]={rect:[i*160,0,160,144],pivot:[80,138],height:h,sourceRect:rect};
 }
 await sharp({create:{width:640,height:144,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(pcomp).png().toFile(path.join(out,'waldo-props.png'));
 fs.writeFileSync(path.join(out,'waldo-props.json'),JSON.stringify(props,null,2)+'\n');
 console.log('Packed '+index+' reviewed keyframes, five scene plates, four property props.');
}
main().catch(e=>{console.error(e);process.exit(1);});
