import fs from 'node:fs';
import path from 'node:path';
import { webkit, devices } from 'playwright';
const BASE=process.env.BOT_BASE_URL||'http://127.0.0.1:4173/';const OUT=process.env.BOT_OUT_DIR||'runtime-bot-artifacts';fs.mkdirSync(OUT,{recursive:true});const failures=[],events=[];const log=(name,data={})=>{events.push({at:new Date().toISOString(),name,...data});console.log(name,JSON.stringify(data));};const fail=(name,data={})=>{failures.push({name,...data});log('FAIL '+name,data);};
async function clickLaunch(page){for(const b of await page.locator('button').all()){const t=(await b.innerText().catch(()=>'' )).trim();if(/118\/1984|BREAKOUT|GOOD\s*BOYS/i.test(t)){await b.click({timeout:1500});return t;}}return null;}
async function snap(page){return page.evaluate(()=>{const o=document.getElementById('good-dogs-cutscene-overlay'),v=o&&o.querySelector('.gd-film-video'),p=document.getElementById('good-boys-campaign-intro'),s=window.S,c=window.NM&&window.NM._v736;return{active:!!(o&&o.classList.contains('active')),src:v?(v.currentSrc||v.getAttribute('src')||''):'',muted:v?!!v.muted:null,volume:v?Number(v.volume):null,premise:!!p,premiseCount:document.querySelectorAll('#good-boys-campaign-intro').length,premiseText:p?p.textContent:'',premiseButton:p&&p.querySelector('button')?p.querySelector('button').textContent:'',legacyStoryCount:document.querySelectorAll('#good-boys-story-cine').length,legacyFollowTrail:[...document.querySelectorAll('button')].filter(b=>/FOLLOW THE TRAIL/i.test(b.textContent||'')).length,state:window.__goodDogsCutsceneState||{},campaign:!!c,mission:Number(c&&c.m||0),titleVisible:(()=>{const t=document.getElementById('title-screen');return!!(t&&!t.classList.contains('hidden')&&getComputedStyle(t).display!=='none');})(),repairVersion:window.TechOpsGoodBoysIntroRepair&&window.TechOpsGoodBoysIntroRepair.VERSION||0,sState:s&&s.meta&&s.meta.goodDogsCutscenes||null};});}
function assertSingleOwner(a,phase){if(a.repairVersion<8)fail('intro-owner-v8-missing',{phase,...a});if(a.legacyStoryCount)fail('legacy-director-premise-visible',{phase,...a});if(a.legacyFollowTrail)fail('retired-follow-trail-cta-visible',{phase,...a});if(a.premiseCount>1)fail('duplicate-canonical-premise',{phase,...a});}
const browser=await webkit.launch({headless:true});const context=await browser.newContext({...devices['iPhone 15 Pro'],viewport:{width:393,height:852}});const page=await context.newPage();
try{await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1500);let a=await snap(page);assertSingleOwner(a,'title');const clicked=await clickLaunch(page);if(!clicked)throw new Error('Good Boys launch button missing');log('launch',{clicked});
await page.waitForSelector('#good-dogs-cutscene-overlay.active',{state:'visible',timeout:3500});a=await snap(page);log('clip1',a);assertSingleOwner(a,'clip1');if(!/01_signal_beyond_earth_pixel\.mp4/i.test(a.src))fail('clip1-order',a);if(a.muted!==true||a.volume!==0)fail('clip1-not-silent',a);await page.screenshot({path:path.join(OUT,'goodboys-clip1.png')});await page.locator('#good-dogs-cutscene-overlay.active .gd-film-skip').click({timeout:1500});
await page.waitForFunction(()=>{const v=document.querySelector('#good-dogs-cutscene-overlay.active .gd-film-video');return !!(v&&/02_signal_pull_transition_pixel\.mp4/i.test(v.currentSrc||v.getAttribute('src')||''));},null,{timeout:3500});a=await snap(page);log('clip2',a);assertSingleOwner(a,'clip2');if(a.muted!==true||a.volume!==0)fail('clip2-not-silent',a);await page.screenshot({path:path.join(OUT,'goodboys-clip2.png')});await page.locator('#good-dogs-cutscene-overlay.active .gd-film-skip').click({timeout:1500});
await page.waitForSelector('#good-boys-campaign-intro',{state:'visible',timeout:3500});await page.waitForTimeout(180);a=await snap(page);log('premise',a);assertSingleOwner(a,'premise');if(a.premiseCount!==1)fail('premise-not-singleton',a);if(!/TAKE CONTROL/i.test(a.premiseButton))fail('wrong-premise-cta',a);if(!/taken the ship/i.test(a.premiseText)||!/Cell 118/i.test(a.premiseText)||!/Cell 1984/i.test(a.premiseText))fail('premise-logic',a);if(a.active)fail('film-overlaps-premise',a);await page.screenshot({path:path.join(OUT,'goodboys-premise.png')});await page.locator('#good-boys-campaign-intro button').click({timeout:1500});
await page.waitForFunction(()=>!!(window.NM&&window.NM._v736),null,{timeout:8000});await page.waitForTimeout(500);a=await snap(page);log('gameplay',a);assertSingleOwner(a,'gameplay');if(!a.campaign||a.mission!==1)fail('gameplay-handoff',a);if(a.titleVisible)fail('title-visible-after-handoff',a);if(a.active||a.premise)fail('opening-overlay-remains',a);if(!(a.sState&&a.sState.GD_CUT_01&&a.sState.GD_CUT_02))fail('opening-state-not-migrated',a);await page.waitForTimeout(500);a=await snap(page);assertSingleOwner(a,'settled-gameplay');if(a.active)fail('opening-replayed-after-handoff',a);await page.screenshot({path:path.join(OUT,'goodboys-gameplay.png')});
}catch(e){fail('bot-exception',{error:String(e&&e.stack||e)});await page.screenshot({path:path.join(OUT,'goodboys-exception.png')}).catch(()=>{});}finally{await browser.close();}const report={pass:failures.length===0,failures,events};fs.writeFileSync(path.join(OUT,'goodboys-intro-mobile.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
