import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
const BASE=process.env.BOT_BASE_URL||'http://127.0.0.1:4173/';
const OUT=process.env.BOT_OUT_DIR||'runtime-bot-artifacts';fs.mkdirSync(OUT,{recursive:true});
const events=[],failures=[];const log=(name,data={})=>{events.push({at:new Date().toISOString(),name,...data});console.log(name,JSON.stringify(data));};const fail=(name,data={})=>{failures.push({name,...data});log('FAIL '+name,data);};
async function clickMatching(page,re){for(const b of await page.locator('button').all()){const t=(await b.innerText().catch(()=>'' )).trim();if(re.test(t)){await b.evaluate(el=>el.click());return t;}}return null;}
async function click(page,sel){return page.evaluate(s=>{const el=document.querySelector(s);if(!el)return false;el.click();return true;},sel).catch(()=>false);}
async function snap(page){return page.evaluate(()=>{const s=window.S||null,n=window.NM||null,c=n&&n._v736,m=s&&s.meta&&s.meta._v736,a=window.TechOpsGoodBoysProgressionAuthority,cs=window.TechOpsGoodBoysCampaignState;return{phase:window.__goodBoysOpeningPhase||null,openingError:window.__goodBoysOpeningErrorDetail||null,mission:Number(c&&c.m||0),metaMission:Number(m&&m.m||0),stateMission:cs&&cs.mission?Number(cs.mission()):0,pair:!!(c&&c.chars&&c.chars.katrin&&c.chars.manchez),activeDog:c&&c.active||null,authority:!!a,campaignState:!!cs,bibleWorld:!!window.TechOpsGoodBoysBibleWorld,backgroundAuthority:!!window.TechOpsGoodBoysBackgroundAuthority,accessCore:!!window.TechOpsGoodBoysAccessCoreAuthority,earthfall:!!window.TechOpsGoodBoysEarthfallEnding,acceptance:a&&a.acceptance?a.acceptance():null,deck:window.__goodBoysDeckAssetState||null,flight:window.__goodBoysSpaceFlight||null,crash:window.__goodBoysCrashScene||null};});}
async function skipFilm(page,part){await page.waitForFunction(p=>{const o=document.querySelector('#good-dogs-cutscene-overlay.active'),v=o&&o.querySelector('video');return !!(o&&v&&String(v.currentSrc||v.getAttribute('src')||'').includes(p));},part,{timeout:10000});if(!await click(page,'#good-dogs-cutscene-overlay.active .gd-film-skip'))throw new Error('cutscene skip unavailable: '+part);}
async function clearBlockingCines(page,ms=5000){const until=Date.now()+ms;while(Date.now()<until){let acted=false;for(const sel of ['#gb-prison-cine button','#good-boys-earthfall-cine button','#good-boys-story-cine button','#dialogue:not(.hidden) #dlg-options button']){if(await page.locator(sel).count()&&await page.locator(sel).first().isVisible().catch(()=>false)){await page.locator(sel).first().evaluate(el=>el.click()).catch(()=>{});acted=true;break;}}if(!acted)return;await page.waitForTimeout(120);}}
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:800}});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();
try{
  await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1500);if(!await clickMatching(page,/(118\/1984|BREAKOUT|GOOD\s*BOYS)/i))throw new Error('Good Boys launch button missing');
  await page.waitForSelector('#good-boys-deck-supplied',{state:'visible',timeout:9000});const d=await snap(page);log('cockpit',d);if(!d.deck||d.deck.nonBlocking!==true)fail('cockpit-blocking-on-image',d);if(!await click(page,'#good-boys-deck-supplied button'))throw new Error('cockpit interaction unavailable');
  await skipFilm(page,'02_signal_pull_transition_pixel.mp4');await page.waitForSelector('#good-boys-flight-v4',{state:'visible',timeout:7000});await page.waitForFunction(()=>window.__goodBoysSpaceFlight&&window.__goodBoysSpaceFlight.completed===true,null,{timeout:8000});
  await skipFilm(page,'03_orbital_approach_pixel.mp4');await page.waitForSelector('#good-boys-crash-canonical',{state:'visible',timeout:7000});await page.waitForFunction(()=>window.__goodBoysCrashScene&&window.__goodBoysCrashScene.completed===true,null,{timeout:10000});
  await page.waitForFunction(()=>window.NM&&window.NM._v736&&Number(window.NM._v736.m)===3,null,{timeout:7000});await clearBlockingCines(page,2500);let s=await snap(page);log('m3-start',s);
  if(s.openingError)fail('opening-error',s);if(s.mission!==3||s.metaMission!==3||s.stateMission!==3)fail('opening-did-not-canonically-enter-m3',s);if(!s.pair)fail('good-dogs-pair-not-attached',s);if(!s.authority||!s.campaignState||!s.accessCore||!s.earthfall)fail('campaign-authorities-not-attached',s);if(s.acceptance&&s.acceptance.invariant&&s.acceptance.invariant.ok===false)fail('opening-handoff-invariant-failed',s);
  const primed=await page.evaluate(()=>window.TechOpsGoodBoysProgressionAuthority&&window.TechOpsGoodBoysProgressionAuthority.testPrimeClear?window.TechOpsGoodBoysProgressionAuthority.testPrimeClear():false);log('m3-prime-clear',{primed});if(!primed)fail('m3-prime-clear-unavailable',s);
  const until=Date.now()+9000;while(Date.now()<until){await clearBlockingCines(page,700);s=await snap(page);if(s.mission===4||s.metaMission===4||s.stateMission===4)break;await page.waitForTimeout(120);}log('m4-result',s);if(s.mission!==4&&s.metaMission!==4&&s.stateMission!==4)fail('m3-did-not-progress-to-m4',s);
  await page.screenshot({path:path.join(OUT,'goodboys-progression-m4.png')});
}catch(e){fail('bot-exception',{error:String(e&&e.stack||e),state:await snap(page).catch(()=>null)});await page.screenshot({path:path.join(OUT,'goodboys-progression-exception.png')}).catch(()=>{});}finally{await context.tracing.stop({path:path.join(OUT,'goodboys-progression-trace.zip')}).catch(()=>{});await browser.close();}
const report={pass:failures.length===0,contract:'cockpit -> takeover -> flight -> approach -> crash -> M3 -> M4',failures,events};fs.writeFileSync(path.join(OUT,'goodboys-progression.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;