import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';

const BASE=process.env.BOT_BASE_URL||'http://127.0.0.1:4173/';
const OUT=process.env.BOT_OUT_DIR||'runtime-bot-artifacts';
fs.mkdirSync(OUT,{recursive:true});
const events=[],failures=[];
const log=(name,data={})=>{events.push({at:new Date().toISOString(),name,...data});console.log(name,JSON.stringify(data));};
const fail=(name,data={})=>{failures.push({name,...data});log('FAIL '+name,data);};
async function clickText(page,re){for(const b of await page.locator('button').all()){let t='';try{t=(await b.innerText()).trim();}catch{}if(re.test(t)){try{await b.evaluate(el=>{el.click();return true;});return true;}catch{}}}return false;}
async function domClick(page,selector){return page.evaluate(sel=>{const el=document.querySelector(sel);if(!el)return false;el.click();return true;},selector).catch(()=>false);}
async function moveShipTo(page,id){
  const result=await page.evaluate(async target=>{
    const right=document.querySelector('#good-boys-ship-interlude [data-move="right"]');
    const interact=document.querySelector('#good-boys-ship-interlude [data-interact]');
    if(!right||!interact)return {ok:false,error:'mobile controls missing'};
    const before=window.__goodBoysOpeningGameplay||{};const xStart=Number(before.x||0);const pointerId=51;
    const fire=(el,type,buttons)=>el.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId,pointerType:'touch',isPrimary:true,buttons}));
    fire(right,'pointerdown',1);let moved=false,last=xStart;
    try{
      const deadline=performance.now()+5000;
      while(performance.now()<deadline){await new Promise(r=>setTimeout(r,40));const s=window.__goodBoysOpeningGameplay||{};last=Number(s.x||last);if(Math.abs(last-xStart)>=5)moved=true;if(s.near&&s.targetId===target)return {ok:true,moved,xStart,xEnd:last,target};}
      return {ok:false,moved,xStart,xEnd:last,target,error:moved?'target proximity not reached':'pointer hold produced no movement'};
    }finally{fire(right,'pointerup',0);}
  },id);
  log('ship-touch-hold',result);if(!result.ok)throw new Error('ship touch hold failed: '+JSON.stringify(result));
  await page.waitForFunction(()=>{const b=document.querySelector('#good-boys-ship-interlude [data-interact]');return !!(b&&!b.disabled);},null,{timeout:1000});
  await page.evaluate(()=>{const b=document.querySelector('#good-boys-ship-interlude [data-interact]');if(!b||b.disabled)throw new Error('INTERACT unavailable');b.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,cancelable:true,pointerId:52,pointerType:'touch',isPrimary:true,buttons:0}));});
  await page.waitForFunction(target=>{const s=window.__goodBoysOpeningGameplay;return !!(s&&Array.isArray(s.systems)&&s.systems.includes(target));},id,{timeout:2000});
}
async function completeShip(page){if(!await page.locator('#good-boys-ship-interlude').count())return false;for(const id of ['nav','flight','dock']){const done=await page.evaluate(target=>{const s=window.__goodBoysOpeningGameplay;return !!(s&&Array.isArray(s.systems)&&s.systems.includes(target));},id).catch(()=>false);if(done)continue;await moveShipTo(page,id);}return true;}
async function dismiss(page,ms=5000){const until=Date.now()+ms;let idle=0;while(Date.now()<until){
  if(await page.locator('#good-boys-ship-interlude').count()){idle=0;try{await completeShip(page);}catch(e){fail('ship-interaction-automation-failed',{error:String(e&&e.stack||e),opening:await page.evaluate(()=>window.__goodBoysOpeningGameplay||null).catch(()=>null)});throw e;}await page.waitForTimeout(100);continue;}
  const premise='#good-boys-campaign-intro button';if(await page.locator(premise).count()){idle=0;await domClick(page,premise);await page.waitForTimeout(120);continue;}
  const film='#good-dogs-cutscene-overlay.active .gd-film-skip';if(await page.locator(film).count()){idle=0;await domClick(page,film);await page.waitForTimeout(120);continue;}
  let handled=false;for(const selector of ['#good-boys-earthfall-cine button','#gb-prison-cine button','#good-boys-story-cine button']){const b=page.locator(selector).last();if(!await b.count())continue;try{if(await b.isVisible()){await b.evaluate(el=>el.click());handled=true;break;}}catch{}}
  if(handled){idle=0;await page.waitForTimeout(100);continue;}
  const txt=await page.locator('body').innerText().catch(()=>'');if(/SELECT SHIFT DIFFICULTY/i.test(txt)){idle=0;await clickText(page,/Standard/i);await page.waitForTimeout(100);continue;}if(/BEGIN THE INCIDENT/i.test(txt)){idle=0;await clickText(page,/BEGIN THE INCIDENT/i);await page.waitForTimeout(100);continue;}if(/CLICK\s*[—-]\s*SKIP|E\s*\/\s*CLICK\s*[—-]\s*SKIP|SKIP CINEMATIC/i.test(txt)){idle=0;await page.keyboard.press('KeyE').catch(()=>{});await page.waitForTimeout(120);continue;}
  const generic=page.locator('#dialogue:not(.hidden) #dlg-options button').first();if(await generic.count()&&await generic.isVisible().catch(()=>false)){idle=0;await generic.evaluate(el=>el.click()).catch(()=>{});await page.waitForTimeout(100);continue;}
  const introBusy=await page.evaluate(()=>!!(window.TechOpsGoodBoysIntroRepair&&window.TechOpsGoodBoysIntroRepair.launching)).catch(()=>false);if(introBusy){idle=0;await page.waitForTimeout(120);continue;}
  idle++;if(idle>=8)return true;await page.waitForTimeout(120);
}return false;}
async function state(page){return page.evaluate(()=>{let r={};try{r=window.eval(`(function(){var s=(typeof S!=='undefined'&&S)?S:null,n=(typeof NM!=='undefined'&&NM)?NM:null,c=n&&n._v736,m=s&&s.meta&&s.meta._v736,a=window.TechOpsGoodBoysProgressionAuthority,w=window.TechOpsGoodBoysBibleWorld,b=window.TechOpsGoodBoysBackgroundAuthority,q=window.TechOpsGoodBoysAccessCoreAuthority,e=window.TechOpsGoodBoysEarthfallEnding,cs=window.TechOpsGoodBoysCampaignState;return {night:!!(s&&s.nightMode),inDialog:!!(s&&s.inDialog),mission:Number(c&&c.m||m&&m.m||0),metaMission:Number(m&&m.m||0),stateMission:cs&&cs.mission?Number(cs.mission()):0,done:!!(m&&m.done),k:!!(m&&m.k),waldo:!!(m&&m.waldo),breakout:!!(s&&s.meta&&s.meta._v736breakout),pair:!!(s&&s.meta&&s.meta._v736pair),active:!!c,x:n&&n.x,ship:!!(n&&n._gbShipRevealed),living:n&&n.enemies?(n.enemies.filter(e=>e&&e.alive!==false&&Number(e.hp)>0).length):0,enemyKinds:n&&n.enemies?n.enemies.filter(e=>e&&e.alive!==false&&Number(e.hp)>0).map(e=>e.kind||e.name):[],authority:!!a,campaignState:!!cs,bibleWorld:!!w,accessCore:!!q,earthfall:!!e,worldAcceptance:w&&w.acceptance?w.acceptance():null,backgroundAcceptance:b&&b.acceptance?b.acceptance():null,accessAcceptance:q&&q.acceptance?q.acceptance():null,earthfallAcceptance:e&&e.acceptance?e.acceptance():null,acceptance:a&&a.acceptance?a.acceptance():null};})()`);}catch(e){r.error=String(e&&e.stack||e);}return {...r,opening:window.__goodBoysOpeningGameplay||null,openingPhase:window.__goodBoysOpeningPhase||null,directorCines:document.querySelectorAll('#good-boys-story-cine').length,prisonCines:document.querySelectorAll('#gb-prison-cine').length,earthfallCines:document.querySelectorAll('#good-boys-earthfall-cine').length,directorPads:document.querySelectorAll('#good-boys-director-controls').length,legacyPads:document.querySelectorAll('#good-boys-loop-controls').length,canonicalPads:document.querySelectorAll('#good-dogs-touch').length,followTrail:[...document.querySelectorAll('button')].filter(b=>/FOLLOW THE TRAIL/i.test(b.textContent||'')).length};});}
async function waitMission(page,want,ms=7000){const until=Date.now()+ms;let s;while(Date.now()<until){s=await state(page);if(s.done||s.mission===want||s.metaMission===want)return s;await dismiss(page,500);await page.waitForTimeout(80);}return s||await state(page);}

const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:800}});const page=await context.newPage();
try{
  await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1900);if(!await clickText(page,/(118\/1984|BREAKOUT|GOOD\s*BOYS)/i)){fail('launch-button-missing');throw new Error('Good Boys launch button missing');}
  await dismiss(page,14000);let s=await state(page);log('started',s);if(!s.opening||!s.opening.completed||s.opening.count!==3){fail('opening-three-system-inspection-not-complete',s);throw new Error('opening did not complete; downstream progression assertions suppressed');}if(!s.active||!s.authority||!s.campaignState||!s.accessCore||!s.earthfall)fail('campaign-authorities-not-attached',s);if(s.followTrail)fail('retired-follow-trail-returned',s);if(s.mission!==2||s.metaMission!==2||s.stateMission!==2)fail('opening-did-not-canonically-enter-m2',s);if(s.acceptance&&s.acceptance.invariant&&s.acceptance.invariant.ok===false)fail('opening-handoff-invariant-failed',s.acceptance);
  if(s.directorPads!==1)fail('director-pad-count',{count:s.directorPads});if(s.legacyPads!==0)fail('legacy-control-pads-remain',{count:s.legacyPads});if(s.canonicalPads!==1)fail('canonical-good-dogs-pad-count',{count:s.canonicalPads});

  await dismiss(page,2500);await page.evaluate(()=>{var n=window.NM,a=window.TechOpsGoodBoysProgressionAuthority;if(!n||!a)throw new Error('M2 runtime unavailable');n.enemies=[{kind:'guard',name:'HANGAR GUARD',x:n.x+40,y:n.y,w:28,h:38,hp:5,maxHp:5,alive:true}];a.tick();n.enemies[0].hp=0;n.enemies[0].alive=false;a.tick();});await page.waitForTimeout(500);s=await state(page);log('m2-ship-reveal',s);if(!s.ship)fail('m2-ship-not-revealed-after-clear',s);await page.evaluate(()=>{window.NM.x=1300;window.TechOpsGoodBoysProgressionAuthority.tick();});s=await waitMission(page,3,7500);log('m2-to-m3',s);if(s.mission!==3&&s.metaMission!==3)fail('m2-did-not-advance-to-m3',s);

  if(await page.locator('#gb-prison-cine').count()){const blocked=await page.evaluate(()=>!!(window.S&&window.S.inDialog));const text=await page.locator('#gb-prison-cine').innerText().catch(()=>'');log('prison-cinematic',{blocked,text:text.slice(0,180)});if(!blocked)fail('prison-cinematic-does-not-block-gameplay');if(!/ORBITAL|BLACKSITE|BREACH/i.test(text))fail('prison-premise-not-clear',{text});}
  await dismiss(page,4800);

  for(let m=3;m<=7;m++){
    let cur=await waitMission(page,m,3500);if(cur.done)break;if(cur.mission!==m&&cur.metaMission!==m){fail('unexpected-mission-before-clear',{expected:m,state:cur});break;}
    if(Number(cur.mission)!==Number(cur.metaMission)||Number(cur.mission)!==Number(cur.stateMission))fail('mission-authority-diverged-before-clear',{mission:m,state:cur});
    if(m===5){await page.waitForTimeout(350);cur=await state(page);log('access-core-roster',{kinds:cur.enemyKinds,access:cur.accessAcceptance});if(cur.enemyKinds.some(k=>String(k).toLowerCase().replace(/[\s_-]+/g,'').includes('mikeindex')))fail('m5-legacy-mike-index-still-active',cur);await page.evaluate(()=>{var n=window.NM,q=window.TechOpsGoodBoysAccessCoreAuthority;n.enemies.push({kind:'mikeindex',name:'THE MIKE INDEX',x:n.x+80,y:n.y,w:30,h:40,hp:99,maxHp:99,alive:true,boss:true});if(q)q.tick();});await page.waitForTimeout(120);cur=await state(page);if(cur.enemyKinds.some(k=>String(k).toLowerCase().replace(/[\s_-]+/g,'').includes('mikeindex'))||Number(cur.accessAcceptance&&cur.accessAcceptance.legacyMikeCount)>0)fail('m5-legacy-mike-index-respawn-not-quarantined',cur);}
    const primed=await page.evaluate(()=>window.TechOpsGoodBoysProgressionAuthority&&window.TechOpsGoodBoysProgressionAuthority.testPrimeClear());log('prime-clear',{mission:m,primed});if(!primed){fail('could-not-prime-clear',{mission:m});break;}await dismiss(page,3500);const next=m+1;cur=await waitMission(page,next,7000);log('mission-advance',{from:m,to:next,state:cur});if(!cur.done&&cur.mission!==next&&cur.metaMission!==next){fail('mission-did-not-advance',{from:m,to:next,state:cur});break;}if(m===4&&!cur.k)fail('k-not-unlocked-after-cell-118',cur);if(m===6&&!cur.waldo)fail('waldo-not-unlocked-after-cell-1984',cur);if(m<7)await dismiss(page,2200);
  }

  s=await state(page);log('earthfall-entered',s);if(!s.done&&s.metaMission!==8&&s.mission!==8)fail('campaign-did-not-reach-earthfall',s);if(!s.done){await page.waitForTimeout(250);s=await state(page);const earthText=await page.locator('#good-boys-earthfall-cine').innerText().catch(()=>'');log('earthfall-cinematic',{count:s.earthfallCines,blocked:s.inDialog,text:earthText.slice(0,220),acceptance:s.earthfallAcceptance});if(s.earthfallCines!==1)fail('authored-earthfall-cinematic-missing',s);if(!s.inDialog)fail('earthfall-cinematic-does-not-block-gameplay',s);if(!/EARTHFALL|WALDO'S PLACE|GOOD BOYS/i.test(earthText))fail('earthfall-story-contract-missing',{text:earthText});await dismiss(page,5000);}
  for(let i=0;i<30;i++){s=await state(page);if(s.done)break;await dismiss(page,500);await page.waitForTimeout(100);}s=await state(page);log('final',s);if(!s.done)fail('earthfall-did-not-complete-campaign',s);if(!s.k||!s.waldo)fail('ending-missing-rescued-party-flags',s);if(!s.breakout||!s.pair)fail('ending-missing-breakout-unlock-flags',s);if(s.earthfallCines!==0)fail('earthfall-overlay-did-not-close',s);if(s.directorPads>1)fail('duplicate-director-pads-at-end',{count:s.directorPads});if(s.legacyPads!==0)fail('legacy-pads-returned',{count:s.legacyPads});await page.screenshot({path:path.join(OUT,'goodboys-progression-final.png'),fullPage:true});
}catch(e){fail('bot-exception',{error:String(e&&e.stack||e)});await page.screenshot({path:path.join(OUT,'goodboys-progression-exception.png'),fullPage:true}).catch(()=>{});}finally{await browser.close();}
const report={pass:failures.length===0,failures,events};fs.writeFileSync(path.join(OUT,'goodboys-progression.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(OUT,'goodboys-progression.md'),['# Good Boys Progression Bot','',`- Result: **${report.pass?'PASS':'FAIL'}**`,`- Failures: ${failures.length}`,'','## Authored progression','',...events.map(e=>`- ${e.name}: \`${JSON.stringify(e)}\``)].join('\n'));if(!report.pass)process.exitCode=1;
